/**
 * Company tags added to existing catalogue problems so that every company page
 * has a real study list (2026-10-05). Product companies: LeetCode's company tags
 * (public company-wise exports, 2021–2025), GeeksforGeeks' company tags, and for
 * Hotstar interview-experience reports. Service companies (Tech Mahindra, Mphasis,
 * Virtusa, HCL, Mindtree): their LeetCode tags plus the fundamentals their coding
 * rounds are reported to ask. Riot Games, Cred and LiveRamp stay under ten.
 * index.ts merges these into each problem's tags;
 * scripts/apply-company-coverage.ts writes them to a database without
 * reseeding cases.
 */
export const COMPANY_COVERAGE: Readonly<Record<string, readonly string[]>> = {
  // ── 1 problem before ──────────────────────────────────────────────
  Palantir: [
    "minimum-time-difference", "check-if-it-is-a-straight-line", "contains-duplicate",
    "single-number", "maximum-size-subarray-sum-equals-k", "selling-pieces-of-wood",
    "smallest-string-with-swaps", "string-compression", "merge-intervals",
    "integer-to-english-words", "course-schedule-ii", "find-players-with-zero-or-one-losses",
    "longest-palindromic-substring", "maximum-length-of-repeated-subarray", "utf-8-validation",
    "number-of-islands", "flood-fill", "trapping-rain-water",
  ],
  "Two Sigma": [
    "number-of-provinces", "maximum-subarray-sum-with-one-deletion", "multiply-strings",
    "wildcard-matching", "longest-string-chain", "game-of-life", "power-of-four",
    "maximum-sum-circular-subarray", "parallel-courses-iii", "word-search-ii",
    "valid-parentheses", "meeting-rooms-ii", "number-of-islands",
    "best-time-to-buy-and-sell-stock-iii", "last-substring-in-lexicographical-order",
  ],
  Dropbox: [
    "minimize-malware-spread", "two-sum", "letter-combinations-of-a-phone-number",
    "grid-illumination", "word-break-ii", "word-pattern", "candy", "merge-intervals",
    "pairs-of-songs-with-total-durations-divisible-by-60", "minimum-path-sum",
    "find-first-occurrence-in-string",
  ],
  Hulu: [
    "sum-of-two-integers", "snakes-and-ladders", "spiral-matrix", "number-of-islands",
    "sum-of-subarray-minimums", "decode-string", "word-break", "top-k-frequent-elements",
    "remove-duplicates-from-sorted-array",
  ],
  Indeed: [
    "minimum-cost-to-split-an-array", "find-players-with-zero-or-one-losses",
    "check-if-every-row-and-column-contains-all-numbers", "subdomain-visit-count",
    "summary-ranges", "basic-calculator", "text-justification",
    "maximum-length-of-repeated-subarray", "maximal-rectangle", "consecutive-numbers-sum",
    "basic-calculator-ii", "intersection-of-two-arrays", "two-sum", "merge-sorted-array",
    "find-pivot-index", "subarray-sum-equals-k", "longest-common-subsequence",
  ],
  Yelp: [
    "remove-colored-pieces-if-both-neighbors-are-the-same-color", "two-sum",
    "longest-substring-without-repeating-characters", "longest-common-prefix",
    "merge-intervals", "word-ladder", "reverse-words-in-a-string", "course-schedule",
    "the-skyline-problem", "valid-anagram", "top-k-frequent-elements", "decode-string",
    "string-compression", "check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence",
    "top-k-frequent-words", "letter-case-permutation",
    "minimum-value-to-get-positive-step-by-step-sum", "integer-to-english-words",
    "word-break", "meeting-rooms-ii", "isomorphic-strings",
  ],
  LiveRamp: [
    "distribute-candies", "shortest-unsorted-continuous-subarray", "course-schedule",
    "minesweeper", "spiral-matrix", "is-graph-bipartite", "valid-parentheses",
    "number-of-islands",
  ],
  "Capital One": [
    "text-justification", "spiral-matrix", "minimum-operations-to-write-the-letter-y-on-a-grid",
    "rotate-image", "simplify-path",
    "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit",
    "largest-rectangle-in-histogram", "four-divisors", "number-of-islands",
    "count-operations-to-obtain-zero", "count-alternating-subarrays", "rotating-the-box",
    "count-prefix-and-suffix-pairs-ii", "container-with-most-water",
    "best-time-to-buy-and-sell-stock", "palindrome-number", "add-strings",
    "minimum-time-difference", "merge-intervals",
    "minimum-absolute-difference-between-elements-with-constraint", "monotonic-array",
    "fizz-buzz", "two-sum",
  ],
  "Epic Systems": [
    "additive-number", "spiral-matrix", "letter-combinations-of-a-phone-number",
    "valid-parentheses", "word-search", "bulls-and-cows", "two-sum", "count-primes",
    "palindromic-substrings", "permutations", "longest-palindromic-substring",
    "longest-increasing-path-in-a-matrix", "valid-palindrome", "count-and-say",
  ],
  "Riot Games": [
    "sudoku-solver", "game-of-life", "valid-sudoku", "divide-two-integers", "valid-parentheses",
  ],
  Mathworks: [
    "total-cost-to-hire-k-workers", "maximum-number-of-alloys", "reshape-the-matrix",
    "count-anagrams", "remove-colored-pieces-if-both-neighbors-are-the-same-color",
    "last-substring-in-lexicographical-order", "minimum-cost-tree-from-leaf-values",
    "earliest-second-to-mark-indices-i", "count-subarrays-with-fixed-bounds", "task-scheduler",
    "count-vowels-permutation", "valid-parentheses", "beautiful-arrangement",
    "shortest-distance-from-all-buildings", "degree-of-an-array", "bulb-switcher",
    "cherry-pickup", "unique-paths-ii", "counting-bits", "number-of-islands",
  ],
  "Tech Mahindra": [
    "best-time-to-buy-and-sell-stock", "maximum-subarray", "two-sum", "reverse-integer",
    "longest-palindromic-substring", "valid-anagram", "valid-palindrome", "merge-sorted-array",
    "remove-duplicates-from-sorted-array", "fibonacci-number", "count-primes",
  ],
  Mphasis: [
    "longest-palindromic-substring", "sort-colors", "n-queens-ii", "armstrong-number",
    "count-primes", "reverse-string", "maximum-subarray", "valid-palindrome",
    "palindrome-number", "coin-change", "add-digits", "network-delay-time",
  ],
  Virtusa: [
    "longest-substring-without-repeating-characters", "two-sum", "roman-to-integer",
    "longest-common-prefix", "rotate-array", "reverse-string", "reverse-words-in-a-string",
    "palindrome-number", "fibonacci-number", "second-largest-element", "count-primes",
    "first-unique-character-in-a-string",
  ],
  Spotify: [
    "longest-substring-without-repeating-characters", "kth-largest-element-in-an-array",
    "two-sum", "valid-parentheses", "ransom-note", "fibonacci-number", "valid-palindrome",
    "longest-consecutive-sequence", "generate-parentheses", "string-compression", "plus-one",
    "number-of-islands", "letter-case-permutation", "word-ladder", "fizz-buzz",
    "top-k-frequent-elements",
  ],
  Dream11: [
    "final-prices-with-a-special-discount-in-a-shop", "asteroid-collision", "gas-station",
    "furthest-building-you-can-reach", "minimum-falling-path-sum", "3sum",
    "number-of-ways-to-select-buildings",
    "minimum-number-of-increments-on-subarrays-to-form-a-target-array",
    "partition-equal-subset-sum", "longest-substring-without-repeating-characters",
    "rotting-oranges", "3sum-closest", "container-with-most-water",
  ],
  // LeetCode's tags plus what candidates report from the rounds.
  Hotstar: [
    "house-robber", "asteroid-collision", "keys-and-rooms", "find-k-pairs-with-smallest-sums",
    "longest-substring-without-repeating-characters", "climbing-stairs", "valid-sudoku",
    "largest-number", "maximum-sum-of-two-non-overlapping-subarrays", "valid-parentheses",
  ],
  PhonePe: [
    "most-stones-removed-with-same-row-or-column", "smallest-range-covering-elements-from-k-lists",
    "maximum-tastiness-of-candy-basket", "check-if-point-is-reachable",
    "smallest-string-with-swaps", "longest-palindromic-substring",
    "minimum-number-of-days-to-make-m-bouquets", "bus-routes", "remove-k-digits",
    "sum-of-distances-in-tree", "maximum-profit-in-job-scheduling",
    "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit",
    "trapping-rain-water", "jump-game-ii", "kth-smallest-element-in-a-sorted-matrix",
    "matchsticks-to-square", "number-of-flowers-in-full-bloom", "house-robber",
    "rotting-oranges", "asteroid-collision", "valid-parentheses", "two-sum",
  ],

  // ── 2 problems before ─────────────────────────────────────────────
  Snapchat: [
    "number-of-islands", "meeting-rooms-ii", "word-ladder", "minimum-window-substring",
    "bus-routes", "number-of-distinct-islands", "making-a-large-island", "basic-calculator-ii",
    "word-break-ii", "combination-sum", "course-schedule-ii", "valid-sudoku", "sudoku-solver",
    "game-of-life", "top-k-frequent-elements", "remove-k-digits", "frog-jump",
    "string-compression", "merge-intervals", "word-search", "power-of-two", "add-binary",
  ],
  HCL: [
    "two-sum", "valid-parentheses", "longest-substring-without-repeating-characters",
    "merge-sorted-array", "valid-palindrome", "best-time-to-buy-and-sell-stock",
    "reverse-string", "longest-palindromic-substring", "palindromic-substrings",
    "reverse-words-in-a-string", "maximum-subarray", "missing-number",
    "minimum-size-subarray-sum", "valid-perfect-square", "trapping-rain-water",
    "palindrome-number", "partition-array-for-maximum-sum",
  ],
  Databricks: [
    "find-all-anagrams-in-a-string", "house-robber", "house-robber-ii",
    "shortest-path-in-a-grid-with-obstacles-elimination",
    "longest-palindrome-by-concatenating-two-letter-words", "unique-paths-iii",
    "permutation-in-string", "text-justification", "number-of-flowers-in-full-bloom",
    "spiral-matrix", "merge-intervals", "shortest-path-in-binary-matrix", "rotting-oranges",
    "longest-mountain-in-array", "string-to-integer-atoi", "two-sum", "first-missing-positive",
    "decode-ways", "the-skyline-problem", "sliding-window-maximum", "trapping-rain-water",
    "intersection-of-two-arrays-ii",
  ],
  "Morgan Stanley": [
    "best-time-to-buy-and-sell-stock", "minimum-cost-to-move-chips-to-the-same-position",
    "two-sum", "the-employee-that-worked-on-the-longest-task",
    "find-the-original-array-of-prefix-xor", "count-subarrays-with-fixed-bounds",
    "delete-and-earn", "longest-substring-without-repeating-characters", "merge-intervals",
    "palindrome-number", "first-unique-character-in-a-string", "jump-game", "sort-colors",
    "kth-largest-element-in-an-array", "remove-duplicates-from-sorted-array", "spiral-matrix",
    "maximum-product-subarray", "daily-temperatures", "subarrays-with-k-different-integers",
    "candy", "longest-valid-parentheses", "maximum-subarray",
  ],
  Nutanix: [
    "broken-calculator", "check-if-word-is-valid-after-substitutions", "grumpy-bookstore-owner",
    "swap-for-longest-repeated-character-substring", "maximum-sum-of-an-hourglass",
    "detect-cycles-in-2d-grid", "car-fleet", "merge-intervals", "sliding-window-maximum",
    "valid-number", "increasing-triplet-subsequence", "spiral-matrix", "decode-string",
    "search-a-2d-matrix", "longest-increasing-path-in-a-matrix", "best-sightseeing-pair",
    "task-scheduler", "course-schedule-ii", "rotate-image",
    "longest-substring-without-repeating-characters", "can-place-flowers", "happy-number",
  ],
  Sprinklr: [
    "number-of-great-partitions", "apply-operations-on-array-to-maximize-sum-of-squares",
    "closest-subsequence-sum", "maximize-score-after-n-operations",
    "maximum-sum-of-two-non-overlapping-subarrays", "gas-station", "asteroid-collision",
    "sum-of-subarray-minimums", "isomorphic-strings", "subarray-sum-equals-k", "odd-even-jump",
    "cherry-pickup-ii", "trapping-rain-water", "max-points-on-a-line",
    "shortest-path-with-alternating-colors", "maximum-sum-circular-subarray", "132-pattern",
    "validate-stack-sequences", "edit-distance", "maximum-points-you-can-obtain-from-cards",
    "count-subarrays-with-median-k",
  ],
  Freshworks: [
    "longest-substring-without-repeating-characters", "valid-parentheses", "meeting-rooms-ii",
    "container-with-most-water", "remove-duplicates-from-sorted-array-ii",
    "product-of-array-except-self", "search-in-rotated-sorted-array", "two-sum",
  ],
  Myntra: [
    "maximum-earnings-from-taxi", "repeated-substring-pattern", "best-time-to-buy-and-sell-stock",
    "largest-rectangle-in-histogram", "first-missing-positive", "target-sum", "find-pivot-index",
    "rotting-oranges", "asteroid-collision", "largest-number", "3sum",
    "minimum-moves-to-equal-array-elements-ii", "container-with-most-water",
    "remove-duplicates-from-sorted-array", "longest-substring-without-repeating-characters",
    "generate-parentheses", "longest-consecutive-sequence",
    "capacity-to-ship-packages-within-d-days", "count-inversions", "super-egg-drop",
  ],

  // ── 3–6 problems before ───────────────────────────────────────────
  Twitter: [
    "minimum-genetic-mutation", "trapping-rain-water", "merge-intervals", "valid-parentheses",
    "multiply-strings", "wildcard-matching", "pascals-triangle", "word-break-ii",
    "time-needed-to-buy-tickets", "max-points-on-a-line", "happy-number", "the-skyline-problem",
    "number-of-connected-components-in-an-undirected-graph",
    "kth-smallest-element-in-a-sorted-matrix",
    "minimum-number-of-steps-to-make-two-strings-anagram",
    "minimum-elements-to-add-to-form-a-given-sum", "binary-gap", "process-tasks-using-servers",
    "remove-all-occurrences-of-a-substring", "count-sub-islands",
  ],
  Yahoo: [
    "two-sum", "roman-to-integer", "word-break", "binary-number-with-alternating-bits",
    "matrix-cells-in-distance-order", "top-k-frequent-elements", "combination-sum",
    "longest-common-prefix", "valid-parentheses", "search-in-rotated-sorted-array",
    "spiral-matrix", "decode-string", "subarray-sum-equals-k", "shortest-path-in-binary-matrix",
    "restore-ip-addresses", "find-peak-element", "word-search", "meeting-rooms-ii",
    "word-search-ii", "integer-to-english-words",
  ],
  Intuit: [
    "valid-parentheses", "plus-one", "maximum-product-of-three-numbers", "dungeon-game",
    "most-profitable-path-in-a-tree", "coin-change", "destroy-sequential-targets",
    "max-area-of-island", "word-break", "course-schedule-ii", "two-sum", "rotting-oranges",
    "number-of-ways-to-paint-n-3-grid", "reverse-pairs", "longest-increasing-subsequence",
    "unique-email-addresses", "russian-doll-envelopes", "daily-temperatures", "merge-intervals",
    "subdomain-visit-count", "text-justification",
  ],
  Arcesium: [
    "partition-array-into-two-arrays-to-minimize-sum-difference", "count-collisions-on-a-road",
    "maximize-the-confusion-of-an-exam", "number-of-people-aware-of-a-secret", "house-robber-iv",
    "minimum-swaps-to-group-all-1s-together-ii", "maximal-rectangle", "word-ladder",
    "longest-substring-without-repeating-characters", "broken-calculator",
    "minimum-size-subarray-sum", "maximum-subarray", "koko-eating-bananas",
  ],
  Ola: [
    "longest-substring-without-repeating-characters", "trapping-rain-water", "two-sum",
    "longest-palindromic-substring", "climbing-stairs", "house-robber", "number-of-islands",
    "decode-string", "container-with-most-water", "3sum", "find-pivot-index",
    "find-minimum-in-rotated-sorted-array", "excel-sheet-column-title", "first-missing-positive",
    "best-time-to-buy-and-sell-stock", "unique-paths", "word-ladder",
  ],
  Razorpay: [
    "two-best-non-overlapping-events", "most-beautiful-item-for-each-query",
    "shortest-subarray-to-be-removed-to-make-array-sorted", "decode-string", "merge-intervals",
    "rotate-array", "first-unique-character-in-a-string", "unique-paths", "smallest-good-base",
    "excel-sheet-column-number", "container-with-most-water",
  ],
  Cred: [
    "longest-repeating-character-replacement", "count-elements-with-maximum-frequency",
  ],
  Zomato: [
    "maximum-spending-after-buying-items", "shortest-cycle-in-a-graph",
    "number-of-ways-to-divide-a-long-corridor", "the-skyline-problem", "first-missing-positive",
    "number-of-islands", "maximum-subarray", "longest-substring-without-repeating-characters",
    "single-element-in-a-sorted-array", "snakes-and-ladders", "single-number-iii",
    "maximal-square", "isomorphic-strings", "course-schedule", "permutations", "move-zeroes",
    "combination-sum", "search-a-2d-matrix-ii", "merge-intervals", "container-with-most-water",
  ],
  Airbnb: [
    "text-justification", "maximum-profit-in-job-scheduling", "sliding-puzzle",
    "trapping-rain-water", "word-search-ii", "two-sum", "regular-expression-matching",
    "valid-parentheses", "single-number", "house-robber", "contains-duplicate",
    "basic-calculator-ii", "robot-bounded-in-circle", "minimum-number-of-vertices-to-reach-all-nodes",
    "cheapest-flights-within-k-stops", "minimum-window-substring", "combination-sum",
    "shortest-path-to-get-all-keys", "coin-change",
  ],
  Atlassian: [
    "merge-intervals", "meeting-rooms-ii", "word-search", "text-justification",
    "minimum-time-to-visit-a-cell-in-a-grid", "best-time-to-buy-and-sell-stock",
    "the-time-when-the-network-becomes-idle", "top-k-frequent-elements", "can-place-flowers",
    "russian-doll-envelopes", "two-sum", "longest-substring-without-repeating-characters",
    "koko-eating-bananas", "jump-game-ii", "longest-consecutive-sequence",
    "pairs-of-songs-with-total-durations-divisible-by-60", "maximum-subarray",
    "rearranging-fruits", "minimum-difficulty-of-a-job-schedule",
  ],
  Rubrik: [
    "existence-of-a-substring-in-a-string-and-its-reverse", "remove-invalid-parentheses",
    "minimum-number-of-moves-to-make-palindrome", "next-permutation", "task-scheduler-ii", "4sum",
    "scramble-string", "task-scheduler", "special-binary-string", "paint-fence",
    "smallest-string-with-swaps", "3sum", "fraction-to-recurring-decimal",
    "best-time-to-buy-and-sell-stock-iii", "minimum-path-sum",
  ],
  // LeetCode's tags plus GeeksforGeeks' Directi list (Word Boggle = Word Search II,
  // Minimum Cost to Connect Houses = Min Cost to Connect All Points).
  Directi: [
    "find-the-winner-of-an-array-game", "min-cost-to-connect-all-points",
    "largest-submatrix-with-rearrangements", "valid-anagram", "sliding-window-maximum",
    "best-time-to-buy-and-sell-stock-ii", "find-nth-root-of-m", "search-a-2d-matrix-ii",
    "search-a-2d-matrix", "sudoku-solver", "maximal-rectangle", "excel-sheet-column-title",
    "word-search-ii",
  ],
  Mindtree: [
    "count-integers-with-even-digit-sum", "palindrome-number", "two-sum", "subarray-sum-equals-k",
    "remove-vowels-from-a-string", "second-largest-element", "armstrong-number", "missing-number",
    "valid-anagram", "first-unique-character-in-a-string", "longest-common-prefix",
    "rotate-array", "valid-parentheses",
  ],
};
