import type { AptitudeSeed } from "./types.js";

/** Further mixtures, counting, probability and mensuration questions. */
export const BANK_QUANT_TOPUP: AptitudeSeed[] = [
  /* ── Mixtures & Alligation ─────────────────────────────────────── */
  {
    slug: "ma3-wheat-blend",
    topic: "mixtures-alligation",
    title: "Blending two grades of wheat",
    prompt:
      "Wheat at **₹24 per kg** is mixed with wheat at **₹36 per kg** so the mixture is worth **₹30 per kg**. In what **ratio** are they mixed?",
    options: ["1 : 1", "1 : 2", "2 : 1", "3 : 2"],
    answer: 0,
    difficulty: "easy",
    hints: ["Use alligation: (36 − 30) : (30 − 24).", "The mean sits exactly halfway between."],
    solution:
      "1. Cheaper : dearer = (36 − 30) : (30 − 24) = 6 : 6 = **1 : 1**.\n2. Check: (24 + 36)/2 = 30. ✓\n\nAnswer: **1 : 1**.",
    approach: "When the mean lies exactly midway between the two prices, the ratio is always 1 : 1. Spotting that saves the cross entirely.",
    tags: ["alligation"],
    timeTargetSec: 45,
  },
  {
    slug: "ma3-milk-water-profit-20",
    topic: "mixtures-alligation",
    title: "Water added for a 20% gain",
    prompt:
      "A milkman mixes water with milk and sells the mixture at **cost price**, gaining **20%**. What is the ratio of **water to milk**?",
    options: ["1 : 4", "1 : 5", "1 : 6", "2 : 5"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "For every 5 litres of milk he sells 6 litres of mixture.",
      "The free litre is the gain, measured against the milk paid for.",
    ],
    solution:
      "1. A 20% gain means the free water is one fifth of the milk bought.\n2. Taking 5 litres of milk and 1 litre of water gives a gain of 1/5 = 20%. ✓\n3. Water : milk = **1 : 5**.\n\nAnswer: **1 : 5**.",
    approach: "The gain equals water ÷ milk, because the water costs nothing and sells at the milk's price. Dividing by the mixture instead would give 16⅔%.",
    tags: ["milk and water"],
    timeTargetSec: 75,
  },
  {
    slug: "ma3-replace-once",
    topic: "mixtures-alligation",
    title: "One replacement",
    prompt:
      "From **50 litres of milk**, **10 litres** is removed and replaced with water. How much **milk** remains?",
    options: ["35 L", "38 L", "40 L", "45 L"],
    answer: 2,
    difficulty: "easy",
    hints: ["One fifth of the milk is removed.", "50 × 0.8."],
    solution: "1. Fraction remaining = 1 − 10/50 = 0.8.\n2. Milk left = 50 × 0.8 = **40 L**.\n\nAnswer: **40 L**.",
    approach: "A single replacement is a plain subtraction, but writing it as a fraction prepares you for the repeated case.",
    tags: ["replacement"],
    timeTargetSec: 45,
  },
  {
    slug: "ma3-two-alloys-copper",
    topic: "mixtures-alligation",
    title: "Copper in two alloys",
    prompt:
      "Alloy P is **30% copper** and alloy Q is **60% copper**. In what **ratio** must they be mixed to obtain **40% copper**?",
    options: ["1 : 2", "2 : 1", "2 : 3", "3 : 2"],
    answer: 1,
    difficulty: "medium",
    hints: ["Alligation on the copper percentages.", "(60 − 40) : (40 − 30)."],
    solution:
      "1. P : Q = (60 − 40) : (40 − 30) = 20 : 10 = **2 : 1**.\n2. Check: (2 × 30 + 1 × 60)/3 = 120/3 = 40. ✓\n\nAnswer: **2 : 1**.",
    approach: "The mean at 40 is nearer 30, so more of the poorer alloy is needed. Checking the direction before computing avoids inverting the ratio.",
    tags: ["alloys"],
    timeTargetSec: 60,
  },
  {
    slug: "ma3-spirit-water",
    topic: "mixtures-alligation",
    title: "Strengthening a spirit solution",
    prompt:
      "How much **pure spirit** must be added to **60 litres of a 40% spirit solution** to make it **50% spirit**?",
    options: ["10 L", "12 L", "15 L", "20 L"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The water is unchanged: 60% of 60 = 36 litres.",
      "In the final mixture water must be 50%, so the total becomes 72 litres.",
    ],
    solution:
      "1. Water = 60% of 60 = 36 L, and it never changes.\n2. For water to be 50% of the final mixture, the total = 36 ÷ 0.5 = 72 L.\n3. Spirit added = 72 − 60 = **12 L**.\n\nAnswer: **12 L**.",
    approach: "Anchor on the component not being added. Tracking the water needs one division; tracking the spirit needs an equation.",
    tags: ["concentration"],
    timeTargetSec: 105,
  },
  {
    slug: "ma3-average-price-three",
    topic: "mixtures-alligation",
    title: "Three quantities blended",
    prompt:
      "**10 kg at ₹20**, **20 kg at ₹30** and **20 kg at ₹40** are mixed. What is the **average price per kg**?",
    options: ["₹30", "₹32", "₹34", "₹36"],
    answer: 1,
    difficulty: "medium",
    hints: ["Total cost, then divide by 50 kg.", "200 + 600 + 800."],
    solution:
      "1. Cost = 10 × 20 + 20 × 30 + 20 × 40 = 200 + 600 + 800 = ₹1,600.\n2. Weight = 50 kg.\n3. Average = 1,600 ÷ 50 = **₹32**.\n\nAnswer: **₹32**.",
    approach: "Weighted average across any number of components: total cost divided by total quantity. The plain mean of 20, 30 and 40 is 30 and is wrong.",
    tags: ["weighted average"],
    timeTargetSec: 75,
  },
  {
    slug: "ma3-milk-water-remove-and-add",
    topic: "mixtures-alligation",
    title: "Draw off and replace",
    prompt:
      "A vessel holds **20 litres of a mixture** with milk and water in the ratio **3 : 1**. **4 litres** is drawn off and replaced with water. What is the **new ratio**?",
    options: ["2 : 1", "3 : 2", "11 : 9", "12 : 8"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Milk starts at 15 L and water at 5 L.",
      "Drawing off 4 L removes milk and water in the same 3 : 1 proportion.",
    ],
    solution:
      "1. Milk = 15 L, water = 5 L.\n2. The 4 L drawn off contains 3 L milk and 1 L water, leaving 12 L milk and 4 L water.\n3. Adding 4 L water gives 12 L milk and 8 L water.\n4. New ratio = 12 : 8 = **3 : 2**.\n\nAnswer: **3 : 2**.",
    approach:
      "What is drawn off has the same composition as the mixture, so remove both components proportionally. Only then add the replacement.",
    tags: ["replacement"],
    timeTargetSec: 120,
  },
  {
    slug: "ma3-two-vessels-unequal",
    topic: "mixtures-alligation",
    title: "Unequal quantities poured together",
    prompt:
      "**10 litres** of a **3 : 2** milk-and-water mixture is poured together with **15 litres** of a **2 : 3** mixture. What is the **new ratio**?",
    options: ["2 : 3", "3 : 2", "12 : 13", "13 : 12"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "First vessel: 6 L milk, 4 L water. Second: 6 L milk, 9 L water.",
      "Add each component separately.",
    ],
    solution:
      "1. First: milk = (3/5) × 10 = 6 L, water = 4 L.\n2. Second: milk = (2/5) × 15 = 6 L, water = 9 L.\n3. Totals: milk 12 L, water 13 L → **12 : 13**.\n\nAnswer: **12 : 13**.",
    approach: "Convert each vessel to actual litres before combining. Ratios cannot be added directly when the volumes differ.",
    tags: ["alloys"],
    timeTargetSec: 105,
  },
  {
    slug: "ma3-alligation-wages",
    topic: "mixtures-alligation",
    title: "Two grades of worker",
    prompt:
      "A firm pays **skilled workers ₹800 a day** and **unskilled workers ₹500 a day**. If the **average daily wage is ₹600**, what is the ratio of **skilled to unskilled** workers?",
    options: ["1 : 2", "2 : 1", "1 : 3", "3 : 1"],
    answer: 0,
    difficulty: "medium",
    hints: ["Alligation with 600 as the mean.", "(600 − 500) : (800 − 600)."],
    solution:
      "1. Skilled : unskilled = (600 − 500) : (800 − 600) = 100 : 200 = **1 : 2**.\n2. Check: (1 × 800 + 2 × 500)/3 = 1,800/3 = 600. ✓\n\nAnswer: **1 : 2**.",
    approach:
      "Each group's share is proportional to the *other* group's distance from the mean. The mean at 600 sits nearer 500, so the cheaper group is larger.",
    tags: ["weighted average"],
    timeTargetSec: 75,
  },
  {
    slug: "ma3-sugar-solution",
    topic: "mixtures-alligation",
    title: "Diluting a sugar solution",
    prompt:
      "**40 litres** of a solution is **25% sugar**. How much **water** must be added to reduce it to **20% sugar**?",
    options: ["8 L", "10 L", "12 L", "15 L"],
    answer: 1,
    difficulty: "medium",
    hints: ["Sugar stays fixed at 10 litres.", "10 must become 20% of the new total."],
    solution:
      "1. Sugar = 25% of 40 = 10 L, unchanged.\n2. New total = 10 ÷ 0.20 = 50 L.\n3. Water added = 50 − 40 = **10 L**.\n\nAnswer: **10 L**.",
    approach: "Dilution keeps the solute constant. Divide it by the target concentration for the new total, then subtract the old volume.",
    tags: ["concentration"],
    timeTargetSec: 75,
  },
  {
    slug: "ma3-tea-mixture-ratio-for-price",
    topic: "mixtures-alligation",
    title: "Mixing for a target selling price",
    prompt:
      "In what ratio must tea at **₹80 per kg** be mixed with tea at **₹120 per kg** so that selling the mixture at **₹110 per kg** gives a **10% profit**?",
    options: ["1 : 1", "1 : 2", "1 : 3", "3 : 1"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "For a 10% profit at ₹110, the mixture must cost ₹100 per kg.",
      "Now use alligation between 80 and 120 with a mean of 100.",
    ],
    solution:
      "1. Cost required = 110 ÷ 1.10 = ₹100 per kg.\n2. Alligation: (120 − 100) : (100 − 80) = 20 : 20 = 1 : 1.\n3. Checking against the options, the ratio is **1 : 1**.\n\nAnswer: **1 : 1**.",
    approach: "Convert the profit requirement into the mixture's cost first, then apply alligation to that cost as the mean.",
    tags: ["alligation"],
    timeTargetSec: 105,
  },
  {
    slug: "ma3-acid-two-solutions",
    topic: "mixtures-alligation",
    title: "Blending two acid solutions",
    prompt:
      "A **20% acid solution** is mixed with a **50% acid solution** to give **30% acid**. In what **ratio** are they mixed?",
    options: ["1 : 2", "2 : 1", "3 : 2", "2 : 3"],
    answer: 1,
    difficulty: "medium",
    hints: ["Alligation on the acid percentages.", "(50 − 30) : (30 − 20)."],
    solution:
      "1. Weaker : stronger = (50 − 30) : (30 − 20) = 20 : 10 = **2 : 1**.\n2. Check: (2 × 20 + 1 × 50)/3 = 90/3 = 30. ✓\n\nAnswer: **2 : 1**.",
    approach: "Alligation works identically for prices, percentages and rates. Always verify by taking the weighted average of your answer.",
    tags: ["alligation"],
    timeTargetSec: 60,
  },
  {
    slug: "ma3-petrol-kerosene",
    topic: "mixtures-alligation",
    title: "Adulterated fuel",
    prompt:
      "A dealer mixes **kerosene costing ₹40 per litre** with **petrol costing ₹100 per litre** and sells the mixture at **₹100 per litre**, gaining **25%**. What is the ratio of **kerosene to petrol**?",
    options: ["1 : 2", "1 : 3", "1 : 4", "2 : 3"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "For a 25% gain at ₹100, the mixture must cost ₹80 per litre.",
      "Then apply alligation between 40 and 100 with a mean of 80.",
    ],
    solution:
      "1. Required cost = 100 ÷ 1.25 = ₹80 per litre.\n2. Kerosene : petrol = (100 − 80) : (80 − 40) = 20 : 40 = **1 : 2**.\n3. Checking the options against this working, the ratio is 1 : 2.\n\nAnswer: **1 : 2**.",
    approach: "Two steps: convert the margin into a required cost, then run alligation. Skipping the first step is the usual error.",
    tags: ["alligation"],
    timeTargetSec: 120,
  },
  {
    slug: "ma3-replace-water-twice-ratio",
    topic: "mixtures-alligation",
    title: "Two replacements from a ratio",
    prompt:
      "A cask holds **64 litres of milk**. **8 litres** is removed and replaced with water, **twice**. How much **milk** remains?",
    options: ["48 L", "49 L", "50 L", "56 L"],
    answer: 1,
    difficulty: "medium",
    hints: ["Each operation leaves 7/8 of the milk.", "64 × (7/8)²."],
    solution:
      "1. Fraction remaining each time = 1 − 8/64 = 7/8.\n2. After two operations: 64 × (7/8)² = 64 × 49/64 = **49 L**.\n\nAnswer: **49 L**.",
    approach: "The power rule again. Choosing numbers where the fraction cancels against the volume makes the arithmetic exact.",
    tags: ["replacement"],
    timeTargetSec: 75,
  },

  /* ── Permutations & Combinations ───────────────────────────────── */
  {
    slug: "pnc3-arrange-apple",
    topic: "permutations-combinations",
    title: "Arranging APPLE",
    prompt: "In how many ways can the letters of **APPLE** be arranged?",
    options: ["24", "60", "120", "240"],
    answer: 1,
    difficulty: "easy",
    hints: ["APPLE has 5 letters with P repeated twice.", "5! ÷ 2!."],
    solution: "1. 5 letters with P twice: 5!/2! = 120/2 = **60**.\n\nAnswer: **60**.",
    approach: "Divide by the factorial of each repeat count. Ignoring the double P gives 120, which is offered.",
    tags: ["arrangements"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc3-arrange-success",
    topic: "permutations-combinations",
    title: "Arranging SUCCESS",
    prompt: "How many distinct arrangements are there of the letters of **SUCCESS**?",
    options: ["360", "420", "630", "840"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "SUCCESS has 7 letters: S three times, C twice, plus U and E.",
      "7! ÷ (3! × 2!).",
    ],
    solution:
      "1. 7 letters with S repeated 3 times and C repeated twice.\n2. Arrangements = 7!/(3! 2!) = 5,040/12 = **420**.\n\nAnswer: **420**.",
    approach: "Count each repeated letter carefully — S appears three times, which is easy to miscount as two.",
    tags: ["arrangements"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc3-choose-team",
    topic: "permutations-combinations",
    title: "Choosing a team",
    prompt: "In how many ways can a team of **4** be chosen from **9 players**?",
    options: ["84", "126", "252", "3,024"],
    answer: 1,
    difficulty: "easy",
    hints: ["Order does not matter, so use combinations.", "C(9,4) = (9 × 8 × 7 × 6)/(4 × 3 × 2 × 1)."],
    solution: "1. C(9,4) = 3,024 ÷ 24 = **126**.\n\nAnswer: **126**.",
    approach: "Selection uses combinations. The permutation P(9,4) = 3,024 is offered for anyone who forgets to divide by 4!.",
    tags: ["combinations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc3-committee-with-captain",
    topic: "permutations-combinations",
    title: "A team with a captain",
    prompt:
      "From **8 players**, in how many ways can a team of **3** be chosen and **one of them named captain**?",
    options: ["56", "112", "168", "336"],
    answer: 2,
    difficulty: "medium",
    hints: ["Choose the team first, then pick the captain from it.", "C(8,3) × 3."],
    solution:
      "1. Choose 3 from 8: C(8,3) = 56.\n2. Choose the captain from those 3: 3 ways.\n3. Total = 56 × 3 = **168**.\n\nAnswer: **168**.",
    approach: "Break a two-stage choice into stages and multiply. Choosing the captain first from all 8 and then two others gives 8 × C(7,2) = 168 as well.",
    tags: ["combinations"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc3-four-digit-even",
    topic: "permutations-combinations",
    title: "Four-digit even numbers",
    prompt:
      "How many **four-digit even numbers** with **distinct digits** can be formed from **1, 2, 3, 4, 5**?",
    options: ["24", "36", "48", "60"],
    answer: 2,
    difficulty: "medium",
    hints: ["The units digit must be 2 or 4.", "Then fill three more places from the remaining four digits."],
    solution:
      "1. Units digit: 2 choices.\n2. The other three places take 4 × 3 × 2 = 24 arrangements from the remaining digits.\n3. Total = 2 × 24 = **48**.\n\nAnswer: **48**.",
    approach: "Fill the constrained position first, then count the free ones. No zero is present, so the leading digit needs no special treatment.",
    tags: ["digits"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc3-word-vowels-together",
    topic: "permutations-combinations",
    title: "Keeping the vowels together",
    prompt:
      "In how many ways can the letters of **MOTHER** be arranged so that the **vowels are always together**?",
    options: ["120", "240", "360", "720"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "MOTHER has vowels O and E, and four consonants.",
      "Treat OE as one block, giving 5 items to arrange.",
    ],
    solution:
      "1. Treating the two vowels as one block gives 5 items: [OE], M, T, H, R.\n2. These arrange in 5! = 120 ways.\n3. The block can be OE or EO: 2 ways.\n4. Total = 120 × 2 = **240**.\n\nAnswer: **240**.",
    approach: "Glue the letters that must stay together, arrange everything, then multiply by the internal arrangements of the block.",
    tags: ["arrangements", "restrictions"],
    timeTargetSec: 90,
  },
  {
    slug: "pnc3-select-from-two-groups",
    topic: "permutations-combinations",
    title: "Selecting from two groups",
    prompt:
      "A committee of **5** is to be chosen from **6 men and 4 women** so that it contains **exactly 3 women**. In how many ways?",
    options: ["40", "60", "84", "120"],
    answer: 1,
    difficulty: "medium",
    hints: ["Choose 3 women from 4 and 2 men from 6.", "C(4,3) × C(6,2)."],
    solution:
      "1. Women: C(4,3) = 4.\n2. Men: C(6,2) = 15.\n3. Total = 4 × 15 = **60**.\n\nAnswer: **60**.",
    approach: "Independent selections from separate groups multiply. Check the numbers add to the committee size: 3 + 2 = 5. ✓",
    tags: ["combinations"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc3-shake-hands-ten",
    topic: "permutations-combinations",
    title: "Handshakes among twelve",
    prompt: "If **12 people** each shake hands with every other exactly once, how many **handshakes** occur?",
    options: ["60", "66", "72", "132"],
    answer: 1,
    difficulty: "easy",
    hints: ["Handshakes = C(12,2).", "(12 × 11)/2."],
    solution: "1. C(12,2) = (12 × 11)/2 = **66**.\n\nAnswer: **66**.",
    approach: "Each handshake is a pair, so divide by 2. Forgetting to halve gives 132, which is offered.",
    tags: ["combinations"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc3-seat-in-a-row",
    topic: "permutations-combinations",
    title: "Seating with one fixed",
    prompt:
      "In how many ways can **5 people** be seated in a row if **one particular person must sit at the left end**?",
    options: ["24", "60", "96", "120"],
    answer: 0,
    difficulty: "easy",
    hints: ["That person's seat is fixed.", "The remaining 4 arrange freely."],
    solution: "1. One seat is fixed, so the other 4 arrange in 4! = **24** ways.\n\nAnswer: **24**.",
    approach: "Fix the constrained person first, then count arrangements of the rest. Constraints always reduce the factorial.",
    tags: ["arrangements", "restrictions"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc3-ncr-identity",
    topic: "permutations-combinations",
    title: "A property of combinations",
    prompt: "What is the value of **C(12, 10)**?",
    options: ["22", "66", "132", "220"],
    answer: 1,
    difficulty: "medium",
    hints: ["C(n, r) = C(n, n − r).", "C(12,10) = C(12,2)."],
    solution: "1. C(12,10) = C(12,2) = (12 × 11)/2 = **66**.\n\nAnswer: **66**.",
    approach: "Use the symmetry C(n,r) = C(n, n−r) to replace a large r with a small one. It turns a long calculation into a short one.",
    tags: ["combinations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc3-flags-signals",
    topic: "permutations-combinations",
    title: "Signals from flags",
    prompt:
      "How many different **signals** can be made using **3 flags out of 5** different flags, where order matters?",
    options: ["10", "20", "60", "125"],
    answer: 2,
    difficulty: "medium",
    hints: ["Order matters, so use permutations.", "P(5,3) = 5 × 4 × 3."],
    solution: "1. P(5,3) = 5 × 4 × 3 = **60**.\n\nAnswer: **60**.",
    approach: "Signals depend on the order of the flags, so this is a permutation. C(5,3) = 10 would be the answer if order were irrelevant.",
    tags: ["permutations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc3-subsets-of-four",
    topic: "permutations-combinations",
    title: "Counting subsets",
    prompt: "How many **subsets** does a set of **6 elements** have, including the empty set?",
    options: ["12", "32", "64", "720"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each element is either in or out.", "2⁶."],
    solution: "1. Each of the 6 elements may be included or excluded: 2⁶ = **64**.\n\nAnswer: **64**.",
    approach: "Total subsets are 2ⁿ; non-empty subsets are 2ⁿ − 1. Which the question wants is worth checking twice.",
    tags: ["subsets"],
    timeTargetSec: 45,
  },

  /* ── Probability ───────────────────────────────────────────────── */
  {
    slug: "pr3-dice-sum-more-than-nine",
    topic: "probability",
    title: "Sum greater than nine",
    prompt: "Two dice are thrown. What is the probability that the **sum is greater than 9**?",
    options: ["1/6", "1/9", "5/36", "1/4"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Sums greater than 9 are 10, 11 and 12.",
      "They have 3, 2 and 1 ways respectively.",
    ],
    solution:
      "1. Sum 10: 3 ways; sum 11: 2 ways; sum 12: 1 way.\n2. Favourable = 6 out of 36.\n3. Probability = **1/6**.\n\nAnswer: **1/6**.",
    approach: "For sums above 7, the count of ways is 13 − s. Adding the counts for each qualifying sum is quicker than listing pairs.",
    tags: ["dice"],
    timeTargetSec: 75,
  },
  {
    slug: "pr3-card-red-king",
    topic: "probability",
    title: "A red king",
    prompt: "One card is drawn from a pack of 52. What is the probability that it is a **red king**?",
    options: ["1/26", "1/13", "1/52", "2/13"],
    answer: 0,
    difficulty: "easy",
    hints: ["There are 4 kings, of which 2 are red.", "2 out of 52."],
    solution: "1. Red kings: hearts and diamonds — 2 cards.\n2. Probability = 2/52 = **1/26**.\n\nAnswer: **1/26**.",
    approach: "Count the cards satisfying both conditions at once. Multiplying separate probabilities for 'red' and 'king' also gives 1/26 here.",
    tags: ["cards"],
    timeTargetSec: 45,
  },
  {
    slug: "pr3-two-balls-same-colour",
    topic: "probability",
    title: "Two balls of the same colour",
    prompt:
      "A bag holds **3 red and 5 blue** balls. Two are drawn at random. What is the probability that **both are the same colour**?",
    options: ["3/28", "5/14", "13/28", "15/28"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Add the two cases: both red and both blue.",
      "C(3,2) + C(5,2) over C(8,2).",
    ],
    solution:
      "1. Both red: C(3,2) = 3. Both blue: C(5,2) = 10.\n2. Favourable = 13; total = C(8,2) = 28.\n3. Probability = **13/28**.\n\nAnswer: **13/28**.",
    approach: "'Same colour' means adding the disjoint cases. The complement, one of each, is 15/28, and the two sum to 1. ✓",
    tags: ["balls"],
    timeTargetSec: 90,
  },
  {
    slug: "pr3-coin-four-tosses",
    topic: "probability",
    title: "Exactly three heads",
    prompt: "Four fair coins are tossed. What is the probability of getting **exactly three heads**?",
    options: ["1/8", "1/4", "3/8", "1/2"],
    answer: 1,
    difficulty: "medium",
    hints: ["There are 16 outcomes.", "C(4,3) = 4 favourable ones."],
    solution:
      "1. Sample space = 2⁴ = 16.\n2. Exactly three heads: C(4,3) = 4 ways.\n3. Probability = 4/16 = **1/4**.\n\nAnswer: **1/4**.",
    approach: "Use C(n,k)/2ⁿ for coin problems. Listing the sample space works for four coins but not for more.",
    tags: ["coins"],
    timeTargetSec: 60,
  },
  {
    slug: "pr3-at-least-one-head",
    topic: "probability",
    title: "At least one head",
    prompt: "Three fair coins are tossed. What is the probability of getting **at least one head**?",
    options: ["1/8", "3/8", "5/8", "7/8"],
    answer: 3,
    difficulty: "easy",
    hints: ["The complement is getting no heads at all.", "1 − 1/8."],
    solution:
      "1. P(no heads) = (1/2)³ = 1/8.\n2. P(at least one head) = 1 − 1/8 = **7/8**.\n\nAnswer: **7/8**.",
    approach: "'At least one' is nearly always easiest through the complement. Listing the seven favourable outcomes gives the same result more slowly.",
    tags: ["coins"],
    timeTargetSec: 50,
  },
  {
    slug: "pr3-number-divisible-3-or-5",
    topic: "probability",
    title: "Divisible by 3 or 5",
    prompt:
      "A number is chosen at random from **1 to 30**. What is the probability that it is divisible by **3 or 5**?",
    options: ["7/15", "1/2", "8/15", "3/5"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Multiples of 3: ten. Multiples of 5: six.",
      "Multiples of 15 are counted twice.",
    ],
    solution:
      "1. Multiples of 3: 10; of 5: 6; of 15: 2.\n2. Favourable = 10 + 6 − 2 = 14.\n3. Probability = 14/30 = **7/15**.\n\nAnswer: **7/15**.",
    approach: "Inclusion and exclusion: add the two counts and subtract the multiples of the LCM. Missing that step gives 16/30.",
    tags: ["numbers", "union"],
    timeTargetSec: 90,
  },
  {
    slug: "pr3-two-students-selected",
    topic: "probability",
    title: "Selecting two students",
    prompt:
      "From **4 boys and 6 girls**, two students are chosen at random. What is the probability that **both are girls**?",
    options: ["1/3", "2/5", "3/5", "5/9"],
    answer: 0,
    difficulty: "medium",
    hints: ["C(6,2) favourable out of C(10,2).", "15 out of 45."],
    solution:
      "1. Both girls: C(6,2) = 15.\n2. Total: C(10,2) = 45.\n3. Probability = 15/45 = **1/3**.\n\nAnswer: **1/3**.",
    approach: "Reduce the fraction fully — papers list the reduced form, and 15/45 would not appear among the options.",
    tags: ["balls"],
    timeTargetSec: 75,
  },
  {
    slug: "pr3-independent-both-fail",
    topic: "probability",
    title: "Neither passes",
    prompt:
      "Two students have probabilities **0.6 and 0.7** of passing an exam, independently. What is the probability that **neither passes**?",
    options: ["0.12", "0.18", "0.28", "0.42"],
    answer: 0,
    difficulty: "medium",
    hints: ["Failure probabilities are 0.4 and 0.3.", "Multiply them."],
    solution: "1. P(both fail) = 0.4 × 0.3 = **0.12**.\n\nAnswer: **0.12**.",
    approach: "For independent events, multiply the individual probabilities. 'Neither' means both fail, so use the failure probabilities.",
    tags: ["independent events"],
    timeTargetSec: 55,
  },
  {
    slug: "pr3-ticket-number",
    topic: "probability",
    title: "A ticket ending in a given digit",
    prompt:
      "Tickets numbered **1 to 40** are placed in a box and one is drawn. What is the probability that it is a **multiple of 4**?",
    options: ["1/8", "1/5", "1/4", "3/10"],
    answer: 2,
    difficulty: "easy",
    hints: ["Multiples of 4 up to 40: 4, 8, …, 40.", "There are 10 of them."],
    solution: "1. Multiples of 4 from 1 to 40: 10 numbers.\n2. Probability = 10/40 = **1/4**.\n\nAnswer: **1/4**.",
    approach: "Count with ⌊n/d⌋ rather than listing. Here ⌊40/4⌋ = 10 immediately.",
    tags: ["numbers"],
    timeTargetSec: 45,
  },
  {
    slug: "pr3-dice-both-even",
    topic: "probability",
    title: "Both dice even",
    prompt: "Two dice are thrown. What is the probability that **both show even numbers**?",
    options: ["1/6", "1/4", "1/3", "1/2"],
    answer: 1,
    difficulty: "easy",
    hints: ["Each die has 3 even faces out of 6.", "(1/2) × (1/2)."],
    solution: "1. P(even on one die) = 3/6 = 1/2.\n2. Both: 1/2 × 1/2 = **1/4**.\n\nAnswer: **1/4**.",
    approach: "The dice are independent, so multiply. Counting favourable outcomes gives 9 out of 36, which is the same 1/4.",
    tags: ["dice"],
    timeTargetSec: 50,
  },
  {
    slug: "pr3-cards-not-face",
    topic: "probability",
    title: "Not a face card",
    prompt: "A card is drawn from a pack of 52. What is the probability that it is **not a face card**?",
    options: ["3/13", "9/13", "10/13", "12/13"],
    answer: 2,
    difficulty: "easy",
    hints: ["There are 12 face cards.", "1 − 12/52."],
    solution: "1. Face cards = 12, so non-face cards = 40.\n2. Probability = 40/52 = **10/13**.\n\nAnswer: **10/13**.",
    approach: "Take the complement of the smaller count. 1 − 3/13 = 10/13 is the same calculation in one step.",
    tags: ["cards"],
    timeTargetSec: 50,
  },
  {
    slug: "pr3-either-a-or-b",
    topic: "probability",
    title: "Either one or the other",
    prompt:
      "P(A) = **0.4**, P(B) = **0.5**, and P(A and B) = **0.2**. What is **P(A or B)**?",
    options: ["0.6", "0.7", "0.8", "0.9"],
    answer: 1,
    difficulty: "easy",
    hints: ["P(A or B) = P(A) + P(B) − P(A and B).", "0.4 + 0.5 − 0.2."],
    solution: "1. P(A or B) = 0.4 + 0.5 − 0.2 = **0.7**.\n\nAnswer: **0.7**.",
    approach: "Subtract the overlap once. Omitting it gives 0.9, which is offered as the trap.",
    tags: ["union"],
    timeTargetSec: 45,
  },

  /* ── Mensuration ───────────────────────────────────────────────── */
  {
    slug: "me3-square-perimeter-from-area",
    topic: "mensuration",
    title: "Perimeter from the area",
    prompt: "The **area of a square is 169 cm²**. What is its **perimeter**?",
    options: ["26 cm", "39 cm", "52 cm", "676 cm"],
    answer: 2,
    difficulty: "easy",
    hints: ["Side = √169.", "Perimeter = 4 × side."],
    solution: "1. Side = √169 = 13 cm.\n2. Perimeter = 4 × 13 = **52 cm**.\n\nAnswer: **52 cm**.",
    approach: "Route through the side length. Area gives the side, and the side gives every other measurement of the square.",
    tags: ["square"],
    timeTargetSec: 45,
  },
  {
    slug: "me3-rectangle-diagonal",
    topic: "mensuration",
    title: "Diagonal of a rectangle",
    prompt: "A rectangle measures **24 cm by 7 cm**. What is the length of its **diagonal**?",
    options: ["23 cm", "25 cm", "27 cm", "31 cm"],
    answer: 1,
    difficulty: "easy",
    hints: ["Use Pythagoras on the two sides.", "√(576 + 49)."],
    solution: "1. Diagonal = √(24² + 7²) = √(576 + 49) = √625 = **25 cm**.\n\nAnswer: **25 cm**.",
    approach: "7-24-25 is a Pythagorean triple worth memorising alongside 3-4-5, 5-12-13 and 8-15-17.",
    tags: ["rectangle"],
    timeTargetSec: 50,
  },
  {
    slug: "me3-circle-sector-area",
    topic: "mensuration",
    title: "Area of a quadrant",
    prompt: "What is the **area of a quadrant** of a circle of radius **14 cm**? (Take π = 22/7.)",
    options: ["77 cm²", "154 cm²", "308 cm²", "616 cm²"],
    answer: 1,
    difficulty: "medium",
    hints: ["A quadrant is one quarter of the circle.", "Full area = 616 cm²."],
    solution:
      "1. Full circle area = (22/7) × 14² = 616 cm².\n2. A quadrant is one quarter: 616 ÷ 4 = **154 cm²**.\n\nAnswer: **154 cm²**.",
    approach: "A sector of angle θ has area (θ/360) × πr². A quadrant is 90°, so exactly a quarter.",
    tags: ["circle"],
    timeTargetSec: 60,
  },
  {
    slug: "me3-cube-volume-from-surface",
    topic: "mensuration",
    title: "Volume from the surface area",
    prompt: "The **total surface area of a cube is 150 cm²**. What is its **volume**?",
    options: ["100 cm³", "125 cm³", "150 cm³", "216 cm³"],
    answer: 1,
    difficulty: "medium",
    hints: ["6a² = 150 gives the side.", "a = 5, so volume = a³."],
    solution: "1. 6a² = 150 → a² = 25 → a = 5 cm.\n2. Volume = 5³ = **125 cm³**.\n\nAnswer: **125 cm³**.",
    approach: "Route through the edge length. Surface area gives a, and a gives volume and diagonal alike.",
    tags: ["cube"],
    timeTargetSec: 60,
  },
  {
    slug: "me3-cylinder-volume-litres",
    topic: "mensuration",
    title: "Capacity of a cylindrical tank",
    prompt:
      "A cylindrical tank has radius **7 m** and height **5 m**. What is its **capacity** in cubic metres? (Take π = 22/7.)",
    options: ["550 m³", "660 m³", "770 m³", "880 m³"],
    answer: 2,
    difficulty: "medium",
    hints: ["Volume = πr²h.", "(22/7) × 49 × 5."],
    solution: "1. Volume = (22/7) × 49 × 5 = 22 × 7 × 5 = **770 m³**.\n\nAnswer: **770 m³**.",
    approach: "Cancel the 7 in π against the radius squared before multiplying. Radii that are multiples of 7 always simplify.",
    tags: ["cylinder"],
    timeTargetSec: 60,
  },
  {
    slug: "me3-triangle-base-height",
    topic: "mensuration",
    title: "Base from area and height",
    prompt: "A triangle has an **area of 84 cm²** and a **height of 12 cm**. What is its **base**?",
    options: ["7 cm", "12 cm", "14 cm", "21 cm"],
    answer: 2,
    difficulty: "easy",
    hints: ["Area = ½ × base × height.", "84 = ½ × b × 12."],
    solution: "1. 84 = ½ × b × 12 = 6b.\n2. b = **14 cm**.\n\nAnswer: **14 cm**.",
    approach: "Rearrange the area formula for whichever quantity is missing. Forgetting the half gives 7, which is offered.",
    tags: ["triangle"],
    timeTargetSec: 45,
  },
  {
    slug: "me3-rhombus-area",
    topic: "mensuration",
    title: "Area of a rhombus",
    prompt: "A rhombus has diagonals of **16 cm and 12 cm**. What is its **area**?",
    options: ["48 cm²", "96 cm²", "144 cm²", "192 cm²"],
    answer: 1,
    difficulty: "medium",
    hints: ["Area = ½ × product of the diagonals.", "½ × 16 × 12."],
    solution: "1. Area = ½ × 16 × 12 = **96 cm²**.\n\nAnswer: **96 cm²**.",
    approach: "The half-product rule works for any quadrilateral whose diagonals are perpendicular, including the square and the kite.",
    tags: ["rhombus"],
    timeTargetSec: 50,
  },
  {
    slug: "me3-circle-radius-ratio-circumference",
    topic: "mensuration",
    title: "Ratio of circumferences",
    prompt: "Two circles have radii in the ratio **3 : 5**. What is the ratio of their **circumferences**?",
    options: ["3 : 5", "9 : 25", "6 : 10", "27 : 125"],
    answer: 0,
    difficulty: "easy",
    hints: ["Circumference is proportional to the radius.", "The ratio is unchanged."],
    solution:
      "1. Circumference = 2πr, so it scales directly with r.\n2. The ratio stays **3 : 5**.\n\nAnswer: **3 : 5**.",
    approach: "Circumference scales with the first power of r, area with the square and volume with the cube. Knowing which applies is the whole question.",
    tags: ["circle", "scaling"],
    timeTargetSec: 45,
  },
  {
    slug: "me3-wall-bricks",
    topic: "mensuration",
    title: "Bricks in a wall",
    prompt:
      "How many bricks measuring **25 cm × 10 cm × 8 cm** are needed to build a wall **5 m × 3 m × 16 cm**?",
    options: ["1,000", "1,200", "1,500", "2,000"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Convert everything to centimetres first.",
      "Wall volume = 500 × 300 × 16; brick volume = 25 × 10 × 8.",
    ],
    solution:
      "1. Wall = 500 × 300 × 16 = 24,00,000 cm³.\n2. Brick = 25 × 10 × 8 = 2,000 cm³.\n3. Bricks needed = 24,00,000 ÷ 2,000 = **1,200**.\n\nAnswer: **1,200**.",
    approach: "Convert to a single unit before dividing volumes. Mixing metres and centimetres is the only real difficulty here.",
    tags: ["cuboid"],
    timeTargetSec: 105,
  },
  {
    slug: "me3-square-inscribed-circle",
    topic: "mensuration",
    title: "A circle inside a square",
    prompt:
      "A circle is inscribed in a **square of side 14 cm**. What is the **area of the circle**? (Take π = 22/7.)",
    options: ["154 cm²", "196 cm²", "308 cm²", "616 cm²"],
    answer: 0,
    difficulty: "medium",
    hints: ["The circle's diameter equals the square's side.", "So the radius is 7 cm."],
    solution:
      "1. The inscribed circle has diameter 14 cm, so radius 7 cm.\n2. Area = (22/7) × 49 = **154 cm²**.\n\nAnswer: **154 cm²**.",
    approach:
      "For an inscribed circle the diameter matches the side; for a circumscribed circle the diameter matches the diagonal. Deciding which applies comes first.",
    tags: ["circle", "square"],
    timeTargetSec: 75,
  },
];
