import type { AptitudeSeed } from "./types.js";

/** Permutations, combinations and probability — the standard exam set. */
export const BANK_PNC_PROBABILITY: AptitudeSeed[] = [
  /* ── Permutations & Combinations ───────────────────────────────── */
  {
    slug: "pnc2-arrange-leader",
    topic: "permutations-combinations",
    title: "Arranging the letters of LEADER",
    prompt: "In how many ways can the letters of the word **LEADER** be arranged?",
    options: ["120", "240", "360", "720"],
    answer: 2,
    difficulty: "medium",
    hints: ["LEADER has 6 letters with E repeated twice.", "6! ÷ 2!."],
    solution:
      "1. LEADER has 6 letters: L, E, A, D, E, R — with E appearing twice.\n2. Arrangements = 6!/2! = 720/2 = **360**.\n\nAnswer: **360**.",
    approach: "Divide n! by the factorial of each repeat count. Ignoring the repeated E gives 720, which is offered.",
    tags: ["arrangements"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc2-arrange-mathematics",
    topic: "permutations-combinations",
    title: "Arranging MATHEMATICS",
    prompt: "How many distinct arrangements can be made of the letters of **MATHEMATICS**?",
    options: ["4,989,600", "5,987,520", "9,979,200", "39,916,800"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "MATHEMATICS has 11 letters.",
      "M appears twice, A twice and T twice; the rest are single.",
    ],
    solution:
      "1. 11 letters in all, with M, A and T each repeated twice.\n2. Arrangements = 11!/(2! 2! 2!) = 39,916,800 / 8 = **4,989,600**.\n\nAnswer: **4,989,600**.",
    approach: "Count the letters carefully first, then divide by 2! for each repeated pair. Three pairs means dividing by 8.",
    tags: ["arrangements"],
    timeTargetSec: 90,
  },
  {
    slug: "pnc2-vowels-together",
    topic: "permutations-combinations",
    title: "Vowels always together",
    prompt:
      "In how many ways can the letters of **DETAIL** be arranged so that the **vowels occupy only odd positions**?",
    options: ["36", "60", "120", "720"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "DETAIL has 6 letters: 3 vowels (E, A, I) and 3 consonants (D, T, L).",
      "There are exactly 3 odd positions: 1, 3 and 5.",
    ],
    solution:
      "1. Odd positions are 1, 3, 5 — exactly three of them, for the three vowels.\n2. Vowels can be arranged in those positions in 3! = 6 ways.\n3. The three consonants fill the even positions in 3! = 6 ways.\n4. Total = 6 × 6 = **36**.\n\nAnswer: **36**.",
    approach: "Place the restricted letters first, then fill the remaining positions. Multiplying the two independent arrangements gives the answer.",
    tags: ["arrangements", "restrictions"],
    timeTargetSec: 105,
  },
  {
    slug: "pnc2-word-together-block",
    topic: "permutations-combinations",
    title: "Two letters always together",
    prompt:
      "In how many ways can the letters of **ORANGE** be arranged so that the **two vowels O and A are always together**?",
    options: ["120", "240", "360", "480"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Treat OA as a single block, giving 5 items to arrange.",
      "The block itself can be OA or AO.",
    ],
    solution:
      "1. Treating O and A as one block gives 5 items: [OA], R, N, G, E.\n2. These arrange in 5! = 120 ways.\n3. Within the block, O and A can swap: 2 ways.\n4. Total = 120 × 2 = **240**.\n\nAnswer: **240**.",
    approach: "Glue the letters that must stay together into a single unit, arrange everything, then multiply by the internal arrangements of the unit.",
    tags: ["arrangements", "restrictions"],
    timeTargetSec: 90,
  },
  {
    slug: "pnc2-committee-3-from-5-4",
    topic: "permutations-combinations",
    title: "A committee of three",
    prompt:
      "In how many ways can a committee of **3 people** be chosen from **5 men and 4 women** so that it has **exactly 2 men**?",
    options: ["30", "40", "60", "84"],
    answer: 1,
    difficulty: "medium",
    hints: ["Choose 2 men from 5 and 1 woman from 4.", "C(5,2) × C(4,1)."],
    solution:
      "1. Ways to choose 2 men from 5 = C(5,2) = 10.\n2. Ways to choose 1 woman from 4 = C(4,1) = 4.\n3. Total = 10 × 4 = **40**.\n\nAnswer: **40**.",
    approach: "Independent choices multiply. Selection uses combinations because the order within a committee does not matter.",
    tags: ["combinations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc2-committee-at-least-two-women",
    topic: "permutations-combinations",
    title: "At least two women",
    prompt:
      "From **4 men and 3 women**, in how many ways can a committee of **3** be formed with **at least 2 women**?",
    options: ["12", "13", "18", "22"],
    answer: 1,
    difficulty: "medium",
    hints: ["Split into exactly 2 women and exactly 3 women.", "C(3,2) × C(4,1) + C(3,3)."],
    solution:
      "1. Exactly 2 women: C(3,2) × C(4,1) = 3 × 4 = 12.\n2. Exactly 3 women: C(3,3) = 1.\n3. Total = 12 + 1 = **13**.\n\nAnswer: **13**.",
    approach: "'At least k' means adding the separate cases. Here the complement route is no shorter, so enumerate the two cases directly.",
    tags: ["combinations"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc2-handshakes-45",
    topic: "permutations-combinations",
    title: "Counting the guests",
    prompt:
      "At a party every guest shakes hands with every other exactly once, making **45 handshakes**. How many **guests** were there?",
    options: ["9", "10", "11", "12"],
    answer: 1,
    difficulty: "medium",
    hints: ["Handshakes = C(n, 2) = n(n − 1)/2.", "n(n − 1) = 90."],
    solution:
      "1. n(n − 1)/2 = 45 → n(n − 1) = 90.\n2. 10 × 9 = 90, so n = **10**.\n\nAnswer: **10**.",
    approach: "Handshakes, matches in a round robin and diagonals of a polygon are all C(n,2). Solve n(n − 1) = 2k by spotting consecutive factors.",
    tags: ["combinations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc2-diagonals-octagon",
    topic: "permutations-combinations",
    title: "Diagonals of an octagon",
    prompt: "How many **diagonals** does a regular **octagon** have?",
    options: ["16", "20", "24", "28"],
    answer: 1,
    difficulty: "medium",
    hints: ["Every pair of vertices gives a line: C(8,2) = 28.", "Eight of those lines are the sides, not diagonals."],
    solution:
      "1. Lines joining any two of the 8 vertices = C(8,2) = 28.\n2. Of these, 8 are the sides of the octagon.\n3. Diagonals = 28 − 8 = **20**.\n\nAnswer: **20**.",
    approach: "Diagonals of an n-gon = n(n − 3)/2 = 8 × 5/2 = 20. Both routes agree; subtracting the sides makes the reason clear.",
    tags: ["combinations", "geometry"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc2-three-digit-no-repeat-with-zero",
    topic: "permutations-combinations",
    title: "Three-digit numbers from 0 to 5",
    prompt:
      "How many **three-digit numbers with distinct digits** can be formed using the digits **0, 1, 2, 3, 4, 5**?",
    options: ["60", "100", "120", "180"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The leading digit cannot be zero.",
      "5 choices for the hundreds place, then 5, then 4.",
    ],
    solution:
      "1. Hundreds digit: 5 choices (not 0).\n2. Tens digit: 5 remaining (0 is now allowed).\n3. Units digit: 4 remaining.\n4. Total = 5 × 5 × 4 = **100**.\n\nAnswer: **100**.",
    approach:
      "Fill the most constrained position first — here the leading digit, which excludes zero. Ignoring that restriction gives 120, which is offered.",
    tags: ["digits"],
    timeTargetSec: 90,
  },
  {
    slug: "pnc2-even-three-digit",
    topic: "permutations-combinations",
    title: "Even numbers from given digits",
    prompt:
      "How many **three-digit even numbers** with **distinct digits** can be formed from **1, 2, 3, 4, 5**?",
    options: ["12", "18", "24", "36"],
    answer: 2,
    difficulty: "medium",
    hints: ["The units digit must be 2 or 4.", "Then fill the other two places from the remaining four digits."],
    solution:
      "1. Units digit: 2 choices (2 or 4).\n2. Hundreds digit: 4 remaining choices; tens digit: 3 remaining.\n3. Total = 2 × 4 × 3 = **24**.\n\nAnswer: **24**.",
    approach: "Fix the constrained position (the units digit) first, then count the free positions. No zero is present, so the leading digit needs no special care.",
    tags: ["digits"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc2-circular-eight",
    topic: "permutations-combinations",
    title: "Eight people at a round table",
    prompt: "In how many ways can **8 people** be seated around a **circular table**?",
    options: ["720", "5,040", "40,320", "362,880"],
    answer: 1,
    difficulty: "easy",
    hints: ["Rotations of the same arrangement are not different.", "Fix one person and arrange the other seven."],
    solution:
      "1. Fix one person to remove rotations.\n2. The remaining 7 arrange in 7! = **5,040** ways.\n\nAnswer: **5,040**.",
    approach: "Circular arrangements of n people = (n − 1)!. If the arrangement can also be flipped over, halve it again.",
    tags: ["circular"],
    timeTargetSec: 50,
  },
  {
    slug: "pnc2-garland",
    topic: "permutations-combinations",
    title: "Flowers in a garland",
    prompt: "In how many ways can **6 different flowers** be strung into a **garland**?",
    options: ["60", "120", "360", "720"],
    answer: 0,
    difficulty: "medium",
    hints: ["A garland is circular, so (6 − 1)! = 120.", "It can also be turned over, so halve that."],
    solution:
      "1. Circular arrangements = (6 − 1)! = 120.\n2. A garland can be flipped, so each arrangement is counted twice.\n3. Total = 120 ÷ 2 = **60**.\n\nAnswer: **60**.",
    approach: "Necklaces and garlands are circular arrangements that can be reversed, so divide (n − 1)! by 2. Seating at a table cannot be flipped, so it is not halved.",
    tags: ["circular"],
    timeTargetSec: 75,
  },
  {
    slug: "pnc2-select-balls",
    topic: "permutations-combinations",
    title: "Choosing from three colours",
    prompt:
      "A bag has **6 red, 4 white and 5 blue** balls. In how many ways can **3 balls of different colours** be drawn?",
    options: ["60", "90", "120", "150"],
    answer: 2,
    difficulty: "medium",
    hints: ["One of each colour, so multiply the three choices.", "6 × 4 × 5."],
    solution: "1. One red from 6, one white from 4 and one blue from 5.\n2. Total = 6 × 4 × 5 = **120**.\n\nAnswer: **120**.",
    approach: "Independent selections multiply. Because exactly one is taken from each group, no combination formula is needed.",
    tags: ["combinations"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc2-ncr-value",
    topic: "permutations-combinations",
    title: "Evaluating a combination",
    prompt: "What is the value of **C(10, 3)**?",
    options: ["30", "72", "120", "720"],
    answer: 2,
    difficulty: "easy",
    hints: ["C(n, r) = n!/(r!(n − r)!).", "(10 × 9 × 8)/(3 × 2 × 1)."],
    solution: "1. C(10,3) = (10 × 9 × 8)/(3 × 2 × 1) = 720/6 = **120**.\n\nAnswer: **120**.",
    approach: "Write r factors from the top and r from the bottom. P(10,3) = 720 without the division, which is why 720 is offered.",
    tags: ["combinations"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc2-npr-value",
    topic: "permutations-combinations",
    title: "Evaluating a permutation",
    prompt: "What is the value of **P(6, 3)**?",
    options: ["18", "20", "120", "216"],
    answer: 2,
    difficulty: "easy",
    hints: ["P(n, r) = n!/(n − r)!.", "6 × 5 × 4."],
    solution: "1. P(6,3) = 6 × 5 × 4 = **120**.\n\nAnswer: **120**.",
    approach: "Permutations count ordered selections, so no division by r!. C(6,3) would be 20, which is offered.",
    tags: ["permutations"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc2-books-on-shelf",
    topic: "permutations-combinations",
    title: "Books of two subjects",
    prompt:
      "In how many ways can **4 maths books and 3 physics books** be arranged on a shelf so that **all the maths books stay together**?",
    options: ["144", "288", "576", "720"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Treat the four maths books as one block, giving 4 items.",
      "The block itself can be arranged internally in 4! ways.",
    ],
    solution:
      "1. The maths block plus 3 physics books = 4 items, arranged in 4! = 24 ways.\n2. Within the block, 4 maths books arrange in 4! = 24 ways.\n3. Total = 24 × 24 = **576**.\n\nAnswer: **576**.",
    approach: "Group, arrange the groups, then arrange within the group. The two factorials multiply.",
    tags: ["arrangements", "restrictions"],
    timeTargetSec: 90,
  },
  {
    slug: "pnc2-select-at-least-one",
    topic: "permutations-combinations",
    title: "Selecting at least one item",
    prompt: "In how many ways can **one or more items** be selected from **5 distinct items**?",
    options: ["25", "31", "32", "120"],
    answer: 1,
    difficulty: "medium",
    hints: ["Each item is either in or out: 2⁵ possibilities.", "Remove the case where nothing is chosen."],
    solution:
      "1. Each of the 5 items may be included or excluded: 2⁵ = 32 subsets.\n2. Exclude the empty selection: 32 − 1 = **31**.\n\nAnswer: **31**.",
    approach: "The number of non-empty subsets of n items is 2ⁿ − 1. Forgetting to subtract the empty set gives 32.",
    tags: ["subsets"],
    timeTargetSec: 60,
  },

  /* ── Probability ───────────────────────────────────────────────── */
  {
    slug: "pr2-two-dice-sum-eight",
    topic: "probability",
    title: "Sum of two dice is 8",
    prompt: "Two fair dice are thrown. What is the probability that the **sum is 8**?",
    options: ["1/9", "5/36", "1/6", "7/36"],
    answer: 1,
    difficulty: "easy",
    hints: ["There are 36 equally likely outcomes.", "List the ordered pairs adding to 8."],
    solution:
      "1. Pairs summing to 8: (2,6), (3,5), (4,4), (5,3), (6,2) — 5 outcomes.\n2. Probability = **5/36**.\n\nAnswer: **5/36**.",
    approach: "For two dice, the number of ways to reach a sum s is s − 1 for s ≤ 7 and 13 − s for s ≥ 7. Sum 8 therefore has 5 ways.",
    tags: ["dice"],
    timeTargetSec: 60,
  },
  {
    slug: "pr2-two-dice-doublet",
    topic: "probability",
    title: "Throwing a doublet",
    prompt: "Two dice are thrown together. What is the probability of getting a **doublet**?",
    options: ["1/12", "1/6", "1/3", "5/36"],
    answer: 1,
    difficulty: "easy",
    hints: ["A doublet is the same number on both dice.", "There are 6 such outcomes out of 36."],
    solution:
      "1. Doublets: (1,1), (2,2), …, (6,6) — 6 outcomes.\n2. Probability = 6/36 = **1/6**.\n\nAnswer: **1/6**.",
    approach: "Count the favourable outcomes directly when the sample space is small. Six doublets out of thirty-six is worth remembering.",
    tags: ["dice"],
    timeTargetSec: 45,
  },
  {
    slug: "pr2-card-face-card",
    topic: "probability",
    title: "Drawing a face card",
    prompt: "One card is drawn from a well-shuffled pack of **52**. What is the probability that it is a **face card**?",
    options: ["1/13", "3/13", "1/4", "4/13"],
    answer: 1,
    difficulty: "easy",
    hints: ["Face cards are the jack, queen and king of each suit.", "3 × 4 = 12 face cards."],
    solution:
      "1. Face cards = 3 per suit × 4 suits = 12.\n2. Probability = 12/52 = **3/13**.\n\nAnswer: **3/13**.",
    approach: "Know the pack: 52 cards, 4 suits of 13, 12 face cards, 26 red and 26 black, 4 aces. Most card questions reduce to counting from these.",
    tags: ["cards"],
    timeTargetSec: 45,
  },
  {
    slug: "pr2-card-queen-or-club",
    topic: "probability",
    title: "A queen or a club",
    prompt: "A card is drawn from a pack of 52. What is the probability that it is a **queen or a club**?",
    options: ["4/13", "17/52", "1/4", "15/52"],
    answer: 0,
    difficulty: "medium",
    hints: ["4 queens and 13 clubs, but the queen of clubs is in both.", "4 + 13 − 1."],
    solution:
      "1. Favourable = 4 + 13 − 1 = 16 cards.\n2. Probability = 16/52 = **4/13**.\n\nAnswer: **4/13**.",
    approach: "P(A or B) = P(A) + P(B) − P(both). Forgetting the overlap gives 17/52, which is offered.",
    tags: ["cards", "union"],
    timeTargetSec: 60,
  },
  {
    slug: "pr2-two-cards-both-kings",
    topic: "probability",
    title: "Two kings in a row",
    prompt:
      "Two cards are drawn **without replacement** from a pack of 52. What is the probability that **both are kings**?",
    options: ["1/169", "1/221", "1/13", "4/663"],
    answer: 1,
    difficulty: "medium",
    hints: ["First king: 4/52. Then 3 kings remain among 51 cards.", "(4/52) × (3/51)."],
    solution:
      "1. P(first king) = 4/52 = 1/13.\n2. P(second king given the first) = 3/51 = 1/17.\n3. Product = 1/221.\n\nAnswer: **1/221**.",
    approach:
      "Without replacement, reduce both the favourable count and the total after each draw. With replacement it would be (1/13)² = 1/169, which is offered.",
    tags: ["cards", "without replacement"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-balls-two-red",
    topic: "probability",
    title: "Two red balls",
    prompt:
      "A bag contains **5 red and 4 green** balls. Two are drawn **at random**. What is the probability that **both are red**?",
    options: ["5/18", "5/9", "2/9", "1/6"],
    answer: 0,
    difficulty: "medium",
    hints: ["Use combinations: C(5,2) favourable out of C(9,2).", "10 out of 36."],
    solution:
      "1. Ways to choose 2 red = C(5,2) = 10.\n2. Total ways = C(9,2) = 36.\n3. Probability = 10/36 = **5/18**.\n\nAnswer: **5/18**.",
    approach: "Counting combinations avoids worrying about order. Drawing sequentially gives (5/9) × (4/8) = 5/18 as well.",
    tags: ["balls"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-balls-one-each",
    topic: "probability",
    title: "One of each colour",
    prompt:
      "A bag has **4 white and 5 black** balls. Two are drawn at random. What is the probability that they are of **different colours**?",
    options: ["5/18", "4/9", "5/9", "2/3"],
    answer: 2,
    difficulty: "medium",
    hints: ["Choose 1 white and 1 black: 4 × 5 = 20.", "Total ways = C(9,2) = 36."],
    solution:
      "1. Favourable = C(4,1) × C(5,1) = 20.\n2. Total = C(9,2) = 36.\n3. Probability = 20/36 = **5/9**.\n\nAnswer: **5/9**.",
    approach: "One from each group multiplies the two counts. The complement (both the same colour) would be 16/36, confirming the total.",
    tags: ["balls"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-three-coins-exactly-two",
    topic: "probability",
    title: "Exactly two heads",
    prompt: "Three fair coins are tossed. What is the probability of getting **exactly two heads**?",
    options: ["1/8", "1/4", "3/8", "1/2"],
    answer: 2,
    difficulty: "easy",
    hints: ["There are 8 outcomes.", "HHT, HTH and THH are the favourable ones."],
    solution:
      "1. Sample space = 2³ = 8 outcomes.\n2. Exactly two heads: HHT, HTH, THH → 3 outcomes.\n3. Probability = **3/8**.\n\nAnswer: **3/8**.",
    approach: "For small coin problems, list the sample space. 'Exactly two' is C(3,2)/2³ = 3/8; 'at least two' would be 4/8.",
    tags: ["coins"],
    timeTargetSec: 50,
  },
  {
    slug: "pr2-coin-all-tails",
    topic: "probability",
    title: "No heads at all",
    prompt: "Four fair coins are tossed. What is the probability of getting **no heads**?",
    options: ["1/16", "1/8", "1/4", "1/2"],
    answer: 0,
    difficulty: "easy",
    hints: ["Every coin must land tails.", "(1/2)⁴."],
    solution: "1. All four must be tails: (1/2)⁴ = **1/16**.\n\nAnswer: **1/16**.",
    approach: "Independent events multiply. The complement, 'at least one head', is 15/16.",
    tags: ["coins"],
    timeTargetSec: 40,
  },
  {
    slug: "pr2-leap-year-53-mondays",
    topic: "probability",
    title: "53 Mondays in a leap year",
    prompt: "What is the probability that a **leap year** chosen at random has **53 Mondays**?",
    options: ["1/7", "2/7", "3/7", "1/2"],
    answer: 1,
    difficulty: "medium",
    hints: ["366 days = 52 weeks + 2 extra days.", "The two extra days are consecutive; how many pairs include a Monday?"],
    solution:
      "1. 366 = 52 × 7 + 2, so every weekday occurs 52 times plus two consecutive extra days.\n2. The extra pair is one of 7 equally likely consecutive pairs, and 2 of them contain a Monday.\n3. Probability = **2/7**.\n\nAnswer: **2/7**.",
    approach: "A leap year has 2 spare days and an ordinary year 1, so the probability of 53 of a given weekday is 2/7 and 1/7 respectively.",
    tags: ["calendar"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-ordinary-year-53-sundays",
    topic: "probability",
    title: "53 Sundays in an ordinary year",
    prompt: "What is the probability that a **non-leap year** has **53 Sundays**?",
    options: ["1/7", "2/7", "3/7", "1/2"],
    answer: 0,
    difficulty: "medium",
    hints: ["365 = 52 weeks + 1 extra day.", "That one day is equally likely to be any weekday."],
    solution:
      "1. 365 = 52 × 7 + 1, so one weekday occurs 53 times.\n2. That day is equally likely to be any of the 7.\n3. Probability = **1/7**.\n\nAnswer: **1/7**.",
    approach: "One spare day in an ordinary year, two in a leap year. Everything else about the calendar is irrelevant.",
    tags: ["calendar"],
    timeTargetSec: 60,
  },
  {
    slug: "pr2-at-least-one-solves",
    topic: "probability",
    title: "At least one solves it",
    prompt:
      "A can solve a problem with probability **1/2** and B with probability **1/3**, independently. What is the probability that the **problem gets solved**?",
    options: ["1/6", "1/2", "2/3", "5/6"],
    answer: 2,
    difficulty: "medium",
    hints: ["Find the probability that neither solves it.", "(1/2) × (2/3) = 1/3."],
    solution:
      "1. P(A fails) = 1/2, P(B fails) = 2/3.\n2. P(both fail) = 1/2 × 2/3 = 1/3.\n3. P(solved) = 1 − 1/3 = **2/3**.\n\nAnswer: **2/3**.",
    approach: "For independent events, P(at least one) = 1 − product of failure probabilities. Adding 1/2 and 1/3 double-counts the case where both succeed.",
    tags: ["independent events"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-both-hit-target",
    topic: "probability",
    title: "Both hit the target",
    prompt:
      "Two marksmen hit a target with probabilities **3/5 and 2/3**. What is the probability that **both hit** it?",
    options: ["2/5", "1/3", "3/5", "4/5"],
    answer: 0,
    difficulty: "easy",
    hints: ["Independent events multiply.", "(3/5) × (2/3)."],
    solution: "1. P(both) = 3/5 × 2/3 = 6/15 = **2/5**.\n\nAnswer: **2/5**.",
    approach: "Multiply for 'and' with independent events, add (minus the overlap) for 'or'. Cancel before multiplying to keep the fractions small.",
    tags: ["independent events"],
    timeTargetSec: 45,
  },
  {
    slug: "pr2-number-divisible-by-5",
    topic: "probability",
    title: "Divisible by 5",
    prompt:
      "A number is chosen at random from **1 to 50**. What is the probability that it is **divisible by 5**?",
    options: ["1/10", "1/5", "1/4", "3/10"],
    answer: 1,
    difficulty: "easy",
    hints: ["Multiples of 5 up to 50: 5, 10, …, 50.", "There are 10 of them."],
    solution: "1. Multiples of 5 from 1 to 50: 10 numbers.\n2. Probability = 10/50 = **1/5**.\n\nAnswer: **1/5**.",
    approach: "Count the favourable cases with ⌊n/d⌋ and divide by the range size. No listing is needed once the count is clear.",
    tags: ["numbers"],
    timeTargetSec: 45,
  },
  {
    slug: "pr2-prime-from-twenty",
    topic: "probability",
    title: "Picking a prime",
    prompt: "A number is picked at random from **1 to 20**. What is the probability that it is **prime**?",
    options: ["1/5", "2/5", "9/20", "1/2"],
    answer: 1,
    difficulty: "easy",
    hints: ["Primes to 20: 2, 3, 5, 7, 11, 13, 17, 19.", "That is 8 numbers."],
    solution:
      "1. Primes from 1 to 20: 2, 3, 5, 7, 11, 13, 17, 19 — eight of them.\n2. Probability = 8/20 = **2/5**.\n\nAnswer: **2/5**.",
    approach: "Remember that 1 is not prime and 2 is. Miscounting by one is the only real risk here.",
    tags: ["numbers"],
    timeTargetSec: 50,
  },
  {
    slug: "pr2-tickets-multiple-of-3-or-5",
    topic: "probability",
    title: "A multiple of 3 or 5",
    prompt:
      "Tickets numbered **1 to 20** are mixed and one is drawn. What is the probability that it is a **multiple of 3 or 5**?",
    options: ["1/2", "8/15", "9/20", "2/5"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Multiples of 3: six of them. Multiples of 5: four.",
      "15 is counted in both, so subtract it once.",
    ],
    solution:
      "1. Multiples of 3: 3, 6, 9, 12, 15, 18 → 6 numbers.\n2. Multiples of 5: 5, 10, 15, 20 → 4 numbers.\n3. 15 belongs to both, so favourable = 6 + 4 − 1 = 9.\n4. Probability = **9/20**.\n\nAnswer: **9/20**.",
    approach: "Inclusion and exclusion: add the two counts and subtract the multiples of the LCM. Missing the overlap gives 10/20 = 1/2.",
    tags: ["numbers", "union"],
    timeTargetSec: 75,
  },
  {
    slug: "pr2-two-children-both-girls",
    topic: "probability",
    title: "Both children girls",
    prompt:
      "A family has **two children**. What is the probability that **both are girls**, assuming each child is equally likely to be a boy or a girl?",
    options: ["1/4", "1/3", "1/2", "2/3"],
    answer: 0,
    difficulty: "easy",
    hints: ["The sample space is BB, BG, GB, GG.", "Only one of the four is favourable."],
    solution:
      "1. Equally likely outcomes: BB, BG, GB, GG.\n2. Only GG is favourable, so the probability is **1/4**.\n\nAnswer: **1/4**.",
    approach: "Order matters when listing the sample space: BG and GB are distinct outcomes, which is why the answer is 1/4 rather than 1/3.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pr2-defective-bulbs",
    topic: "probability",
    title: "Drawing a defective bulb",
    prompt:
      "A box has **20 bulbs**, of which **4 are defective**. One bulb is drawn at random. What is the probability that it is **not defective**?",
    options: ["1/5", "3/5", "4/5", "9/10"],
    answer: 2,
    difficulty: "easy",
    hints: ["Good bulbs = 20 − 4.", "16 out of 20."],
    solution: "1. Good bulbs = 16 of 20.\n2. Probability = 16/20 = **4/5**.\n\nAnswer: **4/5**.",
    approach: "Take the complement when it is easier: 1 − 4/20 = 4/5 gives the same result in one step.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pr2-two-defective-from-box",
    topic: "probability",
    title: "Two good bulbs",
    prompt:
      "From a box of **10 bulbs** of which **3 are defective**, two are drawn at random. What is the probability that **both are good**?",
    options: ["7/15", "7/10", "21/45", "3/5"],
    answer: 0,
    difficulty: "medium",
    hints: ["Good bulbs = 7. Choose 2 from them.", "C(7,2)/C(10,2) = 21/45."],
    solution:
      "1. Favourable = C(7,2) = 21.\n2. Total = C(10,2) = 45.\n3. Probability = 21/45 = **7/15**.\n\nAnswer: **7/15**.",
    approach: "Reduce the fraction at the end — 21/45 and 7/15 are the same value, and papers usually list the reduced form.",
    tags: ["balls"],
    timeTargetSec: 75,
  },
];
