import type { AptitudeSeed } from "./types.js";

/** Synonyms, antonyms and word usage — the standard verbal-ability set. */
export const BANK_VOCABULARY: AptitudeSeed[] = [
  {
    slug: "vo2-synonym-lucid",
    topic: "vocabulary",
    title: "Synonym of LUCID",
    prompt: "Choose the word closest in meaning to **LUCID**:\n\n> Her explanation was remarkably *lucid*.",
    options: ["Clear", "Confusing", "Lengthy", "Technical"],
    answer: 0,
    difficulty: "easy",
    hints: ["Lucid describes something easy to follow.", "Which option means easy to understand?"],
    solution:
      "1. *Lucid* means expressed clearly and easy to understand.\n2. **Clear** is the closest match.\n3. *Confusing* is the opposite; *lengthy* and *technical* describe different qualities.\n\nAnswer: **Clear**.",
    approach: "Read the word inside its sentence first — context alone rules out half the options. Then eliminate the outright opposite.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-prudent",
    topic: "vocabulary",
    title: "Synonym of PRUDENT",
    prompt: "Choose the word closest in meaning to **PRUDENT**:",
    options: ["Cautious", "Reckless", "Generous", "Stubborn"],
    answer: 0,
    difficulty: "easy",
    hints: ["Prudent describes someone who thinks before acting.", "Which option means careful?"],
    solution:
      "1. *Prudent* means showing care and thought for the future.\n2. **Cautious** matches it.\n3. *Reckless* is its opposite.\n\nAnswer: **Cautious**.",
    approach: "Define the word in your own words before looking down the list. The antonym is almost always offered as a distractor.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-benevolent",
    topic: "vocabulary",
    title: "Synonym of BENEVOLENT",
    prompt: "Choose the word closest in meaning to **BENEVOLENT**:",
    options: ["Kind", "Cruel", "Wealthy", "Talkative"],
    answer: 0,
    difficulty: "easy",
    hints: ["The root *bene-* means 'good' or 'well'.", "Benevolent means well-wishing."],
    solution:
      "1. *Benevolent* means kindly and well-meaning.\n2. **Kind** is the closest word.\n3. *Cruel* is the opposite.\n\nAnswer: **Kind**.",
    approach: "Roots help: *bene-* means good (benefit, benign), *mal-* means bad (malice, malignant). Recognising them settles many questions without the definition.",
    tags: ["synonym", "roots"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-tenacious",
    topic: "vocabulary",
    title: "Synonym of TENACIOUS",
    prompt: "Choose the word closest in meaning to **TENACIOUS**:",
    options: ["Persistent", "Fragile", "Hesitant", "Generous"],
    answer: 0,
    difficulty: "medium",
    hints: ["Tenacious describes someone who does not give up.", "Which option means holding on?"],
    solution:
      "1. *Tenacious* means holding firmly and not giving up.\n2. **Persistent** is the closest.\n3. *Hesitant* and *fragile* both suggest weakness.\n\nAnswer: **Persistent**.",
    approach: "The root *ten-* means 'hold' (tenant, retain, tenure). Spotting the root narrows the field immediately.",
    tags: ["synonym", "roots"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-synonym-obsolete",
    topic: "vocabulary",
    title: "Synonym of OBSOLETE",
    prompt: "Choose the word closest in meaning to **OBSOLETE**:",
    options: ["Outdated", "Expensive", "Fragile", "Complicated"],
    answer: 0,
    difficulty: "easy",
    hints: ["Obsolete describes something no longer in use.", "Which option means out of date?"],
    solution: "1. *Obsolete* means no longer produced or used.\n2. **Outdated** matches it.\n\nAnswer: **Outdated**.",
    approach: "Think of where you have met the word — obsolete technology, obsolete rules. The usual context often gives the meaning away.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-eloquent",
    topic: "vocabulary",
    title: "Synonym of ELOQUENT",
    prompt: "Choose the word closest in meaning to **ELOQUENT**:",
    options: ["Articulate", "Silent", "Rude", "Boring"],
    answer: 0,
    difficulty: "medium",
    hints: ["Eloquent describes persuasive, fluent speech.", "The root *loqu-* means 'speak'."],
    solution:
      "1. *Eloquent* means fluent and persuasive in speech.\n2. **Articulate** is the closest.\n3. *Silent* is the opposite.\n\nAnswer: **Articulate**.",
    approach: "The root *loqu-* or *loc-* means speak: eloquent, loquacious, colloquial, elocution.",
    tags: ["synonym", "roots"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-synonym-diligent",
    topic: "vocabulary",
    title: "Synonym of DILIGENT",
    prompt: "Choose the word closest in meaning to **DILIGENT**:",
    options: ["Hardworking", "Lazy", "Cheerful", "Wealthy"],
    answer: 0,
    difficulty: "easy",
    hints: ["Diligent describes steady, careful effort.", "Which option means industrious?"],
    solution: "1. *Diligent* means showing steady and careful effort.\n2. **Hardworking** matches it.\n\nAnswer: **Hardworking**.",
    approach: "Substitute each option back into a sentence with the word. Only the right one leaves the meaning intact.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-ambiguous",
    topic: "vocabulary",
    title: "Synonym of AMBIGUOUS",
    prompt: "Choose the word closest in meaning to **AMBIGUOUS**:",
    options: ["Unclear", "Certain", "Honest", "Brief"],
    answer: 0,
    difficulty: "easy",
    hints: ["Ambiguous means open to more than one interpretation.", "Which option means not clear?"],
    solution: "1. *Ambiguous* means having more than one possible meaning.\n2. **Unclear** is the closest.\n\nAnswer: **Unclear**.",
    approach: "Ambiguous is the opposite of lucid, which appears elsewhere in this set. Pairing opposites as you learn them doubles the value of each word.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-arduous",
    topic: "vocabulary",
    title: "Synonym of ARDUOUS",
    prompt: "Choose the word closest in meaning to **ARDUOUS**:",
    options: ["Difficult", "Simple", "Pleasant", "Short"],
    answer: 0,
    difficulty: "medium",
    hints: ["An arduous climb is a hard one.", "Which option means demanding great effort?"],
    solution: "1. *Arduous* means requiring strenuous effort.\n2. **Difficult** is the closest.\n\nAnswer: **Difficult**.",
    approach: "Recall the word's usual collocations — an arduous journey, an arduous task. That context supplies the sense.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-candid",
    topic: "vocabulary",
    title: "Synonym of CANDID",
    prompt: "Choose the word closest in meaning to **CANDID**:",
    options: ["Frank", "Secretive", "Rude", "Formal"],
    answer: 0,
    difficulty: "easy",
    hints: ["Candid means saying what you really think.", "Which option means open and honest?"],
    solution:
      "1. *Candid* means truthful and straightforward.\n2. **Frank** is the closest.\n3. *Rude* overshoots — candour need not be impolite.\n\nAnswer: **Frank**.",
    approach: "Watch for options that exaggerate the word. Candid is honest, not aggressive, so 'rude' is too strong.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-scrutinise",
    topic: "vocabulary",
    title: "Synonym of SCRUTINISE",
    prompt: "Choose the word closest in meaning to **SCRUTINISE**:",
    options: ["Examine", "Ignore", "Approve", "Repeat"],
    answer: 0,
    difficulty: "easy",
    hints: ["To scrutinise is to look at very closely.", "Which option means to inspect?"],
    solution: "1. *Scrutinise* means to examine closely and critically.\n2. **Examine** matches it.\n\nAnswer: **Examine**.",
    approach: "Verbs must be matched with verbs. Checking the part of speech first removes options that could not fit grammatically.",
    tags: ["synonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-abundant",
    topic: "vocabulary",
    title: "Synonym of ABUNDANT",
    prompt: "Choose the word closest in meaning to **ABUNDANT**:",
    options: ["Plentiful", "Scarce", "Costly", "Hidden"],
    answer: 0,
    difficulty: "easy",
    hints: ["Abundant describes a large quantity.", "Which option means more than enough?"],
    solution: "1. *Abundant* means existing in large quantities.\n2. **Plentiful** matches; *scarce* is its opposite.\n\nAnswer: **Plentiful**.",
    approach: "Where a clear antonym is offered, it confirms the axis being tested. Pick the end of that axis the question asks for.",
    tags: ["synonym"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-synonym-vigilant",
    topic: "vocabulary",
    title: "Synonym of VIGILANT",
    prompt: "Choose the word closest in meaning to **VIGILANT**:",
    options: ["Watchful", "Sleepy", "Friendly", "Angry"],
    answer: 0,
    difficulty: "easy",
    hints: ["A vigilant guard keeps careful watch.", "The root *vigil-* means awake."],
    solution: "1. *Vigilant* means keeping careful watch for danger.\n2. **Watchful** is the closest.\n\nAnswer: **Watchful**.",
    approach: "The root *vigil-* means awake or alert, as in vigil and invigilate. Roots give a reliable first guess.",
    tags: ["synonym", "roots"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-synonym-reluctant",
    topic: "vocabulary",
    title: "Synonym of RELUCTANT",
    prompt: "Choose the word closest in meaning to **RELUCTANT**:",
    options: ["Unwilling", "Eager", "Careless", "Confident"],
    answer: 0,
    difficulty: "easy",
    hints: ["A reluctant volunteer does not really want to help.", "Which option means not wanting to?"],
    solution: "1. *Reluctant* means unwilling and hesitant.\n2. **Unwilling** matches; *eager* is the opposite.\n\nAnswer: **Unwilling**.",
    approach: "Picture the word in use — a reluctant witness, a reluctant apology. The attitude it conveys is the meaning.",
    tags: ["synonym"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-synonym-novice",
    topic: "vocabulary",
    title: "Synonym of NOVICE",
    prompt: "Choose the word closest in meaning to **NOVICE**:",
    options: ["Beginner", "Expert", "Teacher", "Rival"],
    answer: 0,
    difficulty: "easy",
    hints: ["A novice has just started.", "The root *nov-* means new."],
    solution: "1. *Novice* means a person new to something.\n2. **Beginner** matches; *expert* is its opposite.\n\nAnswer: **Beginner**.",
    approach: "The root *nov-* means new: novel, novelty, innovate, renovate. It is one of the most productive roots in these papers.",
    tags: ["synonym", "roots"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-antonym-scarce",
    topic: "vocabulary",
    title: "Antonym of SCARCE",
    prompt: "Choose the word most **opposite** in meaning to **SCARCE**:",
    options: ["Rare", "Plentiful", "Costly", "Small"],
    answer: 1,
    difficulty: "easy",
    hints: ["Scarce means hard to find.", "The opposite is available in large amounts."],
    solution:
      "1. *Scarce* means in short supply.\n2. **Plentiful** is its opposite.\n3. *Rare* is a synonym, placed first as the usual trap.\n\nAnswer: **Plentiful**.",
    approach: "In antonym questions the synonym is almost always offered, often first. Define the word, then look specifically for its reverse.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-humble",
    topic: "vocabulary",
    title: "Antonym of HUMBLE",
    prompt: "Choose the word most **opposite** in meaning to **HUMBLE**:",
    options: ["Modest", "Arrogant", "Quiet", "Poor"],
    answer: 1,
    difficulty: "easy",
    hints: ["Humble describes someone with a modest view of themselves.", "The opposite thinks very highly of themselves."],
    solution:
      "1. *Humble* means modest and unassuming.\n2. **Arrogant** is its opposite.\n3. *Modest* is a synonym.\n\nAnswer: **Arrogant**.",
    approach: "Check every option against the definition rather than against a general impression. Modest and humble are near-identical.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-condense",
    topic: "vocabulary",
    title: "Antonym of CONDENSE",
    prompt: "Choose the word most **opposite** in meaning to **CONDENSE**:",
    options: ["Compress", "Expand", "Freeze", "Reduce"],
    answer: 1,
    difficulty: "medium",
    hints: ["To condense is to make smaller or shorter.", "The opposite makes it larger."],
    solution:
      "1. *Condense* means to make more compact or concise.\n2. **Expand** is its opposite.\n3. *Compress* and *reduce* are synonyms.\n\nAnswer: **Expand**.",
    approach: "Two synonyms among four options is a strong hint that neither is the answer. The odd one out on that axis is usually correct.",
    tags: ["antonym"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-antonym-optimist",
    topic: "vocabulary",
    title: "Antonym of OPTIMIST",
    prompt: "Choose the word most **opposite** in meaning to **OPTIMIST**:",
    options: ["Realist", "Pessimist", "Idealist", "Cynic"],
    answer: 1,
    difficulty: "easy",
    hints: ["An optimist expects good outcomes.", "Who expects bad ones?"],
    solution:
      "1. An *optimist* expects the best.\n2. A **pessimist** expects the worst — the direct opposite.\n3. A *cynic* distrusts motives, which is related but not the antonym.\n\nAnswer: **Pessimist**.",
    approach: "Pick the exact opposite rather than something merely negative. Cynic is offered precisely because it feels close.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-generous",
    topic: "vocabulary",
    title: "Antonym of GENEROUS",
    prompt: "Choose the word most **opposite** in meaning to **GENEROUS**:",
    options: ["Liberal", "Miserly", "Wealthy", "Careless"],
    answer: 1,
    difficulty: "easy",
    hints: ["Generous means willing to give.", "The opposite is unwilling to part with anything."],
    solution:
      "1. *Generous* means giving freely.\n2. **Miserly** is its opposite.\n3. *Liberal* in this sense is a synonym.\n\nAnswer: **Miserly**.",
    approach: "Beware of words with more than one sense: liberal means generous here, not political.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-artificial",
    topic: "vocabulary",
    title: "Antonym of ARTIFICIAL",
    prompt: "Choose the word most **opposite** in meaning to **ARTIFICIAL**:",
    options: ["Synthetic", "Natural", "Modern", "Cheap"],
    answer: 1,
    difficulty: "easy",
    hints: ["Artificial means made by people rather than occurring in nature.", "What is the opposite of man-made?"],
    solution:
      "1. *Artificial* means made by human beings.\n2. **Natural** is its opposite.\n3. *Synthetic* is a synonym.\n\nAnswer: **Natural**.",
    approach: "Synthetic and artificial are near-identical, so neither can be the answer to the other. That observation removes one option at once.",
    tags: ["antonym"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-antonym-victory",
    topic: "vocabulary",
    title: "Antonym of TRIUMPH",
    prompt: "Choose the word most **opposite** in meaning to **TRIUMPH**:",
    options: ["Success", "Failure", "Effort", "Contest"],
    answer: 1,
    difficulty: "easy",
    hints: ["Triumph means a great victory.", "What is the opposite of winning?"],
    solution:
      "1. *Triumph* means a notable victory.\n2. **Failure** is its opposite.\n3. *Success* is a synonym.\n\nAnswer: **Failure**.",
    approach: "Reject related words that are not opposites: contest and effort belong to the same field but sit on no opposing axis.",
    tags: ["antonym"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-antonym-accelerate",
    topic: "vocabulary",
    title: "Antonym of ACCELERATE",
    prompt: "Choose the word most **opposite** in meaning to **ACCELERATE**:",
    options: ["Hasten", "Retard", "Continue", "Steer"],
    answer: 1,
    difficulty: "medium",
    hints: ["To accelerate is to speed up.", "Which option means to slow down?"],
    solution:
      "1. *Accelerate* means to increase speed.\n2. **Retard** means to slow down — the opposite.\n3. *Hasten* is a synonym.\n\nAnswer: **Retard**.",
    approach: "Formal or less common words are often the intended antonym. Do not reject a word merely because it is unfamiliar.",
    tags: ["antonym"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-antonym-transparent",
    topic: "vocabulary",
    title: "Antonym of TRANSPARENT",
    prompt: "Choose the word most **opposite** in meaning to **TRANSPARENT**:",
    options: ["Clear", "Opaque", "Fragile", "Colourless"],
    answer: 1,
    difficulty: "easy",
    hints: ["Transparent means light passes through.", "What does light not pass through?"],
    solution:
      "1. *Transparent* allows light through.\n2. **Opaque** blocks it entirely — the opposite.\n3. *Clear* and *colourless* are close to transparent.\n\nAnswer: **Opaque**.",
    approach: "Three options clustering near the word's own meaning leaves the fourth as the antonym. Grouping the options this way is a quick filter.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-frugal",
    topic: "vocabulary",
    title: "Antonym of LAVISH",
    prompt: "Choose the word most **opposite** in meaning to **LAVISH**:",
    options: ["Extravagant", "Frugal", "Elegant", "Sudden"],
    answer: 1,
    difficulty: "medium",
    hints: ["Lavish means spending or giving very freely.", "The opposite is sparing."],
    solution:
      "1. *Lavish* means generous to the point of excess.\n2. **Frugal** means sparing and economical — the opposite.\n3. *Extravagant* is a synonym.\n\nAnswer: **Frugal**.",
    approach: "The pair frugal/lavish is worth learning together, as either can be the question word.",
    tags: ["antonym"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-antonym-ancient",
    topic: "vocabulary",
    title: "Antonym of ANCIENT",
    prompt: "Choose the word most **opposite** in meaning to **ANCIENT**:",
    options: ["Antique", "Modern", "Historic", "Ruined"],
    answer: 1,
    difficulty: "easy",
    hints: ["Ancient means very old.", "The opposite belongs to the present."],
    solution:
      "1. *Ancient* means belonging to the distant past.\n2. **Modern** is its opposite.\n3. *Antique* and *historic* both point backwards.\n\nAnswer: **Modern**.",
    approach: "Sort the options by which direction in time they point. Only one points the other way.",
    tags: ["antonym"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-antonym-deny",
    topic: "vocabulary",
    title: "Antonym of DENY",
    prompt: "Choose the word most **opposite** in meaning to **DENY**:",
    options: ["Refuse", "Admit", "Ignore", "Question"],
    answer: 1,
    difficulty: "easy",
    hints: ["To deny is to say something is not true.", "The opposite is to accept that it is."],
    solution:
      "1. *Deny* means to state that something is untrue.\n2. **Admit** means to acknowledge it — the opposite.\n3. *Refuse* is close to deny in another sense.\n\nAnswer: **Admit**.",
    approach: "Where a word has two senses, choose the one the options are testing. Here the sense is 'declare untrue', not 'withhold'.",
    tags: ["antonym"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-antonym-praise",
    topic: "vocabulary",
    title: "Antonym of COMMEND",
    prompt: "Choose the word most **opposite** in meaning to **COMMEND**:",
    options: ["Praise", "Criticise", "Recommend", "Notice"],
    answer: 1,
    difficulty: "medium",
    hints: ["To commend is to praise formally.", "The opposite is to find fault."],
    solution:
      "1. *Commend* means to praise or approve.\n2. **Criticise** is its opposite.\n3. *Praise* and *recommend* are both synonyms.\n\nAnswer: **Criticise**.",
    approach: "Two synonyms plus one neutral word leaves the antonym plain. Grouping options is faster than defining each precisely.",
    tags: ["antonym"],
    timeTargetSec: 40,
  },
  {
    slug: "vo2-usage-affect-effect",
    topic: "vocabulary",
    title: "Affect or effect",
    prompt: "Choose the sentence in which the word is used **correctly**:",
    options: [
      "The medicine had little affect on her.",
      "The medicine had little effect on her.",
      "The rain did not effect the match.",
      "She was deeply effected by the news.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["*Affect* is usually the verb; *effect* is usually the noun.", "'Had little ___' needs a noun."],
    solution:
      "1. *Affect* is normally a verb (to influence); *effect* is normally a noun (a result).\n2. 'Had little **effect**' needs the noun, so the second sentence is correct.\n3. The others use the wrong member of the pair.\n\nAnswer: **The medicine had little effect on her.**",
    approach: "Test which part of speech the slot needs. After 'had little' a noun is required, which settles the choice.",
    tags: ["usage"],
    timeTargetSec: 50,
  },
  {
    slug: "vo2-usage-principal-principle",
    topic: "vocabulary",
    title: "Principal or principle",
    prompt: "Choose the sentence in which the word is used **correctly**:",
    options: [
      "The principle of the school addressed us.",
      "She refused on principal.",
      "Honesty is his guiding principle.",
      "The principle reason was cost.",
    ],
    answer: 2,
    difficulty: "medium",
    hints: ["*Principle* is a rule or belief; *principal* means chief, or the head of a school.", "'Guiding ___' calls for a belief."],
    solution:
      "1. *Principle* = a rule or belief; *principal* = chief, or a school head.\n2. 'His guiding **principle**' correctly uses the noun meaning a belief.\n3. The other three swap the two words.\n\nAnswer: **Honesty is his guiding principle.**",
    approach: "Remember that the school head is your 'pal' — principAL. Everything else meaning a rule takes principLE.",
    tags: ["usage"],
    timeTargetSec: 50,
  },
  {
    slug: "vo2-usage-stationary",
    topic: "vocabulary",
    title: "Stationary or stationery",
    prompt: "Choose the sentence in which the word is used **correctly**:",
    options: [
      "He bought pens from the stationary shop.",
      "The car remained stationery at the signal.",
      "The car remained stationary at the signal.",
      "She keeps her stationary in a drawer.",
    ],
    answer: 2,
    difficulty: "medium",
    hints: ["*Stationary* means not moving; *stationery* means writing materials.", "A car at a signal is not moving."],
    solution:
      "1. *Stationary* = motionless; *stationery* = paper, pens and so on.\n2. 'The car remained **stationary**' is correct.\n\nAnswer: **The car remained stationary at the signal.**",
    approach: "Remember the 'e' in stationEry stands for envelope. The other spelling, with 'a', means standing still.",
    tags: ["usage"],
    timeTargetSec: 50,
  },
  {
    slug: "vo2-usage-complement",
    topic: "vocabulary",
    title: "Complement or compliment",
    prompt: "Choose the sentence in which the word is used **correctly**:",
    options: [
      "He paid her a nice complement.",
      "The wine complements the meal perfectly.",
      "Her dress was a lovely complement on her taste.",
      "I would like to complement the chef.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["*Complement* means to complete or go well with; *compliment* means praise.", "Wine going well with a meal is completion, not praise."],
    solution:
      "1. *Complement* = completes or goes well with; *compliment* = an expression of praise.\n2. 'The wine **complements** the meal' is the correct use.\n\nAnswer: **The wine complements the meal perfectly.**",
    approach: "The 'e' in complEment matches complEte. Praise is spelt with an 'i'.",
    tags: ["usage"],
    timeTargetSec: 50,
  },
  {
    slug: "vo2-usage-lie-lay",
    topic: "vocabulary",
    title: "Lie or lay",
    prompt: "Choose the **correct** sentence:",
    options: [
      "I am going to lay down for a rest.",
      "I am going to lie down for a rest.",
      "Please lie the book on the table.",
      "The book is laying on the table.",
    ],
    answer: 1,
    difficulty: "hard",
    hints: [
      "*Lie* means to recline and takes no object; *lay* means to place something and needs an object.",
      "'Down for a rest' has no object, so it needs *lie*.",
    ],
    solution:
      "1. *Lie* (reclined, no object) versus *lay* (placed something, needs an object).\n2. 'I am going to **lie** down' has no object, so *lie* is correct.\n3. 'Lay the book' would be right, and 'the book is lying' would be right.\n\nAnswer: **I am going to lie down for a rest.**",
    approach: "Ask whether the verb has an object. If something is being placed, use *lay*; if a person or thing is reclining by itself, use *lie*.",
    tags: ["usage"],
    timeTargetSec: 60,
  },
  {
    slug: "vo2-usage-fewer-less",
    topic: "vocabulary",
    title: "Fewer or less",
    prompt: "Choose the **correct** sentence:",
    options: [
      "There were less people than expected.",
      "There were fewer people than expected.",
      "I have less books than you.",
      "She has fewer patience than her sister.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["*Fewer* is for things you can count; *less* is for quantities you cannot.", "People can be counted."],
    solution:
      "1. *Fewer* goes with countable nouns, *less* with uncountable ones.\n2. People are countable, so '**fewer** people' is correct.\n3. 'Less patience' would be right, since patience is uncountable.\n\nAnswer: **There were fewer people than expected.**",
    approach: "Ask whether you could put a number in front of the noun. If you could, use fewer; if not, use less.",
    tags: ["usage"],
    timeTargetSec: 50,
  },
  {
    slug: "vo2-usage-among-between",
    topic: "vocabulary",
    title: "Between or among",
    prompt: "Choose the **correct** sentence:",
    options: [
      "The prize was divided between the four winners.",
      "The prize was divided among the four winners.",
      "Choose among the two options.",
      "He sat among his two brothers.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["*Between* is for two; *among* is for more than two.", "Four winners is more than two."],
    solution:
      "1. *Between* applies to two items, *among* to three or more.\n2. With four winners, '**among**' is correct.\n\nAnswer: **The prize was divided among the four winners.**",
    approach: "Count the items the preposition governs. Two takes between; three or more takes among.",
    tags: ["usage"],
    timeTargetSec: 45,
  },
  {
    slug: "vo2-one-word-illegible",
    topic: "vocabulary",
    title: "One word for the phrase",
    prompt: "Choose the **one word** for: *handwriting that cannot be read*.",
    options: ["Illegible", "Ineligible", "Illiterate", "Illicit"],
    answer: 0,
    difficulty: "medium",
    hints: ["The word begins with il- meaning 'not'.", "Legible means readable."],
    solution:
      "1. *Legible* means readable, so **illegible** means unreadable.\n2. *Ineligible* means not qualified; *illiterate* means unable to read; *illicit* means unlawful.\n\nAnswer: **Illegible**.",
    approach: "The near-miss options differ by a single syllable. Build the word from its root — legible — rather than choosing by sound.",
    tags: ["one word"],
    timeTargetSec: 45,
  },
  {
    slug: "vo2-one-word-autobiography",
    topic: "vocabulary",
    title: "A life written by oneself",
    prompt: "Choose the **one word** for: *the story of a person's life written by that person*.",
    options: ["Biography", "Autobiography", "Memoir", "Diary"],
    answer: 1,
    difficulty: "easy",
    hints: ["The prefix *auto-* means self.", "A biography is written by someone else."],
    solution:
      "1. *Auto-* means self, so an **autobiography** is a life story written by its subject.\n2. A *biography* is written by another person.\n\nAnswer: **Autobiography**.",
    approach: "Prefixes carry the distinction: auto- (self), bio- (life), graph- (writing). Together they give the exact meaning.",
    tags: ["one word", "roots"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-one-word-omnipresent",
    topic: "vocabulary",
    title: "Present everywhere",
    prompt: "Choose the **one word** for: *present in all places at the same time*.",
    options: ["Omnipotent", "Omniscient", "Omnipresent", "Omnivorous"],
    answer: 2,
    difficulty: "medium",
    hints: ["*Omni-* means all; the second half tells you which sense.", "Present everywhere."],
    solution:
      "1. *Omni-* means all. **Omnipresent** means present everywhere.\n2. *Omnipotent* means all-powerful, *omniscient* all-knowing, *omnivorous* eating everything.\n\nAnswer: **Omnipresent**.",
    approach: "All four share the prefix, so the second element decides. Learning the omni- family together makes this instant.",
    tags: ["one word", "roots"],
    timeTargetSec: 45,
  },
  {
    slug: "vo2-one-word-pessimist",
    topic: "vocabulary",
    title: "One who expects the worst",
    prompt: "Choose the **one word** for: *a person who always expects the worst*.",
    options: ["Optimist", "Pessimist", "Cynic", "Sceptic"],
    answer: 1,
    difficulty: "easy",
    hints: ["The opposite of an optimist.", "Expecting the worst is pessimism."],
    solution:
      "1. A **pessimist** expects the worst outcome.\n2. A *cynic* doubts people's motives; a *sceptic* doubts claims.\n\nAnswer: **Pessimist**.",
    approach: "Distinguish the near-neighbours: pessimism is about outcomes, cynicism about motives, scepticism about evidence.",
    tags: ["one word"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-one-word-manuscript",
    topic: "vocabulary",
    title: "Written by hand",
    prompt: "Choose the **one word** for: *a document written by hand*.",
    options: ["Manuscript", "Transcript", "Postscript", "Inscription"],
    answer: 0,
    difficulty: "medium",
    hints: ["*Manu-* means hand and *script* means writing.", "Put the two together."],
    solution:
      "1. *Manu-* (hand) + *script* (writing) gives **manuscript**.\n2. A *transcript* is a written copy; a *postscript* is added after; an *inscription* is carved or engraved.\n\nAnswer: **Manuscript**.",
    approach: "Break the compound into its parts. All four options share *script*, so the prefix decides the answer.",
    tags: ["one word", "roots"],
    timeTargetSec: 45,
  },
  {
    slug: "vo2-idiom-once-in-a-blue-moon",
    topic: "vocabulary",
    title: "Once in a blue moon",
    prompt: "What does the idiom **'once in a blue moon'** mean?",
    options: ["Very rarely", "Very often", "At night", "Suddenly"],
    answer: 0,
    difficulty: "easy",
    hints: ["A blue moon is an unusual event.", "The idiom describes frequency."],
    solution: "1. A blue moon is a rare occurrence.\n2. The idiom means something happens **very rarely**.\n\nAnswer: **Very rarely**.",
    approach: "Idioms cannot be worked out word by word, but the image usually points the right way. Rarity is the whole idea of a blue moon.",
    tags: ["idiom"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-idiom-turn-a-blind-eye",
    topic: "vocabulary",
    title: "To turn a blind eye",
    prompt: "What does the idiom **'to turn a blind eye'** mean?",
    options: ["To pretend not to notice", "To lose one's sight", "To look carefully", "To refuse an offer"],
    answer: 0,
    difficulty: "easy",
    hints: ["It describes a deliberate choice, not a physical condition.", "Choosing not to see something wrong."],
    solution:
      "1. To turn a blind eye is to deliberately ignore something you know is wrong.\n2. So it means **to pretend not to notice**.\n\nAnswer: **To pretend not to notice**.",
    approach: "Idioms about the senses usually describe a choice rather than an ability. Literal readings are the standard distractors.",
    tags: ["idiom"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-idiom-break-the-ice",
    topic: "vocabulary",
    title: "To break the ice",
    prompt: "What does the idiom **'to break the ice'** mean?",
    options: ["To start a conversation", "To end a friendship", "To cause damage", "To work quickly"],
    answer: 0,
    difficulty: "easy",
    hints: ["It describes what happens at the start of a social situation.", "Easing an awkward silence."],
    solution: "1. To break the ice is to ease the initial awkwardness between people.\n2. It means **to start a conversation**.\n\nAnswer: **To start a conversation**.",
    approach: "Think about where you have heard the phrase used. Its usual setting gives the meaning more reliably than the image does.",
    tags: ["idiom"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-idiom-hit-the-nail",
    topic: "vocabulary",
    title: "To hit the nail on the head",
    prompt: "What does the idiom **'to hit the nail on the head'** mean?",
    options: ["To describe something exactly", "To act violently", "To make a mistake", "To finish a job"],
    answer: 0,
    difficulty: "easy",
    hints: ["It is a compliment about accuracy.", "Saying precisely the right thing."],
    solution:
      "1. Hitting the nail squarely is doing it exactly right.\n2. The idiom means **to describe something exactly**.\n\nAnswer: **To describe something exactly**.",
    approach: "Decide first whether the idiom is praise or criticism. That halves the options straight away.",
    tags: ["idiom"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-spelling-accommodate",
    topic: "vocabulary",
    title: "Correct spelling",
    prompt: "Choose the **correctly spelt** word:",
    options: ["Accomodate", "Accommodate", "Acommodate", "Accommadate"],
    answer: 1,
    difficulty: "medium",
    hints: ["The word has a double c and a double m.", "Think of it as accommodating two of each."],
    solution: "1. The correct spelling is **accommodate**, with double c and double m.\n\nAnswer: **Accommodate**.",
    approach: "For troublesome spellings, memorise the doubled letters explicitly: accommodate, occurrence, embarrass, necessary (one c, two s).",
    tags: ["spelling"],
    timeTargetSec: 35,
  },
  {
    slug: "vo2-spelling-separate",
    topic: "vocabulary",
    title: "Another spelling",
    prompt: "Choose the **correctly spelt** word:",
    options: ["Seperate", "Separrate", "Separate", "Sepearate"],
    answer: 2,
    difficulty: "easy",
    hints: ["The middle vowel is an 'a', not an 'e'.", "There is 'a rat' in separate."],
    solution: "1. The correct spelling is **separate** — there is 'a rat' in the middle.\n\nAnswer: **Separate**.",
    approach: "A mnemonic beats memory for this word: sep-A-RAT-e. The common misspelling uses an 'e' in that slot.",
    tags: ["spelling"],
    timeTargetSec: 30,
  },
  {
    slug: "vo2-spelling-occurrence",
    topic: "vocabulary",
    title: "A third spelling",
    prompt: "Choose the **correctly spelt** word:",
    options: ["Occurence", "Occurrance", "Ocurrence", "Occurrence"],
    answer: 3,
    difficulty: "medium",
    hints: ["Double c, double r, and it ends in -ence.", "Occur doubles its r before the ending."],
    solution: "1. The correct spelling is **occurrence**: double c, double r, ending -ence.\n\nAnswer: **Occurrence**.",
    approach: "Verbs ending in a stressed short vowel plus one consonant double it before a suffix: occur → occurred, occurrence.",
    tags: ["spelling"],
    timeTargetSec: 40,
  },
];
