import type { AptitudeSeed } from "./types.js";

/** Sentence correction and sentence completion — the standard verbal set. */
export const BANK_GRAMMAR: AptitudeSeed[] = [
  /* ── Sentence Correction ───────────────────────────────────────── */
  {
    slug: "sc2-agreement-neither-nor",
    topic: "sentence-correction",
    title: "Neither ... nor",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Neither the teacher nor the students was present.",
      "Neither the teacher nor the students were present.",
      "Neither the teacher nor the students is present.",
      "Neither the teacher nor the students has been present.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: [
      "With 'neither ... nor', the verb agrees with the nearer subject.",
      "The nearer subject here is 'students', which is plural.",
    ],
    solution:
      "1. In 'neither A nor B', the verb agrees with whichever subject is nearer.\n2. The nearer subject is *students* (plural), so the verb must be **were**.\n\nAnswer: **Neither the teacher nor the students were present.**",
    approach:
      "The proximity rule governs 'either ... or', 'neither ... nor' and 'not only ... but also'. Reversing the two subjects would change the correct verb.",
    tags: ["agreement"],
    timeTargetSec: 50,
  },
  {
    slug: "sc2-agreement-each-every",
    topic: "sentence-correction",
    title: "Each and every",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Each of the boys were given a prize.",
      "Each of the boys was given a prize.",
      "Each of the boy was given a prize.",
      "Each of the boys have been given a prize.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["'Each' is always singular, whatever follows it.", "The subject is 'each', not 'boys'."],
    solution:
      "1. *Each* is singular, so it takes a singular verb.\n2. 'Each of the boys **was** given a prize' is correct.\n3. The plural *boys* after 'of' does not change the subject.\n\nAnswer: **Each of the boys was given a prize.**",
    approach: "Each, every, either, neither, everyone and nobody are all singular. Cross out the phrase after 'of' and the agreement becomes obvious.",
    tags: ["agreement"],
    timeTargetSec: 50,
  },
  {
    slug: "sc2-agreement-collective",
    topic: "sentence-correction",
    title: "A collective noun",
    prompt: "Choose the **correct** sentence:",
    options: [
      "The committee have decided unanimously.",
      "The committee has decided unanimously.",
      "The committee are decided unanimously.",
      "The committee were deciding unanimously.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["A collective noun acting as one body takes a singular verb.", "'Unanimously' shows the committee acted as one."],
    solution:
      "1. A collective noun acting as a single unit takes a singular verb.\n2. *Unanimously* shows the committee acted together, so **has** is correct.\n\nAnswer: **The committee has decided unanimously.**",
    approach: "Collective nouns take a singular verb when acting as one body and a plural verb when the members act separately.",
    tags: ["agreement"],
    timeTargetSec: 50,
  },
  {
    slug: "sc2-agreement-one-of",
    topic: "sentence-correction",
    title: "One of those who",
    prompt: "Choose the **correct** sentence:",
    options: [
      "He is one of the students who has passed.",
      "He is one of the students who have passed.",
      "He is one of the student who have passed.",
      "He is one of the students whom have passed.",
    ],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The verb after 'who' refers back to 'students', not to 'one'.",
      "Ask: who passed? The students did.",
    ],
    solution:
      "1. The relative clause 'who ... passed' describes *students*, which is plural.\n2. So the verb must be **have**.\n3. 'One' governs only the main verb *is*.\n\nAnswer: **He is one of the students who have passed.**",
    approach:
      "In 'one of the X who ...', the relative clause modifies X. Test it by turning the sentence round: 'of the students who have passed, he is one'.",
    tags: ["agreement"],
    timeTargetSec: 75,
  },
  {
    slug: "sc2-tense-since",
    topic: "sentence-correction",
    title: "Since and the perfect tense",
    prompt: "Choose the **correct** sentence:",
    options: [
      "He is living here since 2015.",
      "He has been living here since 2015.",
      "He lives here since 2015.",
      "He lived here since 2015.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["'Since' with an ongoing action needs the present perfect continuous.", "The action started in the past and continues."],
    solution:
      "1. An action that began in the past and still continues takes the present perfect continuous.\n2. '**He has been living** here since 2015' is correct.\n\nAnswer: **He has been living here since 2015.**",
    approach: "'Since' marks a starting point and 'for' a duration; both call for a perfect tense when the action continues into the present.",
    tags: ["tense"],
    timeTargetSec: 50,
  },
  {
    slug: "sc2-tense-past-perfect",
    topic: "sentence-correction",
    title: "Which happened first",
    prompt: "Choose the **correct** sentence:",
    options: [
      "When I reached the station, the train already left.",
      "When I reached the station, the train had already left.",
      "When I had reached the station, the train already left.",
      "When I reach the station, the train had already left.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Two past events: the earlier one takes the past perfect.",
      "The train left before the arrival.",
    ],
    solution:
      "1. Of two past actions, the earlier takes the past perfect (*had left*) and the later the simple past (*reached*).\n2. The train left first, so '**the train had already left**' is correct.\n\nAnswer: **When I reached the station, the train had already left.**",
    approach: "Past perfect marks the earlier of two past events. Putting it on the wrong clause reverses the order of the story.",
    tags: ["tense"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-tense-conditional",
    topic: "sentence-correction",
    title: "An unreal condition",
    prompt: "Choose the **correct** sentence:",
    options: [
      "If I was you, I would accept the offer.",
      "If I were you, I would accept the offer.",
      "If I am you, I would accept the offer.",
      "If I were you, I will accept the offer.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["An imaginary condition uses 'were' for every subject.", "The main clause takes 'would'."],
    solution:
      "1. For a hypothetical condition, the subjunctive *were* is used with every subject.\n2. The main clause takes *would*, giving '**If I were you, I would accept**'.\n\nAnswer: **If I were you, I would accept the offer.**",
    approach: "Second conditional: 'if + past subjunctive' with 'would' in the main clause. 'Will' belongs to the first conditional, which uses the present.",
    tags: ["tense", "conditionals"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-tense-by-the-time",
    topic: "sentence-correction",
    title: "By the time",
    prompt: "Choose the **correct** sentence:",
    options: [
      "By the time we arrive, the film will start.",
      "By the time we arrive, the film will have started.",
      "By the time we will arrive, the film starts.",
      "By the time we arrived, the film will have started.",
    ],
    answer: 1,
    difficulty: "hard",
    hints: [
      "'By the time' introduces a future point, and the other action finishes before it.",
      "Completion before a future moment takes the future perfect.",
    ],
    solution:
      "1. The film finishes starting before the moment of arrival, so the future perfect is needed: **will have started**.\n2. A time clause after 'by the time' uses the present, not 'will'.\n\nAnswer: **By the time we arrive, the film will have started.**",
    approach: "Time clauses (when, by the time, as soon as) take the present tense even when the meaning is future. The main clause carries the future form.",
    tags: ["tense"],
    timeTargetSec: 70,
  },
  {
    slug: "sc2-preposition-different-from",
    topic: "sentence-correction",
    title: "Different from",
    prompt: "Choose the **correct** sentence:",
    options: [
      "His answer is different than mine.",
      "His answer is different from mine.",
      "His answer is different to mine than yours.",
      "His answer is differing from mine.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["The standard idiom is 'different from'.", "'Different than' is not accepted in formal writing."],
    solution:
      "1. The accepted form is **different from**.\n2. 'Different than' is widely regarded as incorrect in formal English.\n\nAnswer: **His answer is different from mine.**",
    approach: "Prepositions after adjectives are fixed by idiom: different from, similar to, superior to, capable of, afraid of.",
    tags: ["prepositions"],
    timeTargetSec: 40,
  },
  {
    slug: "sc2-preposition-comply-with",
    topic: "sentence-correction",
    title: "Comply with",
    prompt: "Choose the **correct** sentence:",
    options: [
      "The company must comply to the rules.",
      "The company must comply with the rules.",
      "The company must comply of the rules.",
      "The company must comply for the rules.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["The verb takes a fixed preposition.", "One complies *with* a rule."],
    solution: "1. The fixed expression is **comply with**.\n\nAnswer: **The company must comply with the rules.**",
    approach: "Learn verb-preposition pairs as single units: comply with, consist of, insist on, depend on, differ from, result in.",
    tags: ["prepositions"],
    timeTargetSec: 40,
  },
  {
    slug: "sc2-preposition-superior-to",
    topic: "sentence-correction",
    title: "Superior to",
    prompt: "Choose the **correct** sentence:",
    options: [
      "This model is superior than the old one.",
      "This model is superior to the old one.",
      "This model is more superior than the old one.",
      "This model is superior from the old one.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["Words ending in -ior take 'to', not 'than'.", "Superior is already comparative, so 'more' is redundant."],
    solution:
      "1. *Superior*, *inferior*, *senior*, *junior* and *prior* all take **to**.\n2. They are already comparative, so 'more superior' is wrong twice over.\n\nAnswer: **This model is superior to the old one.**",
    approach: "The Latin comparatives ending in -ior never take 'than' and never take 'more'. Remembering them as a family covers several exam questions.",
    tags: ["prepositions"],
    timeTargetSec: 50,
  },
  {
    slug: "sc2-article-a-an",
    topic: "sentence-correction",
    title: "A or an",
    prompt: "Choose the **correct** sentence:",
    options: [
      "He is an university student.",
      "He is a university student.",
      "He is an unique candidate.",
      "He is a hour late.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: [
      "The choice depends on the sound, not the letter.",
      "'University' begins with a 'yoo' sound, which is a consonant sound.",
    ],
    solution:
      "1. *An* is used before a vowel **sound**, not merely a vowel letter.\n2. *University* begins with a 'yoo' sound, so it takes **a**.\n3. *Hour* begins with a vowel sound, so it takes *an*.\n\nAnswer: **He is a university student.**",
    approach: "Say the word aloud. A university, a European, a one-rupee coin; but an hour, an honest man, an MBA.",
    tags: ["articles"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-article-the",
    topic: "sentence-correction",
    title: "Using the definite article",
    prompt: "Choose the **correct** sentence:",
    options: [
      "He is best student in the class.",
      "He is the best student in the class.",
      "He is a best student in the class.",
      "He is best student in class.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["Superlatives take the definite article.", "'Best' identifies a unique person."],
    solution:
      "1. A superlative identifies something unique, so it takes **the**.\n2. 'He is **the best** student in the class' is correct.\n\nAnswer: **He is the best student in the class.**",
    approach: "Superlatives, ordinals and unique things all take 'the': the tallest, the first, the sun.",
    tags: ["articles"],
    timeTargetSec: 40,
  },
  {
    slug: "sc2-parallel-not-only",
    topic: "sentence-correction",
    title: "Not only ... but also",
    prompt: "Choose the **correct** sentence:",
    options: [
      "She not only sings but also she dances.",
      "She not only sings but also dances.",
      "She not only sings but dances also well.",
      "Not only she sings but also dances.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: [
      "The words after 'not only' and 'but also' must have the same grammatical form.",
      "Here both should be plain verbs.",
    ],
    solution:
      "1. 'Not only' and 'but also' must be followed by matching structures.\n2. 'not only **sings** but also **dances**' pairs two verbs correctly.\n\nAnswer: **She not only sings but also dances.**",
    approach: "Correlative pairs demand parallel structures. Read the sentence with each half alone to check both make sense.",
    tags: ["parallelism"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-parallel-list",
    topic: "sentence-correction",
    title: "A parallel list",
    prompt: "Choose the **correct** sentence:",
    options: [
      "The job requires accuracy, patience and being punctual.",
      "The job requires accuracy, patience and punctuality.",
      "The job requires being accurate, patience and punctuality.",
      "The job requires to be accurate, patient and punctuality.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["Items in a list must share a grammatical form.", "Three nouns are needed here."],
    solution:
      "1. The list needs three items of the same form.\n2. **accuracy, patience and punctuality** are all nouns.\n\nAnswer: **The job requires accuracy, patience and punctuality.**",
    approach: "Read the list with the introducing phrase repeated before each item. Anything that does not fit breaks the parallelism.",
    tags: ["parallelism"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-modifier-walking",
    topic: "sentence-correction",
    title: "A dangling modifier",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Walking through the park, the flowers looked beautiful.",
      "Walking through the park, she thought the flowers looked beautiful.",
      "Walking through the park, the beauty of flowers was seen.",
      "The flowers looked beautiful, walking through the park.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["The opening phrase must describe the subject that follows it.", "Flowers cannot walk."],
    solution:
      "1. The introductory phrase attaches to whatever noun comes next.\n2. Only in the second sentence is that noun *she*, who can actually walk.\n\nAnswer: **Walking through the park, she thought the flowers looked beautiful.**",
    approach: "After an introductory participial phrase, check the very next noun. If it could not perform the action, the modifier dangles.",
    tags: ["modifiers"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-modifier-only",
    topic: "sentence-correction",
    title: "Placing 'only'",
    prompt:
      "Which sentence means that **she** was given the prize and **nobody else**?",
    options: [
      "Only she was given the prize.",
      "She only was given the prize.",
      "She was given only the prize.",
      "She was only given the prize.",
    ],
    answer: 0,
    difficulty: "hard",
    hints: [
      "'Only' modifies whatever immediately follows it.",
      "To limit the person, put 'only' directly before her.",
    ],
    solution:
      "1. *Only* restricts the word that follows it.\n2. '**Only she** was given the prize' limits the recipient to her alone.\n3. 'Only the prize' would limit what she received; 'only given' would limit the action.\n\nAnswer: **Only she was given the prize.**",
    approach: "Move 'only' next to the word you mean to restrict. Its position changes the meaning of the sentence entirely.",
    tags: ["modifiers"],
    timeTargetSec: 70,
  },
  {
    slug: "sc2-pronoun-case",
    topic: "sentence-correction",
    title: "Pronoun case after a preposition",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Between you and I, the plan is flawed.",
      "Between you and me, the plan is flawed.",
      "Between you and myself, the plan is flawed.",
      "Between yourself and I, the plan is flawed.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["A preposition is followed by the object form of a pronoun.", "'Between' is a preposition, so it takes 'me'."],
    solution:
      "1. After a preposition the pronoun takes the object form.\n2. 'Between you and **me**' is correct.\n3. *Myself* is reflexive and needs an earlier 'I' in the sentence.\n\nAnswer: **Between you and me, the plan is flawed.**",
    approach: "Drop the other person and test the pronoun alone: 'between me' sounds right, 'between I' does not.",
    tags: ["pronouns"],
    timeTargetSec: 55,
  },
  {
    slug: "sc2-pronoun-agreement",
    topic: "sentence-correction",
    title: "Pronoun agreement",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Everyone must bring their own pen.",
      "Everyone must bring his or her own pen.",
      "Everyone must bring they own pen.",
      "Everyone must bring theirs own pen.",
    ],
    answer: 1,
    difficulty: "hard",
    hints: [
      "'Everyone' is grammatically singular.",
      "Formal grammar requires a singular pronoun to match it.",
    ],
    solution:
      "1. *Everyone* is singular, so a strictly formal sentence takes a singular pronoun.\n2. '**his or her**' agrees in number.\n3. (Singular 'their' is widely accepted in modern usage, but examinations test the formal rule.)\n\nAnswer: **Everyone must bring his or her own pen.**",
    approach:
      "Indefinite pronouns — everyone, somebody, nobody, each — are singular for agreement. Exam papers still expect the formal singular pronoun.",
    tags: ["pronouns"],
    timeTargetSec: 70,
  },
  {
    slug: "sc2-double-negative",
    topic: "sentence-correction",
    title: "A double negative",
    prompt: "Choose the **correct** sentence:",
    options: [
      "I did not see nobody in the hall.",
      "I did not see anybody in the hall.",
      "I did not saw anybody in the hall.",
      "I have not seen nobody in the hall.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["Two negatives in one clause cancel out.", "After 'did not', use 'anybody'."],
    solution:
      "1. 'Did not ... nobody' is a double negative and is incorrect.\n2. '**I did not see anybody**' is correct, and 'did' is followed by the base form *see*.\n\nAnswer: **I did not see anybody in the hall.**",
    approach: "One negative per clause. After the auxiliary 'did', the main verb always takes its base form.",
    tags: ["negatives"],
    timeTargetSec: 45,
  },
  {
    slug: "sc2-reported-speech",
    topic: "sentence-correction",
    title: "Reported speech",
    prompt: "Choose the **correct** reported form of: *'I am going to Delhi tomorrow,' he said.*",
    options: [
      "He said that he is going to Delhi tomorrow.",
      "He said that he was going to Delhi the next day.",
      "He said that he was going to Delhi tomorrow.",
      "He says that he was going to Delhi the next day.",
    ],
    answer: 1,
    difficulty: "medium",
    hints: [
      "With a past reporting verb, the tense shifts back.",
      "Time words shift too: tomorrow becomes 'the next day'.",
    ],
    solution:
      "1. *Said* is past, so 'am going' becomes '**was going**'.\n2. *Tomorrow* becomes **the next day**.\n\nAnswer: **He said that he was going to Delhi the next day.**",
    approach: "In reported speech both the tense and the time reference move one step into the past. Changing only one of them is the usual half-correct answer.",
    tags: ["reported speech"],
    timeTargetSec: 60,
  },
  {
    slug: "sc2-active-passive",
    topic: "sentence-correction",
    title: "Changing to the passive",
    prompt: "Choose the correct **passive** form of: *The chef prepared the meal.*",
    options: [
      "The meal was prepared by the chef.",
      "The meal is prepared by the chef.",
      "The meal has prepared by the chef.",
      "The meal was prepare by the chef.",
    ],
    answer: 0,
    difficulty: "easy",
    hints: ["The original is in the simple past.", "Passive = was/were + past participle."],
    solution:
      "1. The active verb *prepared* is simple past, so the passive is *was* + past participle.\n2. '**The meal was prepared by the chef**' is correct.\n\nAnswer: **The meal was prepared by the chef.**",
    approach: "Keep the tense unchanged when switching voice. Simple past becomes was/were + participle; present becomes is/are + participle.",
    tags: ["voice"],
    timeTargetSec: 45,
  },
  {
    slug: "sc2-redundancy",
    topic: "sentence-correction",
    title: "Avoiding redundancy",
    prompt: "Choose the **correct** sentence:",
    options: [
      "Please repeat that again.",
      "Please repeat that.",
      "Please again repeat that once more.",
      "Please re-repeat that.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["'Repeat' already contains the idea of doing something again.", "Adding 'again' says the same thing twice."],
    solution:
      "1. *Repeat* means to say again, so 'repeat again' is redundant.\n2. '**Please repeat that**' is correct.\n\nAnswer: **Please repeat that.**",
    approach: "Watch for built-in meanings: return back, revert back, ascend up, free gift and final conclusion are all redundant in the same way.",
    tags: ["redundancy"],
    timeTargetSec: 40,
  },
  {
    slug: "sc2-comparison-incomplete",
    topic: "sentence-correction",
    title: "A complete comparison",
    prompt: "Choose the **correct** sentence:",
    options: [
      "The climate of Delhi is hotter than Shimla.",
      "The climate of Delhi is hotter than that of Shimla.",
      "The climate of Delhi is more hotter than Shimla.",
      "Delhi climate is hotter than Shimla's climate is.",
    ],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The sentence compares two climates, not a climate and a city.",
      "'That of' stands in for the repeated noun.",
    ],
    solution:
      "1. The comparison must be between like things: the climate of Delhi and the climate of Shimla.\n2. '**that of** Shimla' supplies the second climate without repeating the word.\n\nAnswer: **The climate of Delhi is hotter than that of Shimla.**",
    approach: "Check that both sides of a comparison are the same kind of thing. 'That of' and 'those of' exist precisely to fix this.",
    tags: ["comparison"],
    timeTargetSec: 70,
  },
  {
    slug: "sc2-comparison-double",
    topic: "sentence-correction",
    title: "A double comparative",
    prompt: "Choose the **correct** sentence:",
    options: [
      "This book is more better than that one.",
      "This book is better than that one.",
      "This book is more good than that one.",
      "This book is the more better of the two.",
    ],
    answer: 1,
    difficulty: "easy",
    hints: ["'Better' is already the comparative of 'good'.", "Adding 'more' doubles the comparison."],
    solution:
      "1. *Better* is the comparative form, so 'more better' is incorrect.\n2. '**This book is better than that one**' is correct.\n\nAnswer: **This book is better than that one.**",
    approach: "Use either -er or 'more', never both. The same applies to superlatives: 'most best' is wrong.",
    tags: ["comparison"],
    timeTargetSec: 40,
  },

  /* ── Sentence Completion ───────────────────────────────────────── */
  {
    slug: "sl2-connector-contrast",
    topic: "sentence-completion",
    title: "A connector showing contrast",
    prompt:
      "Fill in the blank:\n\n> The team trained hard all season; ______, they failed to reach the final.",
    options: ["therefore", "nevertheless", "moreover", "similarly"],
    answer: 1,
    difficulty: "easy",
    hints: ["The two halves point in opposite directions.", "Which connector signals a reversal?"],
    solution:
      "1. Hard training would suggest success, but the result was failure — a contrast.\n2. **Nevertheless** marks that reversal.\n\nAnswer: **nevertheless**.",
    approach: "Decide the relation between the halves before reading the options: contrast, cause, addition or example. Each has its own family of connectors.",
    tags: ["connectors"],
    timeTargetSec: 40,
  },
  {
    slug: "sl2-connector-result",
    topic: "sentence-completion",
    title: "A connector showing result",
    prompt: "Fill in the blank:\n\n> The bridge was unsafe; ______, it was closed to traffic.",
    options: ["however", "accordingly", "otherwise", "nonetheless"],
    answer: 1,
    difficulty: "easy",
    hints: ["The second clause follows from the first.", "Which connector introduces a consequence?"],
    solution:
      "1. The closure is a consequence of the bridge being unsafe.\n2. **Accordingly** marks a result.\n\nAnswer: **accordingly**.",
    approach: "Result connectors — therefore, accordingly, consequently, hence — are interchangeable. Contrast connectors are not.",
    tags: ["connectors"],
    timeTargetSec: 40,
  },
  {
    slug: "sl2-connector-addition",
    topic: "sentence-completion",
    title: "A connector showing addition",
    prompt:
      "Fill in the blank:\n\n> The scheme is expensive; ______, it will take years to complete.",
    options: ["furthermore", "however", "instead", "otherwise"],
    answer: 0,
    difficulty: "easy",
    hints: ["Both halves make the same kind of criticism.", "Which connector adds a further point?"],
    solution:
      "1. Both clauses are objections, so the second adds to the first.\n2. **Furthermore** signals addition.\n\nAnswer: **furthermore**.",
    approach: "When both halves push the same way, the connector adds; when they clash, it contrasts. Read both halves before choosing.",
    tags: ["connectors"],
    timeTargetSec: 40,
  },
  {
    slug: "sl2-blank-single-word",
    topic: "sentence-completion",
    title: "A single word",
    prompt:
      "Fill in the blank:\n\n> Despite the ______ evidence against him, the jury acquitted the defendant.",
    options: ["scanty", "overwhelming", "missing", "doubtful"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "'Despite' means the two halves must clash.",
      "For an acquittal to be surprising, the evidence must have been strong.",
    ],
    solution:
      "1. *Despite* demands a contrast with the acquittal.\n2. Only **overwhelming** evidence makes an acquittal surprising.\n3. Scanty, missing or doubtful evidence would make it expected.\n\nAnswer: **overwhelming**.",
    approach: "Let the connector set the direction, then choose the word that creates the required tension. Three options here remove the tension entirely.",
    tags: ["single blank"],
    timeTargetSec: 55,
  },
  {
    slug: "sl2-blank-two-words",
    topic: "sentence-completion",
    title: "Two blanks",
    prompt:
      "Fill in the blanks:\n\n> Although the novel was ______, critics found its ending strangely ______.",
    options: [
      "dull … gripping",
      "acclaimed … disappointing",
      "acclaimed … satisfying",
      "brief … short",
    ],
    answer: 1,
    difficulty: "medium",
    hints: ["'Although' demands a contrast between the two halves.", "A praised novel with a poor ending creates that tension."],
    solution:
      "1. *Although* requires the two halves to clash.\n2. **acclaimed … disappointing** delivers it: a well-received novel with a weak ending.\n3. 'Acclaimed … satisfying' agrees rather than contrasts, and 'brief … short' repeats itself.\n\nAnswer: **acclaimed … disappointing**.",
    approach: "With two blanks, test pairs rather than single words. One wrong half is enough to eliminate the option.",
    tags: ["double blank"],
    timeTargetSec: 60,
  },
  {
    slug: "sl2-blank-cause-word",
    topic: "sentence-completion",
    title: "Filling a causal blank",
    prompt:
      "Fill in the blank:\n\n> Her argument was so ______ that even her opponents were persuaded.",
    options: ["weak", "cogent", "lengthy", "obscure"],
    answer: 1,
    difficulty: "medium",
    hints: ["The result was that opponents were persuaded.", "Which word describes an argument strong enough to do that?"],
    solution:
      "1. Persuading opponents requires a strong, clear argument.\n2. **Cogent** means clear, logical and convincing.\n3. Weak, lengthy and obscure would not persuade anyone.\n\nAnswer: **cogent**.",
    approach: "Use the consequence stated in the sentence to fix the quality required. 'So ... that' always signals that relation.",
    tags: ["single blank"],
    timeTargetSec: 55,
  },
  {
    slug: "sl2-blank-negative-word",
    topic: "sentence-completion",
    title: "A negative blank",
    prompt:
      "Fill in the blank:\n\n> The manager's ______ manner discouraged the staff from raising concerns.",
    options: ["approachable", "brusque", "cheerful", "patient"],
    answer: 1,
    difficulty: "medium",
    hints: ["The effect was that people did not speak up.", "Which word describes a manner that puts people off?"],
    solution:
      "1. Staff were discouraged, so the manner must have been off-putting.\n2. **Brusque** means abrupt and curt.\n3. Approachable, cheerful and patient would all encourage people instead.\n\nAnswer: **brusque**.",
    approach: "Work out whether the blank needs a positive or a negative word first. That alone often leaves only one candidate.",
    tags: ["single blank"],
    timeTargetSec: 55,
  },
  {
    slug: "sl2-para-jumble-bicycle",
    topic: "sentence-completion",
    title: "Arranging four sentences",
    prompt:
      "Arrange the sentences into a coherent paragraph:\n\n**P.** They were used first for carrying messages.\n**Q.** Pigeons have served humans for thousands of years.\n**R.** Today they are kept mostly for sport and show.\n**S.** Later they were bred for their appearance.",
    options: ["Q P S R", "P Q S R", "Q S P R", "P S Q R"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Which sentence introduces the subject by name rather than with a pronoun?",
      "'Later' and 'today' place the last two sentences in order.",
    ],
    solution:
      "1. **Q** names pigeons and can stand alone, so it opens.\n2. **P** gives the earliest use ('first').\n3. **S** follows with 'later'.\n4. **R** closes with 'today'.\n\nAnswer: **Q P S R**.",
    approach:
      "Find the opening sentence first: it introduces the subject by name rather than by a pronoun. Then order the rest by their time markers.",
    tags: ["para jumble"],
    timeTargetSec: 75,
  },
  {
    slug: "sl2-para-jumble-tea",
    topic: "sentence-completion",
    title: "Arranging a paragraph",
    prompt:
      "Arrange the sentences into a coherent paragraph:\n\n**P.** It soon spread along trade routes to the west.\n**Q.** Tea was first drunk in China thousands of years ago.\n**R.** Today it is the most widely consumed drink after water.\n**S.** By the seventeenth century it had reached Europe.",
    options: ["Q P S R", "Q S P R", "P Q S R", "P S Q R"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Only one sentence introduces tea without referring back.",
      "'It soon spread' must follow the origin; 'by the seventeenth century' comes after that.",
    ],
    solution:
      "1. **Q** introduces tea and its origin — it opens.\n2. **P** follows with 'it soon spread'.\n3. **S** gives the later date.\n4. **R** closes with 'today'.\n\nAnswer: **Q P S R**.",
    approach: "Chronology usually settles a jumble. Look for time markers: first, soon, by then, today.",
    tags: ["para jumble"],
    timeTargetSec: 75,
  },
  {
    slug: "sl2-blank-vocabulary-fit",
    topic: "sentence-completion",
    title: "The word that fits",
    prompt:
      "Fill in the blank:\n\n> The witness gave a ______ account, omitting nothing of importance.",
    options: ["vague", "meticulous", "hurried", "biased"],
    answer: 1,
    difficulty: "medium",
    hints: ["'Omitting nothing' tells you the account was complete.", "Which word means thorough and careful?"],
    solution:
      "1. Omitting nothing of importance means the account was thorough.\n2. **Meticulous** means showing great attention to detail.\n3. Vague, hurried and biased all suggest the opposite.\n\nAnswer: **meticulous**.",
    approach: "The clause after the blank usually defines it. Read the whole sentence before choosing rather than stopping at the gap.",
    tags: ["single blank"],
    timeTargetSec: 50,
  },
  {
    slug: "sl2-blank-pair-cause",
    topic: "sentence-completion",
    title: "A causal pair",
    prompt:
      "Fill in the blanks:\n\n> Because the instructions were ______, the assembly proved ______ than expected.",
    options: [
      "clear … harder",
      "confusing … easier",
      "confusing … harder",
      "detailed … harder",
    ],
    answer: 2,
    difficulty: "medium",
    hints: ["'Because' means the second half follows from the first.", "Poor instructions make a task harder, not easier."],
    solution:
      "1. *Because* demands that the second half follow from the first.\n2. **confusing … harder** is the only consistent pair.\n3. 'Clear … harder' and 'confusing … easier' both contradict themselves.\n\nAnswer: **confusing … harder**.",
    approach: "A causal connector requires the halves to agree in direction. Contrast connectors require the opposite, so identify the connector first.",
    tags: ["double blank"],
    timeTargetSec: 60,
  },
  {
    slug: "sl2-connector-example",
    topic: "sentence-completion",
    title: "Introducing an example",
    prompt:
      "Fill in the blank:\n\n> Several cities have banned older vehicles; ______, Delhi withdrew diesel cars over ten years old.",
    options: ["for instance", "in contrast", "nevertheless", "conversely"],
    answer: 0,
    difficulty: "easy",
    hints: ["The second clause gives a specific case of the first.", "Which connector introduces an example?"],
    solution:
      "1. Delhi is one instance of the general claim about cities.\n2. **For instance** introduces an example.\n\nAnswer: **for instance**.",
    approach: "A general statement followed by a specific case calls for an example connector: for instance, for example, notably.",
    tags: ["connectors"],
    timeTargetSec: 40,
  },
];
