import type { AptitudeSeed } from "./types.js";

/** Percentages — the standard placement and bank-exam set. */
export const BANK_PERCENTAGES: AptitudeSeed[] = [
  {
    slug: "pc2-find-the-number",
    topic: "percentages",
    title: "Finding the number from a part",
    prompt: "If **30% of a number is 12.6**, what is the number?",
    options: ["36", "40", "42", "48"],
    answer: 2,
    difficulty: "easy",
    hints: ["Write it as 0.30 × N = 12.6.", "Divide 12.6 by 0.3."],
    solution: "1. 0.30 × N = 12.6\n2. N = 12.6 ÷ 0.30 = **42**.\n3. Check: 30% of 42 = 12.6. ✓\n\nAnswer: **42**.",
    approach: "Percent of a number is multiplication; going back to the number is division. Always check by taking the percentage of your answer.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-what-percent-of-a-day",
    topic: "percentages",
    title: "What percent of a day",
    prompt: "**3 hours** is what percent of a **day**?",
    options: ["10%", "12.5%", "15%", "20%"],
    answer: 1,
    difficulty: "easy",
    hints: ["A day is 24 hours.", "3/24 as a percentage."],
    solution: "1. A day = 24 hours.\n2. 3/24 = 1/8 = **12.5%**.\n\nAnswer: **12.5%**.",
    approach: "Put both quantities in the same unit before dividing. The fractions worth memorising: 1/8 = 12.5%, 1/6 = 16⅔%, 1/3 = 33⅓%, 3/8 = 37.5%.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-pass-mark-fail-by",
    topic: "percentages",
    title: "Total marks from a fail margin",
    prompt: "A student must score **33%** to pass. He gets **125 marks** and fails by **40 marks**. What are the maximum marks?",
    options: ["400", "450", "500", "600"],
    answer: 2,
    difficulty: "easy",
    hints: ["Passing marks = what he scored plus the shortfall.", "165 is 33% of the total."],
    solution:
      "1. Passing marks = 125 + 40 = 165.\n2. 33% of total = 165, so total = 165 ÷ 0.33 = **500**.\n3. Check: 33% of 500 = 165. ✓\n\nAnswer: **500**.",
    approach: "Turn the story into one equation: the pass mark is both a percentage of the maximum and a number you can compute. Then divide.",
    tags: ["exam marks"],
    timeTargetSec: 50,
  },
  {
    slug: "pc2-income-more-then-less",
    topic: "percentages",
    title: "A is 25% more than B",
    prompt: "If **A's income is 25% more than B's**, then B's income is what percent **less than A's**?",
    options: ["16⅔%", "20%", "22%", "25%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Take B = 100, so A = 125.", "The gap of 25 is measured against A, not against B."],
    solution:
      "1. Let B = 100, so A = 125.\n2. B falls short of A by 25, and as a fraction of A that is 25/125 = 1/5.\n3. So B is **20%** less than A.\n\nAnswer: **20%**.",
    approach:
      "If A is x% more than B, then B is 100x/(100 + x) percent less than A. The two percentages differ because they use different bases, and picking 100 for the base removes all the algebra.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-income-less-then-more",
    topic: "percentages",
    title: "A is 20% less than B",
    prompt: "If **A's income is 20% less than B's**, then B's income is what percent **more than A's**?",
    options: ["20%", "22.5%", "25%", "30%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Take B = 100, so A = 80.", "The gap of 20 is measured against A."],
    solution:
      "1. Let B = 100, so A = 80.\n2. B exceeds A by 20, and as a fraction of A that is 20/80 = 1/4.\n3. So B is **25%** more than A.\n\nAnswer: **25%**.",
    approach: "If A is x% less than B, then B is 100x/(100 − x) percent more than A. Note the minus sign: a fall of 20% needs a rise of 25% to undo it.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-consumption-cut-25",
    topic: "percentages",
    title: "Keeping the bill unchanged",
    prompt: "The price of sugar rises by **25%**. By what percent must a family **reduce its consumption** so that its expenditure on sugar is unchanged?",
    options: ["16⅔%", "20%", "25%", "30%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Expenditure = price × quantity.", "If the price becomes 125, the quantity must become 100/125 of what it was."],
    solution:
      "1. Take price 100 and consumption 100, so expenditure = 10,000.\n2. New price = 125, so consumption must be 10,000 ÷ 125 = 80.\n3. Reduction = 20 out of 100 = **20%**.\n\nAnswer: **20%**.",
    approach: "For a price rise of r%, the consumption cut that keeps spending level is 100r/(100 + r) percent. For a price fall it is 100r/(100 − r) percent more consumption.",
    tags: ["expenditure"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-price-rise-from-cut",
    topic: "percentages",
    title: "Working back to the price rise",
    prompt:
      "When the price of a commodity rose, a family **reduced its consumption by 20%** and its expenditure stayed the same. By what percent did the **price rise**?",
    options: ["20%", "25%", "30%", "33⅓%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Consumption fell to 80% of what it was, and price × quantity is unchanged.", "New price × 80 = old price × 100."],
    solution:
      "1. Let the old price be p and consumption 100, so expenditure = 100p.\n2. New consumption = 80, so the new price q satisfies 80q = 100p → q = 1.25p.\n3. The price rose by **25%**.\n\nAnswer: **25%**.",
    approach: "This is the previous question read backwards. Fixing the product price × quantity and solving for the missing factor handles both directions.",
    tags: ["expenditure"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-successive-increase-decrease",
    topic: "percentages",
    title: "Up 20%, then down 20%",
    prompt: "A salary is **increased by 20%** and the new figure is then **decreased by 20%**. What is the net change?",
    options: ["4% decrease", "No change", "2% increase", "4% increase"],
    answer: 0,
    difficulty: "easy",
    hints: ["The decrease applies to the raised figure, not to the original.", "Multiply the factors: 1.20 × 0.80."],
    solution:
      "1. Take the salary as 100. After +20%: 120.\n2. After −20% of 120: 120 − 24 = 96.\n3. Net change = −4, a **4% decrease**.\n\nAnswer: **4% decrease**.",
    approach:
      "An equal rise and fall of x% always ends in a net loss of x²/100 percent. Chaining multipliers (1.2 × 0.8 = 0.96) is the reliable way to see it.",
    tags: ["successive change"],
    timeTargetSec: 45,
  },
  {
    slug: "pc2-net-effect-on-revenue",
    topic: "percentages",
    title: "Price down, sales up",
    prompt: "The price of an article is **reduced by 20%** and its sales **rise by 30%**. What is the net effect on **revenue**?",
    options: ["4% increase", "6% increase", "10% increase", "10% decrease"],
    answer: 0,
    difficulty: "medium",
    hints: ["Revenue = price × quantity, so multiply the two factors.", "0.80 × 1.30 = 1.04."],
    solution:
      "1. Revenue factor = 0.80 × 1.30 = 1.04.\n2. That is a **4% increase**.\n\nAnswer: **4% increase**.",
    approach: "Two percentage changes on a product multiply: a% and b% give a net of a + b + ab/100. Here −20 + 30 − 6 = +4.",
    tags: ["successive change"],
    timeTargetSec: 50,
  },
  {
    slug: "pc2-markup-discount-net",
    topic: "percentages",
    title: "Marked up, then discounted",
    prompt: "A shopkeeper raises the price of an article by **30%** and then offers a **10% discount**. What is the net change in price?",
    options: ["15% increase", "17% increase", "20% increase", "22% increase"],
    answer: 1,
    difficulty: "easy",
    hints: ["Chain the multipliers rather than adding the percentages.", "1.30 × 0.90 = 1.17."],
    solution: "1. Net factor = 1.30 × 0.90 = 1.17.\n2. That is a **17% increase**.\n\nAnswer: **17% increase**.",
    approach: "Never add or subtract successive percentages directly. Convert each to a multiplier and multiply; the answer is always slightly off the naive sum.",
    tags: ["successive change"],
    timeTargetSec: 45,
  },
  {
    slug: "pc2-original-after-both-changes",
    topic: "percentages",
    title: "Working back through two changes",
    prompt: "A number is **increased by 20%** and then **decreased by 20%**, giving **9,600**. What was the original number?",
    options: ["9,216", "9,800", "10,000", "10,400"],
    answer: 2,
    difficulty: "medium",
    hints: ["The two changes together multiply the number by 0.96.", "Divide 9,600 by 0.96."],
    solution:
      "1. Net factor = 1.2 × 0.8 = 0.96.\n2. 0.96 × original = 9,600, so original = 9,600 ÷ 0.96 = **10,000**.\n3. Check: 10,000 → 12,000 → 9,600. ✓\n\nAnswer: **10,000**.",
    approach: "Collapse the chain of changes into one multiplier, then divide the final value by it. Reversing the steps one at a time works too but invites sign errors.",
    tags: ["successive change"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-election-valid-votes",
    topic: "percentages",
    title: "Valid votes in an election",
    prompt:
      "In an election between two candidates, **20% of the votes polled were invalid**. The winner secured **55% of the valid votes**. If **7,500 votes** were polled in all, how many valid votes did the **other candidate** get?",
    options: ["2,700", "3,000", "3,300", "3,375"],
    answer: 0,
    difficulty: "medium",
    hints: ["Find the valid votes first: 80% of 7,500.", "The other candidate got 45% of those."],
    solution:
      "1. Valid votes = 80% of 7,500 = 6,000.\n2. The other candidate got 100% − 55% = 45% of the valid votes.\n3. 45% of 6,000 = **2,700**.\n\nAnswer: **2,700**.",
    approach:
      "Percentages of percentages must be applied in sequence to the right base. Taking 45% of the 7,500 polled (3,375) is the standard trap, and it is offered here.",
    tags: ["elections"],
    timeTargetSec: 75,
  },
  {
    slug: "pc2-three-candidates-winner-share",
    topic: "percentages",
    title: "Winner's share among three candidates",
    prompt:
      "Three candidates polled **1,136**, **7,636** and **11,628** votes respectively. What **percentage of the total votes** did the winner get?",
    options: ["47%", "51%", "57%", "60%"],
    answer: 2,
    difficulty: "easy",
    hints: ["Add all three to get the total.", "11,628 out of 20,400."],
    solution:
      "1. Total = 1,136 + 7,636 + 11,628 = 20,400.\n2. Winner's share = 11,628 / 20,400 = 0.57 = **57%**.\n\nAnswer: **57%**.",
    approach: "Share questions are one division. Sum the parts carefully — an arithmetic slip in the total quietly moves the answer by whole percentage points.",
    tags: ["elections"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-two-numbers-more-than-third",
    topic: "percentages",
    title: "Comparing two numbers through a third",
    prompt:
      "Two numbers are respectively **20%** and **50% more** than a third number. The **first** is what percent of the **second**?",
    options: ["70%", "75%", "80%", "90%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Take the third number as 100.", "The two numbers are 120 and 150."],
    solution:
      "1. Let the third number be 100. Then the first is 120 and the second is 150.\n2. 120/150 = 0.80 = **80%**.\n\nAnswer: **80%**.",
    approach: "Anchor the quantity everything else is described against at 100. Every comparison then reads straight off without algebra.",
    tags: ["comparison"],
    timeTargetSec: 50,
  },
  {
    slug: "pc2-percent-of-percent",
    topic: "percentages",
    title: "40% of 60 is what percent of 240",
    prompt: "**40% of 60** is what percent of **240**?",
    options: ["8%", "10%", "12%", "15%"],
    answer: 1,
    difficulty: "easy",
    hints: ["Compute 40% of 60 first.", "24 as a fraction of 240."],
    solution: "1. 40% of 60 = 24.\n2. 24/240 = 0.10 = **10%**.\n\nAnswer: **10%**.",
    approach: "Work strictly left to right: compute the stated quantity, then express it against the new base. Mixing the two bases is the only way to go wrong.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-twenty-percent-a-equals-thirty-b",
    topic: "percentages",
    title: "20% of A equals 30% of B",
    prompt: "If **20% of A = 30% of B**, then **A : B** is:",
    options: ["2 : 3", "3 : 2", "4 : 5", "5 : 4"],
    answer: 1,
    difficulty: "easy",
    hints: ["Write it as 0.2A = 0.3B.", "Rearranged, A/B = 0.3/0.2."],
    solution: "1. 0.2A = 0.3B → A/B = 0.3/0.2 = 3/2.\n2. So A : B = **3 : 2**.\n\nAnswer: **3 : 2**.",
    approach: "When x% of A = y% of B, the ratio A : B is y : x — the percentages swap sides. Writing the equation out prevents inverting it by accident.",
    tags: ["ratio"],
    timeTargetSec: 45,
  },
  {
    slug: "pc2-ninety-percent-a-thirty-b",
    topic: "percentages",
    title: "B as a percentage of A",
    prompt: "If **90% of A = 30% of B** and **B = x% of A**, what is the value of **x**?",
    options: ["100", "200", "300", "400"],
    answer: 2,
    difficulty: "medium",
    hints: ["0.9A = 0.3B gives B in terms of A.", "B = 3A, so B is 300% of A."],
    solution: "1. 0.9A = 0.3B → B = 3A.\n2. B as a percentage of A = 300%, so x = **300**.\n\nAnswer: **300**.",
    approach: "A percentage above 100 is perfectly ordinary — it just means the quantity is larger than its base. Candidates who assume percentages must be under 100 pick 100 here.",
    tags: ["ratio"],
    timeTargetSec: 50,
  },
  {
    slug: "pc2-savings-increase",
    topic: "percentages",
    title: "The effect on savings",
    prompt:
      "A man spends **75% of his income**. His income rises by **20%** and his expenditure by **10%**. By what percent do his **savings** increase?",
    options: ["25%", "40%", "50%", "60%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Take the income as 100, so expenditure is 75 and savings 25.", "New income 120, new expenditure 82.5."],
    solution:
      "1. Income 100, expenditure 75, savings 25.\n2. New income = 120; new expenditure = 75 × 1.10 = 82.5.\n3. New savings = 120 − 82.5 = 37.5.\n4. Increase = 12.5/25 = **50%**.\n\nAnswer: **50%**.",
    approach:
      "Savings is a residue, so it must be computed, never assumed to move with either figure. A small percentage of a large income easily outweighs a large percentage of small savings.",
    tags: ["income and savings"],
    timeTargetSec: 90,
  },
  {
    slug: "pc2-scholarship-percentage",
    topic: "percentages",
    title: "Students without a scholarship",
    prompt:
      "In a school **60% of the students are boys** and the rest girls. **25% of the boys** and **50% of the girls** receive a scholarship. What percent of students do **not** receive one?",
    options: ["35%", "50%", "65%", "75%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Compute the scholarship holders in each group separately.", "0.60 × 0.25 and 0.40 × 0.50, then subtract from 100%."],
    solution:
      "1. Boys with a scholarship = 60% × 25% = 15% of all students.\n2. Girls with one = 40% × 50% = 20%.\n3. Total with a scholarship = 35%, so without = 100% − 35% = **65%**.\n\nAnswer: **65%**.",
    approach:
      "Apply each rate to its own subgroup, express both as a percentage of the whole, then subtract. Averaging 25% and 50% is wrong because the groups are unequal in size.",
    tags: ["weighted"],
    timeTargetSec: 75,
  },
  {
    slug: "pc2-failed-in-both",
    topic: "percentages",
    title: "Passing in both subjects",
    prompt:
      "In an examination **35% failed in Mathematics**, **45% failed in English** and **20% failed in both**. What percent **passed in both** subjects?",
    options: ["20%", "30%", "40%", "45%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Use the union rule: failed in at least one = 35 + 45 − 20.", "Passing in both is the complement of failing in at least one."],
    solution:
      "1. Failed in at least one = 35% + 45% − 20% = 60%.\n2. Passed in both = 100% − 60% = **40%**.\n\nAnswer: **40%**.",
    approach:
      "Subtract the overlap once when adding two groups, then take the complement. Adding 35 and 45 without removing the 20 counted twice gives 20%, which is offered.",
    tags: ["set theory"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-population-two-years-ago",
    topic: "percentages",
    title: "Population two years ago",
    prompt: "The population of a town is **176,400** and grows at **5% per annum**. What was it **two years ago**?",
    options: ["1,50,000", "1,60,000", "1,64,000", "1,68,000"],
    answer: 1,
    difficulty: "medium",
    hints: ["Two years of growth multiplies by 1.05².", "Divide 176,400 by 1.1025."],
    solution:
      "1. 1.05² = 1.1025.\n2. Population two years ago = 176,400 ÷ 1.1025 = **1,60,000**.\n3. Check: 160,000 → 168,000 → 176,400. ✓\n\nAnswer: **1,60,000**.",
    approach: "Growth forwards multiplies; going backwards divides. Subtracting 10% from the present figure is not the inverse of two 5% rises.",
    tags: ["growth"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-machine-depreciation",
    topic: "percentages",
    title: "Depreciation over two years",
    prompt: "A machine worth **₹1,00,000** depreciates at **10% per annum**. What is its value after **two years**?",
    options: ["₹80,000", "₹81,000", "₹82,000", "₹90,000"],
    answer: 1,
    difficulty: "easy",
    hints: ["Each year the value becomes 90% of what it was.", "1,00,000 × 0.9 × 0.9."],
    solution:
      "1. After one year: 1,00,000 × 0.90 = 90,000.\n2. After two years: 90,000 × 0.90 = **₹81,000**.\n\nAnswer: **₹81,000**.",
    approach: "Depreciation is compound decay: multiply by (1 − r/100) once per period. Two years at 10% removes 19%, not 20%.",
    tags: ["depreciation"],
    timeTargetSec: 45,
  },
  {
    slug: "pc2-exceeds-by",
    topic: "percentages",
    title: "30% exceeds 20% by 18",
    prompt: "**30% of a number exceeds 20% of it by 18.** What is the number?",
    options: ["120", "150", "180", "200"],
    answer: 2,
    difficulty: "easy",
    hints: ["The difference is 10% of the number.", "10% of N = 18."],
    solution: "1. 30% − 20% = 10% of the number.\n2. 0.10N = 18 → N = **180**.\n\nAnswer: **180**.",
    approach: "Subtract the percentages first, then solve one equation. Setting up 0.3N − 0.2N = 18 and simplifying is the same thing done more slowly.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-absent-students",
    topic: "percentages",
    title: "Total from those present",
    prompt: "In a class **20% of the students were absent** and **32 were present**. What is the **total strength** of the class?",
    options: ["36", "40", "42", "45"],
    answer: 1,
    difficulty: "easy",
    hints: ["If 20% were absent, 80% were present.", "80% of the total = 32."],
    solution: "1. Present = 80% of total = 32.\n2. Total = 32 ÷ 0.80 = **40**.\n\nAnswer: **40**.",
    approach: "Convert the stated percentage into the one you were given a number for, then divide. Adding 20% to 32 gives 38.4 and is wrong, because the 20% is of the total, not of those present.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-dilute-salt-solution",
    topic: "percentages",
    title: "Diluting a salt solution",
    prompt:
      "**80 kg** of a solution contains **15% salt** by weight. How much **water** must be added so that the salt content falls to **10%**?",
    options: ["20 kg", "30 kg", "40 kg", "50 kg"],
    answer: 2,
    difficulty: "medium",
    hints: ["The salt does not change; only the total does.", "Salt = 12 kg, and 12 kg must become 10% of the new total."],
    solution:
      "1. Salt = 15% of 80 = 12 kg, and this stays fixed.\n2. For 12 kg to be 10% of the mixture, the new total = 12 ÷ 0.10 = 120 kg.\n3. Water to add = 120 − 80 = **40 kg**.\n\nAnswer: **40 kg**.",
    approach: "In dilution the solute is constant. Divide it by the target concentration to get the new total, then subtract the old total.",
    tags: ["mixtures"],
    timeTargetSec: 75,
  },
  {
    slug: "pc2-fraction-changed",
    topic: "percentages",
    title: "A fraction after two changes",
    prompt:
      "If the **numerator of a fraction is increased by 20%** and the **denominator decreased by 10%**, the new fraction is **20/21**. What was the original fraction?",
    options: ["3/5", "5/7", "5/8", "7/9"],
    answer: 1,
    difficulty: "hard",
    hints: ["Write the new fraction as (1.2n)/(0.9d).", "So n/d = (20/21) × (0.9/1.2)."],
    solution:
      "1. (1.2n)/(0.9d) = 20/21.\n2. n/d = (20/21) × (0.9/1.2) = (20/21) × 0.75 = 15/21 = **5/7**.\n3. Check: numerator 5 → 6, denominator 7 → 6.3, and 6/6.3 = 20/21. ✓\n\nAnswer: **5/7**.",
    approach: "Apply the multipliers to numerator and denominator separately, then invert the whole relation to recover the original. Checking the answer forwards is quick and worth doing.",
    tags: ["fractions"],
    timeTargetSec: 105,
  },
  {
    slug: "pc2-eight-percent-x-four-percent-y",
    topic: "percentages",
    title: "Relating two unknowns",
    prompt: "If **8% of x = 4% of y**, then **20% of x** is what percent of **y**?",
    options: ["5%", "10%", "15%", "20%"],
    answer: 1,
    difficulty: "medium",
    hints: ["8x = 4y gives y in terms of x.", "y = 2x, so compare 0.2x with 2x."],
    solution:
      "1. 8% of x = 4% of y → 8x = 4y → y = 2x.\n2. 20% of x = 0.2x.\n3. As a percentage of y: 0.2x / 2x = 0.10 = **10%**.\n\nAnswer: **10%**.",
    approach: "Reduce the given relation to y in terms of x, then substitute. Keeping everything in one variable makes the final ratio a cancellation rather than a calculation.",
    tags: ["ratio"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-chain-of-comparisons",
    topic: "percentages",
    title: "A chain of comparisons",
    prompt:
      "**A's marks are 20% more than B's**, and **B's marks are 25% less than C's**. A's marks are what percent of **C's**?",
    options: ["85%", "90%", "95%", "105%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Start from C = 100 and work down the chain.", "B = 75, then A = 1.2 × 75."],
    solution:
      "1. Let C = 100. Then B = 75 (25% less).\n2. A = 1.20 × 75 = 90.\n3. A as a percentage of C = **90%**.\n\nAnswer: **90%**.",
    approach: "Anchor the number at the far end of the chain and work towards the one you are asked about. Adding and subtracting the percentages (20 − 25 = −5) gives 95% and is wrong.",
    tags: ["comparison"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-quarter-of-quarter",
    topic: "percentages",
    title: "A percentage of a percentage",
    prompt: "**25% of 25% of a quantity is 25.** What is the quantity?",
    options: ["100", "200", "400", "625"],
    answer: 2,
    difficulty: "easy",
    hints: ["25% of 25% is 6.25% in all.", "0.0625 × Q = 25."],
    solution: "1. 0.25 × 0.25 = 0.0625.\n2. 0.0625 × Q = 25 → Q = 25 ÷ 0.0625 = **400**.\n\nAnswer: **400**.",
    approach: "Percentages of percentages multiply, they do not add. Collapse the chain to a single factor before dividing.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pc2-metric-tonnes-quintals",
    topic: "percentages",
    title: "Percent across units",
    prompt: "**40 quintals** is what percent of **2 metric tonnes**? (1 metric tonne = 10 quintals.)",
    options: ["50%", "100%", "150%", "200%"],
    answer: 3,
    difficulty: "medium",
    hints: ["Convert both to the same unit first.", "2 metric tonnes = 20 quintals."],
    solution:
      "1. 2 metric tonnes = 20 quintals.\n2. 40/20 = 2 = **200%**.\n\nAnswer: **200%**.",
    approach: "Convert units before dividing, and do not be alarmed by an answer above 100% — the first quantity is genuinely larger than the second.",
    tags: ["units"],
    timeTargetSec: 50,
  },
  {
    slug: "pc2-what-is-45-percent-of-750",
    topic: "percentages",
    title: "45% of 750",
    prompt: "What is **45% of 750**?",
    options: ["312.5", "325", "337.5", "350"],
    answer: 2,
    difficulty: "easy",
    hints: ["10% of 750 is 75.", "45% = 40% + 5% = 300 + 37.5."],
    solution: "1. 10% of 750 = 75, so 40% = 300.\n2. 5% = 37.5.\n3. 45% = 300 + 37.5 = **337.5**.\n\nAnswer: **337.5**.",
    approach: "Build awkward percentages from 10% and 5% blocks rather than multiplying directly. It is faster mentally and far less error-prone.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pc2-students-good-at-maths",
    topic: "percentages",
    title: "How many are not",
    prompt: "**72% of 25 students** are good at mathematics. How many are **not** good at it?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    difficulty: "easy",
    hints: ["Those who are not make up 28%.", "28% of 25."],
    solution: "1. Not good at it = 100% − 72% = 28%.\n2. 28% of 25 = 7.\n\nAnswer: **7**.",
    approach: "Take the complement first when it is the smaller figure — one multiplication instead of a multiplication and a subtraction.",
    tags: ["basics"],
    timeTargetSec: 35,
  },
  {
    slug: "pc2-salary-cut-then-raise-needed",
    topic: "percentages",
    title: "Undoing a pay cut",
    prompt:
      "A worker's salary is **reduced by 20%**. By what percent must the reduced salary be **increased** to bring it back to the original?",
    options: ["20%", "22%", "25%", "30%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Take the salary as 100; it becomes 80.", "The rise of 20 is measured against 80, not 100."],
    solution:
      "1. Salary 100 → 80 after the cut.\n2. To return to 100 it must rise by 20, and 20/80 = 0.25.\n3. So it must rise by **25%**.\n\nAnswer: **25%**.",
    approach: "A cut of x% needs a rise of 100x/(100 − x) percent to reverse it. The two are never equal because the base has changed.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pc2-x-percent-of-200",
    topic: "percentages",
    title: "Solving for the percentage",
    prompt: "If **x% of 200 = 40**, what is the value of **x**?",
    options: ["8", "20", "25", "40"],
    answer: 1,
    difficulty: "easy",
    hints: ["Write it as (x/100) × 200 = 40.", "That simplifies to 2x = 40."],
    solution: "1. (x/100) × 200 = 40 → 2x = 40.\n2. x = **20**.\n\nAnswer: **20**.",
    approach: "Percent means 'per hundred', so translate the sentence literally into an equation and solve. The value asked for is the percentage itself, not the quantity.",
    tags: ["basics"],
    timeTargetSec: 35,
  },
  {
    slug: "pc2-two-successive-discounts-single",
    topic: "percentages",
    title: "Two reductions as one",
    prompt: "Successive reductions of **10% and 20%** are together equivalent to a single reduction of:",
    options: ["26%", "28%", "30%", "32%"],
    answer: 1,
    difficulty: "easy",
    hints: ["After the first, 90% remains; after the second, 80% of that.", "0.9 × 0.8 = 0.72."],
    solution:
      "1. Remaining fraction = 0.90 × 0.80 = 0.72.\n2. Total reduction = 1 − 0.72 = **28%**.\n\nAnswer: **28%**.",
    approach: "Successive reductions of a% and b% equal a single reduction of a + b − ab/100. They never simply add.",
    tags: ["successive change"],
    timeTargetSec: 45,
  },
];
