import type { AptitudeSeed } from "./types.js";

/** Coding and decoding — letter shifts, number codes and substitution languages. */
export const BANK_CODING: AptitudeSeed[] = [
  {
    slug: "cd2-teacher-plus-two",
    topic: "coding-decoding",
    title: "If TEACHER is VGCEJGT",
    prompt: "In a certain code **TEACHER** is written as **VGCEJGT**. How is **CHILDREN** written in that code?",
    options: ["EJKNFTGP", "EJKNFTGO", "EJKMFTGP", "EJLNFTGP"],
    answer: 0,
    difficulty: "medium",
    hints: ["Compare the words letter by letter.", "T → V, E → G, A → C: every letter moves forward by two."],
    solution:
      "1. T → V, E → G, A → C, C → E, H → J, E → G, R → T: a shift of **+2** throughout.\n2. Applying +2 to CHILDREN: C→E, H→J, I→K, L→N, D→F, R→T, E→G, N→P.\n3. The code is **EJKNFTGP**.\n\nAnswer: **EJKNFTGP**.",
    approach: "Write the two words one above the other and note the shift at each position. A constant shift is the commonest code of all.",
    tags: ["letter shift"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-madras-plus-one",
    topic: "coding-decoding",
    title: "If MADRAS is NBESBT",
    prompt: "If **MADRAS** is coded as **NBESBT**, how is **BOMBAY** coded?",
    options: ["CPNCBZ", "CPNCBY", "CQNCBZ", "CPMCBZ"],
    answer: 0,
    difficulty: "easy",
    hints: ["M → N, A → B, D → E: each letter moves forward by one.", "Apply +1 to every letter of BOMBAY."],
    solution:
      "1. The shift is **+1** on every letter.\n2. B→C, O→P, M→N, B→C, A→B, Y→Z.\n3. The code is **CPNCBZ**.\n\nAnswer: **CPNCBZ**.",
    approach: "Check the shift on at least three letters before applying it. Y wrapping to Z is fine; only Z would wrap round to A.",
    tags: ["letter shift"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-friend-plus-two",
    topic: "coding-decoding",
    title: "If FRIEND is HTKGPF",
    prompt: "If **FRIEND** is coded as **HTKGPF**, how is **CANDLE** coded?",
    options: ["ECPFNG", "ECPGNF", "ECQFNG", "EDPFNG"],
    answer: 0,
    difficulty: "easy",
    hints: ["F → H, R → T, I → K: a shift of +2.", "Apply +2 to each letter of CANDLE."],
    solution:
      "1. The shift is **+2**.\n2. C→E, A→C, N→P, D→F, L→N, E→G.\n3. The code is **ECPFNG**.\n\nAnswer: **ECPFNG**.",
    approach: "Once the shift is confirmed, work letter by letter and resist reading the result as a word. The options differ by one letter each.",
    tags: ["letter shift"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-sister-minus-one",
    topic: "coding-decoding",
    title: "If SISTER is RHRSDQ",
    prompt: "In a certain code **SISTER** is written as **RHRSDQ**. How is **UNCLE** written?",
    options: ["TMBKD", "TMBLD", "TNBKD", "VOBKD"],
    answer: 0,
    difficulty: "easy",
    hints: ["S → R, I → H, S → R: each letter moves back by one.", "Apply −1 to UNCLE."],
    solution:
      "1. The shift is **−1** on every letter.\n2. U→T, N→M, C→B, L→K, E→D.\n3. The code is **TMBKD**.\n\nAnswer: **TMBKD**.",
    approach: "Backward shifts are as common as forward ones. Confirm the direction on the first two letters before continuing.",
    tags: ["letter shift"],
    timeTargetSec: 55,
  },
  {
    slug: "cd2-delhi-minus-one",
    topic: "coding-decoding",
    title: "If DELHI is CDKGH",
    prompt: "If **DELHI** is coded as **CDKGH**, how is **MUMBAI** coded?",
    options: ["LTLAZH", "LTLAZI", "LULAZH", "NVNCBJ"],
    answer: 0,
    difficulty: "easy",
    hints: ["D → C, E → D, L → K: a shift of −1.", "Apply −1 to MUMBAI."],
    solution:
      "1. The shift is **−1**.\n2. M→L, U→T, M→L, B→A, A→Z, I→H.\n3. The code is **LTLAZH**.\n\nAnswer: **LTLAZH**.",
    approach: "A wraps round to Z when shifting back by one. Handling that wrap correctly is what separates the right option from the others.",
    tags: ["letter shift"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-mouse-plus-three",
    topic: "coding-decoding",
    title: "If MOUSE is PRXVH",
    prompt: "If **MOUSE** is coded as **PRXVH**, how is **SHIFT** coded?",
    options: ["VKLIW", "VKLIV", "VJLIW", "WKLIW"],
    answer: 0,
    difficulty: "easy",
    hints: ["M → P, O → R, U → X: a shift of +3.", "Apply +3 to SHIFT."],
    solution:
      "1. The shift is **+3**.\n2. S→V, H→K, I→L, F→I, T→W.\n3. The code is **VKLIW**.\n\nAnswer: **VKLIW**.",
    approach: "Count forward three places in the alphabet for each letter. Writing the alphabet out once at the start of the paper saves time here.",
    tags: ["letter shift"],
    timeTargetSec: 55,
  },
  {
    slug: "cd2-road-plus-three",
    topic: "coding-decoding",
    title: "If ROAD is URDG",
    prompt: "If **ROAD** is written as **URDG**, how is **SWAN** written?",
    options: ["VZDQ", "VZDP", "VYDQ", "UZDQ"],
    answer: 0,
    difficulty: "easy",
    hints: ["R → U, O → R, A → D: a shift of +3.", "Apply +3 to SWAN."],
    solution: "1. The shift is **+3**.\n2. S→V, W→Z, A→D, N→Q.\n3. The code is **VZDQ**.\n\nAnswer: **VZDQ**.",
    approach: "W + 3 wraps to Z without going past it. Only letters beyond W would wrap round to the start of the alphabet.",
    tags: ["letter shift"],
    timeTargetSec: 50,
  },
  {
    slug: "cd2-sand-plus-one",
    topic: "coding-decoding",
    title: "If SAND is TBOE",
    prompt: "If the code for **SAND** is **TBOE**, what is the code for **BIRD**?",
    options: ["CJSE", "CJSF", "CKSE", "DJSE"],
    answer: 0,
    difficulty: "easy",
    hints: ["Each letter moves forward one place.", "B→C, I→J, R→S, D→E."],
    solution: "1. The shift is **+1**.\n2. B→C, I→J, R→S, D→E.\n3. The code is **CJSE**.\n\nAnswer: **CJSE**.",
    approach: "The simplest possible shift. Verify on every letter of the example so a two-step rule is not missed.",
    tags: ["letter shift"],
    timeTargetSec: 45,
  },
  {
    slug: "cd2-dog-plus-two",
    topic: "coding-decoding",
    title: "If DOG is FQI",
    prompt: "If **DOG** is coded as **FQI**, how is **CAT** coded?",
    options: ["ECV", "EBV", "ECU", "DBU"],
    answer: 0,
    difficulty: "easy",
    hints: ["D → F, O → Q, G → I: a shift of +2.", "Apply +2 to CAT."],
    solution: "1. The shift is **+2**.\n2. C→E, A→C, T→V.\n3. The code is **ECV**.\n\nAnswer: **ECV**.",
    approach: "Three letters is enough to confirm a constant shift. The distractors each get one letter wrong.",
    tags: ["letter shift"],
    timeTargetSec: 45,
  },
  {
    slug: "cd2-tripple-minus-one",
    topic: "coding-decoding",
    title: "A backward shift on a longer word",
    prompt: "If **TRIPPLE** is written as **SQHOOKD**, how is **DISPOSE** written?",
    options: ["CHRONRD", "CHRONRE", "CHROMRD", "EJTQPTF"],
    answer: 0,
    difficulty: "medium",
    hints: ["T → S, R → Q, I → H: a shift of −1.", "Apply −1 to every letter of DISPOSE."],
    solution:
      "1. The shift is **−1**.\n2. D→C, I→H, S→R, P→O, O→N, S→R, E→D.\n3. The code is **CHRONRD**.\n\nAnswer: **CHRONRD**.",
    approach: "Longer words give more chances to slip. Work through the letters in order and check the length of your answer at the end.",
    tags: ["letter shift"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-noida-plus-one",
    topic: "coding-decoding",
    title: "If NOIDA is OPJEB",
    prompt: "If **NOIDA** is coded as **OPJEB**, how is **DELHI** coded?",
    options: ["EFMIJ", "EFMIH", "EFLIJ", "DFMIJ"],
    answer: 0,
    difficulty: "easy",
    hints: ["Each letter moves forward one place.", "D→E, E→F, L→M, H→I, I→J."],
    solution: "1. The shift is **+1**.\n2. D→E, E→F, L→M, H→I, I→J.\n3. The code is **EFMIJ**.\n\nAnswer: **EFMIJ**.",
    approach: "Same rule, different word. Practising the +1 and −1 codes until they are automatic frees time for the harder items.",
    tags: ["letter shift"],
    timeTargetSec: 45,
  },
  {
    slug: "cd2-position-shift-house",
    topic: "coding-decoding",
    title: "A shift that grows with position",
    prompt: "If **HOUSE** is coded as **IQXWJ**, how is **TABLE** coded?",
    options: ["UCEPJ", "UCEPI", "UCDPJ", "VCEPJ"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "The shift is not constant. Compare each position separately.",
      "H → I is +1, O → Q is +2, U → X is +3, S → W is +4, E → J is +5.",
    ],
    solution:
      "1. The shifts run +1, +2, +3, +4, +5 by position.\n2. T + 1 = U, A + 2 = C, B + 3 = E, L + 4 = P, E + 5 = J.\n3. The code is **UCEPJ**.\n\nAnswer: **UCEPJ**.",
    approach:
      "When a constant shift fails, write the shift under each letter and look for a pattern in those numbers. Increasing shifts are the usual second guess.",
    tags: ["variable shift"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-computer-reverse-shift",
    topic: "coding-decoding",
    title: "Reversed, then shifted",
    prompt: "If **COMPUTER** is written as **RFUVQNPC**, how is **MEDICINE** written?",
    options: ["EOJDJEFM", "EOJDJEFN", "MFEJDJOF", "EOJDIEFM"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "A straight shift fails, so try reversing COMPUTER first: RETUPMOC.",
      "Compare RETUPMOC with RFUVQNPC — the first and last letters are unchanged and the middle ones move forward by one.",
    ],
    solution:
      "1. Reverse COMPUTER to get RETUPMOC.\n2. Against RFUVQNPC: the first and last letters stay, and every letter between moves **+1**.\n3. Reverse MEDICINE to get ENICIDEM.\n4. Keep E and M, and add one to the rest: E, O, J, D, J, E, F, M.\n5. The code is **EOJDJEFM**.\n\nAnswer: **EOJDJEFM**.",
    approach:
      "When no shift fits, reverse the word and compare again. Two-step codes almost always combine a reversal with a small shift.",
    tags: ["reverse", "letter shift"],
    timeTargetSec: 150,
  },
  {
    slug: "cd2-letter-sum-cat",
    topic: "coding-decoding",
    title: "Words coded by letter sums",
    prompt:
      "If **CAT = 24** and **DOG = 26**, what is the code for **PIG**? (A = 1, B = 2, …, Z = 26.)",
    options: ["30", "31", "32", "34"],
    answer: 2,
    difficulty: "medium",
    hints: ["Add the alphabet positions.", "C + A + T = 3 + 1 + 20 = 24."],
    solution:
      "1. CAT = 3 + 1 + 20 = 24 ✓ and DOG = 4 + 15 + 7 = 26 ✓.\n2. PIG = 16 + 9 + 7 = **32**.\n\nAnswer: **32**.",
    approach: "Numeric codes are usually the sum of positions, sometimes with a constant added. Verify against both examples before applying.",
    tags: ["letter values"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-word-length-minus-one",
    topic: "coding-decoding",
    title: "A code based on length",
    prompt:
      "If **REASON** is coded as **5** and **BELIEVED** as **7**, what is the code for **GOVERNMENT**?",
    options: ["8", "9", "10", "11"],
    answer: 1,
    difficulty: "medium",
    hints: ["Count the letters in each word.", "REASON has 6 letters and is coded 5."],
    solution:
      "1. REASON has 6 letters → code 5; BELIEVED has 8 letters → code 7.\n2. The code is the number of letters minus one.\n3. GOVERNMENT has 10 letters → **9**.\n\nAnswer: **9**.",
    approach: "When the code is a small number, count the letters before trying to add their positions. Length-based codes are common in the easier papers.",
    tags: ["letter values"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-digit-substitution-rose",
    topic: "coding-decoding",
    title: "Letters standing for digits",
    prompt:
      "In a code, **ROSE** is written as **6821**, **CHAIR** as **73456** and **PREACH** as **961473**. How is **SEARCH** written?",
    options: ["214673", "214763", "216473", "241673"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "Build a letter-to-digit table from the three examples.",
      "From ROSE: R=6, O=8, S=2, E=1. From CHAIR: C=7, H=3, A=4, I=5.",
    ],
    solution:
      "1. ROSE → R=6, O=8, S=2, E=1.\n2. CHAIR → C=7, H=3, A=4, I=5, R=6 (consistent).\n3. PREACH → P=9, R=6, E=1, A=4, C=7, H=3 (consistent).\n4. SEARCH = S,E,A,R,C,H = 2,1,4,6,7,3 = **214673**.\n\nAnswer: **214673**.",
    approach:
      "Write the table out and check every letter that appears twice for consistency. That cross-check is what confirms the mapping is right.",
    tags: ["substitution"],
    timeTargetSec: 135,
  },
  {
    slug: "cd2-digit-substitution-pale",
    topic: "coding-decoding",
    title: "Another digit substitution",
    prompt:
      "If **PALE** is coded as **2134** and **EARTH** as **41590**, how is **PEARL** coded?",
    options: ["24153", "215394", "241539", "241593"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "From PALE: P=2, A=1, L=3, E=4.",
      "From EARTH: E=4, A=1, R=5, T=9, H=0.",
    ],
    solution:
      "1. PALE → P=2, A=1, L=3, E=4.\n2. EARTH → E=4 (consistent), A=1 (consistent), R=5, T=9, H=0.\n3. PEARL = P,E,A,R,L = 2,4,1,5,3 = **24153**.\n\nAnswer: **24153**.",
    approach: "Check the answer's length against the word's — PEARL has five letters, so the code has five digits. That alone rules out two options.",
    tags: ["substitution"],
    timeTargetSec: 105,
  },
  {
    slug: "cd2-digit-substitution-ripple",
    topic: "coding-decoding",
    title: "Repeated letters in a code",
    prompt:
      "If **RIPPLE** is written as **613382** and **LIFE** as **8192**, how is **PILLER** written?",
    options: ["318286", "318826", "318862", "381826"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "RIPPLE has PP together, which must be the repeated digit.",
      "R=6, I=1, P=3, L=8, E=2, and from LIFE, F=9.",
    ],
    solution:
      "1. RIPPLE → 613382: R=6, I=1, P=3, P=3, L=8, E=2.\n2. LIFE → 8192: L=8 ✓, I=1 ✓, F=9, E=2 ✓.\n3. PILLER = P,I,L,L,E,R = 3,1,8,8,2,6 = **318826**.\n\nAnswer: **318826**.",
    approach: "Repeated letters anchor the mapping: the doubled digit in the code must sit where the doubled letter sits in the word.",
    tags: ["substitution"],
    timeTargetSec: 120,
  },
  {
    slug: "cd2-digit-substitution-paint",
    topic: "coding-decoding",
    title: "Two words, one table",
    prompt:
      "If **PAINT** is coded as **74128** and **EXCEL** as **93596**, how is **ACCEPT** coded?",
    options: ["455798", "455978", "455987", "459578"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "From PAINT: P=7, A=4, I=1, N=2, T=8.",
      "From EXCEL: E=9, X=3, C=5, L=6 — note E appears twice as 9.",
    ],
    solution:
      "1. PAINT → P=7, A=4, I=1, N=2, T=8.\n2. EXCEL → E=9, X=3, C=5, E=9, L=6.\n3. ACCEPT = A,C,C,E,P,T = 4,5,5,9,7,8 = **455978**.\n\nAnswer: **455978**.",
    approach: "Map every letter first, then read the target word off the table one letter at a time without rushing.",
    tags: ["substitution"],
    timeTargetSec: 120,
  },
  {
    slug: "cd2-digit-substitution-lose",
    topic: "coding-decoding",
    title: "Codes from two short words",
    prompt: "If **LOSE** is coded as **1357** and **GAIN** as **2468**, how is **SLAIN** coded?",
    options: ["15468", "51468", "51648", "54168"],
    answer: 1,
    difficulty: "medium",
    hints: ["LOSE: L=1, O=3, S=5, E=7.", "GAIN: G=2, A=4, I=6, N=8."],
    solution:
      "1. LOSE → L=1, O=3, S=5, E=7.\n2. GAIN → G=2, A=4, I=6, N=8.\n3. SLAIN = S,L,A,I,N = 5,1,4,6,8 = **51468**.\n\nAnswer: **51468**.",
    approach: "Build the table from both examples, then read the target word strictly left to right. Every letter of SLAIN appears in one of the two given words.",
    tags: ["substitution"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-substitution-language-play",
    topic: "coding-decoding",
    title: "A substitution language",
    prompt:
      "In a certain language:\n\n- **'nik ka pa'** means **'you are good'**\n- **'ka la ma'** means **'good boys play'**\n- **'pa ni ma'** means **'you play cricket'**\n\nWhich word means **'play'**?",
    options: ["ka", "la", "ma", "pa"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Compare the second and third sentences.",
      "They share the code word 'ma' and the English word 'play'.",
    ],
    solution:
      "1. Sentences 2 and 3 share exactly one code word, **ma**, and exactly one English word, **play**.\n2. Therefore ma = play.\n3. (For confirmation: 'ka' is shared by sentences 1 and 2, whose only common word is 'good'.)\n\nAnswer: **ma**.",
    approach:
      "Intersect the code words of two sentences and intersect their meanings. When each intersection has exactly one member, the pairing is settled.",
    tags: ["substitution language"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-substitution-language-good",
    topic: "coding-decoding",
    title: "Which word means 'good'",
    prompt:
      "In a certain language:\n\n- **'nik ka pa'** means **'you are good'**\n- **'ka la ma'** means **'good boys play'**\n\nWhich word means **'good'**?",
    options: ["ka", "la", "nik", "pa"],
    answer: 0,
    difficulty: "easy",
    hints: ["Find the code word common to both sentences.", "Only 'ka' appears in both, and only 'good' appears in both meanings."],
    solution:
      "1. Common code word: **ka**. Common English word: **good**.\n2. So ka = good.\n\nAnswer: **ka**.",
    approach: "One shared code word and one shared meaning gives the pairing immediately. More overlap would need a third sentence.",
    tags: ["substitution language"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-symbol-arithmetic-one",
    topic: "coding-decoding",
    title: "Swapped arithmetic symbols",
    prompt:
      "If **'+' means '÷'**, **'÷' means '−'**, **'−' means '×'** and **'×' means '+'**, what is the value of:\n\n**12 + 6 ÷ 3 − 2 × 8**",
    options: ["2", "4", "6", "8"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Rewrite the expression with the real operations first.",
      "It becomes 12 ÷ 6 − 3 × 2 + 8.",
    ],
    solution:
      "1. Substituting: 12 ÷ 6 − 3 × 2 + 8.\n2. Following BODMAS: 2 − 6 + 8.\n3. = **4**.\n\nAnswer: **4**.",
    approach:
      "Rewrite the whole expression before calculating anything, then apply the normal order of operations. Trying to substitute while computing is where errors come in.",
    tags: ["symbols"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-symbol-arithmetic-two",
    topic: "coding-decoding",
    title: "Letters standing for operations",
    prompt:
      "If **P denotes ÷**, **Q denotes ×**, **R denotes +** and **S denotes −**, what is the value of:\n\n**18 Q 12 P 4 R 5 S 6**",
    options: ["47", "51", "53", "57"],
    answer: 2,
    difficulty: "medium",
    hints: ["Rewrite as 18 × 12 ÷ 4 + 5 − 6.", "Do the multiplication and division left to right first."],
    solution:
      "1. Substituting: 18 × 12 ÷ 4 + 5 − 6.\n2. 18 × 12 = 216; 216 ÷ 4 = 54.\n3. 54 + 5 − 6 = **53**.\n\nAnswer: **53**.",
    approach: "Multiplication and division rank equally and run left to right, as do addition and subtraction. Doing the division first here would give the same answer, but not always.",
    tags: ["symbols"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-symbol-arithmetic-three",
    topic: "coding-decoding",
    title: "Another symbol swap",
    prompt:
      "If **'×' means '+'**, **'+' means '÷'**, **'−' means '×'** and **'÷' means '−'**, what is the value of:\n\n**6 × 4 + 2 − 3 ÷ 5**",
    options: ["5", "7", "9", "11"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Rewrite it as 6 + 4 ÷ 2 × 3 − 5.",
      "Division and multiplication come before addition and subtraction.",
    ],
    solution:
      "1. Substituting: 6 + 4 ÷ 2 × 3 − 5.\n2. 4 ÷ 2 = 2; 2 × 3 = 6.\n3. 6 + 6 − 5 = **7**.\n\nAnswer: **7**.",
    approach: "Substitute first, then apply BODMAS strictly. Writing the rewritten expression on its own line prevents mixing the two steps.",
    tags: ["symbols"],
    timeTargetSec: 105,
  },
  {
    slug: "cd2-number-pattern-n-n-plus-one",
    topic: "coding-decoding",
    title: "A numeric code rule",
    prompt: "If **5 = 30**, **6 = 42** and **7 = 56**, then **8 = ?**",
    options: ["64", "68", "72", "80"],
    answer: 2,
    difficulty: "medium",
    hints: ["Compare each number with its code.", "30 = 5 × 6, 42 = 6 × 7, 56 = 7 × 8."],
    solution:
      "1. The rule is n × (n + 1): 5 × 6 = 30, 6 × 7 = 42, 7 × 8 = 56.\n2. So 8 → 8 × 9 = **72**.\n\nAnswer: **72**.",
    approach: "Try n², n² ± n and n(n + 1) when a number maps to a larger one. Checking against all three examples confirms the rule.",
    tags: ["number code"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-number-pattern-small",
    topic: "coding-decoding",
    title: "A smaller numeric code",
    prompt: "If **2 = 6**, **3 = 12** and **4 = 20**, then **5 = ?**",
    options: ["25", "28", "30", "36"],
    answer: 2,
    difficulty: "easy",
    hints: ["6 = 2 × 3, 12 = 3 × 4, 20 = 4 × 5.", "The rule is n(n + 1)."],
    solution: "1. The rule is n × (n + 1).\n2. 5 → 5 × 6 = **30**.\n\nAnswer: **30**.",
    approach: "The same rule in smaller numbers. Recognising n(n + 1) — the doubled triangular numbers — makes these instant.",
    tags: ["number code"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-alphabet-odd-values",
    topic: "coding-decoding",
    title: "Letters with odd values",
    prompt: "If **A = 1, B = 3, C = 5** and so on, what is the code for **I**?",
    options: ["15", "17", "19", "21"],
    answer: 1,
    difficulty: "medium",
    hints: ["The values are the odd numbers in order.", "The nth letter has value 2n − 1, and I is the 9th letter."],
    solution:
      "1. The values run 1, 3, 5, … so the nth letter is 2n − 1.\n2. I is the 9th letter, so its value is 2 × 9 − 1 = **17**.\n\nAnswer: **17**.",
    approach: "Find the position of the letter, then apply the stated rule. Counting the alphabet on your fingers to I is slower than knowing J = 10.",
    tags: ["letter values"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-alphabet-sum-cab",
    topic: "coding-decoding",
    title: "Adding letter positions",
    prompt: "If **A = 1, B = 2, C = 3** and so on, what is the value of **CAB**?",
    options: ["5", "6", "7", "8"],
    answer: 1,
    difficulty: "easy",
    hints: ["C = 3, A = 1, B = 2.", "Add them."],
    solution: "1. C + A + B = 3 + 1 + 2 = **6**.\n\nAnswer: **6**.",
    approach: "The most basic letter-value code. Larger words use the same idea, so speed at converting letters to numbers pays off.",
    tags: ["letter values"],
    timeTargetSec: 35,
  },
  {
    slug: "cd2-alphabetical-order",
    topic: "coding-decoding",
    title: "Letters in alphabetical order",
    prompt: "If the letters of the word **MASTER** are arranged in **alphabetical order**, which letter is **fourth**?",
    options: ["M", "R", "S", "T"],
    answer: 1,
    difficulty: "easy",
    hints: ["The letters are M, A, S, T, E, R.", "Sorted: A, E, M, R, S, T."],
    solution:
      "1. The letters sorted alphabetically: A, E, M, R, S, T.\n2. The fourth is **R**.\n\nAnswer: **R**.",
    approach: "Write the sorted list out fully rather than counting in your head. Six letters is quick and eliminates any miscount.",
    tags: ["ordering"],
    timeTargetSec: 45,
  },
  {
    slug: "cd2-reverse-word-code",
    topic: "coding-decoding",
    title: "A simple reversal",
    prompt: "If **WORLD** is coded as **DLROW**, how is **INDIA** coded?",
    options: ["AIDNI", "AIDIN", "AINDI", "IDNIA"],
    answer: 0,
    difficulty: "easy",
    hints: ["The code is the word written backwards.", "Read INDIA from the last letter."],
    solution: "1. The code simply reverses the word.\n2. INDIA reversed is **AIDNI**.\n\nAnswer: **AIDNI**.",
    approach: "Always test a plain reversal before anything more elaborate. It is the simplest non-shift code and appears often.",
    tags: ["reverse"],
    timeTargetSec: 40,
  },
  {
    slug: "cd2-opposite-letters",
    topic: "coding-decoding",
    title: "Opposite letters of the alphabet",
    prompt:
      "If **ACT** is coded as **ZXG**, how is **BAD** coded? (Each letter is replaced by its opposite in the alphabet.)",
    options: ["YZW", "YZX", "ZYW", "YAW"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "A pairs with Z, B with Y, C with X, and so on.",
      "The rule is: position n becomes position 27 − n.",
    ],
    solution:
      "1. Opposite pairs: A↔Z, B↔Y, C↔X, D↔W.\n2. Check: A→Z, C→X, T→G ✓ (T is 20, and 27 − 20 = 7 = G).\n3. BAD → B→Y, A→Z, D→W = **YZW**.\n\nAnswer: **YZW**.",
    approach:
      "The opposite of the nth letter is the (27 − n)th. Remembering the pairs A-Z, E-V, J-Q, M-N makes this quick.",
    tags: ["opposite letters"],
    timeTargetSec: 90,
  },
  {
    slug: "cd2-mixed-shift-two-halves",
    topic: "coding-decoding",
    title: "First half forward, second half back",
    prompt:
      "If **BOARD** is coded as **CPBSE**, how is **CHAIR** coded?",
    options: ["DIBJS", "DIBJT", "DHBJS", "EIBJS"],
    answer: 0,
    difficulty: "easy",
    hints: ["B → C, O → P, A → B: a shift of +1.", "Apply +1 to CHAIR."],
    solution: "1. The shift is **+1** throughout.\n2. C→D, H→I, A→B, I→J, R→S.\n3. The code is **DIBJS**.\n\nAnswer: **DIBJS**.",
    approach: "Verify the shift on every letter of the example, not just the first two. A word where the shift changes midway would look identical at the start.",
    tags: ["letter shift"],
    timeTargetSec: 50,
  },
  {
    slug: "cd2-code-for-number-word",
    topic: "coding-decoding",
    title: "Decoding back to a word",
    prompt: "In a certain code **PLANT** is written as **QMBOU**. What does **TFBU** stand for?",
    options: ["SEAT", "SEAL", "TEAM", "REST"],
    answer: 0,
    difficulty: "medium",
    hints: ["P → Q, L → M: a shift of +1, so decoding needs −1.", "Apply −1 to each letter of TFBU."],
    solution:
      "1. The code adds 1 to each letter, so decoding subtracts 1.\n2. T→S, F→E, B→A, U→T.\n3. The word is **SEAT**.\n\nAnswer: **SEAT**.",
    approach: "To decode, reverse the direction of the shift. Confirm by re-encoding your answer and checking it matches the given code.",
    tags: ["letter shift", "decoding"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-decode-minus-two",
    topic: "coding-decoding",
    title: "Decoding a +2 shift",
    prompt: "In a code where **LIGHT** is written as **NKIJV**, what does **HQQF** stand for?",
    options: ["FOOD", "FOOT", "GOOD", "HOOD"],
    answer: 0,
    difficulty: "medium",
    hints: ["L → N, I → K: a shift of +2, so decode with −2.", "H − 2 = F, Q − 2 = O."],
    solution:
      "1. The shift is +2, so decoding subtracts 2.\n2. H→F, Q→O, Q→O, F→D.\n3. The word is **FOOD**.\n\nAnswer: **FOOD**.",
    approach: "Establish the shift from the example, then reverse it. Reading the decoded letters as a real word is the final confirmation.",
    tags: ["letter shift", "decoding"],
    timeTargetSec: 75,
  },
  {
    slug: "cd2-count-letters-between",
    topic: "coding-decoding",
    title: "Position within the alphabet",
    prompt: "Which letter is the **eighth to the left of the twentieth letter** from the left of the alphabet?",
    options: ["J", "K", "L", "M"],
    answer: 2,
    difficulty: "medium",
    hints: ["The twentieth letter from the left is T.", "Count eight places back from T."],
    solution:
      "1. The 20th letter is T.\n2. Eight to the left means position 20 − 8 = 12.\n3. The 12th letter is **L**.\n\nAnswer: **L**.",
    approach: "Work in positions, not letters: subtract for 'to the left' and add for 'to the right'. Convert back only at the end.",
    tags: ["alphabet position"],
    timeTargetSec: 60,
  },
  {
    slug: "cd2-letter-from-right",
    topic: "coding-decoding",
    title: "Counting from the right",
    prompt: "Which is the **seventh letter from the right** in the English alphabet?",
    options: ["S", "T", "U", "V"],
    answer: 1,
    difficulty: "easy",
    hints: ["From the right, Z is first.", "Position from the left = 27 − 7."],
    solution:
      "1. The nth letter from the right is the (27 − n)th from the left.\n2. 27 − 7 = 20, which is **T**.\n\nAnswer: **T**.",
    approach: "The formula 27 − n converts right-counts to left-counts. Counting backwards from Z by hand is slower and easy to slip on.",
    tags: ["alphabet position"],
    timeTargetSec: 50,
  },
];
