import type { AptitudeSeed } from "./types.js";

/** Ratio and proportion — the standard placement and bank-exam set. */
export const BANK_RATIO: AptitudeSeed[] = [
  {
    slug: "rp2-divide-1200-in-237",
    topic: "ratio-and-proportion",
    title: "Dividing ₹1,200 in the ratio 2 : 3 : 7",
    prompt: "**₹1,200** is divided among A, B and C in the ratio **2 : 3 : 7**. How much does **C** receive?",
    options: ["₹200", "₹300", "₹500", "₹700"],
    answer: 3,
    difficulty: "easy",
    hints: ["Add the parts: 2 + 3 + 7 = 12.", "One part is 1,200 ÷ 12 = 100."],
    solution: "1. Total parts = 12, so one part = 1,200 ÷ 12 = ₹100.\n2. C receives 7 parts = **₹700**.\n\nAnswer: **₹700**.",
    approach: "Find the value of one part once, then multiply for each share. Checking that the shares add back to the total catches arithmetic slips instantly.",
    tags: ["sharing"],
    timeTargetSec: 40,
  },
  {
    slug: "rp2-combine-ab-bc",
    topic: "ratio-and-proportion",
    title: "Combining A : B and B : C",
    prompt: "If **A : B = 2 : 3** and **B : C = 4 : 5**, what is **A : B : C**?",
    options: ["2 : 3 : 5", "6 : 9 : 10", "8 : 12 : 15", "10 : 15 : 12"],
    answer: 2,
    difficulty: "easy",
    hints: ["B must be the same number in both ratios.", "Scale the first by 4 and the second by 3 so B becomes 12 in each."],
    solution:
      "1. A : B = 2 : 3 = 8 : 12; B : C = 4 : 5 = 12 : 15.\n2. So A : B : C = **8 : 12 : 15**.\n\nAnswer: **8 : 12 : 15**.",
    approach: "Match the shared term by scaling each ratio to its LCM, then join. The same trick chains any number of ratios together.",
    tags: ["compound ratio"],
    timeTargetSec: 50,
  },
  {
    slug: "rp2-chain-three-ratios",
    topic: "ratio-and-proportion",
    title: "Chaining A : B and B : C again",
    prompt: "If **A : B = 5 : 7** and **B : C = 6 : 11**, what is **A : B : C**?",
    options: ["30 : 42 : 77", "35 : 42 : 66", "5 : 7 : 11", "30 : 42 : 66"],
    answer: 0,
    difficulty: "medium",
    hints: ["B appears as 7 in one ratio and 6 in the other.", "Scale to make B = 42 in both."],
    solution:
      "1. A : B = 5 : 7 = 30 : 42 (multiply by 6).\n2. B : C = 6 : 11 = 42 : 77 (multiply by 7).\n3. So A : B : C = **30 : 42 : 77**.\n\nAnswer: **30 : 42 : 77**.",
    approach: "Scale each ratio by the other's value of the shared term. Here 7 × 6 = 42 does the job without needing the LCM separately.",
    tags: ["compound ratio"],
    timeTargetSec: 60,
  },
  {
    slug: "rp2-add-ten-to-both",
    topic: "ratio-and-proportion",
    title: "Adding 10 to both numbers",
    prompt:
      "Two numbers are in the ratio **3 : 5**. If **10 is added to each**, the ratio becomes **5 : 7**. What is the **smaller number**?",
    options: ["9", "12", "15", "18"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the numbers be 3x and 5x.", "(3x + 10)/(5x + 10) = 5/7; cross-multiply."],
    solution:
      "1. Let the numbers be 3x and 5x.\n2. (3x + 10)/(5x + 10) = 5/7 → 21x + 70 = 25x + 50 → 4x = 20 → x = 5.\n3. The numbers are 15 and 25, so the smaller is **15**.\n\nAnswer: **15**.",
    approach: "Introduce one variable through the ratio, then cross-multiply the second condition. Always substitute back and check both ratios hold.",
    tags: ["algebra"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-add-seven-larger",
    topic: "ratio-and-proportion",
    title: "Adding 7 to both",
    prompt:
      "Two numbers are in the ratio **1 : 2**. If **7 is added to each**, the ratio becomes **3 : 5**. What is the **larger number**?",
    options: ["14", "21", "28", "35"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the numbers be x and 2x.", "(x + 7)/(2x + 7) = 3/5."],
    solution:
      "1. (x + 7)/(2x + 7) = 3/5 → 5x + 35 = 6x + 21 → x = 14.\n2. The numbers are 14 and 28, so the larger is **28**.\n\nAnswer: **28**.",
    approach: "The same pattern as before. Read the question carefully at the end — it asks for the larger number, and 14 is offered for those who stop at x.",
    tags: ["algebra"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-hcf-lcm-from-ratio",
    topic: "ratio-and-proportion",
    title: "LCM from a ratio and an HCF",
    prompt: "Two numbers are in the ratio **3 : 4** and their **HCF is 4**. What is their **LCM**?",
    options: ["24", "36", "48", "60"],
    answer: 2,
    difficulty: "medium",
    hints: ["Numbers in ratio 3 : 4 with HCF h are 3h and 4h.", "So the numbers are 12 and 16."],
    solution:
      "1. The numbers are 3 × 4 = 12 and 4 × 4 = 16.\n2. LCM(12, 16) = 48.\n\nAnswer: **48**.",
    approach:
      "When two numbers are in a ratio of coprime terms, the HCF is the common multiplier and the LCM is HCF × product of the ratio terms — here 4 × 3 × 4 = 48.",
    tags: ["hcf", "lcm"],
    timeTargetSec: 60,
  },
  {
    slug: "rp2-lcm-180-ratio-45",
    topic: "ratio-and-proportion",
    title: "Numbers from a ratio and an LCM",
    prompt: "Two numbers are in the ratio **4 : 5** and their **LCM is 180**. What is their **sum**?",
    options: ["72", "81", "90", "99"],
    answer: 1,
    difficulty: "medium",
    hints: ["Write them as 4x and 5x, where x is the HCF.", "LCM of 4x and 5x is 20x."],
    solution:
      "1. Let the numbers be 4x and 5x with x their HCF.\n2. LCM = 20x = 180 → x = 9.\n3. The numbers are 36 and 45; their sum is **81**.\n\nAnswer: **81**.",
    approach: "For coprime ratio terms a and b, the LCM of ax and bx is abx. Solving for x recovers both numbers at once.",
    tags: ["lcm"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-expression-in-x-y",
    topic: "ratio-and-proportion",
    title: "Evaluating an expression from a ratio",
    prompt: "If **x : y = 5 : 2**, what is **(8x + 9y) : (8x + 2y)**?",
    options: ["22 : 29", "23 : 22", "29 : 22", "31 : 22"],
    answer: 2,
    difficulty: "medium",
    hints: ["Substitute x = 5 and y = 2.", "8(5) + 9(2) = 58 and 8(5) + 2(2) = 44."],
    solution:
      "1. Take x = 5 and y = 2.\n2. 8x + 9y = 40 + 18 = 58; 8x + 2y = 40 + 4 = 44.\n3. 58 : 44 = **29 : 22**.\n\nAnswer: **29 : 22**.",
    approach: "Substitute the ratio terms as actual numbers — any pair in that ratio gives the same answer — then reduce. Algebra with x and y is slower and no more reliable.",
    tags: ["algebra"],
    timeTargetSec: 60,
  },
  {
    slug: "rp2-2a-3b-over-3a-2b",
    topic: "ratio-and-proportion",
    title: "A ratio of two expressions",
    prompt: "If **a : b = 3 : 4**, what is **(2a + 3b) : (3a + 2b)**?",
    options: ["17 : 18", "18 : 17", "5 : 6", "6 : 5"],
    answer: 1,
    difficulty: "easy",
    hints: ["Put a = 3 and b = 4.", "2(3) + 3(4) = 18 and 3(3) + 2(4) = 17."],
    solution:
      "1. Take a = 3, b = 4.\n2. 2a + 3b = 6 + 12 = 18; 3a + 2b = 9 + 8 = 17.\n3. The ratio is **18 : 17**.\n\nAnswer: **18 : 17**.",
    approach: "Substitute and compute. Keep the order the question asks for — 17 : 18 is offered for anyone who writes the two lines the wrong way round.",
    tags: ["algebra"],
    timeTargetSec: 50,
  },
  {
    slug: "rp2-x-plus-y-over-x-minus-y",
    topic: "ratio-and-proportion",
    title: "Sum over difference",
    prompt: "If **x/y = 2/3**, what is the value of **(x + y)/(x − y)**?",
    options: ["−5", "−1/5", "1/5", "5"],
    answer: 0,
    difficulty: "medium",
    hints: ["Take x = 2 and y = 3.", "The denominator 2 − 3 is negative."],
    solution:
      "1. Take x = 2, y = 3.\n2. (x + y)/(x − y) = 5/(2 − 3) = 5/(−1) = **−5**.\n\nAnswer: **−5**.",
    approach: "Substituting is safe, but keep track of the sign: when the numerator of the ratio is smaller, the difference is negative and so is the answer.",
    tags: ["algebra"],
    timeTargetSec: 50,
  },
  {
    slug: "rp2-three-equal-products",
    topic: "ratio-and-proportion",
    title: "When 3A = 4B = 6C",
    prompt: "If **3A = 4B = 6C**, what is **A : B : C**?",
    options: ["2 : 3 : 4", "3 : 4 : 6", "4 : 3 : 2", "6 : 4 : 3"],
    answer: 2,
    difficulty: "medium",
    hints: ["Set all three equal to a convenient number, say 12.", "Then A = 4, B = 3 and C = 2."],
    solution:
      "1. Let 3A = 4B = 6C = 12 (the LCM of 3, 4 and 6).\n2. A = 4, B = 3, C = 2.\n3. So A : B : C = **4 : 3 : 2**.\n\nAnswer: **4 : 3 : 2**.",
    approach:
      "Set the common product to the LCM of the coefficients and read off each variable. The ratio comes out inverse to the coefficients, which is why 3 : 4 : 6 is the trap.",
    tags: ["algebra"],
    timeTargetSec: 60,
  },
  {
    slug: "rp2-fractional-ratio-shares",
    topic: "ratio-and-proportion",
    title: "Sharing in a fractional ratio",
    prompt: "**₹782** is divided among three people in the ratio **½ : ⅔ : ¾**. What is the **first share**?",
    options: ["₹182", "₹190", "₹204", "₹272"],
    answer: 2,
    difficulty: "medium",
    hints: ["Clear the fractions by multiplying all three by 12.", "The ratio becomes 6 : 8 : 9."],
    solution:
      "1. Multiply by 12: ½ : ⅔ : ¾ = 6 : 8 : 9.\n2. Total parts = 23, so one part = 782 ÷ 23 = ₹34.\n3. First share = 6 × 34 = **₹204**.\n\nAnswer: **₹204**.",
    approach: "Never share out fractions directly. Multiply through by the LCM of the denominators first, then treat it as an ordinary whole-number ratio.",
    tags: ["sharing", "fractions"],
    timeTargetSec: 90,
  },
  {
    slug: "rp2-nested-shares",
    topic: "ratio-and-proportion",
    title: "Shares described through one another",
    prompt:
      "A sum of **₹3,400** is divided among A, B and C so that **A gets ⅔ of what B gets**, and **B gets ¼ of what C gets**. What is **B's share**?",
    options: ["₹400", "₹500", "₹600", "₹800"],
    answer: 2,
    difficulty: "hard",
    hints: ["Express A and C in terms of B.", "A = (2/3)B and C = 4B, so the total is (2/3)B + B + 4B."],
    solution:
      "1. A = (2/3)B and C = 4B.\n2. Total = (2/3)B + B + 4B = (17/3)B.\n3. (17/3)B = 3,400 → B = 3,400 × 3 / 17 = **₹600**.\n4. Check: A = 400, B = 600, C = 2,400, total 3,400. ✓\n\nAnswer: **₹600**.",
    approach: "Pick the variable everything else is described against — here B — and write the total in that one variable. Choosing A or C instead makes the fractions much worse.",
    tags: ["sharing"],
    timeTargetSec: 105,
  },
  {
    slug: "rp2-three-shares-two-ratios",
    topic: "ratio-and-proportion",
    title: "Sharing under two linked ratios",
    prompt:
      "**₹3,500** is divided among A, B and C such that **A : B = 2 : 3** and **B : C = 4 : 5**. What is **C's share**?",
    options: ["₹800", "₹1,200", "₹1,500", "₹1,800"],
    answer: 2,
    difficulty: "medium",
    hints: ["First combine the ratios into A : B : C.", "8 : 12 : 15, so 35 parts in all."],
    solution:
      "1. A : B = 2 : 3 = 8 : 12; B : C = 4 : 5 = 12 : 15 → A : B : C = 8 : 12 : 15.\n2. Total parts = 35, so one part = 3,500 ÷ 35 = ₹100.\n3. C = 15 × 100 = **₹1,500**.\n\nAnswer: **₹1,500**.",
    approach: "Combine the ratios before sharing anything out. The total is chosen to divide the part count evenly, which is a hint that you have combined correctly.",
    tags: ["sharing", "compound ratio"],
    timeTargetSec: 90,
  },
  {
    slug: "rp2-sum-98-two-ratios",
    topic: "ratio-and-proportion",
    title: "Three numbers from two ratios",
    prompt:
      "The sum of three numbers is **98**. The ratio of the **first to the second is 2 : 3**, and of the **second to the third is 5 : 8**. What is the **second number**?",
    options: ["20", "30", "48", "58"],
    answer: 1,
    difficulty: "medium",
    hints: ["Make the second number match in both ratios.", "2 : 3 = 10 : 15 and 5 : 8 = 15 : 24."],
    solution:
      "1. First : second = 2 : 3 = 10 : 15; second : third = 5 : 8 = 15 : 24.\n2. So the three are in the ratio 10 : 15 : 24, giving 49 parts.\n3. One part = 98 ÷ 49 = 2, so the second number = 15 × 2 = **30**.\n\nAnswer: **30**.",
    approach: "Scale both ratios so the shared middle term agrees, then share the total. The clean part count (49 into 98) confirms the scaling was right.",
    tags: ["compound ratio"],
    timeTargetSec: 90,
  },
  {
    slug: "rp2-salaries-after-increments",
    topic: "ratio-and-proportion",
    title: "Salaries after different increments",
    prompt:
      "The salaries of A, B and C are in the ratio **2 : 3 : 5**. If they receive increments of **15%, 10% and 20%** respectively, what is the **new ratio**?",
    options: ["3 : 3 : 10", "10 : 11 : 20", "23 : 33 : 60", "23 : 33 : 62"],
    answer: 2,
    difficulty: "medium",
    hints: ["Multiply each ratio term by its own growth factor.", "2 × 1.15, 3 × 1.10 and 5 × 1.20."],
    solution:
      "1. New salaries ∝ 2 × 1.15 = 2.3, 3 × 1.10 = 3.3, 5 × 1.20 = 6.\n2. Multiplying all three by 10: **23 : 33 : 60**.\n\nAnswer: **23 : 33 : 60**.",
    approach: "Apply each percentage to its own term, then clear the decimals by scaling. Percentages never move between terms of a ratio.",
    tags: ["percentages"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-incomes-expenditures-savings",
    topic: "ratio-and-proportion",
    title: "Incomes, expenditures and equal savings",
    prompt:
      "The incomes of two people are in the ratio **3 : 4** and their expenditures in the ratio **5 : 7**. If each **saves ₹200**, what is the **income of the first**?",
    options: ["₹800", "₹1,000", "₹1,200", "₹1,500"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Let the incomes be 3x and 4x, and the expenditures 5y and 7y.",
      "Savings give two equations: 3x − 5y = 200 and 4x − 7y = 200.",
      "Eliminate x by multiplying the first by 4 and the second by 3.",
    ],
    solution:
      "1. 3x − 5y = 200 and 4x − 7y = 200.\n2. Multiply: 12x − 20y = 800 and 12x − 21y = 600.\n3. Subtracting gives y = 200, so 3x = 200 + 1,000 = 1,200.\n4. The first income is 3x = **₹1,200**.\n\nAnswer: **₹1,200**.",
    approach:
      "Two ratios need two variables. Income − expenditure = savings gives one equation per person, and eliminating one variable finishes it. This is the standard two-ratio problem of the chapter.",
    tags: ["algebra", "savings"],
    timeTargetSec: 150,
  },
  {
    slug: "rp2-coins-ratio-value",
    topic: "ratio-and-proportion",
    title: "Coins of three denominations",
    prompt:
      "A bag contains ₹1, 50-paise and 25-paise coins in the ratio **5 : 6 : 8**, worth **₹210** in all. How many **50-paise coins** are there?",
    options: ["105", "126", "168", "210"],
    answer: 1,
    difficulty: "hard",
    hints: ["Work out the value of one 'set' of 5 + 6 + 8 coins.", "One set is worth 5(1) + 6(0.5) + 8(0.25) = ₹10."],
    solution:
      "1. One set of coins is worth 5 × 1 + 6 × 0.50 + 8 × 0.25 = 5 + 3 + 2 = ₹10.\n2. Number of sets = 210 ÷ 10 = 21.\n3. 50-paise coins = 6 × 21 = **126**.\n\nAnswer: **126**.",
    approach:
      "When counts are in a ratio but the total is a value, price one complete set of the ratio and see how many sets the money buys. Converting the count ratio into a value ratio in the head is where mistakes creep in.",
    tags: ["coins"],
    timeTargetSec: 105,
  },
  {
    slug: "rp2-milk-water-to-reverse",
    topic: "ratio-and-proportion",
    title: "Reversing a milk-and-water ratio",
    prompt:
      "A **60-litre** mixture has milk and water in the ratio **2 : 1**. How much **water** must be added to make the ratio **1 : 2**?",
    options: ["20 L", "40 L", "50 L", "60 L"],
    answer: 3,
    difficulty: "medium",
    hints: ["The milk never changes — only the water does.", "Milk is 40 L; for a 1 : 2 ratio the water must be 80 L."],
    solution:
      "1. Milk = (2/3) × 60 = 40 L; water = 20 L.\n2. For milk : water = 1 : 2, water must be 2 × 40 = 80 L.\n3. Water to add = 80 − 20 = **60 L**.\n\nAnswer: **60 L**.",
    approach: "Anchor on the quantity that stays fixed, work out what the other must become, and subtract what is already there.",
    tags: ["mixtures"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-two-alloys-equal-weights",
    topic: "ratio-and-proportion",
    title: "Mixing two alloys in equal weights",
    prompt:
      "One alloy has copper and zinc in the ratio **5 : 3**, another in the ratio **7 : 5**. **Equal weights** of the two are melted together. What is the ratio of **copper to zinc** in the new alloy?",
    options: ["12 : 8", "23 : 19", "29 : 19", "35 : 15"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Take 24 units of each alloy so both ratios divide evenly.",
      "First alloy: 15 copper, 9 zinc. Second: 14 copper, 10 zinc.",
    ],
    solution:
      "1. Take 24 units of each (24 divides both 8 and 12).\n2. First alloy: copper 15, zinc 9. Second: copper 14, zinc 10.\n3. Totals: copper 29, zinc 19 → **29 : 19**.\n\nAnswer: **29 : 19**.",
    approach:
      "Choose a common weight that both ratios divide cleanly — the LCM of the ratio sums — then add the components. Averaging the two ratios directly is wrong.",
    tags: ["alloys"],
    timeTargetSec: 120,
  },
  {
    slug: "rp2-boys-girls-scholarship",
    topic: "ratio-and-proportion",
    title: "Scholarship holders in a ratio",
    prompt:
      "The ratio of boys to girls in a school is **3 : 2**. If **20% of the boys** and **25% of the girls** hold scholarships, what percent of students do **not** hold one?",
    options: ["72%", "75%", "78%", "80%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Boys are 60% of the school and girls 40%.", "0.60 × 0.20 + 0.40 × 0.25 gives the holders."],
    solution:
      "1. Boys = 3/5 = 60%, girls = 2/5 = 40%.\n2. Holders = 60% × 20% + 40% × 25% = 12% + 10% = 22%.\n3. Non-holders = 100% − 22% = **78%**.\n\nAnswer: **78%**.",
    approach: "Convert the ratio to percentages of the whole first, then apply each rate to its own group. Averaging 20% and 25% ignores the unequal group sizes.",
    tags: ["percentages"],
    timeTargetSec: 75,
  },
  {
    slug: "rp2-fourth-proportional",
    topic: "ratio-and-proportion",
    title: "Fourth proportional to 5, 8 and 15",
    prompt: "What is the **fourth proportional** to **5, 8 and 15**?",
    options: ["18", "20", "24", "30"],
    answer: 2,
    difficulty: "easy",
    hints: ["The fourth proportional x satisfies 5 : 8 = 15 : x.", "Cross-multiply: 5x = 120."],
    solution: "1. 5 : 8 = 15 : x → 5x = 8 × 15 = 120.\n2. x = **24**.\n\nAnswer: **24**.",
    approach: "Fourth proportional to a, b, c is bc/a. Keep the pairing right: the first two form one ratio and the last two the other.",
    tags: ["proportion"],
    timeTargetSec: 40,
  },
  {
    slug: "rp2-third-proportional",
    topic: "ratio-and-proportion",
    title: "Third proportional to 4 and 12",
    prompt: "What is the **third proportional** to **4 and 12**?",
    options: ["16", "24", "36", "48"],
    answer: 2,
    difficulty: "easy",
    hints: ["The third proportional x satisfies 4 : 12 = 12 : x.", "So x = 12² / 4."],
    solution: "1. 4 : 12 = 12 : x → 4x = 144.\n2. x = **36**.\n\nAnswer: **36**.",
    approach: "Third proportional to a and b is b²/a — the middle term is repeated. Mean proportional between a and b is √(ab), which is a different question.",
    tags: ["proportion"],
    timeTargetSec: 40,
  },
  {
    slug: "rp2-mean-proportional",
    topic: "ratio-and-proportion",
    title: "Mean proportional between 9 and 16",
    prompt: "What is the **mean proportional** between **9 and 16**?",
    options: ["12", "12.5", "24", "25"],
    answer: 0,
    difficulty: "easy",
    hints: ["The mean proportional between a and b is √(ab).", "√(9 × 16) = √144."],
    solution: "1. Mean proportional = √(9 × 16) = √144 = **12**.\n\nAnswer: **12**.",
    approach: "The mean proportional is the geometric mean, not the arithmetic one — 12, not 12.5. That distinction is exactly what the second option is testing.",
    tags: ["proportion"],
    timeTargetSec: 40,
  },
  {
    slug: "rp2-proportion-with-decimal",
    topic: "ratio-and-proportion",
    title: "Solving a proportion",
    prompt: "If **0.75 : x ∷ 5 : 8**, what is the value of **x**?",
    options: ["1.12", "1.2", "1.25", "1.30"],
    answer: 1,
    difficulty: "easy",
    hints: ["Cross-multiply: 0.75 × 8 = 5x.", "6 = 5x."],
    solution: "1. 0.75 × 8 = 5x → 6 = 5x.\n2. x = **1.2**.\n\nAnswer: **1.2**.",
    approach: "In a : b ∷ c : d the product of the extremes equals the product of the means. Cross-multiplying is the whole of it.",
    tags: ["proportion"],
    timeTargetSec: 45,
  },
  {
    slug: "rp2-men-days-inverse",
    topic: "ratio-and-proportion",
    title: "More men, fewer days",
    prompt: "**15 men** can complete a piece of work in **20 days**. How many **men** are needed to finish it in **12 days**?",
    options: ["18", "20", "25", "30"],
    answer: 2,
    difficulty: "easy",
    hints: ["Men and days vary inversely: their product is constant.", "15 × 20 = 300 man-days."],
    solution: "1. Total work = 15 × 20 = 300 man-days.\n2. Men needed = 300 ÷ 12 = **25**.\n\nAnswer: **25**.",
    approach: "Inverse variation keeps the product fixed; direct variation keeps the ratio fixed. Deciding which applies is the only real step.",
    tags: ["variation"],
    timeTargetSec: 45,
  },
  {
    slug: "rp2-circle-areas-ratio",
    topic: "ratio-and-proportion",
    title: "Ratio of areas from a ratio of radii",
    prompt: "The **radii of two circles** are in the ratio **2 : 3**. What is the ratio of their **areas**?",
    options: ["2 : 3", "4 : 9", "8 : 27", "16 : 81"],
    answer: 1,
    difficulty: "easy",
    hints: ["Area is proportional to the square of the radius.", "Square both terms of the ratio."],
    solution: "1. Area ∝ r², so the ratio of areas = 2² : 3² = **4 : 9**.\n\nAnswer: **4 : 9**.",
    approach:
      "Lengths in ratio a : b give areas a² : b² and volumes a³ : b³. Knowing all three saves time whenever a question scales a figure.",
    tags: ["geometry"],
    timeTargetSec: 40,
  },
  {
    slug: "rp2-p-q-r-chain",
    topic: "ratio-and-proportion",
    title: "From p : q and q : r to p : r",
    prompt: "If **p : q = 3 : 4** and **q : r = 8 : 9**, what is **p : r**?",
    options: ["1 : 2", "2 : 3", "3 : 4", "4 : 9"],
    answer: 1,
    difficulty: "easy",
    hints: ["Multiply the ratios: p/r = (p/q) × (q/r).", "(3/4) × (8/9) = 24/36."],
    solution:
      "1. p/r = (p/q) × (q/r) = (3/4) × (8/9) = 24/36 = 2/3.\n2. So p : r = **2 : 3**.\n\nAnswer: **2 : 3**.",
    approach: "When only the two outer terms are wanted, multiply the fractions and skip building the full three-term ratio.",
    tags: ["compound ratio"],
    timeTargetSec: 45,
  },
  {
    slug: "rp2-divide-60-two-parts",
    topic: "ratio-and-proportion",
    title: "Dividing 60 in the ratio 2 : 3",
    prompt: "Divide **60** into two parts in the ratio **2 : 3**. What is the **smaller part**?",
    options: ["20", "24", "30", "36"],
    answer: 1,
    difficulty: "easy",
    hints: ["There are 5 parts in all.", "One part is 12."],
    solution: "1. Total parts = 5, so one part = 60 ÷ 5 = 12.\n2. Smaller part = 2 × 12 = **24**.\n\nAnswer: **24**.",
    approach: "Divide by the sum of the ratio terms to size one part, then multiply. The two parts should add back to the original total.",
    tags: ["sharing"],
    timeTargetSec: 35,
  },
  {
    slug: "rp2-ages-ratio-future",
    topic: "ratio-and-proportion",
    title: "A ratio that changes with time",
    prompt:
      "The present ages of two people are in the ratio **4 : 5**. After **5 years** the ratio becomes **5 : 6**. What is the **present age of the younger**?",
    options: ["16", "20", "24", "25"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let the ages be 4x and 5x.", "(4x + 5)/(5x + 5) = 5/6."],
    solution:
      "1. (4x + 5)/(5x + 5) = 5/6 → 24x + 30 = 25x + 25 → x = 5.\n2. The younger is 4x = **20**.\n\nAnswer: **20**.",
    approach: "Add the same number of years to both terms and cross-multiply. The difference between the two ages never changes, which is a quick sanity check on the answer.",
    tags: ["ages"],
    timeTargetSec: 75,
  },
];
