import type { AptitudeSeed } from "./types.js";

/** Averages — the standard placement and bank-exam set. */
export const BANK_AVERAGES: AptitudeSeed[] = [
  {
    slug: "av2-primes-between-30-and-50",
    topic: "averages",
    title: "Average of the primes between 30 and 50",
    prompt: "What is the **average of all prime numbers between 30 and 50**?",
    options: ["37.8", "38.8", "39.8", "40.8"],
    answer: 2,
    difficulty: "medium",
    hints: ["List the primes first: 31, 37, 41, 43, 47.", "Their sum is 199, over five numbers."],
    solution:
      "1. The primes between 30 and 50 are 31, 37, 41, 43 and 47.\n2. Sum = 199, and there are 5 of them.\n3. Average = 199 ÷ 5 = **39.8**.\n\nAnswer: **39.8**.",
    approach:
      "Primes are not evenly spaced, so the midpoint shortcut fails — the list must be written out and added. The risk here is missing 43 or wrongly including 39 or 49.",
    tags: ["primes"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-first-five-multiples-of-three",
    topic: "averages",
    title: "Average of the first five multiples of 3",
    prompt: "What is the **average of the first five multiples of 3**?",
    options: ["6", "9", "12", "15"],
    answer: 1,
    difficulty: "easy",
    hints: ["The numbers are 3, 6, 9, 12, 15.", "They are evenly spaced, so take the middle one."],
    solution: "1. The multiples are 3, 6, 9, 12, 15.\n2. With an odd count of evenly spaced terms the average is the middle term: **9**.\n\nAnswer: **9**.",
    approach: "An odd number of evenly spaced terms has its average sitting exactly on the middle term. No addition is needed at all.",
    tags: ["series"],
    timeTargetSec: 35,
  },
  {
    slug: "av2-even-numbers-2-to-50",
    topic: "averages",
    title: "Average of the even numbers to 50",
    prompt: "What is the **average of all even numbers from 2 to 50**?",
    options: ["24", "25", "26", "28"],
    answer: 2,
    difficulty: "easy",
    hints: ["The list is 2, 4, …, 50.", "Average = (2 + 50)/2."],
    solution: "1. The numbers are evenly spaced from 2 to 50.\n2. Average = (2 + 50)/2 = **26**.\n\nAnswer: **26**.",
    approach: "Evenly spaced again: midpoint of the ends. The count (25 numbers) is never needed for the average, only for the sum.",
    tags: ["series"],
    timeTargetSec: 35,
  },
  {
    slug: "av2-squares-first-five",
    topic: "averages",
    title: "Average of the squares of the first five naturals",
    prompt: "What is the **average of the squares of the first five natural numbers**?",
    options: ["9", "11", "13", "15"],
    answer: 1,
    difficulty: "easy",
    hints: ["The squares are 1, 4, 9, 16, 25.", "Their sum is 55."],
    solution: "1. Squares: 1 + 4 + 9 + 16 + 25 = 55.\n2. Average = 55 ÷ 5 = **11**.\n\nAnswer: **11**.",
    approach:
      "Squares are not evenly spaced, so the midpoint shortcut does not apply — add them. The formula n(n+1)(2n+1)/6 gives the sum directly if the list is long.",
    tags: ["series"],
    timeTargetSec: 45,
  },
  {
    slug: "av2-teacher-included",
    topic: "averages",
    title: "The teacher joins the class",
    prompt:
      "The average age of **30 students** is **15 years**. When the teacher's age is included the average becomes **16**. How old is the **teacher**?",
    options: ["31", "40", "46", "50"],
    answer: 2,
    difficulty: "easy",
    hints: ["Compare the totals before and after.", "31 × 16 − 30 × 15."],
    solution:
      "1. Total age of students = 30 × 15 = 450.\n2. Total with the teacher = 31 × 16 = 496.\n3. Teacher = 496 − 450 = **46**.\n\nAnswer: **46**.",
    approach:
      "A newcomer who raises the average of n people by d is worth (new average) + n × d — here 16 + 30 = 46. They sit at the new average and lift everyone else by d.",
    tags: ["adding a member"],
    timeTargetSec: 50,
  },
  {
    slug: "av2-manager-joins",
    topic: "averages",
    title: "A manager joins the company",
    prompt:
      "The average salary of **20 employees** is **₹15,000**. When the manager's salary is added the average rises by **₹500**. What is the **manager's salary**?",
    options: ["₹20,000", "₹25,500", "₹27,000", "₹30,000"],
    answer: 1,
    difficulty: "medium",
    hints: ["The new average is ₹15,500 across 21 people.", "21 × 15,500 − 20 × 15,000."],
    solution:
      "1. Old total = 20 × 15,000 = ₹3,00,000.\n2. New total = 21 × 15,500 = ₹3,25,500.\n3. Manager = 3,25,500 − 3,00,000 = **₹25,500**.\n\nAnswer: **₹25,500**.",
    approach: "Or use the shortcut: new average + n × rise = 15,500 + 20 × 500 = 25,500. Both routes agree; the shortcut is faster under time pressure.",
    tags: ["adding a member"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-replacement-weight",
    topic: "averages",
    title: "One person is replaced",
    prompt:
      "The average weight of **8 people** increases by **2.5 kg** when a person weighing **65 kg** is replaced by someone new. What is the **new person's weight**?",
    options: ["75 kg", "80 kg", "85 kg", "90 kg"],
    answer: 2,
    difficulty: "easy",
    hints: ["The total rose by 8 × 2.5 kg.", "New weight = 65 + the rise in total."],
    solution: "1. Rise in total = 8 × 2.5 = 20 kg.\n2. New person = 65 + 20 = **85 kg**.\n\nAnswer: **85 kg**.",
    approach: "A swap changes the total by n × (change in average). Add that to the departing member's value; the count itself never changes.",
    tags: ["replacement"],
    timeTargetSec: 50,
  },
  {
    slug: "av2-misread-entry",
    topic: "averages",
    title: "A number was misread",
    prompt:
      "The average of **10 numbers** was found to be **42**. It was later noticed that **64 had been read as 46**. What is the **correct average**?",
    options: ["43.2", "43.8", "44.0", "44.4"],
    answer: 1,
    difficulty: "easy",
    hints: ["Only the total changes, by the size of the error.", "The shortfall of 18 is spread over 10 numbers."],
    solution:
      "1. The total was short by 64 − 46 = 18.\n2. The average rises by 18 ÷ 10 = 1.8.\n3. Correct average = 42 + 1.8 = **43.8**.\n\nAnswer: **43.8**.",
    approach: "A corrected entry shifts the average by (correct − wrong) ÷ n. There is never any need to recompute the whole total.",
    tags: ["correction"],
    timeTargetSec: 50,
  },
  {
    slug: "av2-two-groups-combined",
    topic: "averages",
    title: "Combining two groups",
    prompt:
      "The average of **30 results is 20** and the average of **20 other results is 30**. What is the average of **all 50**?",
    options: ["23", "24", "25", "26"],
    answer: 1,
    difficulty: "easy",
    hints: ["Add the two totals, then divide by 50.", "600 + 600 = 1,200."],
    solution:
      "1. Totals: 30 × 20 = 600 and 20 × 30 = 600.\n2. Combined = 1,200 over 50 results.\n3. Average = **24**.\n\nAnswer: **24**.",
    approach:
      "A combined average is total ÷ total count, never the mean of the two averages. Here the plain mean would give 25, which is offered.",
    tags: ["weighted average"],
    timeTargetSec: 50,
  },
  {
    slug: "av2-two-classes-combined",
    topic: "averages",
    title: "Two classes together",
    prompt:
      "A class of **30 students** averages **40 marks** and another of **50 students** averages **60 marks**. What is the **combined average**?",
    options: ["50", "52.5", "54", "55"],
    answer: 1,
    difficulty: "medium",
    hints: ["Totals first: 1,200 and 3,000.", "Divide 4,200 by 80."],
    solution:
      "1. Totals: 30 × 40 = 1,200 and 50 × 60 = 3,000.\n2. Combined total = 4,200 over 80 students.\n3. Average = 4,200 ÷ 80 = **52.5**.\n\nAnswer: **52.5**.",
    approach: "The combined average leans towards the larger group — here towards 60, so above the midpoint of 50. That is a useful check on the answer.",
    tags: ["weighted average"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-three-classes",
    topic: "averages",
    title: "Three sections of a year group",
    prompt:
      "Three classes have **25, 30 and 45 students** with average marks **50, 60 and 70** respectively. What is the **overall average**?",
    options: ["60", "62", "64", "65"],
    answer: 1,
    difficulty: "medium",
    hints: ["Compute each total and add.", "1,250 + 1,800 + 3,150 = 6,200 across 100 students."],
    solution:
      "1. Totals: 25 × 50 = 1,250; 30 × 60 = 1,800; 45 × 70 = 3,150.\n2. Sum = 6,200 over 100 students.\n3. Average = **62**.\n\nAnswer: **62**.",
    approach: "Weighted average across any number of groups: sum of (count × average) divided by the total count. The plain mean of 50, 60 and 70 is 60 and is wrong.",
    tags: ["weighted average"],
    timeTargetSec: 75,
  },
  {
    slug: "av2-batsman-seventeenth",
    topic: "averages",
    title: "A score in the 17th innings",
    prompt:
      "A batsman's average after **16 innings is 40**. He scores **91** in the 17th. What is his **new average**?",
    options: ["41", "42", "43", "44"],
    answer: 2,
    difficulty: "easy",
    hints: ["Total after 16 innings is 640.", "(640 + 91) ÷ 17."],
    solution:
      "1. Runs after 16 innings = 640.\n2. After 17 innings = 731.\n3. New average = 731 ÷ 17 = **43**.\n\nAnswer: **43**.",
    approach: "The average moves by (new score − old average) ÷ new count = (91 − 40)/17 = 3. Deviation from the old average is what shifts a mean.",
    tags: ["running average"],
    timeTargetSec: 50,
  },
  {
    slug: "av2-runs-to-raise-average",
    topic: "averages",
    title: "Runs needed to raise the average",
    prompt:
      "A cricketer has an average of **48 runs in 12 innings**. How many runs must he score in the **13th innings** to raise his average by **5**?",
    options: ["93", "103", "113", "123"],
    answer: 2,
    difficulty: "medium",
    hints: ["The target average is 53 across 13 innings.", "13 × 53 − 12 × 48."],
    solution:
      "1. Required total = 13 × 53 = 689.\n2. Present total = 12 × 48 = 576.\n3. Runs needed = 689 − 576 = **113**.\n\nAnswer: **113**.",
    approach:
      "Shortcut: new average + (old count × rise) = 53 + 12 × 5 = 113. The innings must reach the new average and also lift every earlier innings by the increase.",
    tags: ["running average"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-fourth-innings",
    topic: "averages",
    title: "The fourth innings",
    prompt:
      "A player's average after **3 innings is 42**. After the **4th** his average becomes **44**. How many runs did he score in the 4th?",
    options: ["46", "48", "50", "52"],
    answer: 2,
    difficulty: "easy",
    hints: ["Totals: 3 × 42 and 4 × 44.", "176 − 126."],
    solution: "1. Old total = 126; new total = 4 × 44 = 176.\n2. Fourth innings = 176 − 126 = **50**.\n\nAnswer: **50**.",
    approach: "Difference of totals gives the new value. The shortcut 44 + 3 × 2 = 50 gives the same thing.",
    tags: ["running average"],
    timeTargetSec: 45,
  },
  {
    slug: "av2-excluded-number",
    topic: "averages",
    title: "One number is excluded",
    prompt:
      "The average of **5 numbers is 27**. When one number is excluded the average becomes **25**. What was the **excluded number**?",
    options: ["25", "30", "35", "40"],
    answer: 2,
    difficulty: "easy",
    hints: ["Totals: 5 × 27 and 4 × 25.", "135 − 100."],
    solution: "1. Original total = 135; remaining total = 4 × 25 = 100.\n2. Excluded number = 135 − 100 = **35**.\n\nAnswer: **35**.",
    approach: "Difference of totals again. A number above the old average always pulls the average down when removed, which the answer confirms.",
    tags: ["removal"],
    timeTargetSec: 45,
  },
  {
    slug: "av2-new-observation",
    topic: "averages",
    title: "A new observation is added",
    prompt:
      "The average of **6 observations is 12**. A new observation is included and the average becomes **13**. What is the **new observation**?",
    options: ["13", "16", "19", "22"],
    answer: 2,
    difficulty: "easy",
    hints: ["The new total is 7 × 13.", "91 − 72."],
    solution: "1. Old total = 72; new total = 7 × 13 = 91.\n2. New observation = 91 − 72 = **19**.\n\nAnswer: **19**.",
    approach: "New value = new average + old count × rise = 13 + 6 × 1 = 19. The same relation as the batsman questions, in smaller numbers.",
    tags: ["adding a member"],
    timeTargetSec: 45,
  },
  {
    slug: "av2-discard-two-numbers",
    topic: "averages",
    title: "Two numbers discarded",
    prompt:
      "The average of **50 numbers is 38**. If the numbers **45 and 55 are discarded**, what is the average of the rest?",
    options: ["36.5", "37", "37.5", "38"],
    answer: 2,
    difficulty: "medium",
    hints: ["Total = 50 × 38 = 1,900.", "Remove 100 and divide by 48."],
    solution:
      "1. Total = 1,900.\n2. After discarding: 1,900 − 100 = 1,800 over 48 numbers.\n3. Average = 1,800 ÷ 48 = **37.5**.\n\nAnswer: **37.5**.",
    approach:
      "Both discarded numbers are above the average, so the average must fall — a quick check before computing. Work with totals, never with the averages directly.",
    tags: ["removal"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-eleven-results-sixth",
    topic: "averages",
    title: "Finding the sixth result",
    prompt:
      "The average of **11 results is 50**. The average of the **first six is 49** and of the **last six is 52**. What is the **sixth result**?",
    options: ["48", "52", "56", "60"],
    answer: 2,
    difficulty: "medium",
    hints: ["The sixth result is counted in both groups of six.", "6 × 49 + 6 × 52 − 11 × 50."],
    solution:
      "1. First six total = 294; last six total = 312; sum = 606.\n2. All eleven total = 550.\n3. The sixth result is counted twice, so it equals 606 − 550 = **56**.\n\nAnswer: **56**.",
    approach:
      "When two overlapping groups are given, their totals double-count the shared member. Subtracting the true total isolates it.",
    tags: ["overlap"],
    timeTargetSec: 90,
  },
  {
    slug: "av2-eleven-numbers-middle",
    topic: "averages",
    title: "The middle number of eleven",
    prompt:
      "The average of **11 numbers is 10.9**. If the average of the **first six is 10.5** and of the **last six is 11.4**, what is the **sixth number**?",
    options: ["10.3", "11.0", "11.5", "12.0"],
    answer: 2,
    difficulty: "medium",
    hints: ["The sixth number belongs to both groups.", "6 × 10.5 + 6 × 11.4 − 11 × 10.9."],
    solution:
      "1. First six = 63.0; last six = 68.4; sum = 131.4.\n2. All eleven = 11 × 10.9 = 119.9.\n3. Sixth number = 131.4 − 119.9 = **11.5**.\n\nAnswer: **11.5**.",
    approach: "The same overlap rule with decimals. Keep one decimal place throughout rather than rounding early.",
    tags: ["overlap"],
    timeTargetSec: 90,
  },
  {
    slug: "av2-abc-weights",
    topic: "averages",
    title: "The weight of B",
    prompt:
      "The average weight of **A, B and C is 45 kg**. The average of **A and B is 40 kg** and of **B and C is 43 kg**. What is **B's weight**?",
    options: ["17 kg", "20 kg", "26 kg", "31 kg"],
    answer: 3,
    difficulty: "medium",
    hints: ["A + B + C = 135, A + B = 80 and B + C = 86.", "Add the last two and subtract the first."],
    solution:
      "1. A + B + C = 135; A + B = 80; B + C = 86.\n2. (A + B) + (B + C) = 166, which is (A + B + C) + B.\n3. B = 166 − 135 = **31 kg**.\n\nAnswer: **31 kg**.",
    approach:
      "Adding the two pair totals counts B twice; subtracting the three-person total leaves B alone. This is faster than solving for A and C first.",
    tags: ["overlap"],
    timeTargetSec: 90,
  },
  {
    slug: "av2-workshop-technicians",
    topic: "averages",
    title: "Technicians and the rest",
    prompt:
      "The average salary of all workers in a workshop is **₹8,000**. The average of **7 technicians is ₹12,000** and of the remaining workers **₹6,000**. How many **workers** are there in all?",
    options: ["18", "20", "21", "24"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Let the total number of workers be n.",
      "12,000 × 7 + 6,000 × (n − 7) = 8,000n.",
    ],
    solution:
      "1. 84,000 + 6,000(n − 7) = 8,000n.\n2. 84,000 + 6,000n − 42,000 = 8,000n → 42,000 = 2,000n.\n3. n = **21**.\n4. Check: 7 × 12,000 + 14 × 6,000 = 84,000 + 84,000 = 1,68,000 = 21 × 8,000. ✓\n\nAnswer: **21**.",
    approach:
      "Set the sum of the group totals equal to the overall total and solve for the unknown count. Alligation gives the same answer faster: the ratio of technicians to others is (8,000 − 6,000) : (12,000 − 8,000) = 1 : 2.",
    tags: ["weighted average"],
    timeTargetSec: 120,
  },
  {
    slug: "av2-six-numbers-pairs",
    topic: "averages",
    title: "Three pairs of numbers",
    prompt:
      "The average of **6 numbers is 3.95**. The average of **two of them is 3.4** and of **another two is 3.85**. What is the average of the **remaining two**?",
    options: ["4.2", "4.5", "4.6", "4.7"],
    answer: 2,
    difficulty: "medium",
    hints: ["Total = 6 × 3.95 = 23.7.", "Subtract the two known pair totals, 6.8 and 7.7."],
    solution:
      "1. Total = 6 × 3.95 = 23.7.\n2. First pair = 6.8; second pair = 7.7; together 14.5.\n3. Remaining pair = 23.7 − 14.5 = 9.2, so their average is 9.2 ÷ 2 = **4.6**.\n\nAnswer: **4.6**.",
    approach: "Work in totals throughout and divide only at the very end. Averaging averages would be wrong even here, where the groups happen to be equal.",
    tags: ["groups"],
    timeTargetSec: 90,
  },
  {
    slug: "av2-temperature-monday-thursday",
    topic: "averages",
    title: "Temperatures across four days",
    prompt:
      "The average temperature for **Monday, Tuesday and Wednesday was 37°**, and for **Tuesday, Wednesday and Thursday it was 34°**. If **Thursday's temperature was 4/5 of Monday's**, what was **Monday's** temperature?",
    options: ["36°", "38°", "40°", "45°"],
    answer: 3,
    difficulty: "hard",
    hints: [
      "Mon + Tue + Wed = 111 and Tue + Wed + Thu = 102.",
      "Subtracting gives Mon − Thu = 9.",
      "With Thu = 0.8 × Mon, that becomes 0.2 × Mon = 9.",
    ],
    solution:
      "1. Mon + Tue + Wed = 3 × 37 = 111.\n2. Tue + Wed + Thu = 3 × 34 = 102.\n3. Subtracting: Mon − Thu = 9.\n4. Thu = (4/5)Mon, so Mon − 0.8Mon = 9 → 0.2Mon = 9 → Mon = **45°**.\n\nAnswer: **45°**.",
    approach:
      "Overlapping windows: subtract the two totals so the shared days cancel and only the two end days remain. Then use the given relation between them.",
    tags: ["overlap"],
    timeTargetSec: 135,
  },
  {
    slug: "av2-expenditure-and-savings",
    topic: "averages",
    title: "Average monthly income",
    prompt:
      "A man's average monthly expenditure for the **first 3 months was ₹2,200** and for the **next 9 months ₹1,800**. He **saved ₹1,200** during the year. What was his **average monthly income**?",
    options: ["₹1,900", "₹2,000", "₹2,100", "₹2,200"],
    answer: 1,
    difficulty: "medium",
    hints: ["Total spending for the year, then add the savings.", "6,600 + 16,200 + 1,200 = 24,000."],
    solution:
      "1. Spending = 3 × 2,200 + 9 × 1,800 = 6,600 + 16,200 = ₹22,800.\n2. Income = spending + savings = 22,800 + 1,200 = ₹24,000.\n3. Average monthly income = 24,000 ÷ 12 = **₹2,000**.\n\nAnswer: **₹2,000**.",
    approach: "Income = expenditure + savings over the same period. Work out the annual figures, then divide by 12 once at the end.",
    tags: ["income and savings"],
    timeTargetSec: 90,
  },
  {
    slug: "av2-family-after-five-years",
    topic: "averages",
    title: "A family five years on",
    prompt:
      "The average age of a **husband and wife was 23 years** when they married. **Five years later** they have a **one-year-old child**. What is the **average age of the family** now?",
    options: ["17", "18", "19", "20"],
    answer: 2,
    difficulty: "medium",
    hints: ["Each parent is five years older now.", "Their combined age is 46 + 10 = 56, plus the child."],
    solution:
      "1. At marriage the couple's total age = 2 × 23 = 46.\n2. Five years later = 46 + 10 = 56.\n3. With the child: (56 + 1)/3 = 57/3 = **19**.\n\nAnswer: **19**.",
    approach: "Age the existing members forward by the same number of years each, then add the new member and divide by the new count.",
    tags: ["ages"],
    timeTargetSec: 75,
  },
  {
    slug: "av2-seven-consecutive",
    topic: "averages",
    title: "Seven consecutive numbers",
    prompt: "The average of **seven consecutive numbers is 20**. What is the **largest** of them?",
    options: ["21", "22", "23", "24"],
    answer: 2,
    difficulty: "easy",
    hints: ["The average of consecutive numbers is the middle one.", "So the numbers run from 17 to 23."],
    solution:
      "1. With seven consecutive terms the middle one is the average, so it is 20.\n2. The numbers are 17, 18, 19, 20, 21, 22, 23.\n3. The largest is **23**.\n\nAnswer: **23**.",
    approach: "For an odd count of consecutive numbers, the average is the middle term and the largest is average + (count − 1)/2.",
    tags: ["series"],
    timeTargetSec: 40,
  },
  {
    slug: "av2-five-consecutive-even",
    topic: "averages",
    title: "Five consecutive even numbers",
    prompt: "The average of **five consecutive even numbers is 24**. What is the **smallest** of them?",
    options: ["18", "20", "22", "26"],
    answer: 1,
    difficulty: "easy",
    hints: ["The middle number is the average.", "The numbers step down by two from 24."],
    solution:
      "1. The middle number is 24, so the numbers are 20, 22, 24, 26, 28.\n2. The smallest is **20**.\n\nAnswer: **20**.",
    approach: "Evenly spaced with an odd count: middle term = average, then step out by the common difference.",
    tags: ["series"],
    timeTargetSec: 40,
  },
  {
    slug: "av2-multiply-each-by-three",
    topic: "averages",
    title: "Scaling every number",
    prompt: "The average of **8 numbers is 20**. If **each number is multiplied by 3**, what is the new average?",
    options: ["20", "23", "40", "60"],
    answer: 3,
    difficulty: "easy",
    hints: ["Scaling every value scales the total by the same factor.", "The count does not change."],
    solution: "1. Every number triples, so the total triples.\n2. The count is unchanged, so the average triples: 20 × 3 = **60**.\n\nAnswer: **60**.",
    approach:
      "Multiplying all values by k multiplies the average by k; adding k to all values adds k to the average. Confusing the two gives 23, which is offered.",
    tags: ["transformation"],
    timeTargetSec: 40,
  },
  {
    slug: "av2-at-most-greater-than-zero",
    topic: "averages",
    title: "How many can be positive",
    prompt:
      "The average of **20 numbers is zero**. **At most** how many of them may be **greater than zero**?",
    options: ["0", "1", "19", "20"],
    answer: 2,
    difficulty: "medium",
    hints: ["The numbers must sum to zero.", "If all were positive the sum could not be zero — but only one needs to be negative."],
    solution:
      "1. An average of zero means the total is zero.\n2. If 19 numbers are positive, a single sufficiently large negative number can balance them.\n3. All 20 cannot be positive, so the maximum is **19**.\n\nAnswer: **19**.",
    approach:
      "'At most' questions ask for the extreme case that is still possible. One negative number of any size can offset any number of positives, so only one must be sacrificed.",
    tags: ["reasoning"],
    timeTargetSec: 60,
  },
  {
    slug: "av2-average-speed-two-legs",
    topic: "averages",
    title: "Average speed over two legs",
    prompt:
      "A car covers **100 km at 60 km/h** and another **100 km at 40 km/h**. What is its **average speed** for the whole journey?",
    options: ["45 km/h", "48 km/h", "50 km/h", "52 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Average speed = total distance ÷ total time, not the mean of the speeds.", "Times are 100/60 and 100/40 hours."],
    solution:
      "1. Time = 100/60 + 100/40 = 5/3 + 5/2 = 25/6 hours.\n2. Total distance = 200 km.\n3. Average speed = 200 ÷ (25/6) = **48 km/h**.\n\nAnswer: **48 km/h**.",
    approach:
      "For equal distances the average speed is the harmonic mean 2ab/(a + b) = 48, always below the arithmetic mean of 50. Equal *times* would give 50 instead.",
    tags: ["speed"],
    timeTargetSec: 75,
  },
];
