import type { AptitudeSeed } from "./types.js";

/** Analogies and classification — verbal and numeric. */
export const BANK_ANALOGIES: AptitudeSeed[] = [
  {
    slug: "an2-pen-write",
    topic: "analogies-classification",
    title: "Pen is to write",
    prompt: "**Pen : Write :: Knife : ?**",
    options: ["Sharp", "Cut", "Metal", "Kitchen"],
    answer: 1,
    difficulty: "easy",
    hints: ["A pen is a tool used to write.", "What is a knife used to do?"],
    solution:
      "1. The relation is tool to its function: a pen is used to write.\n2. A knife is used to **cut**.\n3. *Sharp* is a property, *metal* a material and *kitchen* a place — none of them is a function.\n\nAnswer: **Cut**.",
    approach: "State the relation as a short sentence before reading the options, then test each option in that same sentence.",
    tags: ["function"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-bird-nest",
    topic: "analogies-classification",
    title: "Bird is to nest",
    prompt: "**Bird : Nest :: Bee : ?**",
    options: ["Honey", "Hive", "Flower", "Sting"],
    answer: 1,
    difficulty: "easy",
    hints: ["A nest is where a bird lives.", "Where does a bee live?"],
    solution:
      "1. The relation is creature to dwelling.\n2. A bee lives in a **hive**.\n3. *Honey* is what it produces and *sting* is what it has — different relations.\n\nAnswer: **Hive**.",
    approach: "Distinguish 'lives in' from 'produces'. Distractors in this pattern are almost always the product or a body part.",
    tags: ["dwelling"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-hunger-food",
    topic: "analogies-classification",
    title: "Hunger is to food",
    prompt: "**Hunger : Food :: Thirst : ?**",
    options: ["Drink", "Water", "Dry", "Throat"],
    answer: 1,
    difficulty: "easy",
    hints: ["Food is what relieves hunger.", "What relieves thirst?"],
    solution:
      "1. The relation is need to what satisfies it.\n2. Thirst is satisfied by **water**.\n3. *Drink* is a verb here rather than the substance, and *dry* and *throat* are unrelated.\n\nAnswer: **Water**.",
    approach: "Match the part of speech as well as the meaning. Food is a noun, so the answer must be a noun too.",
    tags: ["need"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-book-author",
    topic: "analogies-classification",
    title: "Book is to author",
    prompt: "**Book : Author :: Painting : ?**",
    options: ["Canvas", "Colour", "Artist", "Gallery"],
    answer: 2,
    difficulty: "easy",
    hints: ["An author creates a book.", "Who creates a painting?"],
    solution:
      "1. The relation is creation to creator.\n2. A painting is created by an **artist**.\n3. *Canvas* and *colour* are materials; *gallery* is where it hangs.\n\nAnswer: **Artist**.",
    approach: "Creation-to-creator is one of the commonest analogy relations. Materials and locations are the standard distractors.",
    tags: ["creator"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-cow-calf",
    topic: "analogies-classification",
    title: "Cow is to calf",
    prompt: "**Cow : Calf :: Dog : ?**",
    options: ["Kitten", "Puppy", "Cub", "Foal"],
    answer: 1,
    difficulty: "easy",
    hints: ["A calf is a young cow.", "What is a young dog called?"],
    solution:
      "1. The relation is adult to young.\n2. A young dog is a **puppy**.\n3. A kitten is a young cat, a cub a young lion or bear, a foal a young horse.\n\nAnswer: **Puppy**.",
    approach: "Young-animal names are worth learning as a set: calf, puppy, kitten, cub, foal, lamb, chick, kid.",
    tags: ["young"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-foot-man",
    topic: "analogies-classification",
    title: "Foot is to man",
    prompt: "**Foot : Man :: Hoof : ?**",
    options: ["Bird", "Fish", "Horse", "Snake"],
    answer: 2,
    difficulty: "easy",
    hints: ["A foot is what a man walks on.", "Which animal has hooves?"],
    solution:
      "1. The relation is body part to the creature that has it.\n2. A **horse** has hooves.\n3. Birds have claws, fish have fins and snakes have neither.\n\nAnswer: **Horse**.",
    approach: "Body-part analogies test vocabulary more than logic. Read the pair in both directions to be sure of the relation.",
    tags: ["body parts"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-carpenter-wood",
    topic: "analogies-classification",
    title: "Carpenter is to wood",
    prompt: "**Carpenter : Wood :: Blacksmith : ?**",
    options: ["Fire", "Iron", "Hammer", "Anvil"],
    answer: 1,
    difficulty: "easy",
    hints: ["A carpenter works with wood.", "What material does a blacksmith work with?"],
    solution:
      "1. The relation is worker to the material worked.\n2. A blacksmith works with **iron**.\n3. *Hammer* and *anvil* are his tools, not his material.\n\nAnswer: **Iron**.",
    approach: "Be precise about which relation is at play: worker-to-material, not worker-to-tool. Both appear among the options here.",
    tags: ["occupation"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-clock-time",
    topic: "analogies-classification",
    title: "Clock is to time",
    prompt: "**Clock : Time :: Thermometer : ?**",
    options: ["Heat", "Temperature", "Mercury", "Weather"],
    answer: 1,
    difficulty: "easy",
    hints: ["A clock measures time.", "What does a thermometer measure?"],
    solution:
      "1. The relation is instrument to what it measures.\n2. A thermometer measures **temperature**.\n3. *Mercury* is what it contains and *heat* is a related but distinct quantity.\n\nAnswer: **Temperature**.",
    approach:
      "Instrument-to-quantity pairs are common: barometer and pressure, speedometer and speed, seismograph and earthquakes. Precision of the quantity matters — heat is not temperature.",
    tags: ["instrument"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-light-blind",
    topic: "analogies-classification",
    title: "Light is to blind",
    prompt: "**Light : Blind :: Sound : ?**",
    options: ["Dumb", "Deaf", "Loud", "Silent"],
    answer: 1,
    difficulty: "medium",
    hints: ["A blind person cannot perceive light.", "Who cannot perceive sound?"],
    solution:
      "1. The relation is a stimulus to the person unable to perceive it.\n2. A **deaf** person cannot perceive sound.\n3. *Dumb* refers to speech, not hearing.\n\nAnswer: **Deaf**.",
    approach: "The dumb-versus-deaf confusion is exactly what this question tests. Deafness concerns receiving sound; dumbness concerns producing it.",
    tags: ["senses"],
    timeTargetSec: 45,
  },
  {
    slug: "an2-guitar-strings",
    topic: "analogies-classification",
    title: "Guitar is to strings",
    prompt: "**Guitar : Strings :: Piano : ?**",
    options: ["Keys", "Music", "Wood", "Pedals"],
    answer: 0,
    difficulty: "easy",
    hints: ["Strings are what you play on a guitar.", "What do you play on a piano?"],
    solution:
      "1. The relation is instrument to the part played.\n2. A piano is played with its **keys**.\n3. *Pedals* exist but are not what produces the notes.\n\nAnswer: **Keys**.",
    approach: "Choose the part that plays the same role, not merely a part that exists. A piano does have pedals, but they are not its strings.",
    tags: ["parts"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-teacher-student",
    topic: "analogies-classification",
    title: "Teacher is to student",
    prompt: "**Teacher : Student :: Doctor : ?**",
    options: ["Nurse", "Patient", "Hospital", "Medicine"],
    answer: 1,
    difficulty: "easy",
    hints: ["A teacher serves students.", "Whom does a doctor serve?"],
    solution:
      "1. The relation is professional to the person served.\n2. A doctor serves a **patient**.\n3. A nurse is a colleague, not the person served.\n\nAnswer: **Patient**.",
    approach: "Identify who is on the receiving end of the professional's work. Colleagues and workplaces are the usual distractors.",
    tags: ["occupation"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-ocean-water",
    topic: "analogies-classification",
    title: "Ocean is to water",
    prompt: "**Ocean : Water :: Desert : ?**",
    options: ["Camel", "Heat", "Sand", "Dry"],
    answer: 2,
    difficulty: "easy",
    hints: ["An ocean is made up of water.", "What is a desert made up of?"],
    solution:
      "1. The relation is place to the substance it consists of.\n2. A desert consists of **sand**.\n3. *Camel* lives there and *heat* is a condition, not the substance.\n\nAnswer: **Sand**.",
    approach: "Keep the relation identical on both sides. Anything merely associated with a desert will not match 'is made of'.",
    tags: ["composition"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-poet-poem",
    topic: "analogies-classification",
    title: "Poet is to poem",
    prompt: "**Poet : Poem :: Composer : ?**",
    options: ["Orchestra", "Symphony", "Piano", "Concert"],
    answer: 1,
    difficulty: "easy",
    hints: ["A poet writes a poem.", "What does a composer write?"],
    solution:
      "1. The relation is creator to work created.\n2. A composer writes a **symphony**.\n3. An orchestra performs it and a concert is where it is heard.\n\nAnswer: **Symphony**.",
    approach: "Distinguish the work itself from those who perform it and where it is performed. All three appear among the options.",
    tags: ["creator"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-square-of-nine",
    topic: "analogies-classification",
    title: "A numerical analogy",
    prompt: "**7 : 49 :: 11 : ?**",
    options: ["77", "111", "121", "132"],
    answer: 2,
    difficulty: "easy",
    hints: ["49 is 7 squared.", "What is 11 squared?"],
    solution: "1. 49 = 7².\n2. 11² = **121**.\n\nAnswer: **121**.",
    approach: "Test the simple operations in order: square, cube, double, add a constant. Confirm on the given pair before applying it.",
    tags: ["numeric analogy"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-cube-of-four",
    topic: "analogies-classification",
    title: "Cubes in an analogy",
    prompt: "**4 : 64 :: 5 : ?**",
    options: ["100", "125", "150", "625"],
    answer: 1,
    difficulty: "easy",
    hints: ["64 is 4 cubed.", "What is 5 cubed?"],
    solution: "1. 64 = 4³.\n2. 5³ = **125**.\n\nAnswer: **125**.",
    approach: "Since 64 is both 4³ and 8², check the second pair to break the tie. Here 5² = 25 is not offered, so the cube is intended.",
    tags: ["numeric analogy"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-cube-of-two",
    topic: "analogies-classification",
    title: "Small cubes",
    prompt: "**2 : 8 :: 3 : ?**",
    options: ["9", "12", "18", "27"],
    answer: 3,
    difficulty: "easy",
    hints: ["8 is 2 cubed.", "3³ = ?"],
    solution: "1. 8 = 2³.\n2. 3³ = **27**.\n\nAnswer: **27**.",
    approach: "Nine is offered for anyone who reads the relation as squaring. Checking 2² = 4 against the given 8 rules that out immediately.",
    tags: ["numeric analogy"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-square-root",
    topic: "analogies-classification",
    title: "Square roots",
    prompt: "**16 : 4 :: 49 : ?**",
    options: ["6", "7", "8", "9"],
    answer: 1,
    difficulty: "easy",
    hints: ["4 is the square root of 16.", "What is the square root of 49?"],
    solution: "1. 4 = √16.\n2. √49 = **7**.\n\nAnswer: **7**.",
    approach: "The relation may run either way — squaring or taking the root. The order of the pair tells you which.",
    tags: ["numeric analogy"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-square-root-large",
    topic: "analogies-classification",
    title: "Larger square roots",
    prompt: "**121 : 11 :: 169 : ?**",
    options: ["12", "13", "14", "17"],
    answer: 1,
    difficulty: "easy",
    hints: ["11 is the square root of 121.", "169 = 13²."],
    solution: "1. 11 = √121.\n2. √169 = **13**.\n\nAnswer: **13**.",
    approach: "Memorise squares to at least 25²: 121, 144, 169, 196, 225 come up constantly in these questions.",
    tags: ["numeric analogy"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-n-times-n-plus-one",
    topic: "analogies-classification",
    title: "A product analogy",
    prompt: "**6 : 42 :: 7 : ?**",
    options: ["48", "49", "56", "63"],
    answer: 2,
    difficulty: "medium",
    hints: ["42 = 6 × 7.", "So the rule is n × (n + 1)."],
    solution: "1. 42 = 6 × 7, so the rule is n(n + 1).\n2. 7 × 8 = **56**.\n\nAnswer: **56**.",
    approach: "When the result is close to but not equal to n², try n(n + 1) or n(n − 1). Here 49 is offered as the square trap.",
    tags: ["numeric analogy"],
    timeTargetSec: 45,
  },
  {
    slug: "an2-doubling-plus",
    topic: "analogies-classification",
    title: "Double and add",
    prompt: "**5 : 12 :: 8 : ?**",
    options: ["16", "17", "18", "20"],
    answer: 2,
    difficulty: "medium",
    hints: ["12 is a little more than double 5.", "The rule is 2n + 2."],
    solution: "1. 12 = 2 × 5 + 2.\n2. 2 × 8 + 2 = **18**.\n\nAnswer: **18**.",
    approach: "Try 2n, 2n ± k and 3n − k when the result is a small multiple of the input. Confirm with the numbers you are given.",
    tags: ["numeric analogy"],
    timeTargetSec: 50,
  },
  {
    slug: "an2-odd-flower",
    topic: "analogies-classification",
    title: "The odd one out",
    prompt: "Which one does **not** belong with the others?\n\n**Apple, Banana, Potato, Mango**",
    options: ["Apple", "Banana", "Potato", "Mango"],
    answer: 2,
    difficulty: "easy",
    hints: ["Three of these are the same kind of thing.", "Potato grows underground and is a vegetable."],
    solution:
      "1. Apple, banana and mango are fruits.\n2. **Potato** is a vegetable.\n\nAnswer: **Potato**.",
    approach: "Find the category covering most of the items; the exception is the answer. A good category leaves exactly one item out.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-odd-indoor-game",
    topic: "analogies-classification",
    title: "The odd game out",
    prompt: "Which one does **not** belong?\n\n**Cricket, Football, Hockey, Chess**",
    options: ["Cricket", "Football", "Hockey", "Chess"],
    answer: 3,
    difficulty: "easy",
    hints: ["Three of these are played outdoors on a field.", "Chess is an indoor board game."],
    solution:
      "1. Cricket, football and hockey are outdoor field games.\n2. **Chess** is an indoor board game.\n\nAnswer: **Chess**.",
    approach: "Look for the sharpest dividing line. Indoor versus outdoor separates these cleanly, while 'team game' would too — both give the same answer.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-odd-alloy",
    topic: "analogies-classification",
    title: "The odd substance",
    prompt: "Which one does **not** belong?\n\n**Copper, Zinc, Brass, Iron**",
    options: ["Copper", "Zinc", "Brass", "Iron"],
    answer: 2,
    difficulty: "medium",
    hints: ["Three of these are pure metals.", "Brass is a mixture of copper and zinc."],
    solution:
      "1. Copper, zinc and iron are elements.\n2. **Brass** is an alloy of copper and zinc, not an element.\n\nAnswer: **Brass**.",
    approach: "Element versus alloy is the intended split. Bronze and steel appear in the same family of questions.",
    tags: ["classification"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-odd-shape",
    topic: "analogies-classification",
    title: "The odd shape",
    prompt: "Which one does **not** belong?\n\n**Triangle, Square, Circle, Rectangle**",
    options: ["Triangle", "Square", "Circle", "Rectangle"],
    answer: 2,
    difficulty: "easy",
    hints: ["Three of these are made of straight sides.", "A circle has no sides or corners."],
    solution:
      "1. Triangle, square and rectangle are polygons with straight sides and vertices.\n2. A **circle** has neither.\n\nAnswer: **Circle**.",
    approach: "Ask what property three share that the fourth lacks. Here it is having straight edges and corners.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-odd-month",
    topic: "analogies-classification",
    title: "The odd month",
    prompt: "Which one does **not** belong?\n\n**January, March, June, July**",
    options: ["January", "March", "June", "July"],
    answer: 2,
    difficulty: "medium",
    hints: ["Count the days in each month.", "Three have 31 days."],
    solution:
      "1. January, March and July have 31 days.\n2. **June** has 30.\n\nAnswer: **June**.",
    approach: "When the items are dates or names, count something about them — days, letters, or position. Day counts are the usual test.",
    tags: ["classification"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-odd-non-prime",
    topic: "analogies-classification",
    title: "The odd number",
    prompt: "Which one does **not** belong?\n\n**3, 5, 7, 9, 11**",
    options: ["3", "5", "9", "11"],
    answer: 2,
    difficulty: "easy",
    hints: ["All five are odd, so that is not the distinguishing property.", "Four of them are prime."],
    solution:
      "1. All the numbers are odd, so oddness cannot be the rule.\n2. 3, 5, 7 and 11 are prime; **9** = 3 × 3 is not.\n\nAnswer: **9**.",
    approach: "When an obvious property is shared by everything, look for a second one. Being odd is a decoy here.",
    tags: ["classification", "primes"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-odd-not-square",
    topic: "analogies-classification",
    title: "The number that is not a square",
    prompt: "Which one does **not** belong?\n\n**25, 36, 49, 62**",
    options: ["25", "36", "49", "62"],
    answer: 3,
    difficulty: "easy",
    hints: ["Three of these are perfect squares.", "62 lies between 49 and 64."],
    solution: "1. 25 = 5², 36 = 6², 49 = 7².\n2. **62** is not a perfect square.\n\nAnswer: **62**.",
    approach: "Check the squares first. A number sitting between two consecutive squares cannot itself be one.",
    tags: ["classification", "squares"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-odd-wild-animal",
    topic: "analogies-classification",
    title: "The odd animal",
    prompt: "Which one does **not** belong?\n\n**Dog, Cat, Lion, Horse**",
    options: ["Dog", "Cat", "Lion", "Horse"],
    answer: 2,
    difficulty: "easy",
    hints: ["Three of these are commonly kept by people.", "A lion is a wild animal."],
    solution:
      "1. Dog, cat and horse are domestic animals.\n2. A **lion** is wild.\n\nAnswer: **Lion**.",
    approach: "Domestic versus wild is the intended split. All four are mammals, so that shared property cannot decide it.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-odd-bat",
    topic: "analogies-classification",
    title: "The odd flier",
    prompt: "Which one does **not** belong?\n\n**Sparrow, Parrot, Eagle, Bat**",
    options: ["Sparrow", "Parrot", "Eagle", "Bat"],
    answer: 3,
    difficulty: "medium",
    hints: ["All four can fly, so flight is not the test.", "Three of them are birds."],
    solution:
      "1. Sparrow, parrot and eagle are birds.\n2. A **bat** is a mammal, even though it flies.\n\nAnswer: **Bat**.",
    approach: "Flight is the decoy property here. The real classification is biological, and the bat is the only mammal.",
    tags: ["classification"],
    timeTargetSec: 40,
  },
  {
    slug: "an2-odd-country",
    topic: "analogies-classification",
    title: "The odd place",
    prompt: "Which one does **not** belong?\n\n**Delhi, Mumbai, Chennai, Nepal**",
    options: ["Delhi", "Mumbai", "Chennai", "Nepal"],
    answer: 3,
    difficulty: "easy",
    hints: ["Three of these are Indian cities.", "Nepal is a country."],
    solution:
      "1. Delhi, Mumbai and Chennai are cities.\n2. **Nepal** is a country, not a city.\n\nAnswer: **Nepal**.",
    approach: "Watch the level of the category: city, state and country are different kinds of place, and mixing them is the usual trick.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-odd-vowel-letters",
    topic: "analogies-classification",
    title: "The odd letter group",
    prompt: "Which one does **not** belong?\n\n**BD, FH, JL, MO**",
    options: ["BD", "FH", "JL", "MO"],
    answer: 3,
    difficulty: "hard",
    hints: [
      "Convert each pair to alphabet positions.",
      "BD is 2 and 4, FH is 6 and 8, JL is 10 and 12, MO is 13 and 15.",
    ],
    solution:
      "1. Positions: BD = 2, 4; FH = 6, 8; JL = 10, 12; MO = 13, 15.\n2. The first three pairs start on an even position; **MO** starts on the odd position 13.\n3. (The gap of 2 is the same in all four, so the gap cannot be the distinguishing feature.)\n\nAnswer: **MO**.",
    approach:
      "Convert letters to numbers before comparing. When the obvious feature — here the gap of two — is shared by all, look for a second property.",
    tags: ["classification", "letters"],
    timeTargetSec: 90,
  },
  {
    slug: "an2-doctor-patient-treat",
    topic: "analogies-classification",
    title: "Chef is to kitchen",
    prompt: "**Chef : Kitchen :: Judge : ?**",
    options: ["Law", "Court", "Justice", "Lawyer"],
    answer: 1,
    difficulty: "easy",
    hints: ["A kitchen is where a chef works.", "Where does a judge work?"],
    solution:
      "1. The relation is worker to workplace.\n2. A judge works in a **court**.\n3. *Law* and *justice* are abstractions, and *lawyer* is a colleague.\n\nAnswer: **Court**.",
    approach: "Workplace analogies are straightforward once the relation is named. Abstractions and colleagues are the standard distractors.",
    tags: ["occupation"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-hot-cold",
    topic: "analogies-classification",
    title: "Opposites",
    prompt: "**Hot : Cold :: Victory : ?**",
    options: ["Battle", "Defeat", "Win", "Army"],
    answer: 1,
    difficulty: "easy",
    hints: ["Hot and cold are opposites.", "What is the opposite of victory?"],
    solution:
      "1. The relation is a word to its opposite.\n2. The opposite of victory is **defeat**.\n3. *Win* is a synonym, not an opposite.\n\nAnswer: **Defeat**.",
    approach: "Check whether the relation is opposite or synonym before choosing. A synonym is always offered alongside the antonym.",
    tags: ["antonym"],
    timeTargetSec: 30,
  },
  {
    slug: "an2-part-whole",
    topic: "analogies-classification",
    title: "Part and whole",
    prompt: "**Petal : Flower :: Chapter : ?**",
    options: ["Story", "Book", "Page", "Author"],
    answer: 1,
    difficulty: "easy",
    hints: ["A petal is a part of a flower.", "A chapter is a part of what?"],
    solution:
      "1. The relation is part to whole.\n2. A chapter is part of a **book**.\n3. A page is a smaller unit, not the whole.\n\nAnswer: **Book**.",
    approach: "Keep the direction consistent: part first, whole second. Reversing it would make 'page' look plausible.",
    tags: ["part whole"],
    timeTargetSec: 35,
  },
  {
    slug: "an2-degree-relation",
    topic: "analogies-classification",
    title: "A matter of degree",
    prompt: "**Warm : Hot :: Cool : ?**",
    options: ["Cold", "Ice", "Wind", "Mild"],
    answer: 0,
    difficulty: "medium",
    hints: ["Hot is a stronger version of warm.", "What is a stronger version of cool?"],
    solution:
      "1. The relation is mild form to intense form.\n2. The intense form of cool is **cold**.\n3. *Ice* is a substance, not a degree of temperature.\n\nAnswer: **Cold**.",
    approach: "Degree analogies run from weaker to stronger. Keep the same direction on both sides of the pair.",
    tags: ["degree"],
    timeTargetSec: 40,
  },
];
