import type { AptitudeSeed } from "./types.js";

/** Number and letter series — the standard placement and bank-exam set. */
export const BANK_SERIES: AptitudeSeed[] = [
  {
    slug: "ls2-n-squared-plus-n",
    topic: "number-series",
    title: "2, 6, 12, 20, 30, ?",
    prompt: "Find the next term:\n\n**2, 6, 12, 20, 30, ?**",
    options: ["36", "40", "42", "46"],
    answer: 2,
    difficulty: "easy",
    hints: ["Take the differences between consecutive terms.", "They are 4, 6, 8, 10 — the next is 12."],
    solution:
      "1. Differences: 4, 6, 8, 10, rising by 2 each time.\n2. Next difference = 12, so the term is 30 + 12 = **42**.\n3. The terms are n(n + 1): 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42. ✓\n\nAnswer: **42**.",
    approach: "First differences that rise steadily point to a quadratic. Recognising n(n + 1) confirms the pattern instantly.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-perfect-squares",
    topic: "number-series",
    title: "1, 4, 9, 16, 25, ?",
    prompt: "Find the next term:\n\n**1, 4, 9, 16, 25, ?**",
    options: ["30", "35", "36", "49"],
    answer: 2,
    difficulty: "easy",
    hints: ["These are all perfect squares.", "1², 2², 3², 4², 5² — what comes next?"],
    solution: "1. The terms are 1², 2², 3², 4², 5².\n2. The next is 6² = **36**.\n\nAnswer: **36**.",
    approach: "Check the small squares and cubes before anything else. Squares up to 400 and cubes up to 1,000 cover almost every series question.",
    tags: ["squares"],
    timeTargetSec: 35,
  },
  {
    slug: "ls2-perfect-cubes",
    topic: "number-series",
    title: "1, 8, 27, 64, ?",
    prompt: "Find the next term:\n\n**1, 8, 27, 64, ?**",
    options: ["81", "100", "125", "144"],
    answer: 2,
    difficulty: "easy",
    hints: ["These are perfect cubes.", "1³, 2³, 3³, 4³ — the next is 5³."],
    solution: "1. The terms are 1³, 2³, 3³, 4³.\n2. Next = 5³ = **125**.\n\nAnswer: **125**.",
    approach: "Cubes grow much faster than squares. Once two terms match a cube, the rest almost always follow.",
    tags: ["cubes"],
    timeTargetSec: 35,
  },
  {
    slug: "ls2-odd-squares",
    topic: "number-series",
    title: "1, 9, 25, 49, ?",
    prompt: "Find the next term:\n\n**1, 9, 25, 49, ?**",
    options: ["64", "72", "81", "100"],
    answer: 2,
    difficulty: "easy",
    hints: ["These are squares of odd numbers.", "1², 3², 5², 7² — next is 9²."],
    solution: "1. The terms are 1², 3², 5², 7².\n2. Next = 9² = **81**.\n\nAnswer: **81**.",
    approach: "When squares skip values, check whether the roots follow their own pattern — here the odd numbers.",
    tags: ["squares"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-n-squared-minus-one",
    topic: "number-series",
    title: "3, 8, 15, 24, 35, ?",
    prompt: "Find the next term:\n\n**3, 8, 15, 24, 35, ?**",
    options: ["42", "45", "48", "50"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is one less than a perfect square.", "4 − 1, 9 − 1, 16 − 1, 25 − 1, 36 − 1."],
    solution:
      "1. The terms are 2² − 1, 3² − 1, 4² − 1, 5² − 1, 6² − 1.\n2. Next = 7² − 1 = **48**.\n\nAnswer: **48**.",
    approach: "Add one to each term and see whether the results are recognisable. Small offsets from squares and cubes are extremely common.",
    tags: ["squares"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-n-cubed-minus-one",
    topic: "number-series",
    title: "7, 26, 63, 124, ?",
    prompt: "Find the next term:\n\n**7, 26, 63, 124, ?**",
    options: ["180", "195", "215", "216"],
    answer: 2,
    difficulty: "medium",
    hints: ["Add one to each term.", "8, 27, 64, 125 are cubes."],
    solution:
      "1. Adding one gives 8, 27, 64, 125 — that is 2³, 3³, 4³, 5³.\n2. Next term = 6³ − 1 = 216 − 1 = **215**.\n\nAnswer: **215**.",
    approach: "Offsetting by one is the standard disguise for a cube series. Note the trap of choosing 216 itself.",
    tags: ["cubes"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-n-cubed-minus-n",
    topic: "number-series",
    title: "336, 210, 120, 60, 24, ?",
    prompt: "Find the next term:\n\n**336, 210, 120, 60, 24, ?**",
    options: ["6", "8", "10", "12"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "The terms are falling fast — try n³ − n.",
      "7³ − 7 = 336, 6³ − 6 = 210, and so on downwards.",
    ],
    solution:
      "1. 7³ − 7 = 336, 6³ − 6 = 210, 5³ − 5 = 120, 4³ − 4 = 60, 3³ − 3 = 24.\n2. Next is 2³ − 2 = **6**.\n\nAnswer: **6**.",
    approach: "A rapidly falling series usually runs on a decreasing n. Test n³ − n and n³ + n against the largest term first.",
    tags: ["cubes"],
    timeTargetSec: 105,
  },
  {
    slug: "ls2-n-cubed-plus-n-squared",
    topic: "number-series",
    title: "2, 12, 36, 80, ?",
    prompt: "Find the next term:\n\n**2, 12, 36, 80, ?**",
    options: ["120", "150", "160", "180"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Try splitting each term into a cube plus a square.",
      "1 + 1, 8 + 4, 27 + 9, 64 + 16 — the pattern is n³ + n².",
    ],
    solution:
      "1. 1³ + 1² = 2, 2³ + 2² = 12, 3³ + 3² = 36, 4³ + 4² = 80.\n2. Next = 5³ + 5² = 125 + 25 = **150**.\n\nAnswer: **150**.",
    approach: "When a term sits between n³ and (n+1)³, try adding a square or a multiple of n to the cube. Testing the smallest terms is fastest.",
    tags: ["cubes"],
    timeTargetSec: 120,
  },
  {
    slug: "ls2-odd-differences",
    topic: "number-series",
    title: "3, 6, 11, 18, 27, ?",
    prompt: "Find the next term:\n\n**3, 6, 11, 18, 27, ?**",
    options: ["36", "38", "40", "42"],
    answer: 1,
    difficulty: "easy",
    hints: ["Differences are 3, 5, 7, 9.", "The next difference is 11."],
    solution:
      "1. Differences: 3, 5, 7, 9 — consecutive odd numbers.\n2. Next difference = 11, so the term is 27 + 11 = **38**.\n\nAnswer: **38**.",
    approach: "Odd-number differences always signal a quadratic. Here the terms are n² + 2.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-diff-3-5-7-9",
    topic: "number-series",
    title: "4, 7, 12, 19, 28, ?",
    prompt: "Find the next term:\n\n**4, 7, 12, 19, 28, ?**",
    options: ["37", "38", "39", "41"],
    answer: 2,
    difficulty: "easy",
    hints: ["Differences: 3, 5, 7, 9.", "Next difference is 11."],
    solution: "1. Differences: 3, 5, 7, 9, rising by 2.\n2. Next = 28 + 11 = **39**.\n\nAnswer: **39**.",
    approach: "The same odd-difference pattern, shifted. The terms are n² + 3.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-diff-5-7-9-11",
    topic: "number-series",
    title: "2, 7, 14, 23, 34, ?",
    prompt: "Find the next term:\n\n**2, 7, 14, 23, 34, ?**",
    options: ["45", "46", "47", "48"],
    answer: 2,
    difficulty: "easy",
    hints: ["Differences: 5, 7, 9, 11.", "The next is 13."],
    solution: "1. Differences: 5, 7, 9, 11.\n2. Next = 34 + 13 = **47**.\n\nAnswer: **47**.",
    approach: "Always write the differences under the terms. A steady rise of 2 in the differences settles the answer at once.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-diff-4-8-12-16",
    topic: "number-series",
    title: "5, 9, 17, 29, 45, ?",
    prompt: "Find the next term:\n\n**5, 9, 17, 29, 45, ?**",
    options: ["61", "63", "65", "67"],
    answer: 2,
    difficulty: "medium",
    hints: ["Differences: 4, 8, 12, 16.", "They rise by 4, so the next is 20."],
    solution: "1. Differences: 4, 8, 12, 16 — multiples of 4.\n2. Next = 45 + 20 = **65**.\n\nAnswer: **65**.",
    approach: "Differences in arithmetic progression again, this time stepping by 4. The method does not change with the step size.",
    tags: ["differences"],
    timeTargetSec: 50,
  },
  {
    slug: "ls2-diff-5-10-15-20",
    topic: "number-series",
    title: "6, 11, 21, 36, 56, ?",
    prompt: "Find the next term:\n\n**6, 11, 21, 36, 56, ?**",
    options: ["76", "81", "86", "91"],
    answer: 1,
    difficulty: "medium",
    hints: ["Differences: 5, 10, 15, 20.", "The next difference is 25."],
    solution: "1. Differences: 5, 10, 15, 20.\n2. Next = 56 + 25 = **81**.\n\nAnswer: **81**.",
    approach: "Differences that are multiples of a fixed number make the next step obvious once written down.",
    tags: ["differences"],
    timeTargetSec: 50,
  },
  {
    slug: "ls2-diff-6-9-12-15",
    topic: "number-series",
    title: "6, 12, 21, 33, ?",
    prompt: "Find the next term:\n\n**6, 12, 21, 33, ?**",
    options: ["45", "48", "51", "54"],
    answer: 1,
    difficulty: "easy",
    hints: ["Differences: 6, 9, 12.", "They rise by 3, so the next is 15."],
    solution: "1. Differences: 6, 9, 12.\n2. Next = 33 + 15 = **48**.\n\nAnswer: **48**.",
    approach: "Three differences are enough to establish an arithmetic pattern. Extend it by one step and add.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-decreasing-differences",
    topic: "number-series",
    title: "120, 99, 80, 63, 48, ?",
    prompt: "Find the next term:\n\n**120, 99, 80, 63, 48, ?**",
    options: ["33", "35", "37", "39"],
    answer: 1,
    difficulty: "medium",
    hints: ["Differences: −21, −19, −17, −15.", "The next difference is −13."],
    solution:
      "1. Differences: −21, −19, −17, −15 — shrinking by 2.\n2. Next = 48 − 13 = **35**.\n3. The terms are n² − 1 for n = 11, 10, 9, 8, 7, 6. ✓\n\nAnswer: **35**.",
    approach: "A falling series with shrinking gaps is still a quadratic, just read backwards. Recognising n² − 1 confirms it.",
    tags: ["differences"],
    timeTargetSec: 75,
  },
  {
    slug: "ls2-decreasing-1-2-3",
    topic: "number-series",
    title: "20, 19, 17, 14, 10, ?",
    prompt: "Find the next term:\n\n**20, 19, 17, 14, 10, ?**",
    options: ["3", "4", "5", "6"],
    answer: 2,
    difficulty: "easy",
    hints: ["Differences: −1, −2, −3, −4.", "The next is −5."],
    solution: "1. Differences: −1, −2, −3, −4.\n2. Next = 10 − 5 = **5**.\n\nAnswer: **5**.",
    approach: "Falling by one more each time. Write the differences out rather than trying to see the rule in the terms.",
    tags: ["differences"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-double-plus-one",
    topic: "number-series",
    title: "1, 3, 7, 15, 31, ?",
    prompt: "Find the next term:\n\n**1, 3, 7, 15, 31, ?**",
    options: ["47", "55", "63", "64"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is about double the one before.", "Term = 2 × previous + 1."],
    solution:
      "1. 1 × 2 + 1 = 3, 3 × 2 + 1 = 7, 7 × 2 + 1 = 15, 15 × 2 + 1 = 31.\n2. Next = 31 × 2 + 1 = **63**.\n3. The terms are 2ⁿ − 1. ✓\n\nAnswer: **63**.",
    approach: "Roughly doubling means testing 'previous × 2 ± k'. Powers of two offset by one are the commonest form.",
    tags: ["multiplicative"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-double-plus-one-large",
    topic: "number-series",
    title: "15, 31, 63, 127, 255, ?",
    prompt: "Find the next term:\n\n**15, 31, 63, 127, 255, ?**",
    options: ["383", "479", "511", "512"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is 2 × previous + 1.", "255 × 2 + 1."],
    solution: "1. 255 × 2 + 1 = **511**.\n2. The terms are 2ⁿ − 1: 16−1, 32−1, 64−1, 128−1, 256−1, 512−1. ✓\n\nAnswer: **511**.",
    approach: "Same rule as before with larger numbers. Choosing 512 forgets the −1 and is the trap on offer.",
    tags: ["multiplicative"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-times-two-plus-one-variant",
    topic: "number-series",
    title: "2, 5, 11, 23, 47, ?",
    prompt: "Find the next term:\n\n**2, 5, 11, 23, 47, ?**",
    options: ["83", "91", "95", "96"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is 2 × previous + 1.", "47 × 2 + 1."],
    solution: "1. 2×2+1 = 5, 5×2+1 = 11, 11×2+1 = 23, 23×2+1 = 47.\n2. Next = 47 × 2 + 1 = **95**.\n\nAnswer: **95**.",
    approach: "Once the doubling rule is confirmed on three consecutive pairs, apply it once more. No need to find a closed form.",
    tags: ["multiplicative"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-multiply-add-increasing",
    topic: "number-series",
    title: "5, 11, 24, 51, 106, ?",
    prompt: "Find the next term:\n\n**5, 11, 24, 51, 106, ?**",
    options: ["195", "205", "212", "217"],
    answer: 3,
    difficulty: "hard",
    hints: [
      "Each term is roughly double the previous, but the extra amount grows.",
      "5×2+1 = 11, 11×2+2 = 24, 24×2+3 = 51, 51×2+4 = 106.",
    ],
    solution:
      "1. The rule is × 2 then add 1, 2, 3, 4 in turn.\n2. Next = 106 × 2 + 5 = **217**.\n\nAnswer: **217**.",
    approach: "When doubling leaves an inconsistent remainder, check whether that remainder itself follows a pattern.",
    tags: ["multiplicative"],
    timeTargetSec: 105,
  },
  {
    slug: "ls2-alternating-multiply-add",
    topic: "number-series",
    title: "9, 27, 31, 155, 161, ?",
    prompt: "Find the next term:\n\n**9, 27, 31, 155, 161, ?**",
    options: ["805", "966", "1,127", "1,288"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "The operations alternate between multiplying and adding.",
      "×3, +4, ×5, +6 — so the next is ×7.",
    ],
    solution:
      "1. 9 × 3 = 27; 27 + 4 = 31; 31 × 5 = 155; 155 + 6 = 161.\n2. The next operation is × 7: 161 × 7 = **1,127**.\n\nAnswer: **1,127**.",
    approach:
      "Alternating operations are common in the harder papers. Look at each step separately rather than trying to find one rule for the whole series.",
    tags: ["alternating"],
    timeTargetSec: 120,
  },
  {
    slug: "ls2-multiply-divide-alternate",
    topic: "number-series",
    title: "8, 24, 12, 36, 18, ?",
    prompt: "Find the next term:\n\n**8, 24, 12, 36, 18, ?**",
    options: ["45", "48", "54", "72"],
    answer: 2,
    difficulty: "medium",
    hints: ["The operations alternate: × 3 then ÷ 2.", "18 × 3."],
    solution:
      "1. 8 × 3 = 24; 24 ÷ 2 = 12; 12 × 3 = 36; 36 ÷ 2 = 18.\n2. Next = 18 × 3 = **54**.\n\nAnswer: **54**.",
    approach: "Terms that rise and fall alternately point to two operations taking turns. Identify both before extending.",
    tags: ["alternating"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-divide-then-add",
    topic: "number-series",
    title: "100, 50, 52, 26, 28, ?",
    prompt: "Find the next term:\n\n**100, 50, 52, 26, 28, ?**",
    options: ["12", "14", "16", "30"],
    answer: 1,
    difficulty: "medium",
    hints: ["Operations alternate: ÷ 2 then + 2.", "28 ÷ 2."],
    solution:
      "1. 100 ÷ 2 = 50; 50 + 2 = 52; 52 ÷ 2 = 26; 26 + 2 = 28.\n2. Next = 28 ÷ 2 = **14**.\n\nAnswer: **14**.",
    approach: "Track which operation comes next by counting the steps taken. Here the sixth term follows an addition, so it must be a division.",
    tags: ["alternating"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-divide-multiply-alternate",
    topic: "number-series",
    title: "48, 24, 96, 48, 192, ?",
    prompt: "Find the next term:\n\n**48, 24, 96, 48, 192, ?**",
    options: ["96", "144", "384", "768"],
    answer: 0,
    difficulty: "medium",
    hints: ["The operations alternate: ÷ 2 then × 4.", "192 ÷ 2."],
    solution:
      "1. 48 ÷ 2 = 24; 24 × 4 = 96; 96 ÷ 2 = 48; 48 × 4 = 192.\n2. Next = 192 ÷ 2 = **96**.\n\nAnswer: **96**.",
    approach: "Repeating values in a series are a strong hint of alternating operations. Confirm each step before extending.",
    tags: ["alternating"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-plus-three-minus-two",
    topic: "number-series",
    title: "7, 10, 8, 11, 9, ?",
    prompt: "Find the next term:\n\n**7, 10, 8, 11, 9, ?**",
    options: ["6", "10", "12", "13"],
    answer: 2,
    difficulty: "easy",
    hints: ["The operations alternate: + 3 then − 2.", "9 + 3."],
    solution: "1. 7 + 3 = 10; 10 − 2 = 8; 8 + 3 = 11; 11 − 2 = 9.\n2. Next = 9 + 3 = **12**.\n\nAnswer: **12**.",
    approach: "A zig-zag series alternates a rise and a fall. Read the differences in order: +3, −2, +3, −2.",
    tags: ["alternating"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-two-interleaved",
    topic: "number-series",
    title: "22, 21, 23, 22, 24, 23, ?",
    prompt: "Find the next term:\n\n**22, 21, 23, 22, 24, 23, ?**",
    options: ["22", "24", "25", "26"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Two series are interleaved. Read the odd positions and the even positions separately.",
      "Odd positions: 22, 23, 24. Even positions: 21, 22, 23.",
    ],
    solution:
      "1. Odd positions (1st, 3rd, 5th): 22, 23, 24 — rising by 1.\n2. Even positions (2nd, 4th, 6th): 21, 22, 23 — also rising by 1.\n3. The seventh term is in the odd series, so it is 24 + 1 = **25**.\n\nAnswer: **25**.",
    approach: "When the differences alternate in sign, split the series by position and solve each half independently.",
    tags: ["alternating"],
    timeTargetSec: 75,
  },
  {
    slug: "ls2-fibonacci",
    topic: "number-series",
    title: "1, 1, 2, 3, 5, 8, ?",
    prompt: "Find the next term:\n\n**1, 1, 2, 3, 5, 8, ?**",
    options: ["11", "12", "13", "16"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is the sum of the two before it.", "5 + 8."],
    solution: "1. Each term is the sum of the previous two.\n2. Next = 5 + 8 = **13**.\n\nAnswer: **13**.",
    approach: "The Fibonacci pattern is worth recognising on sight. Test it whenever the terms grow but not by a constant ratio.",
    tags: ["fibonacci"],
    timeTargetSec: 35,
  },
  {
    slug: "ls2-triangular-numbers",
    topic: "number-series",
    title: "0, 2, 6, 12, 20, ?",
    prompt: "Find the next term:\n\n**0, 2, 6, 12, 20, ?**",
    options: ["26", "28", "30", "32"],
    answer: 2,
    difficulty: "easy",
    hints: ["Differences: 2, 4, 6, 8.", "The next difference is 10."],
    solution:
      "1. Differences: 2, 4, 6, 8 — the even numbers.\n2. Next = 20 + 10 = **30**.\n3. The terms are n² − n. ✓\n\nAnswer: **30**.",
    approach: "Even differences point to n² − n or a shift of it. Extending the differences is quicker than finding the formula.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls2-sum-of-squares",
    topic: "number-series",
    title: "1, 5, 14, 30, 55, ?",
    prompt: "Find the next term:\n\n**1, 5, 14, 30, 55, ?**",
    options: ["80", "85", "91", "95"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Differences: 4, 9, 16, 25 — those are perfect squares.",
      "The next difference is 36.",
    ],
    solution:
      "1. Differences: 4, 9, 16, 25 = 2², 3², 4², 5².\n2. Next difference = 6² = 36, so the term is 55 + 36 = **91**.\n3. The terms are the running sums of squares. ✓\n\nAnswer: **91**.",
    approach: "When the differences themselves are squares or cubes, the series is a running total. Extend the differences and add.",
    tags: ["differences", "squares"],
    timeTargetSec: 90,
  },
  {
    slug: "ls2-factorials",
    topic: "number-series",
    title: "1, 2, 6, 24, 120, ?",
    prompt: "Find the next term:\n\n**1, 2, 6, 24, 120, ?**",
    options: ["240", "480", "600", "720"],
    answer: 3,
    difficulty: "medium",
    hints: ["Each term multiplies the previous by an increasing number.", "×2, ×3, ×4, ×5 — the next is ×6."],
    solution:
      "1. The multipliers are 2, 3, 4, 5 — these are the factorials 1!, 2!, 3!, 4!, 5!.\n2. Next = 120 × 6 = **720** (that is 6!).\n\nAnswer: **720**.",
    approach: "Rapid growth with rising multipliers means factorials. Knowing 5! = 120 and 6! = 720 settles it immediately.",
    tags: ["factorial"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-multiply-increasing",
    topic: "number-series",
    title: "2, 4, 12, 48, ?",
    prompt: "Find the next term:\n\n**2, 4, 12, 48, ?**",
    options: ["96", "144", "196", "240"],
    answer: 3,
    difficulty: "medium",
    hints: ["The multipliers rise: ×2, ×3, ×4.", "The next multiplier is 5."],
    solution: "1. 2 × 2 = 4; 4 × 3 = 12; 12 × 4 = 48.\n2. Next = 48 × 5 = **240**.\n\nAnswer: **240**.",
    approach: "Divide each term by the previous to expose the multipliers. A rising sequence of multipliers is the pattern.",
    tags: ["multiplicative"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-divide-increasing",
    topic: "number-series",
    title: "240, 120, 40, 10, ?",
    prompt: "Find the next term:\n\n**240, 120, 40, 10, ?**",
    options: ["2", "4", "5", "8"],
    answer: 0,
    difficulty: "medium",
    hints: ["The divisors rise: ÷2, ÷3, ÷4.", "The next divisor is 5."],
    solution: "1. 240 ÷ 2 = 120; 120 ÷ 3 = 40; 40 ÷ 4 = 10.\n2. Next = 10 ÷ 5 = **2**.\n\nAnswer: **2**.",
    approach: "The mirror of the rising-multiplier series. Dividing consecutive terms exposes the pattern in one line.",
    tags: ["multiplicative"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-powers-of-two",
    topic: "number-series",
    title: "1, 2, 4, 8, 16, ?",
    prompt: "Find the next term:\n\n**1, 2, 4, 8, 16, ?**",
    options: ["24", "30", "32", "64"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term doubles.", "16 × 2."],
    solution: "1. Each term is twice the previous.\n2. Next = **32**.\n\nAnswer: **32**.",
    approach: "A constant ratio makes a geometric series. Divide two consecutive terms to find it.",
    tags: ["multiplicative"],
    timeTargetSec: 30,
  },
  {
    slug: "ls2-geometric-doubling",
    topic: "number-series",
    title: "5, 10, 20, 40, ?",
    prompt: "Find the next term:\n\n**5, 10, 20, 40, ?**",
    options: ["50", "60", "80", "100"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is double the previous.", "40 × 2."],
    solution: "1. The ratio is 2 throughout.\n2. Next = 40 × 2 = **80**.\n\nAnswer: **80**.",
    approach: "Check the ratio between consecutive terms first when the series grows quickly but smoothly.",
    tags: ["multiplicative"],
    timeTargetSec: 30,
  },
  {
    slug: "ls2-three-n-squared",
    topic: "number-series",
    title: "3, 12, 27, 48, ?",
    prompt: "Find the next term:\n\n**3, 12, 27, 48, ?**",
    options: ["60", "69", "75", "80"],
    answer: 2,
    difficulty: "medium",
    hints: ["Divide each term by 3.", "1, 4, 9, 16 are the squares."],
    solution:
      "1. Dividing by 3 gives 1, 4, 9, 16 — the perfect squares.\n2. Next = 3 × 25 = **75**.\n\nAnswer: **75**.",
    approach: "Factoring out a common multiplier often reveals a familiar sequence underneath. Try dividing by the first term.",
    tags: ["squares"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-primes",
    topic: "number-series",
    title: "2, 3, 5, 7, 11, ?",
    prompt: "Find the next term:\n\n**2, 3, 5, 7, 11, ?**",
    options: ["12", "13", "14", "15"],
    answer: 1,
    difficulty: "easy",
    hints: ["These are not related by arithmetic.", "They are the prime numbers in order."],
    solution: "1. The terms are the primes 2, 3, 5, 7, 11.\n2. The next prime is **13**.\n\nAnswer: **13**.",
    approach: "If no arithmetic rule fits, check for primes, squares or cubes. Irregular gaps that never repeat usually mean primes.",
    tags: ["primes"],
    timeTargetSec: 35,
  },
  {
    slug: "ls2-primes-later",
    topic: "number-series",
    title: "11, 13, 17, 19, 23, ?",
    prompt: "Find the next term:\n\n**11, 13, 17, 19, 23, ?**",
    options: ["25", "27", "29", "31"],
    answer: 2,
    difficulty: "easy",
    hints: ["These are consecutive primes.", "The next prime after 23."],
    solution: "1. The terms are consecutive primes.\n2. After 23 comes **29** (25 = 5² and 27 = 3³ are not prime).\n\nAnswer: **29**.",
    approach: "Know the primes to at least 50. The composite traps 25 and 27 are always among the options.",
    tags: ["primes"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-hundreds-differences",
    topic: "number-series",
    title: "10, 100, 200, 310, ?",
    prompt: "Find the next term:\n\n**10, 100, 200, 310, ?**",
    options: ["400", "420", "430", "440"],
    answer: 2,
    difficulty: "medium",
    hints: ["Differences: 90, 100, 110.", "The next difference is 120."],
    solution: "1. Differences: 90, 100, 110 — rising by 10.\n2. Next = 310 + 120 = **430**.\n\nAnswer: **430**.",
    approach: "Large numbers do not change the method: write the differences and look for their own pattern.",
    tags: ["differences"],
    timeTargetSec: 50,
  },
  {
    slug: "ls2-concatenation",
    topic: "number-series",
    title: "13, 35, 57, 79, 911, ?",
    prompt: "Find the next term:\n\n**13, 35, 57, 79, 911, ?**",
    options: ["1,011", "1,113", "1,213", "1,315"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "These are not arithmetic — look at the digits.",
      "Each term joins two consecutive odd numbers: 1 and 3, 3 and 5, 5 and 7, 7 and 9, 9 and 11.",
    ],
    solution:
      "1. Each term is two consecutive odd numbers written side by side: 1|3, 3|5, 5|7, 7|9, 9|11.\n2. The next pair is 11 and 13, giving **1113**.\n\nAnswer: **1,113**.",
    approach:
      "When the arithmetic makes no sense, read the digits as a pattern rather than the value. Concatenation series are common in the harder papers.",
    tags: ["digits"],
    timeTargetSec: 105,
  },
  {
    slug: "ls2-letters-plus-two",
    topic: "number-series",
    title: "B, D, F, H, ?",
    prompt: "Find the next letter:\n\n**B, D, F, H, ?**",
    options: ["I", "J", "K", "L"],
    answer: 1,
    difficulty: "easy",
    hints: ["Convert to positions: B = 2, D = 4, F = 6, H = 8.", "Each step adds 2."],
    solution: "1. Positions: 2, 4, 6, 8 — rising by 2.\n2. Next = 10 = **J**.\n\nAnswer: **J**.",
    approach: "Turn letters into numbers (A = 1 … Z = 26), find the numeric rule, then convert back. The landmarks E = 5, J = 10, O = 15, T = 20 speed this up.",
    tags: ["letters"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-letters-plus-three",
    topic: "number-series",
    title: "B, E, H, K, ?",
    prompt: "Find the next letter:\n\n**B, E, H, K, ?**",
    options: ["L", "M", "N", "O"],
    answer: 2,
    difficulty: "easy",
    hints: ["Positions: 2, 5, 8, 11.", "Each step adds 3."],
    solution: "1. Positions: 2, 5, 8, 11.\n2. Next = 14 = **N**.\n\nAnswer: **N**.",
    approach: "A constant letter gap is the simplest pattern. Count carefully — miscounting by one is the only real risk.",
    tags: ["letters"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-letters-increasing-gap",
    topic: "number-series",
    title: "A, C, F, J, ?",
    prompt: "Find the next letter:\n\n**A, C, F, J, ?**",
    options: ["M", "N", "O", "P"],
    answer: 2,
    difficulty: "medium",
    hints: ["Positions: 1, 3, 6, 10.", "The gaps are 2, 3, 4 — the next is 5."],
    solution: "1. Positions: 1, 3, 6, 10, with gaps 2, 3, 4.\n2. Next position = 10 + 5 = 15 = **O**.\n\nAnswer: **O**.",
    approach: "Widening gaps are just as common with letters as with numbers. Work entirely in positions and convert only at the end.",
    tags: ["letters"],
    timeTargetSec: 60,
  },
  {
    slug: "ls2-letters-backwards",
    topic: "number-series",
    title: "Z, X, V, T, ?",
    prompt: "Find the next letter:\n\n**Z, X, V, T, ?**",
    options: ["P", "Q", "R", "S"],
    answer: 2,
    difficulty: "easy",
    hints: ["Positions: 26, 24, 22, 20.", "Each step subtracts 2."],
    solution: "1. Positions: 26, 24, 22, 20.\n2. Next = 18 = **R**.\n\nAnswer: **R**.",
    approach: "Counting backwards from Z is easier with the position numbers than with the letters themselves.",
    tags: ["letters"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-letter-pairs",
    topic: "number-series",
    title: "AZ, BY, CX, ?",
    prompt: "Find the next pair:\n\n**AZ, BY, CX, ?**",
    options: ["DV", "DW", "EW", "EV"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "The first letters run forward: A, B, C.",
      "The second letters run backward: Z, Y, X.",
    ],
    solution:
      "1. First letters: A, B, C → next is D.\n2. Second letters: Z, Y, X → next is W.\n3. The pair is **DW**.\n\nAnswer: **DW**.",
    approach: "Treat each position in the pair as its own series. Here one counts up and the other counts down.",
    tags: ["letters"],
    timeTargetSec: 50,
  },
  {
    slug: "ls2-odd-one-out-cubes",
    topic: "number-series",
    title: "The number that does not belong",
    prompt: "Which number does **not** belong?\n\n**4, 9, 16, 24, 36, 49**",
    options: ["9", "16", "24", "36"],
    answer: 2,
    difficulty: "easy",
    hints: ["Most of these are perfect squares.", "24 is not a square."],
    solution:
      "1. 4 = 2², 9 = 3², 16 = 4², 36 = 6², 49 = 7².\n2. **24** is not a perfect square.\n\nAnswer: **24**.",
    approach: "Test the small squares first in any odd-one-out question. Only one item should break the rule.",
    tags: ["odd one out"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-odd-one-out-primes",
    topic: "number-series",
    title: "The odd one out among primes",
    prompt: "Which number does **not** belong?\n\n**17, 23, 29, 33, 41**",
    options: ["17", "23", "33", "41"],
    answer: 2,
    difficulty: "easy",
    hints: ["Four of these are prime.", "33 = 3 × 11."],
    solution: "1. 17, 23, 29 and 41 are prime.\n2. **33** = 3 × 11 is composite.\n\nAnswer: **33**.",
    approach: "Check divisibility by 3 and 7 quickly — those catch most of the composite traps in this range.",
    tags: ["odd one out", "primes"],
    timeTargetSec: 40,
  },
  {
    slug: "ls2-missing-middle",
    topic: "number-series",
    title: "A term in the middle",
    prompt: "Find the missing term:\n\n**3, 7, 15, ?, 63, 127**",
    options: ["23", "27", "31", "35"],
    answer: 2,
    difficulty: "medium",
    hints: ["Each term is 2 × previous + 1.", "15 × 2 + 1, and check it leads to 63."],
    solution:
      "1. The rule is × 2 + 1: 3 → 7 → 15 → ? → 63 → 127.\n2. 15 × 2 + 1 = **31**, and 31 × 2 + 1 = 63. ✓\n\nAnswer: **31**.",
    approach: "With a gap in the middle, verify the rule on both sides of it. That confirms the answer rather than merely suggesting it.",
    tags: ["multiplicative"],
    timeTargetSec: 60,
  },
];
