import type { AptitudeSeed } from "./types.js";

/** Simple and compound interest — the standard placement and bank-exam set. */
export const BANK_INTEREST: AptitudeSeed[] = [
  {
    slug: "in2-si-basic",
    topic: "interest",
    title: "Simple interest for three years",
    prompt: "What is the **simple interest** on **₹12,000** at **8% per annum** for **3 years**?",
    options: ["₹2,400", "₹2,880", "₹3,120", "₹3,600"],
    answer: 1,
    difficulty: "easy",
    hints: ["SI = P × R × T / 100.", "8% for 3 years is 24% in total."],
    solution: "1. Total rate = 8 × 3 = 24%.\n2. SI = 24% of 12,000 = **₹2,880**.\n\nAnswer: **₹2,880**.",
    approach: "Simple interest is linear, so multiply rate by time to get one total percentage and apply it once. No compounding is involved.",
    tags: ["simple interest"],
    timeTargetSec: 40,
  },
  {
    slug: "in2-si-find-principal",
    topic: "interest",
    title: "Principal from the interest",
    prompt:
      "A sum earns **₹1,750 as simple interest** in **5 years at 7% per annum**. What is the **principal**?",
    options: ["₹4,000", "₹4,500", "₹5,000", "₹5,500"],
    answer: 2,
    difficulty: "easy",
    hints: ["Total rate = 35%.", "1,750 ÷ 0.35."],
    solution: "1. Total rate = 7 × 5 = 35%.\n2. P = 1,750 ÷ 0.35 = **₹5,000**.\n\nAnswer: **₹5,000**.",
    approach: "Rearrange P = 100 × SI / (R × T). Combining rate and time into one percentage keeps it to a single division.",
    tags: ["simple interest"],
    timeTargetSec: 45,
  },
  {
    slug: "in2-si-find-rate",
    topic: "interest",
    title: "Rate from the interest",
    prompt:
      "At what **rate of simple interest** will **₹8,000** earn **₹1,920** in **4 years**?",
    options: ["5%", "6%", "7%", "8%"],
    answer: 1,
    difficulty: "easy",
    hints: ["R = 100 × SI / (P × T).", "100 × 1,920 / (8,000 × 4)."],
    solution: "1. R = (100 × 1,920) / (8,000 × 4) = 192,000 / 32,000 = **6%**.\n\nAnswer: **6%**.",
    approach: "Rearrange the same formula for R. Checking is quick: 6% of 8,000 is 480 a year, and 480 × 4 = 1,920. ✓",
    tags: ["simple interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-si-find-time",
    topic: "interest",
    title: "Time from the interest",
    prompt: "In how many **years** will **₹6,000** earn **₹1,800** as simple interest at **5% per annum**?",
    options: ["4", "5", "6", "8"],
    answer: 2,
    difficulty: "easy",
    hints: ["Interest per year = 5% of 6,000.", "1,800 ÷ 300."],
    solution: "1. Yearly interest = 5% of 6,000 = ₹300.\n2. Years = 1,800 ÷ 300 = **6**.\n\nAnswer: **6**.",
    approach: "Find the interest for one year and divide. Simple interest accrues the same amount every year, which is what makes this work.",
    tags: ["simple interest"],
    timeTargetSec: 45,
  },
  {
    slug: "in2-si-doubles-in-eight",
    topic: "interest",
    title: "Doubling under simple interest",
    prompt: "At what **rate of simple interest** does a sum **double itself in 8 years**?",
    options: ["10%", "12%", "12.5%", "15%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Doubling means the interest equals the principal, that is 100%.", "R × T = 100."],
    solution: "1. To double, SI must equal P, so R × T = 100.\n2. R = 100 ÷ 8 = **12.5%**.\n\nAnswer: **12.5%**.",
    approach: "Under simple interest a sum becomes n times itself when R × T = 100(n − 1). Doubling gives 100, tripling 200.",
    tags: ["doubling"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-si-triples",
    topic: "interest",
    title: "Tripling under simple interest",
    prompt: "In how many **years** will a sum **triple itself** at **10% per annum simple interest**?",
    options: ["10", "15", "20", "25"],
    answer: 2,
    difficulty: "medium",
    hints: ["Tripling means the interest is twice the principal, that is 200%.", "R × T = 200."],
    solution: "1. To triple, SI = 2P, so R × T = 200.\n2. T = 200 ÷ 10 = **20 years**.\n\nAnswer: **20**.",
    approach: "Becoming n times needs R × T = 100(n − 1). Reading 'triple' as 300 instead of 200 is the standard error.",
    tags: ["doubling"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-si-doubles-then-quadruples",
    topic: "interest",
    title: "From doubling to quadrupling",
    prompt:
      "A sum **doubles itself in 10 years** at simple interest. In how many years will it become **four times** itself?",
    options: ["20", "25", "30", "40"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Doubling means the interest earned equals the principal in 10 years.",
      "Becoming four times needs interest equal to three times the principal.",
    ],
    solution:
      "1. In 10 years the interest earned equals P.\n2. To become 4P the interest must be 3P, which takes 3 × 10 = **30 years**.\n\nAnswer: **30**.",
    approach:
      "Under simple interest the interest grows linearly, so the time scales with the multiple minus one. Doubling in 10 means tripling in 20 and quadrupling in 30.",
    tags: ["doubling"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-ci-two-years",
    topic: "interest",
    title: "Compound interest for two years",
    prompt:
      "What is the **compound interest** on **₹20,000** at **10% per annum** for **2 years**, compounded annually?",
    options: ["₹4,000", "₹4,200", "₹4,400", "₹4,800"],
    answer: 1,
    difficulty: "easy",
    hints: ["Amount = P(1 + r)².", "20,000 × 1.21 = 24,200."],
    solution:
      "1. Amount = 20,000 × 1.1² = 20,000 × 1.21 = ₹24,200.\n2. CI = 24,200 − 20,000 = **₹4,200**.\n\nAnswer: **₹4,200**.",
    approach: "For two years, CI% = 2r + r²/100 = 21%. The extra 1% is the interest earned on the first year's interest.",
    tags: ["compound interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-ci-three-years",
    topic: "interest",
    title: "Compound interest for three years",
    prompt:
      "What is the **amount** on **₹10,000** at **10% per annum compound interest** for **3 years**?",
    options: ["₹13,000", "₹13,310", "₹13,400", "₹13,500"],
    answer: 1,
    difficulty: "easy",
    hints: ["Amount = 10,000 × 1.1³.", "1.1³ = 1.331."],
    solution: "1. 1.1³ = 1.331.\n2. Amount = 10,000 × 1.331 = **₹13,310**.\n\nAnswer: **₹13,310**.",
    approach: "Worth memorising: 1.1² = 1.21, 1.1³ = 1.331, 1.2² = 1.44, 1.05² = 1.1025. They cover most exam questions instantly.",
    tags: ["compound interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-ci-minus-si-two-years",
    topic: "interest",
    title: "The gap between CI and SI",
    prompt:
      "What is the **difference between compound and simple interest** on **₹8,000** at **10% per annum** for **2 years**?",
    options: ["₹60", "₹80", "₹100", "₹120"],
    answer: 1,
    difficulty: "medium",
    hints: ["For two years the difference is P(r/100)².", "8,000 × 0.01."],
    solution:
      "1. Difference for 2 years = P(r/100)² = 8,000 × (0.1)² = 8,000 × 0.01 = **₹80**.\n2. Check: SI = 1,600; CI = 8,000 × 1.21 − 8,000 = 1,680. Difference 80. ✓\n\nAnswer: **₹80**.",
    approach:
      "The two-year gap is the interest earned on the first year's interest, namely P(r/100)². For three years it is P(r/100)²(3 + r/100).",
    tags: ["ci vs si"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-ci-minus-si-find-principal",
    topic: "interest",
    title: "Principal from the CI–SI gap",
    prompt:
      "The **difference between compound and simple interest** for **2 years at 5% per annum** is **₹50**. What is the **principal**?",
    options: ["₹15,000", "₹18,000", "₹20,000", "₹25,000"],
    answer: 2,
    difficulty: "medium",
    hints: ["Difference = P(r/100)².", "P × 0.0025 = 50."],
    solution:
      "1. P × (5/100)² = 50 → P × 0.0025 = 50.\n2. P = 50 ÷ 0.0025 = **₹20,000**.\n\nAnswer: **₹20,000**.",
    approach: "Rearranging P = difference × (100/r)² is one step. A small rate makes the gap tiny, so the principal comes out large.",
    tags: ["ci vs si"],
    timeTargetSec: 75,
  },
  {
    slug: "in2-ci-half-yearly",
    topic: "interest",
    title: "Compounded half-yearly",
    prompt:
      "What is the **compound interest** on **₹8,000** at **20% per annum** for **1 year**, compounded **half-yearly**?",
    options: ["₹1,600", "₹1,680", "₹1,720", "₹1,800"],
    answer: 1,
    difficulty: "medium",
    hints: ["Halve the rate and double the periods: 10% for two half-years.", "8,000 × 1.21 = 9,680."],
    solution:
      "1. Rate per half-year = 10%; number of periods = 2.\n2. Amount = 8,000 × 1.1² = 8,000 × 1.21 = ₹9,680.\n3. CI = 9,680 − 8,000 = **₹1,680**.\n\nAnswer: **₹1,680**.",
    approach:
      "Compounding k times a year means rate ÷ k per period and n × k periods. More frequent compounding always earns a little more than annual (₹1,680 against ₹1,600).",
    tags: ["half-yearly"],
    timeTargetSec: 75,
  },
  {
    slug: "in2-ci-quarterly",
    topic: "interest",
    title: "Compounded quarterly",
    prompt:
      "What is the **amount** on **₹10,000** at **8% per annum** for **1 year**, compounded **quarterly**?",
    options: ["₹10,800", "₹10,824", "₹10,850", "₹10,900"],
    answer: 1,
    difficulty: "hard",
    hints: ["Quarterly means 2% per quarter for 4 quarters.", "10,000 × 1.02⁴, and 1.02⁴ ≈ 1.0824."],
    solution:
      "1. Rate per quarter = 8 ÷ 4 = 2%; periods = 4.\n2. Amount = 10,000 × 1.02⁴ = 10,000 × 1.08243 ≈ **₹10,824**.\n\nAnswer: **₹10,824**.",
    approach: "Divide the annual rate by the number of compounding periods and raise to that power. Quarterly compounding at 8% gives an effective annual rate of about 8.24%.",
    tags: ["quarterly"],
    timeTargetSec: 90,
  },
  {
    slug: "in2-ci-principal-from-amount",
    topic: "interest",
    title: "Working back to the principal",
    prompt:
      "A sum amounts to **₹9,261** in **3 years** at **5% per annum compound interest**. What was the **principal**?",
    options: ["₹7,500", "₹8,000", "₹8,400", "₹8,500"],
    answer: 1,
    difficulty: "medium",
    hints: ["Amount = P × 1.05³.", "1.05³ = 1.157625."],
    solution:
      "1. 1.05³ = 1.157625.\n2. P = 9,261 ÷ 1.157625 = **₹8,000**.\n3. Check: 8,000 → 8,400 → 8,820 → 9,261. ✓\n\nAnswer: **₹8,000**.",
    approach: "Present value = amount ÷ (1 + r)ⁿ. Stepping the years forward from the answer is the fastest way to confirm it.",
    tags: ["compound interest"],
    timeTargetSec: 75,
  },
  {
    slug: "in2-ci-successive-amounts",
    topic: "interest",
    title: "From one year's amount to the next",
    prompt:
      "A sum at compound interest amounts to **₹4,410 in 2 years** and **₹4,630.50 in 3 years**. What is the **rate of interest**?",
    options: ["4%", "5%", "6%", "7%"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The growth in the third year is interest on the amount after two years.",
      "220.50 as a percentage of 4,410.",
    ],
    solution:
      "1. Interest for the third year = 4,630.50 − 4,410 = ₹220.50.\n2. This is one year's interest on ₹4,410.\n3. Rate = 220.50 / 4,410 × 100 = **5%**.\n\nAnswer: **5%**.",
    approach:
      "Consecutive amounts differ by exactly one year's interest on the earlier amount. That single division gives the rate without ever finding the principal.",
    tags: ["compound interest"],
    timeTargetSec: 105,
  },
  {
    slug: "in2-si-successive-amounts",
    topic: "interest",
    title: "Two amounts under simple interest",
    prompt:
      "A sum amounts to **₹1,560 in 3 years** and **₹1,680 in 5 years** at simple interest. What is the **principal**?",
    options: ["₹1,200", "₹1,320", "₹1,380", "₹1,440"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "The extra two years earned 1,680 − 1,560 = ₹120.",
      "So one year's interest is ₹60; subtract three years' worth from ₹1,560.",
    ],
    solution:
      "1. Interest for 2 years = 1,680 − 1,560 = ₹120, so one year's interest = ₹60.\n2. Interest for 3 years = ₹180.\n3. Principal = 1,560 − 180 = **₹1,380**.\n\nAnswer: **₹1,380**.",
    approach:
      "Under simple interest each year adds the same amount, so the difference between two amounts gives the annual interest directly. Subtract back to reach the principal.",
    tags: ["simple interest"],
    timeTargetSec: 105,
  },
  {
    slug: "in2-si-two-parts",
    topic: "interest",
    title: "A sum split into two investments",
    prompt:
      "**₹2,600** is split into two parts, one lent at **10%** and the other at **8%** simple interest for one year. If the **total interest is ₹230**, what is the part lent at **10%**?",
    options: ["₹1,000", "₹1,100", "₹1,200", "₹1,400"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Let the 10% part be x, so the other is 2,600 − x.",
      "0.10x + 0.08(2,600 − x) = 230.",
    ],
    solution:
      "1. 0.10x + 0.08(2,600 − x) = 230.\n2. 0.10x + 208 − 0.08x = 230 → 0.02x = 22.\n3. x = **₹1,100**.\n4. Check: 110 + 0.08 × 1,500 = 110 + 120 = 230. ✓\n\nAnswer: **₹1,100**.",
    approach:
      "One variable for one part, the remainder for the other, then one equation on the total interest. Alligation also works: the average rate is 230/2,600 ≈ 8.85%.",
    tags: ["two parts"],
    timeTargetSec: 120,
  },
  {
    slug: "in2-si-rate-difference",
    topic: "interest",
    title: "A higher rate earns more",
    prompt:
      "A sum lent at a **rate 3% higher** would have earned **₹300 more** in **4 years** under simple interest. What is the **sum**?",
    options: ["₹2,000", "₹2,500", "₹3,000", "₹3,500"],
    answer: 1,
    difficulty: "medium",
    hints: ["Extra interest = P × 3 × 4 / 100.", "0.12P = 300."],
    solution:
      "1. Extra interest = P × 3 × 4 / 100 = 0.12P.\n2. 0.12P = 300 → P = **₹2,500**.\n\nAnswer: **₹2,500**.",
    approach:
      "The extra interest depends only on the extra rate, not on the original one — which is why the original rate is never given. P × Δr × T / 100 = extra.",
    tags: ["simple interest"],
    timeTargetSec: 75,
  },
  {
    slug: "in2-ci-doubles-in-five",
    topic: "interest",
    title: "Doubling under compound interest",
    prompt:
      "A sum **doubles in 5 years** at compound interest. In how many years will it become **eight times** itself?",
    options: ["10", "15", "20", "25"],
    answer: 1,
    difficulty: "medium",
    hints: ["Eight is 2³.", "Each doubling takes 5 years."],
    solution:
      "1. Eight times = 2³, that is three successive doublings.\n2. Each doubling takes 5 years, so 3 × 5 = **15 years**.\n\nAnswer: **15**.",
    approach:
      "Under compound interest the multiples are powers, not multiples: doubling in t years gives 4× in 2t and 8× in 3t. Under *simple* interest the answer would be 35 years.",
    tags: ["doubling", "compound interest"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-ci-triples-in-four",
    topic: "interest",
    title: "Nine times under compound interest",
    prompt:
      "A sum **triples in 4 years** at compound interest. In how many years will it become **nine times** itself?",
    options: ["6", "8", "12", "16"],
    answer: 1,
    difficulty: "medium",
    hints: ["Nine is 3².", "Two triplings, each taking 4 years."],
    solution: "1. Nine times = 3², that is two successive triplings.\n2. Time = 2 × 4 = **8 years**.\n\nAnswer: **8**.",
    approach: "Express the target multiple as a power of the known multiple, then multiply the time by that exponent.",
    tags: ["doubling", "compound interest"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-si-total-interest-two-rates",
    topic: "interest",
    title: "Two loans, one total",
    prompt:
      "A man lends **₹5,000 at 6%** and **₹4,000 at 8%** simple interest for **2 years**. What is his **total interest**?",
    options: ["₹1,200", "₹1,240", "₹1,280", "₹1,320"],
    answer: 1,
    difficulty: "easy",
    hints: ["Compute each interest separately.", "5,000 × 0.12 and 4,000 × 0.16."],
    solution:
      "1. First: 5,000 × 6 × 2/100 = ₹600.\n2. Second: 4,000 × 8 × 2/100 = ₹640.\n3. Total = **₹1,240**.\n\nAnswer: **₹1,240**.",
    approach: "Two independent loans, so compute and add. Averaging the rates would be wrong because the principals differ.",
    tags: ["simple interest"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-si-amount-after-time",
    topic: "interest",
    title: "Amount after simple interest",
    prompt: "What **amount** will **₹15,000** grow to in **4 years** at **9% per annum simple interest**?",
    options: ["₹19,800", "₹20,400", "₹21,000", "₹21,600"],
    answer: 3,
    difficulty: "easy",
    hints: ["Interest = 36% of the principal.", "15,000 + 5,400."],
    solution:
      "1. Total rate = 9 × 4 = 36%.\n2. Interest = 36% of 15,000 = ₹5,400.\n3. Amount = 15,000 + 5,400 = **₹21,600**.\n\nAnswer: **₹21,600**.",
    approach: "Amount = principal + interest under simple interest, or P(1 + RT/100) in one step.",
    tags: ["simple interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-ci-population-style",
    topic: "interest",
    title: "Compound growth of a deposit",
    prompt:
      "A deposit of **₹6,250** grows at **4% per annum compound interest**. What is the **amount after 2 years**?",
    options: ["₹6,500", "₹6,760", "₹6,800", "₹6,900"],
    answer: 1,
    difficulty: "medium",
    hints: ["Amount = 6,250 × 1.04².", "1.04² = 1.0816."],
    solution:
      "1. 1.04² = 1.0816.\n2. Amount = 6,250 × 1.0816 = **₹6,760**.\n3. Check: 6,250 → 6,500 → 6,760. ✓\n\nAnswer: **₹6,760**.",
    approach: "Stepping year by year is often faster than squaring the multiplier, and it produces a natural check on the arithmetic.",
    tags: ["compound interest"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-si-fraction-of-principal",
    topic: "interest",
    title: "Interest as a fraction of the principal",
    prompt:
      "A sum becomes **9/8 of itself in 3 years** at simple interest. What is the **rate of interest**?",
    options: ["3⅓%", "4%", "4⅙%", "5%"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "The interest earned is 1/8 of the principal.",
      "So R × 3 / 100 = 1/8.",
    ],
    solution:
      "1. Amount = 9P/8, so interest = P/8.\n2. P × R × 3/100 = P/8 → 3R/100 = 1/8.\n3. R = 100/24 = **4⅙%**.\n\nAnswer: **4⅙%**.",
    approach: "Convert 'becomes a fraction of itself' into the interest as a fraction of P; the principal then cancels out of the equation entirely.",
    tags: ["simple interest"],
    timeTargetSec: 105,
  },
  {
    slug: "in2-si-equal-amounts",
    topic: "interest",
    title: "Two sums, equal after different times",
    prompt:
      "**₹1,000** is lent at **5% simple interest**. After how many **years** will the amount be **₹1,400**?",
    options: ["6", "7", "8", "10"],
    answer: 2,
    difficulty: "easy",
    hints: ["Interest needed = ₹400.", "Yearly interest = ₹50."],
    solution:
      "1. Interest required = 1,400 − 1,000 = ₹400.\n2. Yearly interest = 5% of 1,000 = ₹50.\n3. Years = 400 ÷ 50 = **8**.\n\nAnswer: **8**.",
    approach: "Find the interest needed, then divide by the yearly amount. Under simple interest every year contributes equally.",
    tags: ["simple interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-ci-first-year-interest",
    topic: "interest",
    title: "Interest in the second year",
    prompt:
      "The **compound interest for the first year** on a sum at **10% per annum** is **₹500**. What is the interest for the **second year**?",
    options: ["₹500", "₹525", "₹550", "₹600"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "The first year's interest of ₹500 means the principal is ₹5,000.",
      "In the second year, interest is charged on ₹5,500.",
    ],
    solution:
      "1. First year's interest = 10% of P = 500, so P = ₹5,000.\n2. Amount after one year = ₹5,500.\n3. Second year's interest = 10% of 5,500 = **₹550**.\n\nAnswer: **₹550**.",
    approach: "Each year's compound interest exceeds the previous by r% of it. Here ₹500 grows to ₹550, a rise of exactly 10%.",
    tags: ["compound interest"],
    timeTargetSec: 75,
  },
  {
    slug: "in2-si-borrow-and-lend",
    topic: "interest",
    title: "Borrowing cheap and lending dear",
    prompt:
      "A man borrows **₹5,000 at 4%** simple interest and lends it at **6%** for **3 years**. What is his **total gain**?",
    options: ["₹200", "₹300", "₹400", "₹600"],
    answer: 1,
    difficulty: "medium",
    hints: ["The gain comes from the 2% difference in rates.", "5,000 × 2 × 3 / 100."],
    solution:
      "1. Gain per year = (6 − 4)% of 5,000 = ₹100.\n2. Over 3 years = **₹300**.\n\nAnswer: **₹300**.",
    approach: "Work with the difference in rates rather than computing both interests. The principal and time are shared, so only the rate gap matters.",
    tags: ["simple interest"],
    timeTargetSec: 60,
  },
  {
    slug: "in2-si-sum-of-two-interests",
    topic: "interest",
    title: "Same sum, two periods",
    prompt:
      "The **simple interest** on a sum for **3 years at 8%** exceeds that for **2 years at 5%** by **₹280**. What is the **sum**?",
    options: ["₹2,000", "₹2,400", "₹2,800", "₹3,000"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "First interest is 24% of P, the second 10% of P.",
      "The difference of 14% equals ₹280.",
    ],
    solution:
      "1. First: P × 8 × 3/100 = 0.24P. Second: P × 5 × 2/100 = 0.10P.\n2. Difference = 0.14P = 280.\n3. P = **₹2,000**.\n\nAnswer: **₹2,000**.",
    approach: "Convert each interest to a percentage of the same principal, subtract, and solve once. The principal never has to be split.",
    tags: ["simple interest"],
    timeTargetSec: 90,
  },
  {
    slug: "in2-ci-effective-rate-two-years",
    topic: "interest",
    title: "Two-year effective rate",
    prompt: "What **single percentage** is equivalent to **compound interest at 20% per annum for 2 years**?",
    options: ["40%", "42%", "44%", "48%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Multiply the growth factors: 1.2 × 1.2.", "1.44 means a 44% rise."],
    solution: "1. Growth = 1.2² = 1.44.\n2. That is a **44%** increase.\n\nAnswer: **44%**.",
    approach: "Two years at r% compound equals 2r + r²/100 percent overall — here 40 + 4 = 44. Simple interest would give exactly 40%.",
    tags: ["compound interest"],
    timeTargetSec: 50,
  },
  {
    slug: "in2-si-installments",
    topic: "interest",
    title: "Equal annual instalments",
    prompt:
      "A sum of **₹1,000** is to be repaid in **two equal annual instalments** at **5% simple interest** on the outstanding amount. What is each instalment, to the nearest rupee?",
    options: ["₹525", "₹537", "₹550", "₹564"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Let each instalment be x. The first is paid after one year, the second after two.",
      "Discount each back: x/1.05 + x/1.10 = 1,000 under simple interest.",
    ],
    solution:
      "1. Under simple interest the present value of a payment after n years is x/(1 + 0.05n).\n2. x/1.05 + x/1.10 = 1,000.\n3. x(0.95238 + 0.90909) = 1,000 → x × 1.86147 = 1,000.\n4. x ≈ **₹537**.\n\nAnswer: **₹537**.",
    approach:
      "Bring every instalment back to its present value and set the total equal to the sum borrowed. Note that simple interest discounts by dividing by (1 + rn), not by a power.",
    tags: ["instalments"],
    timeTargetSec: 150,
  },
  {
    slug: "in2-ci-amount-after-half-year-partial",
    topic: "interest",
    title: "Interest for one and a half years",
    prompt:
      "What is the **amount** on **₹8,000** at **10% per annum compound interest** for **1½ years**, compounded **half-yearly**?",
    options: ["₹9,000", "₹9,261", "₹9,300", "₹9,400"],
    answer: 1,
    difficulty: "hard",
    hints: ["Half-yearly at 10% p.a. means 5% per period.", "One and a half years is 3 periods, so 8,000 × 1.05³."],
    solution:
      "1. Rate per half-year = 5%; periods = 3.\n2. 1.05³ = 1.157625.\n3. Amount = 8,000 × 1.157625 = **₹9,261**.\n\nAnswer: **₹9,261**.",
    approach: "Count the compounding periods rather than the years. One and a half years compounded half-yearly is three periods, not one and a half.",
    tags: ["half-yearly"],
    timeTargetSec: 90,
  },
  {
    slug: "in2-si-average-rate",
    topic: "interest",
    title: "Rate changing over the years",
    prompt:
      "A sum of **₹10,000** earns simple interest at **5% for the first 2 years**, **8% for the next 3 years** and **10% thereafter**. What is the **total interest after 7 years**?",
    options: ["₹5,400", "₹5,600", "₹5,800", "₹6,000"],
    answer: 0,
    difficulty: "medium",
    hints: ["Handle each stretch separately.", "2 years at 5%, 3 at 8%, and 2 at 10%."],
    solution:
      "1. First 2 years: 10,000 × 5 × 2/100 = ₹1,000.\n2. Next 3 years: 10,000 × 8 × 3/100 = ₹2,400.\n3. Last 2 years: 10,000 × 10 × 2/100 = ₹2,000.\n4. Total = **₹5,400**.\n\nAnswer: **₹5,400**.",
    approach: "Break the period at each rate change and add. Under simple interest the principal never changes, so each stretch is independent.",
    tags: ["simple interest"],
    timeTargetSec: 90,
  },
  {
    slug: "in2-ci-difference-three-years",
    topic: "interest",
    title: "The three-year gap",
    prompt:
      "The **difference between compound and simple interest** on a sum for **3 years at 10% per annum** is **₹93**. What is the **sum**?",
    options: ["₹2,500", "₹3,000", "₹3,500", "₹4,000"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "For three years the difference is P(r/100)²(3 + r/100).",
      "P × 0.01 × 3.1 = 93.",
    ],
    solution:
      "1. Difference for 3 years = P(r/100)²(3 + r/100) = P × 0.01 × 3.1 = 0.031P.\n2. 0.031P = 93 → P = **₹3,000**.\n3. Check: CI = 3,000 × 1.331 − 3,000 = 993; SI = 900; difference 93. ✓\n\nAnswer: **₹3,000**.",
    approach:
      "Learn both gap formulas: two years is P(r/100)² and three years is P(r/100)²(3 + r/100). Verifying against the full calculation once builds trust in them.",
    tags: ["ci vs si"],
    timeTargetSec: 120,
  },
  {
    slug: "in2-si-simple-vs-compound-same",
    topic: "interest",
    title: "When simple and compound agree",
    prompt:
      "For which period are the **simple and compound interest** on the same sum at the same rate **exactly equal**?",
    options: ["1 year", "2 years", "3 years", "They are never equal"],
    answer: 0,
    difficulty: "medium",
    hints: ["Compounding only matters once interest has been earned and left to grow.", "In the first year there is nothing yet to compound."],
    solution:
      "1. In the first year interest is charged on the principal alone under both schemes.\n2. Compounding only begins to differ from the second year, when interest earns interest.\n3. So they are equal for **1 year**.\n\nAnswer: **1 year**.",
    approach:
      "The whole difference between the two schemes is interest on interest. Until a full period has passed there is no accumulated interest to compound, so the two coincide.",
    tags: ["ci vs si"],
    timeTargetSec: 50,
  },
];
