import type { AptitudeSeed } from "./types.js";

/** Mixtures and alligation, and mensuration — the standard exam set. */
export const BANK_MIXTURES_MENSURATION: AptitudeSeed[] = [
  /* ── Mixtures & Alligation ─────────────────────────────────────── */
  {
    slug: "ma2-two-rice-varieties",
    topic: "mixtures-alligation",
    title: "Blending two varieties of rice",
    prompt:
      "Rice at **₹30 per kg** is mixed with rice at **₹45 per kg** so that the mixture is worth **₹35 per kg**. In what **ratio** are they mixed?",
    options: ["1 : 2", "2 : 1", "2 : 3", "3 : 2"],
    answer: 1,
    difficulty: "easy",
    hints: ["Use the alligation cross: (dearer − mean) : (mean − cheaper).", "(45 − 35) : (35 − 30)."],
    solution:
      "1. Cheaper : dearer = (45 − 35) : (35 − 30) = 10 : 5 = **2 : 1**.\n2. Check: (2 × 30 + 1 × 45)/3 = 105/3 = 35. ✓\n\nAnswer: **2 : 1**.",
    approach:
      "The alligation cross gives quantity of cheaper ÷ quantity of dearer = (dearer − mean) ÷ (mean − cheaper). The mean sits nearer the ingredient there is more of.",
    tags: ["alligation"],
    timeTargetSec: 50,
  },
  {
    slug: "ma2-tea-blend-profit",
    topic: "mixtures-alligation",
    title: "Blending tea for a target price",
    prompt:
      "In what **ratio** must tea at **₹62 per kg** be mixed with tea at **₹72 per kg** so the mixture is worth **₹64.50 per kg**?",
    options: ["1 : 3", "2 : 3", "3 : 1", "3 : 2"],
    answer: 2,
    difficulty: "medium",
    hints: ["(72 − 64.50) : (64.50 − 62).", "7.5 : 2.5."],
    solution:
      "1. Cheaper : dearer = (72 − 64.5) : (64.5 − 62) = 7.5 : 2.5 = **3 : 1**.\n2. Check: (3 × 62 + 1 × 72)/4 = 258/4 = 64.5. ✓\n\nAnswer: **3 : 1**.",
    approach: "Decimals in the mean are no obstacle — the differences reduce cleanly. Always verify by taking the weighted average of your answer.",
    tags: ["alligation"],
    timeTargetSec: 60,
  },
  {
    slug: "ma2-milk-water-cost",
    topic: "mixtures-alligation",
    title: "Adding water to milk for profit",
    prompt:
      "In what **ratio** must water be mixed with milk costing **₹32 per litre** so that the seller **gains 25%** by selling the mixture at **₹32 per litre**?",
    options: ["1 : 3", "1 : 4", "1 : 5", "2 : 5"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Selling at cost price but gaining 25% means the mixture must cost ₹32/1.25 per litre.",
      "That is ₹25.60; now use alligation between water at ₹0 and milk at ₹32.",
    ],
    solution:
      "1. To gain 25% selling at ₹32, the mixture must cost 32 ÷ 1.25 = ₹25.60 per litre.\n2. Alligation between water (₹0) and milk (₹32) at a mean of ₹25.60:\n   water : milk = (32 − 25.6) : (25.6 − 0) = 6.4 : 25.6 = **1 : 4**.\n\nAnswer: **1 : 4**.",
    approach:
      "Convert the profit requirement into the cost the mixture must have, then treat water as a free ingredient in an ordinary alligation.",
    tags: ["alligation", "milk and water"],
    timeTargetSec: 120,
  },
  {
    slug: "ma2-replace-milk-twice",
    topic: "mixtures-alligation",
    title: "Replacing milk with water twice",
    prompt:
      "A vessel holds **40 litres of milk**. **4 litres** is removed and replaced with water, and this is done **twice** in all. How much **milk** remains?",
    options: ["30.8 L", "32.4 L", "32.8 L", "36 L"],
    answer: 1,
    difficulty: "medium",
    hints: ["Each operation leaves 90% of the milk present.", "40 × 0.9 × 0.9."],
    solution:
      "1. Each replacement removes one tenth of the milk, leaving 9/10.\n2. After two operations: 40 × (0.9)² = 40 × 0.81 = **32.4 L**.\n\nAnswer: **32.4 L**.",
    approach: "Repeated replacement: remaining = initial × (1 − drawn/total)ⁿ. It is compound decay with the same formula as depreciation.",
    tags: ["replacement"],
    timeTargetSec: 75,
  },
  {
    slug: "ma2-replace-three-times",
    topic: "mixtures-alligation",
    title: "Three replacements",
    prompt:
      "A cask holds **80 litres of wine**. **8 litres** is drawn off and replaced with water **three times**. How much **wine** is left?",
    options: ["46.6 L", "52.4 L", "58.3 L", "64.8 L"],
    answer: 2,
    difficulty: "medium",
    hints: ["Each operation leaves 90% of the wine.", "80 × 0.9³, and 0.9³ = 0.729."],
    solution:
      "1. Fraction remaining each time = 1 − 8/80 = 0.9.\n2. After three operations: 80 × 0.729 = **58.32 ≈ 58.3 L**.\n\nAnswer: **58.3 L**.",
    approach: "The same power rule with n = 3. Note that the amount drawn each time is the same volume, not the same amount of wine.",
    tags: ["replacement"],
    timeTargetSec: 75,
  },
  {
    slug: "ma2-alloy-copper-tin",
    topic: "mixtures-alligation",
    title: "Blending two alloys",
    prompt:
      "Alloy A contains **60% copper** and alloy B contains **20% copper**. In what **ratio** must they be mixed to obtain an alloy with **45% copper**?",
    options: ["3 : 5", "5 : 3", "4 : 3", "3 : 4"],
    answer: 1,
    difficulty: "medium",
    hints: ["Alligation on the copper percentages.", "(45 − 20) : (60 − 45)."],
    solution:
      "1. A : B = (45 − 20) : (60 − 45) = 25 : 15 = **5 : 3**.\n2. Check: (5 × 60 + 3 × 20)/8 = 360/8 = 45. ✓\n\nAnswer: **5 : 3**.",
    approach:
      "Take care with the direction: the quantity of the *richer* alloy is proportional to (mean − poorer). The mean at 45 is nearer 60, so more of A is needed.",
    tags: ["alloys"],
    timeTargetSec: 60,
  },
  {
    slug: "ma2-average-price-of-mixture",
    topic: "mixtures-alligation",
    title: "Price of the mixture",
    prompt:
      "**15 kg of sugar at ₹40 per kg** is mixed with **25 kg at ₹32 per kg**. What is the **price per kg of the mixture**?",
    options: ["₹34", "₹35", "₹36", "₹38"],
    answer: 1,
    difficulty: "easy",
    hints: ["Total cost, then divide by total weight.", "600 + 800 over 40 kg."],
    solution:
      "1. Cost = 15 × 40 + 25 × 32 = 600 + 800 = ₹1,400.\n2. Weight = 40 kg.\n3. Price = 1,400 ÷ 40 = **₹35 per kg**.\n\nAnswer: **₹35**.",
    approach: "A weighted average, so it leans towards the larger quantity — here towards ₹32, giving ₹35 rather than the plain mean of ₹36.",
    tags: ["weighted average"],
    timeTargetSec: 60,
  },
  {
    slug: "ma2-milk-water-ratio-after-adding",
    topic: "mixtures-alligation",
    title: "The ratio after adding water",
    prompt:
      "A **45-litre mixture** has milk and water in the ratio **4 : 1**. If **10 litres of water** is added, what is the **new ratio**?",
    options: ["4 : 3", "36 : 19", "18 : 11", "2 : 1"],
    answer: 1,
    difficulty: "medium",
    hints: ["Milk = 36 L and water = 9 L to start with.", "After adding, water becomes 19 L."],
    solution:
      "1. Milk = (4/5) × 45 = 36 L; water = 9 L.\n2. After adding 10 L of water: water = 19 L, milk unchanged at 36 L.\n3. New ratio = **36 : 19**.\n\nAnswer: **36 : 19**.",
    approach: "Only the added component changes. Compute both amounts first, adjust one, and leave the ratio unreduced if it has no common factor.",
    tags: ["milk and water"],
    timeTargetSec: 75,
  },
  {
    slug: "ma2-two-vessels-equal",
    topic: "mixtures-alligation",
    title: "Two vessels poured together",
    prompt:
      "Two vessels of **equal capacity** hold milk and water in the ratios **5 : 3** and **5 : 7**. Their contents are poured into a third vessel. What is the **new ratio**?",
    options: ["25 : 21", "25 : 23", "5 : 4", "12 : 11"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Take 24 litres from each so both ratios divide evenly.",
      "First: milk 15, water 9. Second: milk 10, water 14.",
    ],
    solution:
      "1. Take 24 L from each vessel (24 divides both 8 and 12).\n2. First: milk 15, water 9. Second: milk 10, water 14.\n3. Totals: milk 25, water 23 → **25 : 23**.\n\nAnswer: **25 : 23**.",
    approach: "Choose a common volume that both ratio sums divide — the LCM of 8 and 12 is 24. Averaging the ratios directly is always wrong.",
    tags: ["alloys"],
    timeTargetSec: 105,
  },
  {
    slug: "ma2-quantity-of-water-to-add",
    topic: "mixtures-alligation",
    title: "Water needed to reach a ratio",
    prompt:
      "A **60-litre mixture** contains milk and water in the ratio **7 : 3**. How much **water** must be added so the ratio becomes **3 : 2**?",
    options: ["4 L", "6 L", "8 L", "10 L"],
    answer: 3,
    difficulty: "medium",
    hints: ["Milk = 42 L and does not change.", "For a 3 : 2 ratio with 42 L of milk, water must be 28 L."],
    solution:
      "1. Milk = (7/10) × 60 = 42 L; water = 18 L.\n2. For milk : water = 3 : 2 with milk fixed at 42, water must be 42 × 2/3 = 28 L.\n3. Water to add = 28 − 18 = **10 L**.\n\nAnswer: **10 L**.",
    approach: "Anchor on the unchanged component, work out the new amount the other must reach, and subtract what is already present.",
    tags: ["milk and water"],
    timeTargetSec: 90,
  },
  {
    slug: "ma2-acid-concentration",
    topic: "mixtures-alligation",
    title: "Strengthening an acid solution",
    prompt:
      "How much **pure acid** must be added to **50 litres of a 20% acid solution** to make it **50% acid**?",
    options: ["20 L", "25 L", "30 L", "35 L"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Acid at the start = 10 L; water = 40 L and stays fixed.",
      "In the final solution water must be 50%, so the total must be 80 L.",
    ],
    solution:
      "1. Acid = 20% of 50 = 10 L; water = 40 L, and the water never changes.\n2. In the final mixture water is 50%, so the total = 40 ÷ 0.5 = 80 L.\n3. Acid to add = 80 − 50 = **30 L**.\n\nAnswer: **30 L**.",
    approach:
      "Anchor on the component that is not being added — the water. Tracking the acid instead needs an equation, while tracking the water is a single division.",
    tags: ["concentration"],
    timeTargetSec: 120,
  },
  {
    slug: "ma2-profit-from-mixture",
    topic: "mixtures-alligation",
    title: "Milkman's profit from water",
    prompt:
      "A milkman mixes **water with milk** in the ratio **1 : 4** and sells the mixture at **cost price**. What is his **profit percent**?",
    options: ["20%", "25%", "30%", "33⅓%"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "For every 4 litres of milk he sells 5 litres of mixture.",
      "The free litre of water is pure profit, measured against the 4 litres he paid for.",
    ],
    solution:
      "1. Take 4 L of milk and 1 L of water: 5 L of mixture.\n2. He pays for 4 L but receives the price of 5 L.\n3. Profit = 1/4 = **25%**.\n\nAnswer: **25%**.",
    approach:
      "The gain is the free component measured against the cost of what was bought, not against the mixture sold. Dividing by 5 instead of 4 gives 20%, which is offered.",
    tags: ["milk and water"],
    timeTargetSec: 90,
  },

  /* ── Mensuration ───────────────────────────────────────────────── */
  {
    slug: "me2-rectangle-area-from-ratio",
    topic: "mensuration",
    title: "Area from a ratio and perimeter",
    prompt:
      "The **length and breadth of a rectangle are in the ratio 3 : 2** and its **perimeter is 80 cm**. What is its **area**?",
    options: ["336 cm²", "364 cm²", "384 cm²", "400 cm²"],
    answer: 2,
    difficulty: "medium",
    hints: ["Half the perimeter gives l + b = 40.", "With l : b = 3 : 2, the parts are 24 and 16."],
    solution:
      "1. l + b = 80 ÷ 2 = 40.\n2. Splitting 40 in the ratio 3 : 2 gives l = 24, b = 16.\n3. Area = 24 × 16 = **384 cm²**.\n\nAnswer: **384 cm²**.",
    approach: "Halve the perimeter first — that single step converts a perimeter question into a simple sharing problem.",
    tags: ["rectangle"],
    timeTargetSec: 75,
  },
  {
    slug: "me2-square-diagonal-area",
    topic: "mensuration",
    title: "Area from the diagonal",
    prompt: "The **diagonal of a square is 8 cm**. What is its **area**?",
    options: ["16 cm²", "32 cm²", "48 cm²", "64 cm²"],
    answer: 1,
    difficulty: "medium",
    hints: ["Area of a square = d²/2.", "64 ÷ 2."],
    solution: "1. Area = d²/2 = 64/2 = **32 cm²**.\n\nAnswer: **32 cm²**.",
    approach: "For a square, area = d²/2 and side = d/√2. Squaring the diagonal and forgetting to halve gives 64, which is offered.",
    tags: ["square"],
    timeTargetSec: 50,
  },
  {
    slug: "me2-circle-area-from-radius",
    topic: "mensuration",
    title: "Area of a circle",
    prompt: "What is the **area of a circle** with radius **14 cm**? (Take π = 22/7.)",
    options: ["308 cm²", "462 cm²", "616 cm²", "704 cm²"],
    answer: 2,
    difficulty: "easy",
    hints: ["Area = πr².", "22/7 × 196."],
    solution: "1. Area = (22/7) × 14 × 14 = 22 × 2 × 14 = **616 cm²**.\n\nAnswer: **616 cm²**.",
    approach: "Cancel the 7 in π = 22/7 against the radius before multiplying. Radii that are multiples of 7 always work out to whole numbers.",
    tags: ["circle"],
    timeTargetSec: 50,
  },
  {
    slug: "me2-circumference-from-area",
    topic: "mensuration",
    title: "Circumference from the area",
    prompt: "The **area of a circle is 154 cm²**. What is its **circumference**? (Take π = 22/7.)",
    options: ["22 cm", "33 cm", "44 cm", "55 cm"],
    answer: 2,
    difficulty: "medium",
    hints: ["Find the radius first: πr² = 154.", "r = 7, then use 2πr."],
    solution:
      "1. (22/7)r² = 154 → r² = 49 → r = 7 cm.\n2. Circumference = 2 × (22/7) × 7 = **44 cm**.\n\nAnswer: **44 cm**.",
    approach: "Route through the radius: area gives r, and r gives the circumference. The pair r = 7, area 154, circumference 44 is worth memorising.",
    tags: ["circle"],
    timeTargetSec: 60,
  },
  {
    slug: "me2-triangle-heron",
    topic: "mensuration",
    title: "Area by Heron's formula",
    prompt: "What is the **area of a triangle** with sides **13 cm, 14 cm and 15 cm**?",
    options: ["78 cm²", "84 cm²", "91 cm²", "96 cm²"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The semi-perimeter is (13 + 14 + 15)/2 = 21.",
      "Area = √(21 × 8 × 7 × 6).",
    ],
    solution:
      "1. s = (13 + 14 + 15)/2 = 21.\n2. Area = √(21 × (21−13) × (21−14) × (21−15)) = √(21 × 8 × 7 × 6).\n3. = √7056 = **84 cm²**.\n\nAnswer: **84 cm²**.",
    approach:
      "Heron's formula when no height is given. The 13-14-15 triangle with area 84 is a standard exam favourite, so it is worth recognising on sight.",
    tags: ["triangle"],
    timeTargetSec: 120,
  },
  {
    slug: "me2-equilateral-triangle-area",
    topic: "mensuration",
    title: "Area of an equilateral triangle",
    prompt: "What is the **area of an equilateral triangle** of side **12 cm**? (Take √3 = 1.73.)",
    options: ["36√3 cm²", "48√3 cm²", "62.28 cm²", "72 cm²"],
    answer: 0,
    difficulty: "medium",
    hints: ["Area = (√3/4)a².", "(√3/4) × 144."],
    solution:
      "1. Area = (√3/4) × 12² = (√3/4) × 144 = **36√3 cm²** (about 62.28 cm²).\n\nAnswer: **36√3 cm²**.",
    approach: "Learn (√3/4)a² for the area and (√3/2)a for the height. Both come up constantly in geometry questions.",
    tags: ["triangle"],
    timeTargetSec: 60,
  },
  {
    slug: "me2-cuboid-volume",
    topic: "mensuration",
    title: "Volume of a cuboid",
    prompt: "What is the **volume of a cuboid** measuring **12 cm × 8 cm × 5 cm**?",
    options: ["380 cm³", "440 cm³", "480 cm³", "520 cm³"],
    answer: 2,
    difficulty: "easy",
    hints: ["Volume = length × breadth × height.", "12 × 8 × 5."],
    solution: "1. Volume = 12 × 8 × 5 = **480 cm³**.\n\nAnswer: **480 cm³**.",
    approach: "Base area × height for any prism. The surface area, 2(lb + bh + hl), is a different question and often asked alongside.",
    tags: ["cuboid"],
    timeTargetSec: 40,
  },
  {
    slug: "me2-cuboid-surface-area",
    topic: "mensuration",
    title: "Surface area of a cuboid",
    prompt: "What is the **total surface area** of a cuboid measuring **10 cm × 6 cm × 4 cm**?",
    options: ["188 cm²", "228 cm²", "248 cm²", "268 cm²"],
    answer: 2,
    difficulty: "medium",
    hints: ["Surface area = 2(lb + bh + hl).", "2(60 + 24 + 40)."],
    solution:
      "1. lb + bh + hl = 60 + 24 + 40 = 124.\n2. Surface area = 2 × 124 = **248 cm²**.\n\nAnswer: **248 cm²**.",
    approach: "Three distinct faces, each appearing twice. Compute the three products, add, then double.",
    tags: ["cuboid"],
    timeTargetSec: 60,
  },
  {
    slug: "me2-cube-diagonal",
    topic: "mensuration",
    title: "Diagonal of a cube",
    prompt: "What is the length of the **diagonal of a cube** of side **6 cm**? (Take √3 = 1.73.)",
    options: ["6√2 cm", "6√3 cm", "12 cm", "18 cm"],
    answer: 1,
    difficulty: "medium",
    hints: ["The space diagonal of a cube is a√3.", "6 × √3."],
    solution: "1. Diagonal = a√3 = **6√3 cm** (about 10.39 cm).\n\nAnswer: **6√3 cm**.",
    approach: "A cube's face diagonal is a√2 and its space diagonal a√3. The question asks for the longer of the two.",
    tags: ["cube"],
    timeTargetSec: 50,
  },
  {
    slug: "me2-cylinder-curved-surface",
    topic: "mensuration",
    title: "Curved surface of a cylinder",
    prompt:
      "What is the **curved surface area** of a cylinder with radius **7 cm** and height **10 cm**? (Take π = 22/7.)",
    options: ["220 cm²", "308 cm²", "440 cm²", "748 cm²"],
    answer: 2,
    difficulty: "medium",
    hints: ["Curved surface = 2πrh.", "2 × 22/7 × 7 × 10."],
    solution: "1. CSA = 2 × (22/7) × 7 × 10 = 2 × 22 × 10 = **440 cm²**.\n\nAnswer: **440 cm²**.",
    approach:
      "Curved surface is 2πrh; adding the two circular ends gives the total surface 2πr(r + h). Read which one the question wants.",
    tags: ["cylinder"],
    timeTargetSec: 60,
  },
  {
    slug: "me2-sphere-volume",
    topic: "mensuration",
    title: "Volume of a sphere",
    prompt: "What is the **volume of a sphere** of radius **3 cm**? (Take π = 22/7.)",
    options: ["88.6 cm³", "113.1 cm³", "121.5 cm³", "132 cm³"],
    answer: 1,
    difficulty: "medium",
    hints: ["Volume = (4/3)πr³.", "(4/3) × (22/7) × 27."],
    solution:
      "1. Volume = (4/3) × (22/7) × 27 = (4 × 22 × 27)/(3 × 7) = 2376/21 ≈ **113.1 cm³**.\n\nAnswer: **113.1 cm³**.",
    approach: "Sphere: volume (4/3)πr³ and surface 4πr². Cancel the 3 against the 27 before multiplying to keep the numbers small.",
    tags: ["sphere"],
    timeTargetSec: 75,
  },
  {
    slug: "me2-cone-volume",
    topic: "mensuration",
    title: "Volume of a cone",
    prompt:
      "What is the **volume of a cone** with radius **7 cm** and height **12 cm**? (Take π = 22/7.)",
    options: ["528 cm³", "616 cm³", "660 cm³", "704 cm³"],
    answer: 1,
    difficulty: "medium",
    hints: ["Volume = (1/3)πr²h.", "(1/3) × (22/7) × 49 × 12."],
    solution:
      "1. Volume = (1/3) × (22/7) × 49 × 12 = (1/3) × 22 × 7 × 12 = **616 cm³**.\n\nAnswer: **616 cm³**.",
    approach: "A cone is one third of the cylinder on the same base and height. Forgetting the third gives 1,848 and is the standard slip.",
    tags: ["cone"],
    timeTargetSec: 75,
  },
  {
    slug: "me2-path-around-garden",
    topic: "mensuration",
    title: "A path around a garden",
    prompt:
      "A rectangular garden **50 m × 30 m** is surrounded by a path **2 m wide** on the **outside**. What is the **area of the path**?",
    options: ["316 m²", "336 m²", "356 m²", "376 m²"],
    answer: 1,
    difficulty: "medium",
    hints: ["The outer rectangle measures (50 + 4) × (30 + 4).", "Subtract the garden's area from it."],
    solution:
      "1. Outer rectangle = 54 × 34 = 1,836 m².\n2. Garden = 50 × 30 = 1,500 m².\n3. Path = 1,836 − 1,500 = **336 m²**.\n\nAnswer: **336 m²**.",
    approach: "An outside path adds twice its width to each dimension; an inside path subtracts twice. Everything else is the difference of two rectangles.",
    tags: ["path"],
    timeTargetSec: 90,
  },
  {
    slug: "me2-carpet-cost",
    topic: "mensuration",
    title: "Cost of carpeting a room",
    prompt:
      "What does it cost to **carpet a room 15 m × 12 m** with carpet costing **₹40 per square metre**?",
    options: ["₹6,400", "₹7,200", "₹8,000", "₹9,600"],
    answer: 1,
    difficulty: "easy",
    hints: ["Find the floor area first.", "180 m² at ₹40."],
    solution: "1. Area = 15 × 12 = 180 m².\n2. Cost = 180 × 40 = **₹7,200**.\n\nAnswer: **₹7,200**.",
    approach: "Area then rate. If the carpet were sold by length at a given width, you would divide the area by that width first.",
    tags: ["cost"],
    timeTargetSec: 45,
  },
  {
    slug: "me2-parallelogram-area",
    topic: "mensuration",
    title: "Area of a parallelogram",
    prompt: "What is the **area of a parallelogram** with base **18 cm** and height **9 cm**?",
    options: ["81 cm²", "144 cm²", "162 cm²", "324 cm²"],
    answer: 2,
    difficulty: "easy",
    hints: ["Area = base × height.", "18 × 9."],
    solution: "1. Area = 18 × 9 = **162 cm²**.\n\nAnswer: **162 cm²**.",
    approach: "A parallelogram is base × perpendicular height, not base × side. A triangle on the same base and height is half of it.",
    tags: ["parallelogram"],
    timeTargetSec: 40,
  },
  {
    slug: "me2-trapezium-area",
    topic: "mensuration",
    title: "Area of a trapezium",
    prompt:
      "What is the **area of a trapezium** whose **parallel sides are 20 cm and 12 cm** and whose **height is 10 cm**?",
    options: ["120 cm²", "150 cm²", "160 cm²", "200 cm²"],
    answer: 2,
    difficulty: "easy",
    hints: ["Area = ½ × (sum of parallel sides) × height.", "½ × 32 × 10."],
    solution: "1. Area = ½ × (20 + 12) × 10 = ½ × 320 = **160 cm²**.\n\nAnswer: **160 cm²**.",
    approach: "Average the two parallel sides and multiply by the height. Using only one of the parallel sides is the usual error.",
    tags: ["trapezium"],
    timeTargetSec: 45,
  },
  {
    slug: "me2-wire-bent-into-square",
    topic: "mensuration",
    title: "A wire bent into a square",
    prompt:
      "A wire in the shape of a **circle of radius 28 cm** is bent into a **square**. What is the **area of the square**? (Take π = 22/7.)",
    options: ["1,936 cm²", "2,916 cm²", "3,136 cm²", "3,844 cm²"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "The wire's length is the circle's circumference, 2πr.",
      "That becomes the square's perimeter, so divide by 4 for the side.",
    ],
    solution:
      "1. Circumference = 2 × (22/7) × 28 = 176 cm.\n2. As a square's perimeter, each side = 176 ÷ 4 = 44 cm.\n3. Area = 44² = **1,936 cm²**.\n\nAnswer: **1,936 cm²**.",
    approach:
      "Bending a wire preserves its length, so circumference becomes perimeter. The shape changes but the total length does not.",
    tags: ["circle", "square"],
    timeTargetSec: 105,
  },
  {
    slug: "me2-square-area-increase",
    topic: "mensuration",
    title: "Increasing the side of a square",
    prompt: "If the **side of a square is increased by 20%**, by what percent does its **area increase**?",
    options: ["20%", "40%", "44%", "48%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Area scales as the square of the side.", "1.2² = 1.44."],
    solution:
      "1. New side = 1.2 × old, so new area = 1.2² = 1.44 times the old.\n2. Increase = **44%**.\n\nAnswer: **44%**.",
    approach: "Lengths scale by k, areas by k² and volumes by k³. Doubling the percentage (40%) is the standard mistake.",
    tags: ["scaling"],
    timeTargetSec: 50,
  },
  {
    slug: "me2-cube-volume-increase",
    topic: "mensuration",
    title: "Doubling the edge of a cube",
    prompt: "If the **edge of a cube is doubled**, by what factor does its **volume increase**?",
    options: ["2", "4", "6", "8"],
    answer: 3,
    difficulty: "easy",
    hints: ["Volume scales as the cube of the edge.", "2³."],
    solution: "1. Volume ∝ a³, so doubling the edge multiplies the volume by 2³ = **8**.\n\nAnswer: **8**.",
    approach: "Volumes scale as the cube of any linear change. The surface area, meanwhile, would only quadruple.",
    tags: ["scaling"],
    timeTargetSec: 40,
  },
  {
    slug: "me2-room-four-walls",
    topic: "mensuration",
    title: "Area of the four walls",
    prompt:
      "What is the **area of the four walls** of a room **8 m long, 6 m wide and 4 m high**?",
    options: ["96 m²", "112 m²", "128 m²", "144 m²"],
    answer: 1,
    difficulty: "medium",
    hints: ["Area of four walls = 2(l + b) × h.", "2 × 14 × 4."],
    solution: "1. Area = 2(8 + 6) × 4 = 2 × 14 × 4 = **112 m²**.\n\nAnswer: **112 m²**.",
    approach: "The four walls form a band of height h around a perimeter of 2(l + b). The floor and ceiling are excluded.",
    tags: ["cuboid"],
    timeTargetSec: 60,
  },
];
