import type { AptitudeSeed } from "./types.js";

/** Profit and loss — the standard placement and bank-exam set. */
export const BANK_PROFIT_LOSS: AptitudeSeed[] = [
  {
    slug: "pl2-gain-percent-basic",
    topic: "profit-and-loss",
    title: "Gain percent from cost and sale",
    prompt: "An article bought for **₹27.50** is sold for **₹28.60**. What is the **gain percent**?",
    options: ["2%", "3%", "4%", "5%"],
    answer: 2,
    difficulty: "easy",
    hints: ["Gain = SP − CP.", "Express the gain of 1.10 as a fraction of 27.50."],
    solution:
      "1. Gain = 28.60 − 27.50 = ₹1.10.\n2. Gain % = 1.10 / 27.50 × 100 = **4%**.\n\nAnswer: **4%**.",
    approach: "Profit percent is always measured on the cost price unless a question says otherwise. Divide the gain by the cost, never by the selling price.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pl2-cp-from-sp-and-profit",
    topic: "profit-and-loss",
    title: "Cost price from a 10% profit",
    prompt: "An article sold for **₹27.50** yields a **profit of 10%**. What was the **cost price**?",
    options: ["₹22.50", "₹24.75", "₹25.00", "₹25.50"],
    answer: 2,
    difficulty: "easy",
    hints: ["SP = CP × 1.10.", "Divide 27.50 by 1.10."],
    solution: "1. CP × 1.10 = 27.50.\n2. CP = 27.50 ÷ 1.10 = **₹25.00**.\n\nAnswer: **₹25.00**.",
    approach: "Going from SP back to CP is a division by (1 + profit/100). Subtracting 10% of the selling price instead gives 24.75, which is offered as the trap.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pl2-cp-from-loss",
    topic: "profit-and-loss",
    title: "Cost price after a 20% loss",
    prompt: "An article sold at a **loss of 20%** fetched **₹480**. What was the **cost price**?",
    options: ["₹540", "₹576", "₹600", "₹620"],
    answer: 2,
    difficulty: "easy",
    hints: ["SP = CP × 0.80.", "Divide 480 by 0.8."],
    solution: "1. CP × 0.80 = 480.\n2. CP = 480 ÷ 0.80 = **₹600**.\n\nAnswer: **₹600**.",
    approach: "A 20% loss means the sale recovers 80% of the cost. Adding 20% to 480 gives 576 and is wrong, because the percentage is of the cost, not of the sale.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pl2-sp-of-12-equals-cp-of-15",
    topic: "profit-and-loss",
    title: "SP of 12 equals CP of 15",
    prompt: "If the **selling price of 12 articles equals the cost price of 15 articles**, what is the **gain percent**?",
    options: ["20%", "25%", "30%", "33⅓%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let one article cost ₹1, so 12 articles sell for ₹15.", "Selling price per article = 15/12."],
    solution:
      "1. Let CP per article = ₹1. Then 12 articles sell for ₹15, so SP per article = 15/12 = ₹1.25.\n2. Gain = 0.25 on a cost of 1 = **25%**.\n\nAnswer: **25%**.",
    approach: "If SP of a articles = CP of b articles, gain% = (b − a)/a × 100. Setting one cost price to 1 turns the whole question into a single fraction.",
    tags: ["articles"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-cp-of-20-equals-sp-of-16",
    topic: "profit-and-loss",
    title: "CP of 20 equals SP of 16",
    prompt: "If the **cost price of 20 articles equals the selling price of 16 articles**, what is the **gain percent**?",
    options: ["16%", "20%", "25%", "30%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let one article cost ₹1, so 16 articles sell for ₹20.", "SP per article = 20/16 = 1.25."],
    solution:
      "1. Let CP per article = ₹1. Then 16 articles sell for ₹20, so SP per article = ₹1.25.\n2. Gain = **25%**.\n\nAnswer: **25%**.",
    approach: "The wording flips but the method does not: price one article at 1 and read off the other side. Whichever count is smaller belongs to the more valuable side.",
    tags: ["articles"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-markup-then-discount-profit",
    topic: "profit-and-loss",
    title: "Marked 40% up, 25% off",
    prompt: "A trader marks his goods **40% above cost** and allows a **discount of 25%**. What is his **profit percent**?",
    options: ["5%", "8%", "10%", "15%"],
    answer: 0,
    difficulty: "medium",
    hints: ["Take the cost as 100, so the marked price is 140.", "A 25% discount leaves 75% of 140."],
    solution:
      "1. CP = 100, marked price = 140.\n2. SP = 75% of 140 = 105.\n3. Profit = 5 on a cost of 100 = **5%**.\n\nAnswer: **5%**.",
    approach: "Chain the multipliers: CP × 1.40 × 0.75 = CP × 1.05. Markup is on cost while discount is on the marked price, so the two never cancel arithmetically.",
    tags: ["marked price", "discount"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-markup-30-gain-4",
    topic: "profit-and-loss",
    title: "The discount that still leaves 4%",
    prompt:
      "A shopkeeper marks his goods **30% above cost price**. What **discount percent** can he allow and still make a **profit of 4%**?",
    options: ["18%", "20%", "22%", "25%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Take CP = 100, so the marked price is 130 and the target selling price 104.", "The discount is 26 off a marked price of 130."],
    solution:
      "1. CP = 100, marked price = 130, required SP = 104.\n2. Discount = 130 − 104 = 26.\n3. Discount % = 26/130 = **20%**.\n\nAnswer: **20%**.",
    approach: "Fix the cost at 100 so both the marked price and the target sale price are plain numbers. The discount percent is always taken on the marked price.",
    tags: ["marked price", "discount"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-equal-sp-gain-loss-15",
    topic: "profit-and-loss",
    title: "Two horses at the same price",
    prompt:
      "A man sold two horses for **₹1,955 each**, gaining **15%** on one and losing **15%** on the other. What was his overall **loss percent**?",
    options: ["1.5%", "2.25%", "3%", "No loss"],
    answer: 1,
    difficulty: "medium",
    hints: ["Equal selling prices with equal gain and loss percentages always end in a loss.", "The loss is x²/100 percent, with x = 15."],
    solution:
      "1. CP of the first = 1955 / 1.15 = ₹1,700; CP of the second = 1955 / 0.85 = ₹2,300.\n2. Total CP = ₹4,000; total SP = ₹3,910.\n3. Loss = 90 on 4,000 = **2.25%**.\n4. This matches the shortcut 15²/100 = 2.25. ✓\n\nAnswer: **2.25%**.",
    approach:
      "Same selling price, equal gain and loss of x% — the result is always a loss of x²/100 percent, whatever the price. The intuition: the loss is taken on a larger cost than the gain.",
    tags: ["equal selling price"],
    timeTargetSec: 90,
  },
  {
    slug: "pl2-two-articles-99-each",
    topic: "profit-and-loss",
    title: "Two articles at ₹99",
    prompt:
      "A shopkeeper sells two articles at **₹99 each**, gaining **10%** on one and losing **10%** on the other. What is his **net loss percent**?",
    options: ["1%", "2%", "5%", "No loss"],
    answer: 0,
    difficulty: "medium",
    hints: ["Find each cost price separately: 99/1.1 and 99/0.9.", "Compare the total cost with the total sale of ₹198."],
    solution:
      "1. CP of the first = 99/1.10 = ₹90; CP of the second = 99/0.90 = ₹110.\n2. Total CP = ₹200; total SP = ₹198.\n3. Loss = 2 on 200 = **1%**, matching 10²/100. ✓\n\nAnswer: **1%**.",
    approach: "The same x²/100 rule as before, with x = 10. Working it out longhand once is worth doing so the shortcut is trusted rather than memorised.",
    tags: ["equal selling price"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-false-weight-800",
    topic: "profit-and-loss",
    title: "A dishonest 800 g kilogram",
    prompt:
      "A dealer professes to sell his goods at **cost price** but uses a weight of **800 g** for a kilogram. What is his **gain percent**?",
    options: ["20%", "22%", "25%", "30%"],
    answer: 2,
    difficulty: "medium",
    hints: ["The customer pays for 1,000 g and receives 800 g.", "The gain of 200 g is measured against the 800 g actually handed over."],
    solution:
      "1. For every 800 g given, the dealer collects the price of 1,000 g.\n2. Gain = 200 g on goods worth 800 g.\n3. Gain % = 200/800 × 100 = **25%**.\n\nAnswer: **25%**.",
    approach: "Gain from a false weight = error ÷ (true weight − error) × 100. The base is what was actually delivered, which is why the answer exceeds the obvious 20%.",
    tags: ["false weight"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-false-weight-900",
    topic: "profit-and-loss",
    title: "A 900 g kilogram",
    prompt: "A trader sells at cost price but uses a **900 g** weight instead of **1 kg**. What is his **profit percent**?",
    options: ["9%", "10%", "11.11%", "12.5%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Error = 100 g; true weight = 1,000 g.", "Profit % = 100 / (1000 − 100) × 100."],
    solution:
      "1. The dealer hands over 900 g but charges for 1,000 g.\n2. Gain = 100 g on goods worth 900 g.\n3. Gain % = 100/900 × 100 = **11.11%**.\n\nAnswer: **11.11%**.",
    approach: "Same formula as the 800 g case. The answer is never the simple 10% that the missing tenth suggests, because the base is the reduced weight.",
    tags: ["false weight"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-sp-doubled-profit-tripled",
    topic: "profit-and-loss",
    title: "Doubling the price triples the profit",
    prompt: "If the **selling price is doubled**, the **profit triples**. What is the original **profit percent**?",
    options: ["50%", "66⅔%", "100%", "150%"],
    answer: 2,
    difficulty: "hard",
    hints: ["Let CP = 100 and SP = x, so profit = x − 100.", "Doubling gives profit 2x − 100, and that equals 3(x − 100)."],
    solution:
      "1. Let CP = 100 and SP = x. Original profit = x − 100.\n2. Doubled selling price 2x gives profit 2x − 100.\n3. Setting 2x − 100 = 3(x − 100) gives 2x − 100 = 3x − 300, so x = 200.\n4. Profit = 100 on a cost of 100 = **100%**.\n\nAnswer: **100%**.",
    approach:
      "Note that doubling the selling price does not double the profit — the cost is unchanged, so the profit more than doubles. Setting CP to 100 keeps the algebra to one line.",
    tags: ["algebra"],
    timeTargetSec: 105,
  },
  {
    slug: "pl2-loss-equals-cp-of-five-balls",
    topic: "profit-and-loss",
    title: "Loss equal to the cost of five balls",
    prompt:
      "On selling **17 balls for ₹720**, there is a loss equal to the **cost price of 5 balls**. What is the **cost price of one ball**?",
    options: ["₹45", "₹50", "₹55", "₹60"],
    answer: 3,
    difficulty: "medium",
    hints: ["Let one ball cost ₹c. Then 17c − 720 = 5c.", "Solve for c."],
    solution:
      "1. Let the cost of one ball be ₹c.\n2. Loss = 17c − 720, and this equals 5c.\n3. 17c − 720 = 5c → 12c = 720 → c = **₹60**.\n\nAnswer: **₹60**.",
    approach: "Write loss as cost minus revenue, then equate it to the quantity the question describes. One linear equation settles it.",
    tags: ["algebra"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-toffees-per-rupee",
    topic: "profit-and-loss",
    title: "Toffees for a rupee",
    prompt:
      "A vendor buys toffees at **6 for a rupee**. How many must he **sell for a rupee** to gain **20%**?",
    options: ["3", "4", "5", "6"],
    answer: 2,
    difficulty: "medium",
    hints: ["Cost per toffee is 1/6 of a rupee.", "For a 20% gain the selling price per toffee must be 1.2/6 = 0.2 rupees."],
    solution:
      "1. CP of one toffee = ₹1/6.\n2. For a 20% gain, SP of one toffee = (1/6) × 1.2 = ₹0.20.\n3. At ₹0.20 each, one rupee buys **5** toffees.\n\nAnswer: **5**.",
    approach:
      "Work in price per unit, then invert at the end. Note the inverse relation: to gain, you must sell *fewer* per rupee, so the answer is always below the buying count.",
    tags: ["per unit"],
    timeTargetSec: 90,
  },
  {
    slug: "pl2-rice-mixture-rate",
    topic: "profit-and-loss",
    title: "Selling rate for a rice mixture",
    prompt:
      "A grocer buys **80 kg of rice at ₹13.50 per kg** and mixes it with **120 kg at ₹16 per kg**. At what **rate per kg** must he sell the mixture to gain **16%**?",
    options: ["₹16.50", "₹17.00", "₹17.40", "₹18.00"],
    answer: 2,
    difficulty: "medium",
    hints: ["Find the total cost of the 200 kg first.", "Total cost ₹3,000; add 16% and divide by 200."],
    solution:
      "1. Cost = 80 × 13.50 + 120 × 16 = 1,080 + 1,920 = ₹3,000.\n2. For a 16% gain, total SP = 3,000 × 1.16 = ₹3,480.\n3. Rate = 3,480 ÷ 200 = **₹17.40 per kg**.\n\nAnswer: **₹17.40**.",
    approach: "Total the cost, apply the profit to the total, then divide by the total quantity. Averaging the two buying rates first is wrong whenever the quantities differ.",
    tags: ["mixtures"],
    timeTargetSec: 90,
  },
  {
    slug: "pl2-tea-mixture-profit",
    topic: "profit-and-loss",
    title: "Profit on a tea mixture",
    prompt:
      "A trader mixes **25 kg of tea at ₹60 per kg** with **25 kg at ₹80 per kg** and sells the mixture at **₹84 per kg**. What is his **profit percent**?",
    options: ["15%", "18%", "20%", "22%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Total cost for 50 kg, then total sale for 50 kg.", "Cost ₹3,500, sale ₹4,200."],
    solution:
      "1. Cost = 25 × 60 + 25 × 80 = 1,500 + 2,000 = ₹3,500.\n2. Sale = 50 × 84 = ₹4,200.\n3. Profit = 700 on 3,500 = **20%**.\n\nAnswer: **20%**.",
    approach: "With equal quantities the average cost is the simple mean (₹70), and the profit follows from 84 against 70. Unequal quantities would need the weighted average.",
    tags: ["mixtures"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-successive-discounts-three",
    topic: "profit-and-loss",
    title: "Three discounts as one",
    prompt: "Successive discounts of **10%, 20% and 30%** are equivalent to a single discount of:",
    options: ["45.5%", "49.6%", "52%", "60%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Multiply what remains after each: 0.9 × 0.8 × 0.7.", "0.504 remains, so the discount is the rest."],
    solution:
      "1. Remaining fraction = 0.90 × 0.80 × 0.70 = 0.504.\n2. Total discount = 1 − 0.504 = **49.6%**.\n\nAnswer: **49.6%**.",
    approach: "Chain the surviving fractions rather than the discounts. Adding the three (60%) always overstates the true reduction.",
    tags: ["discount"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-successive-discounts-two-on-2000",
    topic: "profit-and-loss",
    title: "Final price after two discounts",
    prompt: "An article marked **₹2,000** is sold after successive discounts of **25% and 20%**. What is the **final price**?",
    options: ["₹1,100", "₹1,200", "₹1,300", "₹1,400"],
    answer: 1,
    difficulty: "easy",
    hints: ["Apply 25% first, then 20% to the reduced figure.", "2,000 × 0.75 × 0.80."],
    solution: "1. After 25% off: 2,000 × 0.75 = ₹1,500.\n2. After a further 20% off: 1,500 × 0.80 = **₹1,200**.\n\nAnswer: **₹1,200**.",
    approach: "Apply discounts one at a time in order. The order does not change the result, but combining them into 45% off does — that would give ₹1,100.",
    tags: ["discount"],
    timeTargetSec: 45,
  },
  {
    slug: "pl2-buy-three-get-one-free",
    topic: "profit-and-loss",
    title: "Buy three, get one free",
    prompt: "A shop offers **'buy 3, get 1 free'**. What is the effective **discount percent**?",
    options: ["20%", "25%", "30%", "33⅓%"],
    answer: 1,
    difficulty: "medium",
    hints: ["The customer takes home four articles but pays for three.", "The saving of one article is measured against the four received."],
    solution:
      "1. The customer receives 4 articles and pays for 3.\n2. Saving = the price of 1 article out of 4 articles' worth.\n3. Discount = 1/4 = **25%**.\n\nAnswer: **25%**.",
    approach:
      "The discount base is what is received, not what is paid. Dividing the free item by the three paid for gives 33⅓%, which is the trap offered here.",
    tags: ["discount"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-discount-percent-from-prices",
    topic: "profit-and-loss",
    title: "Discount from marked and sale price",
    prompt: "An article marked **₹800** is sold for **₹680**. What is the **discount percent**?",
    options: ["12%", "15%", "17.5%", "20%"],
    answer: 1,
    difficulty: "easy",
    hints: ["Discount = marked price − selling price.", "120 out of 800."],
    solution: "1. Discount = 800 − 680 = ₹120.\n2. Discount % = 120/800 × 100 = **15%**.\n\nAnswer: **15%**.",
    approach: "Discount is always a percentage of the marked price, whereas profit is a percentage of the cost price. Confusing the two bases is the commonest slip in this chapter.",
    tags: ["discount"],
    timeTargetSec: 40,
  },
  {
    slug: "pl2-profit-on-sp-to-cp",
    topic: "profit-and-loss",
    title: "Profit on selling price versus cost",
    prompt: "A profit of **25% on the selling price** is what percent on the **cost price**?",
    options: ["25%", "30%", "33⅓%", "40%"],
    answer: 2,
    difficulty: "medium",
    hints: ["Take SP = 100, so profit = 25 and CP = 75.", "Now express 25 as a fraction of 75."],
    solution:
      "1. Let SP = 100. Profit = 25, so CP = 75.\n2. Profit as a percentage of cost = 25/75 = **33⅓%**.\n\nAnswer: **33⅓%**.",
    approach: "When a percentage is quoted on the selling price, set SP to 100 instead of CP. Profit on SP is always the smaller of the two figures.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-cp-96-percent-of-sp",
    topic: "profit-and-loss",
    title: "Cost price is 96% of selling price",
    prompt: "If the **cost price is 96% of the selling price**, what is the **profit percent**?",
    options: ["4%", "4.17%", "5%", "6%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Take SP = 100, so CP = 96.", "Profit of 4 on a cost of 96."],
    solution:
      "1. Let SP = 100, so CP = 96.\n2. Profit = 4 on a cost of 96 = 4/96 × 100 = **4.17%**.\n\nAnswer: **4.17%**.",
    approach: "The answer is slightly above 4% precisely because the cost is the smaller base. Reading 4% straight off is the intended mistake.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-gain-then-cost-rises",
    topic: "profit-and-loss",
    title: "When the cost rises but the price does not",
    prompt:
      "A trader makes a **20% profit**. If his **cost price rises by 25%** but he keeps the **selling price unchanged**, what is his new position?",
    options: ["4% loss", "5% loss", "No profit, no loss", "4% profit"],
    answer: 0,
    difficulty: "medium",
    hints: ["Take CP = 100, so SP = 120.", "The new cost is 125 against an unchanged sale of 120."],
    solution:
      "1. CP = 100, SP = 120.\n2. New CP = 125, SP still 120.\n3. Loss = 5 on a cost of 125 = **4% loss**.\n\nAnswer: **4% loss**.",
    approach: "Recompute the percentage against the *new* cost, not the old one. Taking 5 against the original 100 gives 5%, which is the offered trap.",
    tags: ["base change"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-mango-rate-for-profit",
    topic: "profit-and-loss",
    title: "New rate after a loss",
    prompt:
      "By selling mangoes at **₹12 per kg**, a seller **loses 20%**. At what rate per kg must he sell to make a **20% profit**?",
    options: ["₹15", "₹16", "₹18", "₹20"],
    answer: 2,
    difficulty: "medium",
    hints: ["Find the cost price first: 12 ÷ 0.8.", "Then add 20% to the cost."],
    solution:
      "1. CP = 12 ÷ 0.80 = ₹15 per kg.\n2. For a 20% profit, SP = 15 × 1.20 = **₹18 per kg**.\n\nAnswer: **₹18**.",
    approach: "Always route through the cost price: recover it from the first sale, then apply the new margin. Adding 40% to ₹12 directly gives ₹16.80 and is wrong.",
    tags: ["basics"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-sp-for-15-percent-gain",
    topic: "profit-and-loss",
    title: "From a 10% loss to a 15% gain",
    prompt:
      "An article sold for **₹1,080** results in a **loss of 10%**. What should the selling price be to gain **15%**?",
    options: ["₹1,320", "₹1,350", "₹1,380", "₹1,400"],
    answer: 2,
    difficulty: "medium",
    hints: ["CP = 1,080 ÷ 0.9.", "Then multiply the cost by 1.15."],
    solution:
      "1. CP = 1,080 ÷ 0.90 = ₹1,200.\n2. For a 15% gain, SP = 1,200 × 1.15 = **₹1,380**.\n\nAnswer: **₹1,380**.",
    approach: "Two steps, both through the cost price. Applying 25% to ₹1,080 to bridge from −10% to +15% is a common shortcut and a wrong one.",
    tags: ["basics"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-cheaper-purchase-condition",
    topic: "profit-and-loss",
    title: "Had he bought cheaper",
    prompt:
      "A man sells an article at a **profit of 10%**. Had he bought it for **10% less** and sold it for **₹35 less**, he would have gained **20%**. What was the **cost price**?",
    options: ["₹1,250", "₹1,400", "₹1,750", "₹2,000"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Let the cost be ₹x, so the original selling price is 1.1x.",
      "New cost = 0.9x, new selling price = 1.1x − 35, and that must be 1.2 × 0.9x.",
    ],
    solution:
      "1. Let CP = x. Original SP = 1.1x.\n2. New CP = 0.9x, and a 20% gain on it means SP = 1.2 × 0.9x = 1.08x.\n3. That new SP is also 1.1x − 35, so 1.1x − 35 = 1.08x.\n4. 0.02x = 35 → x = **₹1,750**.\n\nAnswer: **₹1,750**.",
    approach:
      "Express every quantity as a multiple of the unknown cost, then set the two expressions for the new selling price equal. The small coefficient (0.02) is why the answer is large.",
    tags: ["algebra"],
    timeTargetSec: 135,
  },
  {
    slug: "pl2-two-articles-no-net-gain",
    topic: "profit-and-loss",
    title: "Gain on one, loss on the other",
    prompt:
      "Two articles are bought for a total of **₹900**. One is sold at a **20% profit** and the other at a **10% loss**, and there is **no overall gain or loss**. What was the cost of the article sold at a profit?",
    options: ["₹300", "₹360", "₹450", "₹600"],
    answer: 0,
    difficulty: "hard",
    hints: ["Let its cost be ₹x; the other cost ₹(900 − x).", "For no net change, 0.20x must equal 0.10(900 − x)."],
    solution:
      "1. Let the first article cost ₹x, the second ₹(900 − x).\n2. Profit = 0.20x, loss = 0.10(900 − x), and these cancel.\n3. 0.20x = 90 − 0.10x → 0.30x = 90 → x = **₹300**.\n4. Check: profit 60 on ₹300, loss 60 on ₹600. ✓\n\nAnswer: **₹300**.",
    approach: "Set the rupee profit equal to the rupee loss, not the percentages. The article with the higher rate always turns out to be the cheaper one.",
    tags: ["algebra"],
    timeTargetSec: 105,
  },
  {
    slug: "pl2-damaged-items",
    topic: "profit-and-loss",
    title: "Some stock is unsellable",
    prompt:
      "A trader buys **100 items at ₹10 each**. **10 items** are damaged and cannot be sold; the rest are sold at **₹12 each**. What is his **profit percent**?",
    options: ["6%", "8%", "10%", "12%"],
    answer: 1,
    difficulty: "medium",
    hints: ["The cost covers all 100 items, damaged or not.", "Revenue comes from 90 items only."],
    solution:
      "1. Total cost = 100 × 10 = ₹1,000.\n2. Revenue = 90 × 12 = ₹1,080.\n3. Profit = 80 on 1,000 = **8%**.\n\nAnswer: **8%**.",
    approach: "Cost is incurred on everything bought; revenue only on what is sold. Computing the margin per sold item (20%) ignores the loss on the damaged stock.",
    tags: ["wastage"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-consignment-two-parts",
    topic: "profit-and-loss",
    title: "A consignment sold in two parts",
    prompt:
      "**Two-thirds** of a consignment was sold at a **5% profit** and the rest at a **2% loss**, giving an overall profit of **₹400**. What was the **value of the consignment**?",
    options: ["₹12,000", "₹15,000", "₹18,000", "₹20,000"],
    answer: 1,
    difficulty: "hard",
    hints: ["Let the consignment be worth ₹x.", "Net profit = (2/3)x × 0.05 − (1/3)x × 0.02."],
    solution:
      "1. Profit on two-thirds = (2/3)x × 0.05 = x/30.\n2. Loss on one-third = (1/3)x × 0.02 = x/150.\n3. Net = x/30 − x/150 = (5x − x)/150 = 4x/150 = 2x/75.\n4. 2x/75 = 400 → x = **₹15,000**.\n\nAnswer: **₹15,000**.",
    approach: "Weight each rate by the fraction of stock it applies to, subtract, and solve. Working in fractions rather than decimals keeps the arithmetic exact.",
    tags: ["weighted"],
    timeTargetSec: 120,
  },
  {
    slug: "pl2-markup-20-discount-10-gain-40",
    topic: "profit-and-loss",
    title: "Cost price from a rupee profit",
    prompt:
      "A trader marks goods **20% above cost** and gives a **10% discount**, making a profit of **₹40**. What was the **cost price**?",
    options: ["₹400", "₹500", "₹600", "₹800"],
    answer: 1,
    difficulty: "medium",
    hints: ["Find the profit percent first: 1.20 × 0.90.", "That is a gain of 8%, and 8% of the cost is ₹40."],
    solution:
      "1. Net factor = 1.20 × 0.90 = 1.08, a profit of 8%.\n2. 8% of CP = 40 → CP = 40 ÷ 0.08 = **₹500**.\n\nAnswer: **₹500**.",
    approach: "Convert the chain of percentages into a single profit rate, then use the rupee figure to unlock the base. One division at the end.",
    tags: ["marked price"],
    timeTargetSec: 75,
  },
  {
    slug: "pl2-buy-and-resell-twice",
    topic: "profit-and-loss",
    title: "Buying and selling twice",
    prompt:
      "A man buys an article for **₹100** and sells it for **₹120**. He then buys it back for **₹110** and sells it again for **₹130**. What is his **total profit**?",
    options: ["₹20", "₹30", "₹40", "₹50"],
    answer: 2,
    difficulty: "easy",
    hints: ["Treat the two transactions separately.", "20 on the first, 20 on the second."],
    solution:
      "1. First deal: 120 − 100 = ₹20 profit.\n2. Second deal: 130 − 110 = ₹20 profit.\n3. Total = **₹40**.\n\nAnswer: **₹40**.",
    approach:
      "Add the profit of each completed transaction. The buy-back price being higher than the first sale feels like a loss, but each deal stands on its own.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "pl2-sp-for-6000-at-15",
    topic: "profit-and-loss",
    title: "Selling price at 15% gain",
    prompt: "What is the **selling price** of an article costing **₹6,000** if it is sold at a **gain of 15%**?",
    options: ["₹6,600", "₹6,750", "₹6,900", "₹7,200"],
    answer: 2,
    difficulty: "easy",
    hints: ["SP = CP × 1.15.", "10% of 6,000 is 600 and 5% is 300."],
    solution: "1. Gain = 15% of 6,000 = 900.\n2. SP = 6,000 + 900 = **₹6,900**.\n\nAnswer: **₹6,900**.",
    approach: "Build the percentage from 10% and 5% blocks rather than multiplying by 1.15 directly. Faster to do in the head and easy to check.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pl2-cp-from-20-loss-400",
    topic: "profit-and-loss",
    title: "Cost from a 20% loss",
    prompt: "An article is sold for **₹400** at a **loss of 20%**. What is its **cost price**?",
    options: ["₹450", "₹480", "₹500", "₹520"],
    answer: 2,
    difficulty: "easy",
    hints: ["The sale recovers 80% of the cost.", "400 ÷ 0.8."],
    solution: "1. 0.80 × CP = 400.\n2. CP = 400 ÷ 0.80 = **₹500**.\n\nAnswer: **₹500**.",
    approach: "Divide by the surviving fraction. Adding 20% of the selling price gives 480 and is the standard error.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pl2-cp-of-10-equals-sp-of-8",
    topic: "profit-and-loss",
    title: "CP of 10 pens equals SP of 8",
    prompt: "If the **cost price of 10 pens equals the selling price of 8 pens**, what is the **profit percent**?",
    options: ["20%", "25%", "30%", "40%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let one pen cost ₹1, so 8 pens sell for ₹10.", "SP per pen = 10/8."],
    solution:
      "1. Let CP per pen = ₹1. Then 8 pens sell for ₹10, so SP per pen = ₹1.25.\n2. Profit = **25%**.\n\nAnswer: **25%**.",
    approach: "The (b − a)/a rule again, with b = 10 and a = 8. Pricing one unit at 1 makes every question of this shape identical.",
    tags: ["articles"],
    timeTargetSec: 60,
  },
  {
    slug: "pl2-equal-gain-loss-prices",
    topic: "profit-and-loss",
    title: "Loss at one price, gain at another",
    prompt:
      "A man selling an article for **₹21** loses as much as he would **gain by selling it for ₹33**. What is the **cost price**?",
    options: ["₹24", "₹25", "₹27", "₹30"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the cost be ₹c: the loss is c − 21 and the gain is 33 − c.", "Set them equal."],
    solution:
      "1. Loss at ₹21 = c − 21; gain at ₹33 = 33 − c.\n2. Equal, so c − 21 = 33 − c → 2c = 54 → c = **₹27**.\n3. The cost is the midpoint of the two prices. ✓\n\nAnswer: **₹27**.",
    approach: "When the loss at one price equals the gain at another, the cost price is exactly halfway between them. The average is the answer without any algebra.",
    tags: ["algebra"],
    timeTargetSec: 60,
  },
];
