import type { AptitudeSeed } from "./types.js";

/** Blood relations and direction sense — the standard reasoning set. */
export const BANK_RELATIONS_DIRECTIONS: AptitudeSeed[] = [
  /* ── Blood Relations ───────────────────────────────────────────── */
  {
    slug: "br2-only-daughter-of-my-mother",
    topic: "blood-relations",
    title: "His mother is my mother's only daughter",
    prompt:
      "Pointing to a man, a woman said, *'His mother is the only daughter of my mother.'* How is the **woman related to the man**?",
    options: ["Sister", "Aunt", "Mother", "Grandmother"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "'The only daughter of my mother' — could that be the speaker herself?",
      "If the woman is her mother's only daughter, that phrase means the woman.",
    ],
    solution:
      "1. 'The only daughter of my mother' is the speaker herself.\n2. So the man's mother is the woman.\n3. She is his **mother**.\n\nAnswer: **Mother**.",
    approach: "Resolve the innermost phrase first and replace it with one person. The word 'only' is what forces it back onto the speaker.",
    tags: ["photograph"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-no-brother-portrait",
    topic: "blood-relations",
    title: "I have no brother or sister",
    prompt:
      "Looking at a portrait, a man said, *'I have no brother or sister, but that man's father is my father's son.'* Whose portrait is it?",
    options: ["His own", "His son's", "His father's", "His nephew's"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "'My father's son' — with no brothers, who can that be?",
      "It is the speaker himself, so the man in the portrait has the speaker as his father.",
    ],
    solution:
      "1. Having no brothers, 'my father's son' must be the speaker himself.\n2. So the man in the portrait has the speaker as his father.\n3. The portrait is of **his son**.\n\nAnswer: **His son's**.",
    approach:
      "Substitute the resolved phrase back into the sentence and read it plainly: 'that man's father is me'. The relation then falls out immediately.",
    tags: ["photograph"],
    timeTargetSec: 90,
  },
  {
    slug: "br2-grandfathers-only-son",
    topic: "blood-relations",
    title: "My grandfather's only son",
    prompt:
      "Pointing to a lady, a man said, *'She is the daughter of my grandfather's only son.'* How is the **lady related to the man**?",
    options: ["Sister", "Cousin", "Niece", "Aunt"],
    answer: 0,
    difficulty: "medium",
    hints: ["Grandfather's only son is the speaker's father.", "His father's daughter is his sister."],
    solution:
      "1. The grandfather's only son is the speaker's father.\n2. The lady is his father's daughter.\n3. She is his **sister**.\n\nAnswer: **Sister**.",
    approach: "Work outwards one relation at a time, naming each person as you resolve them. Two steps settle most photograph questions.",
    tags: ["photograph"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-only-son-of-my-mothers-mother",
    topic: "blood-relations",
    title: "My mother's mother's only son",
    prompt:
      "Introducing a man, a woman said, *'He is the only son of my mother's mother.'* How is the **woman related to the man**?",
    options: ["Sister", "Niece", "Daughter", "Aunt"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Her mother's mother is her grandmother.",
      "The grandmother's only son is the woman's maternal uncle.",
    ],
    solution:
      "1. 'My mother's mother' is the woman's grandmother.\n2. That grandmother's only son is the woman's maternal uncle.\n3. So the woman is his **niece**.\n\nAnswer: **Niece**.",
    approach:
      "Note the direction the question asks for. The man is her uncle, so she is his niece — answering 'uncle' would be describing the wrong person.",
    tags: ["photograph"],
    timeTargetSec: 75,
  },
  {
    slug: "br2-fathers-brothers-son",
    topic: "blood-relations",
    title: "My father's brother's son",
    prompt: "How is your **father's brother's son** related to you?",
    options: ["Brother", "Cousin", "Uncle", "Nephew"],
    answer: 1,
    difficulty: "easy",
    hints: ["Father's brother is your paternal uncle.", "An uncle's son is a cousin, not a brother."],
    solution:
      "1. Father's brother = paternal uncle.\n2. His son is your **cousin**.\n3. A brother would have to share your own parents, not your uncle's.\n\nAnswer: **Cousin**.",
    approach: "Walk the chain one link at a time. A cousin is any child of a parent's sibling, on either side of the family.",
    tags: ["chain"],
    timeTargetSec: 40,
  },
  {
    slug: "br2-fathers-sisters-daughter",
    topic: "blood-relations",
    title: "My father's only sister's daughter",
    prompt:
      "Pointing to a girl, Rajan said, *'She is the daughter of the only sister of my father.'* How is the **girl related to Rajan**?",
    options: ["Sister", "Cousin", "Niece", "Aunt"],
    answer: 1,
    difficulty: "easy",
    hints: ["Father's sister is Rajan's aunt.", "The aunt's daughter is his cousin."],
    solution: "1. His father's sister is his paternal aunt.\n2. Her daughter is his **cousin**.\n\nAnswer: **Cousin**.",
    approach: "Aunt's or uncle's children are always cousins, whichever side of the family they come from.",
    tags: ["chain"],
    timeTargetSec: 45,
  },
  {
    slug: "br2-brother-of-sons-son",
    topic: "blood-relations",
    title: "Brother of Y's son's son",
    prompt: "If **X is the brother of the son of Y's son**, how is **X related to Y**?",
    options: ["Son", "Grandson", "Nephew", "Brother"],
    answer: 1,
    difficulty: "medium",
    hints: ["Y's son's son is Y's grandson.", "The brother of a grandson is also a grandson."],
    solution:
      "1. Y's son's son is Y's grandson.\n2. X is that grandson's brother, so X is also a child of Y's son.\n3. X is Y's **grandson**.\n\nAnswer: **Grandson**.",
    approach: "Read the phrase from the inside out. Siblings share a generation, so a brother of a grandson is another grandson.",
    tags: ["chain"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-p-q-r-s-t-chain",
    topic: "blood-relations",
    title: "A four-generation chain",
    prompt:
      "**P is Q's brother**, **R is Q's mother**, **S is R's father** and **T is S's mother**. How is **P related to T**?",
    options: ["Grandson", "Great-grandson", "Son", "Nephew"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Work up the generations: R is Q's mother, S is R's father.",
      "So S is Q's grandfather and T is Q's great-grandmother.",
    ],
    solution:
      "1. R is Q's mother; S is R's father, so S is Q's grandfather.\n2. T is S's mother, so T is Q's great-grandmother.\n3. P is Q's brother, so T is P's great-grandmother too.\n4. P is T's **great-grandson**.\n\nAnswer: **Great-grandson**.",
    approach:
      "Draw the generations as a column, oldest at the top. Siblings sit on the same line, so what holds for one holds for the other.",
    tags: ["family tree"],
    timeTargetSec: 105,
  },
  {
    slug: "br2-e-related-to-c",
    topic: "blood-relations",
    title: "How is E related to C",
    prompt:
      "**A is B's brother**, **C is D's father**, **E is B's mother**, and **A and D are brothers**. How is **E related to C**?",
    options: ["Sister", "Wife", "Daughter", "Mother"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "A, B and D are all siblings.",
      "E is the mother of all three, and C is D's father.",
    ],
    solution:
      "1. A is B's brother and A and D are brothers, so A, B and D are siblings.\n2. E is B's mother, so E is the mother of all three, including D.\n3. C is D's father, so C and E are D's parents.\n4. E is C's **wife**.\n\nAnswer: **Wife**.",
    approach: "Collect the siblings first, then identify the shared parents. Two people who are both parents of the same child are spouses.",
    tags: ["family tree"],
    timeTargetSec: 105,
  },
  {
    slug: "br2-deepak-ravi-rekha",
    topic: "blood-relations",
    title: "Deepak, Ravi and Rekha",
    prompt:
      "**Deepak is the brother of Ravi**, **Rekha is the sister of Atul**, and **Ravi is the son of Rekha**. How is **Deepak related to Rekha**?",
    options: ["Son", "Brother", "Nephew", "Husband"],
    answer: 0,
    difficulty: "medium",
    hints: ["Ravi is Rekha's son.", "Deepak is Ravi's brother, so he shares Ravi's parents."],
    solution:
      "1. Ravi is Rekha's son.\n2. Deepak is Ravi's brother, so Deepak is also Rekha's child.\n3. Deepak is Rekha's **son**.\n\nAnswer: **Son**.",
    approach: "A sibling relation transfers parenthood: whoever is the parent of one brother is the parent of the other.",
    tags: ["family tree"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-atul-to-deepak",
    topic: "blood-relations",
    title: "Atul and Deepak",
    prompt:
      "**Deepak is the brother of Ravi**, **Rekha is the sister of Atul**, and **Ravi is the son of Rekha**. How is **Atul related to Deepak**?",
    options: ["Father", "Brother", "Maternal uncle", "Cousin"],
    answer: 2,
    difficulty: "medium",
    hints: ["Deepak is Rekha's son.", "Atul is Rekha's brother, so he is the mother's brother."],
    solution:
      "1. Deepak is Rekha's son (as Ravi's brother).\n2. Atul is Rekha's brother.\n3. So Atul is Deepak's mother's brother — his **maternal uncle**.\n\nAnswer: **Maternal uncle**.",
    approach: "A mother's brother is the maternal uncle; a father's brother is the paternal uncle. Papers often distinguish the two.",
    tags: ["family tree"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-a-mother-father-is-b-father",
    topic: "blood-relations",
    title: "A shared grandfather",
    prompt: "**A's mother's father is B's father.** How is **A related to B**?",
    options: ["Son or daughter", "Nephew or niece", "Brother or sister", "Cousin"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "A's mother's father is A's grandfather.",
      "If that man is also B's father, then A's mother and B are siblings.",
    ],
    solution:
      "1. A's mother's father is A's maternal grandfather.\n2. He is also B's father, so A's mother and B are brother and sister.\n3. A is therefore the child of B's sibling — B's **nephew or niece**.\n\nAnswer: **Nephew or niece**.",
    approach:
      "When two chains meet at one person, the people either side of them are siblings. From there the answer is one more generation down.",
    tags: ["family tree"],
    timeTargetSec: 105,
  },
  {
    slug: "br2-ravi-mother-only-daughter",
    topic: "blood-relations",
    title: "Ravi's mother and Rani",
    prompt:
      "**Ravi's mother is the only daughter of Rani's father.** How is **Rani related to Ravi**?",
    options: ["Aunt", "Sister", "Mother", "Grandmother"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "The only daughter of Rani's father must be Rani herself.",
      "So Ravi's mother is Rani.",
    ],
    solution:
      "1. Rani's father has only one daughter, and Rani is his daughter — so that daughter is Rani.\n2. Ravi's mother is therefore Rani.\n3. Rani is Ravi's **mother**.\n\nAnswer: **Mother**.",
    approach: "The word 'only' collapses the phrase onto the person named in it. Watch for that whenever a relation is described as unique.",
    tags: ["photograph"],
    timeTargetSec: 75,
  },
  {
    slug: "br2-girl-no-sister-no-daughter",
    topic: "blood-relations",
    title: "She has no sister or daughter",
    prompt:
      "Pointing to a photograph of a girl, Rajesh said, *'She has no sister or daughter, but her mother is the only daughter of my mother.'* How is the **girl related to Rajesh**?",
    options: ["Daughter", "Niece", "Sister", "Cousin"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "'The only daughter of my mother' is Rajesh's sister.",
      "So the girl's mother is Rajesh's sister.",
    ],
    solution:
      "1. The only daughter of Rajesh's mother is Rajesh's sister (Rajesh is male, so it is not himself).\n2. The girl's mother is that sister.\n3. The girl is Rajesh's sister's daughter — his **niece**.\n\nAnswer: **Niece**.",
    approach:
      "Compare with the version where the speaker is a woman: there the phrase resolves to the speaker herself. The speaker's own sex decides it.",
    tags: ["photograph"],
    timeTargetSec: 105,
  },
  {
    slug: "br2-nephew-maternal-grandmother",
    topic: "blood-relations",
    title: "My nephew's maternal grandmother",
    prompt:
      "A man pointing to a photograph says, *'The lady in the photograph is my nephew's maternal grandmother.'* How is the lady related to the **man's sister**, who has no other sister?",
    options: ["Mother", "Aunt", "Sister", "Grandmother"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "The nephew's maternal grandmother is the mother of the nephew's mother.",
      "The man's nephew is his sister's son, so the nephew's mother is that sister.",
    ],
    solution:
      "1. The nephew is the son of the man's sister, so the nephew's mother is that sister.\n2. The lady is the mother of the nephew's mother, that is the sister's mother.\n3. So the lady is the sister's **mother**.\n\nAnswer: **Mother**.",
    approach: "Identify who the intermediate person is before resolving the outer relation. 'Maternal grandmother' always means the mother's mother.",
    tags: ["photograph"],
    timeTargetSec: 120,
  },
  {
    slug: "br2-x-y-z-w",
    topic: "blood-relations",
    title: "X, Y, Z and W",
    prompt:
      "**X is Y's father**, **Z is Y's sister** and **W is Z's mother**. How is **X related to W**?",
    options: ["Brother", "Father", "Husband", "Son"],
    answer: 2,
    difficulty: "medium",
    hints: ["Y and Z are siblings.", "X is their father and W is their mother."],
    solution:
      "1. Z is Y's sister, so they share parents.\n2. X is their father and W is their mother.\n3. X is W's **husband**.\n\nAnswer: **Husband**.",
    approach: "Two people identified as the father and mother of the same children are spouses. The sibling link is what joins the two statements.",
    tags: ["family tree"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-m-n-o-p",
    topic: "blood-relations",
    title: "M, N, O and P",
    prompt:
      "**M is the sister of N**, **N is the brother of O**, and **O is the daughter of P**. How is **M related to P**?",
    options: ["Son", "Daughter", "Sister", "Mother"],
    answer: 1,
    difficulty: "easy",
    hints: ["M, N and O are all siblings.", "O is P's daughter, so P is the parent of all three."],
    solution:
      "1. M, N and O are siblings.\n2. O is P's daughter, so P is their parent.\n3. M is female (she is a sister), so M is P's **daughter**.\n\nAnswer: **Daughter**.",
    approach: "Chain the sibling links first, then attach the parent. The sex of the person asked about decides between son and daughter.",
    tags: ["family tree"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-a-b-c-d-brother",
    topic: "blood-relations",
    title: "D and A",
    prompt:
      "**A is B's daughter**, **B is C's mother** and **D is C's brother**. How is **D related to A**?",
    options: ["Father", "Brother", "Uncle", "Son"],
    answer: 1,
    difficulty: "medium",
    hints: ["A and C are both children of B.", "D is C's brother, so D shares the same parents."],
    solution:
      "1. A is B's daughter and C is B's child, so A and C are siblings.\n2. D is C's brother, so D is also B's child.\n3. D is A's **brother**.\n\nAnswer: **Brother**.",
    approach: "Everyone traced back to the same parent is a sibling. Watch for the trap of reading D as belonging to a different generation.",
    tags: ["family tree"],
    timeTargetSec: 75,
  },
  {
    slug: "br2-symbols-mother-sister",
    topic: "blood-relations",
    title: "Relations written as symbols",
    prompt:
      "If **A + B** means *A is the mother of B* and **A × B** means *A is the sister of B*, what does **P + Q × R** mean?",
    options: ["P is the mother of R", "P is the sister of R", "P is the aunt of R", "P is the grandmother of R"],
    answer: 0,
    difficulty: "medium",
    hints: ["Read it left to right: P is the mother of Q, and Q is the sister of R.", "Q and R share the same mother."],
    solution:
      "1. P + Q: P is the mother of Q.\n2. Q × R: Q is the sister of R, so Q and R have the same parents.\n3. Therefore P is also R's mother: **P is the mother of R**.\n\nAnswer: **P is the mother of R**.",
    approach: "Translate each symbol into a sentence, then combine. A sibling link passes a parent relation across to the sibling.",
    tags: ["symbols"],
    timeTargetSec: 75,
  },
  {
    slug: "br2-symbols-father-brother",
    topic: "blood-relations",
    title: "Another symbol chain",
    prompt:
      "If **A − B** means *A is the brother of B* and **A × B** means *A is the father of B*, what does **P × Q − R** mean?",
    options: ["P is the father of R", "P is the brother of R", "P is the uncle of R", "P is the son of R"],
    answer: 0,
    difficulty: "medium",
    hints: ["P is the father of Q, and Q is the brother of R.", "Brothers share a father."],
    solution:
      "1. P × Q: P is the father of Q.\n2. Q − R: Q is the brother of R, so they share parents.\n3. So P is also R's father: **P is the father of R**.\n\nAnswer: **P is the father of R**.",
    approach: "The same principle as before with different symbols. Always re-read which letter stands for which relation before starting.",
    tags: ["symbols"],
    timeTargetSec: 75,
  },
  {
    slug: "br2-wife-son-husband",
    topic: "blood-relations",
    title: "Q and R",
    prompt: "If **P is the wife of Q** and **R is the son of P**, how is **Q related to R**?",
    options: ["Brother", "Father", "Uncle", "Son"],
    answer: 1,
    difficulty: "easy",
    hints: ["P is R's mother.", "Q is married to P."],
    solution: "1. R is P's son, so P is R's mother.\n2. Q is P's husband, so Q is R's **father**.\n\nAnswer: **Father**.",
    approach: "The spouse of a parent is the other parent. Two short steps and the relation is settled.",
    tags: ["chain"],
    timeTargetSec: 45,
  },
  {
    slug: "br2-bindu-mahipal",
    topic: "blood-relations",
    title: "Bindu and Mahipal",
    prompt:
      "Neena says, *'Anita's father Raman is the only son of my father-in-law Mahipal.'* How is **Bindu**, who is Anita's sister, related to **Mahipal**?",
    options: ["Daughter", "Granddaughter", "Niece", "Sister-in-law"],
    answer: 1,
    difficulty: "medium",
    hints: ["Raman is Mahipal's only son.", "Anita and Bindu are Raman's daughters."],
    solution:
      "1. Raman is Mahipal's son.\n2. Anita is Raman's daughter, and Bindu is Anita's sister, so Bindu is also Raman's daughter.\n3. Bindu is Mahipal's **granddaughter**.\n\nAnswer: **Granddaughter**.",
    approach: "Neena's own position is a distraction: the chain from Bindu to Mahipal runs entirely through Raman.",
    tags: ["family tree"],
    timeTargetSec: 90,
  },
  {
    slug: "br2-b-related-to-d",
    topic: "blood-relations",
    title: "B and D",
    prompt:
      "**B is the husband of P**. **Q is the only grandson of E**, who is the **wife of D** and the **mother-in-law of P**. How is **B related to D**?",
    options: ["Son", "Son-in-law", "Nephew", "Brother"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "E is P's mother-in-law, so E is the mother of P's husband.",
      "P's husband is B, so B is E's son — and E is D's wife.",
    ],
    solution:
      "1. E is P's mother-in-law, so E is the mother of P's spouse.\n2. P's spouse is B, so B is E's son.\n3. E is D's wife, so D is B's father.\n4. B is D's **son**.\n\nAnswer: **Son**.",
    approach: "Mother-in-law of P means mother of P's husband. Resolving that one phrase unlocks the whole chain.",
    tags: ["family tree"],
    timeTargetSec: 120,
  },
  {
    slug: "br2-son-of-my-fathers-sons-son",
    topic: "blood-relations",
    title: "That man's son",
    prompt:
      "A woman said, *'The son of that man is my father's son's son.'* How is the **man related to the woman**?",
    options: ["Father", "Brother", "Uncle", "Cousin"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The woman is female, so 'my father's son' is her brother.",
      "Her brother's son is her nephew, and that nephew is the man's son.",
    ],
    solution:
      "1. 'My father's son' is the woman's brother.\n2. So her father's son's son is her brother's son, that is her nephew.\n3. The man's son is that nephew, so the man is the woman's brother.\n\nAnswer: **Brother**.",
    approach:
      "Resolve from the inside out, and use the speaker's sex: a woman cannot be her father's son, so the phrase must mean her brother.",
    tags: ["photograph"],
    timeTargetSec: 120,
  },
  {
    slug: "br2-boy-son-of-daughter",
    topic: "blood-relations",
    title: "The son of the daughter of my uncle's father",
    prompt:
      "Introducing a boy, a girl said, *'He is the son of the daughter of the father of my uncle.'* How is the **boy related to the girl**?",
    options: ["Brother", "Nephew", "Uncle", "Son-in-law"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "The father of her uncle is her grandfather.",
      "Her grandfather's daughter is her mother (or an aunt); the son of her mother is her brother.",
    ],
    solution:
      "1. The father of the girl's uncle is her grandfather.\n2. The grandfather's daughter is the girl's mother.\n3. The son of her mother is her **brother**.\n\nAnswer: **Brother**.",
    approach: "Three nested relations, resolved one at a time from the innermost. Naming each person as you go keeps the chain straight.",
    tags: ["photograph"],
    timeTargetSec: 120,
  },
  {
    slug: "br2-a-father-b-c-daughter",
    topic: "blood-relations",
    title: "Four generations",
    prompt:
      "**A is the father of B**, **C is the daughter of B**, and **E is the son of C**. How is **E related to A**?",
    options: ["Grandson", "Great-grandson", "Son", "Nephew"],
    answer: 1,
    difficulty: "medium",
    hints: ["Count the generations: A, then B, then C, then E.", "That is three steps down from A."],
    solution:
      "1. A → B is one generation, B → C is two, C → E is three.\n2. Three generations below A makes E his **great-grandson**.\n\nAnswer: **Great-grandson**.",
    approach: "Count the parent-child links: one is a child, two a grandchild, three a great-grandchild.",
    tags: ["family tree"],
    timeTargetSec: 60,
  },
  {
    slug: "br2-that-woman-mother-brother-daughter",
    topic: "blood-relations",
    title: "My mother's brother's daughter again",
    prompt:
      "Pointing to a woman, a man said, *'She is the daughter of my mother's only brother.'* How is the **man related to the woman**?",
    options: ["Brother", "Cousin", "Uncle", "Nephew"],
    answer: 1,
    difficulty: "easy",
    hints: ["His mother's brother is his maternal uncle.", "The uncle's daughter is his cousin, and the relation is mutual."],
    solution:
      "1. His mother's brother is his maternal uncle.\n2. That uncle's daughter is his cousin.\n3. Cousinhood runs both ways, so the man is her **cousin**.\n\nAnswer: **Cousin**.",
    approach: "Cousin is a symmetric relation, unlike uncle or niece. Check whether the relation the question asks for needs reversing.",
    tags: ["chain"],
    timeTargetSec: 50,
  },

  /* ── Direction Sense ───────────────────────────────────────────── */
  {
    slug: "ds2-north-then-east",
    topic: "direction-sense",
    title: "North then east",
    prompt: "A man walks **4 km north**, then **3 km east**. How **far** is he from his starting point?",
    options: ["5 km", "6 km", "7 km", "12 km"],
    answer: 0,
    difficulty: "easy",
    hints: ["The two legs are at right angles.", "√(4² + 3²)."],
    solution: "1. The displacement is the hypotenuse: √(16 + 9) = √25 = **5 km**.\n\nAnswer: **5 km**.",
    approach: "Perpendicular legs mean Pythagoras. Watch for the 3-4-5 family, which needs no square root at all.",
    tags: ["pythagoras"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-three-four-hypotenuse",
    topic: "direction-sense",
    title: "North then west",
    prompt: "A woman cycles **3 km north** and then **4 km west**. How far is she from her starting point?",
    options: ["1 km", "5 km", "7 km", "25 km"],
    answer: 1,
    difficulty: "easy",
    hints: ["The legs are perpendicular.", "√(9 + 16)."],
    solution: "1. Displacement = √(3² + 4²) = √25 = **5 km**.\n\nAnswer: **5 km**.",
    approach: "The direction of each leg does not affect the distance, only the final bearing. Any two perpendicular legs of 3 and 4 give 5.",
    tags: ["pythagoras"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-south-left-left",
    topic: "direction-sense",
    title: "South, then two left turns",
    prompt:
      "A man walks **5 km south**, turns **left** and walks **3 km**, then turns **left** and walks **5 km**. How far is he from the start and in which direction?",
    options: ["3 km east", "3 km west", "5 km east", "8 km east"],
    answer: 0,
    difficulty: "medium",
    hints: ["Facing south, a left turn faces east.", "The two 5 km legs cancel out."],
    solution:
      "1. South 5 km, then left (east) 3 km, then left (north) 5 km.\n2. The southward and northward 5 km cancel.\n3. He is **3 km east** of the start.\n\nAnswer: **3 km east**.",
    approach: "Track the north–south and east–west totals separately. Opposite legs of equal length cancel entirely.",
    tags: ["displacement"],
    timeTargetSec: 60,
  },
  {
    slug: "ds2-north-left-left",
    topic: "direction-sense",
    title: "North, then two left turns",
    prompt:
      "A man goes **5 km north**, turns **left** and goes **3 km**, then turns **left** and goes **5 km**. Where is he relative to the start?",
    options: ["3 km east", "3 km west", "5 km west", "8 km west"],
    answer: 1,
    difficulty: "medium",
    hints: ["Facing north, a left turn faces west.", "The 5 km legs cancel."],
    solution:
      "1. North 5 km, then left (west) 3 km, then left (south) 5 km.\n2. North and south cancel.\n3. He is **3 km west** of the start.\n\nAnswer: **3 km west**.",
    approach: "The mirror of the previous question. Getting the first turn right decides everything that follows.",
    tags: ["displacement"],
    timeTargetSec: 60,
  },
  {
    slug: "ds2-rectangle-back-to-start",
    topic: "direction-sense",
    title: "Round a rectangle",
    prompt:
      "A person walks **20 m north**, **30 m east**, **20 m south** and **30 m west**. How far is he from the starting point?",
    options: ["0 m", "20 m", "30 m", "50 m"],
    answer: 0,
    difficulty: "easy",
    hints: ["Each leg is cancelled by its opposite.", "He has walked a closed rectangle."],
    solution:
      "1. North 20 and south 20 cancel; east 30 and west 30 cancel.\n2. He is back where he started, so the distance is **0 m**.\n\nAnswer: **0 m**.",
    approach: "Opposite legs of equal length always cancel. Distance travelled (100 m) and displacement (0 m) are different questions.",
    tags: ["displacement"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-north-east-south",
    topic: "direction-sense",
    title: "Two of three legs cancel",
    prompt: "A boy walks **15 m north**, **20 m east** and **15 m south**. How far is he from the start?",
    options: ["15 m", "20 m", "35 m", "50 m"],
    answer: 1,
    difficulty: "easy",
    hints: ["The north and south legs are equal.", "Only the eastward leg is left."],
    solution: "1. North 15 and south 15 cancel.\n2. He is **20 m** east of the start.\n\nAnswer: **20 m**.",
    approach: "Add up each axis separately before reaching for Pythagoras. Often one axis cancels and no square root is needed.",
    tags: ["displacement"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-six-eight-legs",
    topic: "direction-sense",
    title: "Six north, eight east, six south",
    prompt: "A man walks **6 m north**, **8 m east** and **6 m south**. How far is he from his starting point?",
    options: ["6 m", "8 m", "10 m", "14 m"],
    answer: 1,
    difficulty: "easy",
    hints: ["The north and south legs cancel.", "Only the 8 m east remains."],
    solution: "1. The 6 m north and 6 m south cancel.\n2. Distance = **8 m**.\n\nAnswer: **8 m**.",
    approach: "The 6-8-10 triangle is offered as a distractor, but only one axis has any net movement here.",
    tags: ["displacement"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-west-right-right-left",
    topic: "direction-sense",
    title: "A zig-zag walk",
    prompt:
      "Ravi walks **10 m west**, turns **right** and walks **5 m**, turns **right** and walks **10 m**, then turns **left** and walks **5 m**. Where is he relative to the start?",
    options: ["10 m north", "10 m east", "5 m north", "20 m north"],
    answer: 0,
    difficulty: "hard",
    hints: [
      "Facing west, a right turn faces north.",
      "Track the east–west and north–south totals separately.",
    ],
    solution:
      "1. West 10 m; right → north 5 m; right → east 10 m; left → north 5 m.\n2. East–west: 10 west and 10 east cancel.\n3. North–south: 5 + 5 = 10 m north.\n4. He is **10 m north** of the start.\n\nAnswer: **10 m north**.",
    approach: "Write the direction of each leg before adding anything. A right turn from west is north; a left turn from east is also north.",
    tags: ["displacement"],
    timeTargetSec: 105,
  },
  {
    slug: "ds2-diagonal-walk",
    topic: "direction-sense",
    title: "Two easts and two norths",
    prompt:
      "A man walks **1 km east**, **1 km north**, **1 km east** and **1 km north**. How far is he from his starting point?",
    options: ["2 km", "2√2 km", "4 km", "√2 km"],
    answer: 1,
    difficulty: "medium",
    hints: ["Total east = 2 km, total north = 2 km.", "√(2² + 2²)."],
    solution:
      "1. East total = 2 km; north total = 2 km.\n2. Distance = √(4 + 4) = √8 = **2√2 km** (about 2.83 km).\n\nAnswer: **2√2 km**.",
    approach: "Sum each axis first, then apply Pythagoras once. Equal totals on both axes always give a multiple of √2.",
    tags: ["pythagoras"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-two-villages",
    topic: "direction-sense",
    title: "Distance between two villages",
    prompt:
      "Village **A is 10 km north of B**, and village **C is 10 km east of B**. What is the distance from **A to C**?",
    options: ["10 km", "10√2 km", "20 km", "14 km"],
    answer: 1,
    difficulty: "medium",
    hints: ["A and C are at right angles as seen from B.", "√(10² + 10²)."],
    solution:
      "1. AB and BC are perpendicular, each 10 km.\n2. AC = √(100 + 100) = √200 = **10√2 km** (about 14.14 km).\n\nAnswer: **10√2 km**.",
    approach: "Sketch the three points before computing. Equal perpendicular legs of length a give a diagonal of a√2.",
    tags: ["pythagoras"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-two-men-apart",
    topic: "direction-sense",
    title: "Two men walking apart",
    prompt:
      "Two men start from the same point. One walks **4 km north** and the other **3 km east**. How far apart are they?",
    options: ["1 km", "5 km", "7 km", "12 km"],
    answer: 1,
    difficulty: "easy",
    hints: ["Their paths are at right angles.", "√(16 + 9)."],
    solution: "1. Distance apart = √(4² + 3²) = **5 km**.\n\nAnswer: **5 km**.",
    approach: "Two perpendicular displacements from a common start form a right triangle whose hypotenuse is the gap between them.",
    tags: ["pythagoras"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-two-buses-diagonal",
    topic: "direction-sense",
    title: "Two buses in opposite quadrants",
    prompt:
      "Two buses leave the same depot. One goes **30 km north then 40 km east**; the other goes **40 km south then 30 km west**. How far apart are they?",
    options: ["70 km", "70√2 km", "100 km", "140 km"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Give the depot coordinates (0, 0) with east positive and north positive.",
      "The buses end at (40, 30) and (−30, −40).",
    ],
    solution:
      "1. First bus ends at (40, 30); second at (−30, −40).\n2. Differences: 70 east–west and 70 north–south.\n3. Distance = √(70² + 70²) = **70√2 km** (about 98.99 km).\n\nAnswer: **70√2 km**.",
    approach: "Coordinates are safer than sketching once the paths bend more than once. Sum each axis, then apply Pythagoras to the differences.",
    tags: ["pythagoras"],
    timeTargetSec: 120,
  },
  {
    slug: "ds2-facing-north-right-right-left",
    topic: "direction-sense",
    title: "Three turns from north",
    prompt:
      "A man facing **north** turns **right**, then **right** again, then **left**. Which direction is he facing now?",
    options: ["North", "South", "East", "West"],
    answer: 2,
    difficulty: "easy",
    hints: ["Facing north, a right turn faces east.", "Take one turn at a time."],
    solution:
      "1. North → right → **east**.\n2. East → right → **south**.\n3. South → left → **east**.\n\nAnswer: **East**.",
    approach: "Right turns run N → E → S → W; left turns run the same list backwards. Name the new direction aloud after each turn.",
    tags: ["turns"],
    timeTargetSec: 50,
  },
  {
    slug: "ds2-facing-south-clockwise",
    topic: "direction-sense",
    title: "Ninety then one hundred and eighty",
    prompt:
      "A person facing **south** turns **90° clockwise** and then **180°**. Which direction is he facing?",
    options: ["North", "South", "East", "West"],
    answer: 2,
    difficulty: "medium",
    hints: ["Facing south, 90° clockwise faces west.", "A further 180° reverses that."],
    solution:
      "1. South, turned 90° clockwise, faces **west**.\n2. A further 180° turn reverses it to **east**.\n\nAnswer: **East**.",
    approach: "Convert degrees into quarter turns: 90° is one, 180° is two. Clockwise follows N → E → S → W.",
    tags: ["turns"],
    timeTargetSec: 60,
  },
  {
    slug: "ds2-facing-west-180-right",
    topic: "direction-sense",
    title: "About turn, then right",
    prompt: "A man facing **west** turns **180°** and then turns **right**. Which direction does he face?",
    options: ["North", "South", "East", "West"],
    answer: 1,
    difficulty: "easy",
    hints: ["180° from west is east.", "Facing east, a right turn faces south."],
    solution: "1. West → 180° → **east**.\n2. East → right → **south**.\n\nAnswer: **South**.",
    approach: "A 180° turn always gives the opposite direction. Then apply the quarter turn from there.",
    tags: ["turns"],
    timeTargetSec: 45,
  },
  {
    slug: "ds2-facing-east-45-degrees",
    topic: "direction-sense",
    title: "Two forty-five degree turns",
    prompt:
      "A man facing **east** turns **45° clockwise twice**, then **90° anticlockwise**. Which direction is he facing?",
    options: ["North", "South", "East", "West"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Two 45° clockwise turns make one 90° clockwise turn.",
      "That is then undone by the 90° anticlockwise turn.",
    ],
    solution:
      "1. East, turned 45° clockwise twice, is 90° clockwise: **south**.\n2. A 90° anticlockwise turn from south returns to **east**.\n\nAnswer: **East**.",
    approach: "Combine the turns into one net rotation before applying it. Here they cancel exactly, so the final direction is the starting one.",
    tags: ["turns"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-shadow-sunrise-left",
    topic: "direction-sense",
    title: "Shadow on the left at sunrise",
    prompt: "At **sunrise**, a man's shadow falls to his **left**. Which direction is he facing?",
    options: ["North", "South", "East", "West"],
    answer: 1,
    difficulty: "medium",
    hints: ["At sunrise the sun is in the east, so shadows point west.", "If west is on his left, what is ahead?"],
    solution:
      "1. The sun rises in the east, so shadows fall towards the west.\n2. West is on his left, so facing that way means south is ahead.\n3. He faces **south**.\n\nAnswer: **South**.",
    approach: "Fix the sun's side first, so the shadow points the opposite way. Then rotate yourself until the shadow lands where the question puts it.",
    tags: ["shadows"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-shadow-sunset-right",
    topic: "direction-sense",
    title: "Shadow on the right at sunset",
    prompt: "At **sunset**, a boy's shadow falls to his **right**. Which direction is he facing?",
    options: ["North", "South", "East", "West"],
    answer: 0,
    difficulty: "medium",
    hints: ["At sunset the sun is in the west, so shadows point east.", "East is on his right."],
    solution:
      "1. The sun sets in the west, so shadows fall towards the east.\n2. East is on his right, which means he faces **north**.\n\nAnswer: **North**.",
    approach: "Sunrise casts shadows west, sunset casts them east. Everything else is a matter of orienting yourself correctly.",
    tags: ["shadows"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-a-south-of-b-c-east",
    topic: "direction-sense",
    title: "Relative bearing of two places",
    prompt: "**A is south of B** and **C is east of B**. In which direction is **A from C**?",
    options: ["North-east", "North-west", "South-east", "South-west"],
    answer: 3,
    difficulty: "medium",
    hints: [
      "Put B at the origin: A is below it and C is to its right.",
      "From C, A lies both to the left and below.",
    ],
    solution:
      "1. Take B at the origin. A is directly south of B; C is directly east of B.\n2. From C, A is to the west and to the south.\n3. So A is **south-west** of C.\n\nAnswer: **South-west**.",
    approach: "Sketch the points on a grid before answering. The bearing from C to A is the opposite of the bearing from A to C.",
    tags: ["bearings"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-rotation-north-becomes-east",
    topic: "direction-sense",
    title: "A rotated compass",
    prompt:
      "If **north becomes east** and **east becomes south**, what does **south-west** become?",
    options: ["North-east", "North-west", "South-east", "South-west"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "North → east is a 90° clockwise rotation of the whole compass.",
      "Apply the same 90° clockwise turn to south-west.",
    ],
    solution:
      "1. North becoming east is a rotation of 90° clockwise.\n2. Rotating south-west by 90° clockwise gives **north-west**.\n3. (Check: south → west and west → north under the same rotation.)\n\nAnswer: **North-west**.",
    approach:
      "Work out the single rotation the mapping describes, then apply it to whatever direction is asked. Testing it on a second known pair confirms the angle.",
    tags: ["bearings"],
    timeTargetSec: 105,
  },
  {
    slug: "ds2-rotation-southeast-becomes-north",
    topic: "direction-sense",
    title: "A larger rotation",
    prompt: "If **south-east becomes north** and **north-east becomes west**, what does **west** become?",
    options: ["North-east", "North-west", "South-east", "South-west"],
    answer: 2,
    difficulty: "hard",
    hints: [
      "Write the compass in degrees: N 0°, NE 45°, E 90°, SE 135°, S 180°, SW 225°, W 270°, NW 315°.",
      "South-east (135°) becoming north (0°) is a rotation of 135° anticlockwise.",
      "Check it on the second pair before applying it to west.",
    ],
    solution:
      "1. South-east is 135° and north is 0°, so the mapping subtracts 135°.\n2. Check on the second pair: north-east (45°) − 135° = −90°, which is 270° — that is west. ✓\n3. West (270°) − 135° = 135°, which is **south-east**.\n\nAnswer: **South-east**.",
    approach:
      "Assign compass bearings in degrees and treat the mapping as a fixed rotation. Verifying on the second given pair guards against getting the direction of rotation wrong.",
    tags: ["bearings"],
    timeTargetSec: 120,
  },
  {
    slug: "ds2-clock-hands-direction",
    topic: "direction-sense",
    title: "Clock hands as directions",
    prompt:
      "At **3 o'clock**, the **minute hand points north**. Which direction does the **hour hand** point?",
    options: ["North", "South", "East", "West"],
    answer: 2,
    difficulty: "medium",
    hints: ["At 3 o'clock the minute hand is on 12 and the hour hand on 3.", "If 12 is north, 3 is a quarter turn clockwise."],
    solution:
      "1. At 3 o'clock the minute hand is at 12 (north) and the hour hand at 3.\n2. Three is a quarter turn clockwise from twelve, which is **east**.\n\nAnswer: **East**.",
    approach: "Map the clock face onto the compass: 12 is north, 3 is east, 6 is south and 9 is west when the minute hand starts at north.",
    tags: ["clocks"],
    timeTargetSec: 60,
  },
  {
    slug: "ds2-anil-net-direction",
    topic: "direction-sense",
    title: "Which direction from home",
    prompt:
      "Anil walks **10 m south** from home, turns **left** and walks **10 m**, turns **right** and walks **5 m**, then turns **right** and walks **10 m**. In which direction is he from home?",
    options: ["North", "South", "East", "West"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Facing south, a left turn faces east.",
      "Add the north–south and east–west movements separately.",
    ],
    solution:
      "1. South 10; left → east 10; right → south 5; right → west 10.\n2. East–west: 10 east and 10 west cancel.\n3. North–south: 10 + 5 = 15 m south.\n4. He is due **south** of home.\n\nAnswer: **South**.",
    approach: "Label each leg with its compass direction before totalling. The turns matter only for working out those labels.",
    tags: ["displacement"],
    timeTargetSec: 105,
  },
  {
    slug: "ds2-northwest-clockwise",
    topic: "direction-sense",
    title: "Turning from north-west",
    prompt: "A man facing **north-west** turns **90° clockwise**. Which direction does he face?",
    options: ["North-east", "South-east", "South-west", "North"],
    answer: 0,
    difficulty: "medium",
    hints: ["North-west is 315° on the compass.", "Adding 90° clockwise gives 405°, which is 45°."],
    solution:
      "1. North-west is at 315°.\n2. A 90° clockwise turn gives 315 + 90 = 405°, which is the same as 45°.\n3. That is **north-east**.\n\nAnswer: **North-east**.",
    approach: "Use degrees for the diagonal directions: NE 45°, SE 135°, SW 225°, NW 315°. Subtract 360 whenever the total passes a full turn.",
    tags: ["turns"],
    timeTargetSec: 75,
  },
  {
    slug: "ds2-square-perimeter-walk",
    topic: "direction-sense",
    title: "Three sides of a square",
    prompt:
      "A man walks **8 m east**, turns **left** and walks **8 m**, then turns **left** and walks **8 m**. How far is he from the start?",
    options: ["8 m", "8√2 m", "16 m", "24 m"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "The legs run east, north and west.",
      "The east and west legs cancel, leaving only the northward one.",
    ],
    solution:
      "1. East 8; left → north 8; left → west 8.\n2. East and west cancel, leaving 8 m north.\n3. He is **8 m** from the start.\n\nAnswer: **8 m**.",
    approach: "Three equal sides of a square leave you exactly one side-length away from the start, at right angles to where you began.",
    tags: ["displacement"],
    timeTargetSec: 60,
  },
];
