import type { AptitudeSeed } from "./types.js";

/** Time, speed and distance, with trains, boats and races. */
export const BANK_TSD: AptitudeSeed[] = [
  {
    slug: "tsd2-convert-ms-to-kmh",
    topic: "time-speed-distance",
    title: "Converting m/s to km/h",
    prompt: "A speed of **20 m/s** is equal to how many **km/h**?",
    options: ["54 km/h", "60 km/h", "72 km/h", "80 km/h"],
    answer: 2,
    difficulty: "easy",
    hints: ["Multiply by 18/5 to go from m/s to km/h.", "20 × 18/5."],
    solution: "1. m/s → km/h means multiplying by 18/5.\n2. 20 × 18/5 = **72 km/h**.\n\nAnswer: **72 km/h**.",
    approach: "m/s to km/h: multiply by 18/5. km/h to m/s: multiply by 5/18. Getting the direction wrong is the single most common error in this chapter.",
    tags: ["units"],
    timeTargetSec: 35,
  },
  {
    slug: "tsd2-train-crosses-pole",
    topic: "time-speed-distance",
    title: "A train crosses a pole",
    prompt: "A train **180 m long** crosses a pole in **12 seconds**. What is its **speed**?",
    options: ["48 km/h", "54 km/h", "60 km/h", "72 km/h"],
    answer: 1,
    difficulty: "easy",
    hints: ["Crossing a pole means covering just the train's own length.", "15 m/s, then convert."],
    solution:
      "1. Distance = 180 m in 12 s → 15 m/s.\n2. 15 × 18/5 = **54 km/h**.\n\nAnswer: **54 km/h**.",
    approach: "A pole, a person or a signal post has no length, so the train covers only itself. A platform or bridge adds its own length.",
    tags: ["trains"],
    timeTargetSec: 45,
  },
  {
    slug: "tsd2-train-crosses-bridge",
    topic: "time-speed-distance",
    title: "A train crosses a bridge",
    prompt:
      "A train **150 m long** running at **72 km/h** crosses a bridge **250 m long**. How long does it take?",
    options: ["15 s", "18 s", "20 s", "24 s"],
    answer: 2,
    difficulty: "medium",
    hints: ["Total distance = train length + bridge length.", "72 km/h = 20 m/s."],
    solution:
      "1. Distance = 150 + 250 = 400 m.\n2. Speed = 72 × 5/18 = 20 m/s.\n3. Time = 400 ÷ 20 = **20 s**.\n\nAnswer: **20 s**.",
    approach: "Convert the speed to m/s first so that every quantity is in metres and seconds. Then it is one division.",
    tags: ["trains"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-platform-length",
    topic: "time-speed-distance",
    title: "Length of the platform",
    prompt:
      "A train **120 m long** travelling at **54 km/h** crosses a platform in **20 seconds**. What is the **length of the platform**?",
    options: ["150 m", "180 m", "200 m", "220 m"],
    answer: 1,
    difficulty: "medium",
    hints: ["54 km/h = 15 m/s, so in 20 s it covers 300 m.", "That 300 m is the train plus the platform."],
    solution:
      "1. Speed = 54 × 5/18 = 15 m/s; distance in 20 s = 300 m.\n2. Platform = 300 − 120 = **180 m**.\n\nAnswer: **180 m**.",
    approach: "Total distance covered minus the train's own length gives the platform. Forgetting to subtract gives 300, which is why the arithmetic must be laid out.",
    tags: ["trains"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-two-trains-opposite",
    topic: "time-speed-distance",
    title: "Two trains passing each other",
    prompt:
      "Two trains **140 m and 160 m long** run **towards each other** at **60 km/h and 48 km/h**. How long do they take to **cross each other**?",
    options: ["8 s", "10 s", "12 s", "15 s"],
    answer: 1,
    difficulty: "medium",
    hints: ["Opposite directions: add the speeds.", "108 km/h = 30 m/s, and the distance is 300 m."],
    solution:
      "1. Relative speed = 60 + 48 = 108 km/h = 108 × 5/18 = 30 m/s.\n2. Distance = 140 + 160 = 300 m.\n3. Time = 300 ÷ 30 = **10 s**.\n\nAnswer: **10 s**.",
    approach: "Opposite directions add speeds, same direction subtracts them. The distance to clear is always the sum of both lengths.",
    tags: ["trains", "relative speed"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-two-trains-same-direction",
    topic: "time-speed-distance",
    title: "One train overtaking another",
    prompt:
      "Two trains **100 m and 150 m long** run in the **same direction** at **72 km/h and 54 km/h**. How long does the faster take to **completely overtake** the slower?",
    options: ["30 s", "40 s", "50 s", "60 s"],
    answer: 2,
    difficulty: "medium",
    hints: ["Same direction: subtract the speeds.", "18 km/h = 5 m/s, and the distance is 250 m."],
    solution:
      "1. Relative speed = 72 − 54 = 18 km/h = 5 m/s.\n2. Distance = 100 + 150 = 250 m.\n3. Time = 250 ÷ 5 = **50 s**.\n\nAnswer: **50 s**.",
    approach: "Overtaking uses the difference of speeds, which is small, so overtaking always takes far longer than crossing head-on.",
    tags: ["trains", "relative speed"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-train-passes-man",
    topic: "time-speed-distance",
    title: "A train passes a running man",
    prompt:
      "A train **150 m long** running at **68 km/h** passes a man running at **8 km/h** in the **same direction**. How long does it take?",
    options: ["7 s", "8 s", "9 s", "10 s"],
    answer: 2,
    difficulty: "medium",
    hints: ["Same direction, so relative speed = 68 − 8 = 60 km/h.", "The man has no length, so the distance is 150 m."],
    solution:
      "1. Relative speed = 60 km/h = 60 × 5/18 = 50/3 m/s.\n2. Time = 150 ÷ (50/3) = 150 × 3/50 = **9 s**.\n\nAnswer: **9 s**.",
    approach: "A person contributes no length. Use the relative speed and the train's length alone.",
    tags: ["trains", "relative speed"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-average-speed-round-trip",
    topic: "time-speed-distance",
    title: "Average speed there and back",
    prompt:
      "A man goes from A to B at **40 km/h** and returns at **60 km/h**. What is his **average speed** for the whole journey?",
    options: ["45 km/h", "48 km/h", "50 km/h", "52 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Average speed is total distance ÷ total time, not the mean of the speeds.", "For equal distances use 2ab/(a + b)."],
    solution:
      "1. Take the distance as 120 km each way. Times: 120/40 = 3 h and 120/60 = 2 h.\n2. Total = 240 km in 5 h.\n3. Average = **48 km/h**, matching 2 × 40 × 60/100.\n\nAnswer: **48 km/h**.",
    approach:
      "Equal distances give the harmonic mean 2ab/(a + b), always below the arithmetic mean. Equal *times* would give the arithmetic mean of 50 instead.",
    tags: ["average speed"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-three-equal-parts",
    topic: "time-speed-distance",
    title: "A journey in three equal parts",
    prompt:
      "A man covers **equal distances** at **10, 20 and 60 km/h**. What is his **average speed** for the whole journey?",
    options: ["18 km/h", "20 km/h", "24 km/h", "30 km/h"],
    answer: 0,
    difficulty: "hard",
    hints: ["Take each part as 60 km so the times are whole numbers.", "Times are 6, 3 and 1 hours for 180 km."],
    solution:
      "1. Take each stretch as 60 km. Times: 6 h, 3 h and 1 h.\n2. Total = 180 km in 10 h.\n3. Average = **18 km/h**.\n\nAnswer: **18 km/h**.",
    approach:
      "For equal distances the average is the harmonic mean 3/(1/10 + 1/20 + 1/60). Choosing the LCM of the speeds as the distance makes every time a whole number.",
    tags: ["average speed"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-late-and-early",
    topic: "time-speed-distance",
    title: "Late at one speed, early at another",
    prompt:
      "Walking at **4 km/h** a man reaches his office **10 minutes late**; at **6 km/h** he arrives **5 minutes early**. How **far** is the office?",
    options: ["2 km", "3 km", "4 km", "5 km"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The two journeys differ in time by 10 + 5 = 15 minutes.",
      "d/4 − d/6 = 15/60 hours.",
    ],
    solution:
      "1. Time difference = 15 min = 1/4 hour.\n2. d/4 − d/6 = 1/4 → d(3 − 2)/12 = 1/4 → d/12 = 1/4.\n3. d = **3 km**.\n4. Check: 45 min at 4 km/h and 30 min at 6 km/h, a difference of 15 min. ✓\n\nAnswer: **3 km**.",
    approach:
      "Late by a and early by b means the two trips differ by (a + b) in time. The scheduled arrival time never has to be found.",
    tags: ["late early"],
    timeTargetSec: 120,
  },
  {
    slug: "tsd2-late-late",
    topic: "time-speed-distance",
    title: "Late at both speeds",
    prompt:
      "A boy walking at **5 km/h** reaches school **6 minutes late**; walking at **6 km/h** he is **2 minutes late**. How **far** is the school?",
    options: ["1 km", "1.5 km", "2 km", "2.5 km"],
    answer: 2,
    difficulty: "hard",
    hints: ["The difference in lateness is 4 minutes.", "d/5 − d/6 = 4/60 hours."],
    solution:
      "1. Difference in time = 6 − 2 = 4 min = 1/15 hour.\n2. d/5 − d/6 = 1/15 → d(6 − 5)/30 = 1/15 → d/30 = 1/15.\n3. d = **2 km**.\n\nAnswer: **2 km**.",
    approach: "When both cases are late, subtract the lateness figures rather than adding them. Only one is early would mean adding.",
    tags: ["late early"],
    timeTargetSec: 120,
  },
  {
    slug: "tsd2-boat-downstream-upstream",
    topic: "time-speed-distance",
    title: "Downstream and upstream speeds",
    prompt:
      "A boat's speed in **still water is 15 km/h** and the **stream flows at 3 km/h**. What are its **downstream and upstream speeds**?",
    options: ["12 and 18 km/h", "15 and 3 km/h", "18 and 12 km/h", "18 and 15 km/h"],
    answer: 2,
    difficulty: "easy",
    hints: ["Downstream the stream helps; upstream it hinders.", "15 + 3 and 15 − 3."],
    solution:
      "1. Downstream = 15 + 3 = 18 km/h.\n2. Upstream = 15 − 3 = 12 km/h.\n\nAnswer: **18 and 12 km/h**.",
    approach: "Downstream = boat + stream, upstream = boat − stream. Keep the order the question asks for.",
    tags: ["boats and streams"],
    timeTargetSec: 40,
  },
  {
    slug: "tsd2-boat-from-two-speeds",
    topic: "time-speed-distance",
    title: "Boat and stream from two speeds",
    prompt:
      "A boat goes **downstream at 16 km/h** and **upstream at 10 km/h**. What is the **speed of the boat in still water** and of the **stream**?",
    options: ["12 and 4 km/h", "13 and 3 km/h", "14 and 2 km/h", "15 and 1 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["The boat's speed is the average of the two.", "The stream's speed is half the difference."],
    solution:
      "1. Boat = (16 + 10)/2 = 13 km/h.\n2. Stream = (16 − 10)/2 = 3 km/h.\n\nAnswer: **13 and 3 km/h**.",
    approach: "Boat = (down + up)/2 and stream = (down − up)/2. These two formulas answer most boat questions immediately.",
    tags: ["boats and streams"],
    timeTargetSec: 50,
  },
  {
    slug: "tsd2-boat-round-trip-time",
    topic: "time-speed-distance",
    title: "A round trip on the river",
    prompt:
      "A boat whose speed in still water is **10 km/h** travels **24 km downstream and back** on a stream flowing at **2 km/h**. How long does the whole trip take?",
    options: ["4 h", "5 h", "6 h", "7 h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Downstream 12 km/h, upstream 8 km/h.", "24/12 + 24/8."],
    solution:
      "1. Downstream = 12 km/h → 24/12 = 2 h.\n2. Upstream = 8 km/h → 24/8 = 3 h.\n3. Total = **5 hours**.\n\nAnswer: **5 h**.",
    approach: "Compute each leg separately and add. The upstream leg always takes longer, so the total exceeds twice the still-water time.",
    tags: ["boats and streams"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-boat-still-water-from-times",
    topic: "time-speed-distance",
    title: "Still-water speed from two times",
    prompt:
      "A man rows **30 km downstream in 2 hours** and the **same distance upstream in 6 hours**. What is his speed in **still water**?",
    options: ["8 km/h", "10 km/h", "12 km/h", "15 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Downstream speed = 30/2, upstream = 30/6.", "Still water = the average of the two."],
    solution:
      "1. Downstream = 15 km/h; upstream = 5 km/h.\n2. Still water = (15 + 5)/2 = **10 km/h**.\n\nAnswer: **10 km/h**.",
    approach: "Convert both legs to speeds before averaging. Averaging the times instead is meaningless.",
    tags: ["boats and streams"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-distance-from-speed-time",
    topic: "time-speed-distance",
    title: "Distance from speed and time",
    prompt: "A car travels at **60 km/h** for **2 hours 30 minutes**. How **far** does it go?",
    options: ["120 km", "140 km", "150 km", "180 km"],
    answer: 2,
    difficulty: "easy",
    hints: ["Convert the time to hours: 2.5.", "60 × 2.5."],
    solution: "1. Time = 2.5 hours.\n2. Distance = 60 × 2.5 = **150 km**.\n\nAnswer: **150 km**.",
    approach: "Express time as a decimal or fraction of an hour before multiplying. Treating 2 h 30 min as 2.30 gives 138 and is wrong.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "tsd2-time-from-distance-speed",
    topic: "time-speed-distance",
    title: "Time for a journey",
    prompt: "How long does a train take to cover **330 km** at **55 km/h**?",
    options: ["5 h", "6 h", "6.5 h", "7 h"],
    answer: 1,
    difficulty: "easy",
    hints: ["Time = distance ÷ speed.", "330 ÷ 55."],
    solution: "1. Time = 330 ÷ 55 = **6 hours**.\n\nAnswer: **6 h**.",
    approach: "The three quantities are linked by distance = speed × time; rearrange for whichever is missing.",
    tags: ["basics"],
    timeTargetSec: 35,
  },
  {
    slug: "tsd2-increase-speed-save-time",
    topic: "time-speed-distance",
    title: "Raising the speed to save time",
    prompt:
      "A man covers a distance in **6 hours at 40 km/h**. At what speed must he travel to cover it in **4 hours**?",
    options: ["50 km/h", "55 km/h", "60 km/h", "65 km/h"],
    answer: 2,
    difficulty: "easy",
    hints: ["Find the distance first: 240 km.", "240 ÷ 4."],
    solution: "1. Distance = 40 × 6 = 240 km.\n2. Required speed = 240 ÷ 4 = **60 km/h**.\n\nAnswer: **60 km/h**.",
    approach: "Speed and time are inversely proportional for a fixed distance: two-thirds the time needs three-halves the speed.",
    tags: ["basics"],
    timeTargetSec: 45,
  },
  {
    slug: "tsd2-two-thirds-distance",
    topic: "time-speed-distance",
    title: "Two speeds on one journey",
    prompt:
      "A man travels **the first 60 km at 30 km/h** and the **next 60 km at 60 km/h**. What is his **average speed**?",
    options: ["36 km/h", "40 km/h", "45 km/h", "50 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Times: 2 hours and 1 hour.", "120 km in 3 hours."],
    solution:
      "1. Times: 60/30 = 2 h and 60/60 = 1 h.\n2. Total = 120 km in 3 h.\n3. Average = **40 km/h**.\n\nAnswer: **40 km/h**.",
    approach: "Equal distances again, so the harmonic mean 2 × 30 × 60/90 = 40 applies. The arithmetic mean of 45 is offered as the trap.",
    tags: ["average speed"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-relative-speed-catch-up",
    topic: "time-speed-distance",
    title: "Catching up",
    prompt:
      "A thief runs at **10 km/h** and a policeman **100 metres behind** chases at **12 km/h**. How long does the policeman take to **catch him**?",
    options: ["2 min", "3 min", "4 min", "5 min"],
    answer: 1,
    difficulty: "medium",
    hints: ["Relative speed = 12 − 10 = 2 km/h.", "Convert 100 m to km and divide."],
    solution:
      "1. Relative speed = 2 km/h.\n2. Gap = 100 m = 0.1 km.\n3. Time = 0.1 ÷ 2 = 0.05 h = **3 minutes**.\n\nAnswer: **3 min**.",
    approach: "Chasing uses the difference of speeds. Keep the gap and the speed in the same units before dividing, then convert the answer to minutes.",
    tags: ["relative speed"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-two-trains-meet",
    topic: "time-speed-distance",
    title: "Two trains meeting",
    prompt:
      "Two trains start at the same time from stations **330 km apart** and travel **towards each other** at **60 km/h and 50 km/h**. After how long do they **meet**?",
    options: ["2 h", "3 h", "4 h", "5 h"],
    answer: 1,
    difficulty: "easy",
    hints: ["They close the gap at the sum of their speeds.", "330 ÷ 110."],
    solution: "1. Closing speed = 60 + 50 = 110 km/h.\n2. Time = 330 ÷ 110 = **3 hours**.\n\nAnswer: **3 h**.",
    approach: "Approaching objects close the gap at the sum of their speeds. The meeting point is not needed unless the question asks for it.",
    tags: ["relative speed"],
    timeTargetSec: 45,
  },
  {
    slug: "tsd2-meeting-point-distance",
    topic: "time-speed-distance",
    title: "Where they meet",
    prompt:
      "Two trains **300 km apart** move towards each other at **40 km/h and 60 km/h**. How far from the **first station** do they meet?",
    options: ["100 km", "120 km", "150 km", "180 km"],
    answer: 1,
    difficulty: "medium",
    hints: ["Find the time to meet first: 300 ÷ 100.", "Then multiply by the first train's speed."],
    solution:
      "1. Closing speed = 100 km/h, so they meet after 300 ÷ 100 = 3 hours.\n2. The first train covers 40 × 3 = **120 km**.\n\nAnswer: **120 km**.",
    approach: "Find the meeting time first, then apply it to whichever train the question names. The two distances must add to the original gap.",
    tags: ["relative speed"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-race-head-start",
    topic: "time-speed-distance",
    title: "A race with a head start",
    prompt:
      "In a **100 m race** A beats B by **10 metres**. If A's speed is **10 m/s**, what is **B's speed**?",
    options: ["8 m/s", "9 m/s", "9.5 m/s", "10 m/s"],
    answer: 1,
    difficulty: "medium",
    hints: ["A finishes 100 m in 10 seconds.", "In that time B covers only 90 m."],
    solution:
      "1. A takes 100 ÷ 10 = 10 seconds.\n2. In 10 seconds B covers 90 m.\n3. B's speed = 90 ÷ 10 = **9 m/s**.\n\nAnswer: **9 m/s**.",
    approach: "'Beats by 10 metres' means that when the winner finishes, the loser is 10 m short. Both are compared over the same time, not the same distance.",
    tags: ["races"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-race-beats-by-time",
    topic: "time-speed-distance",
    title: "Beaten by a distance and a time",
    prompt:
      "In a **200 m race** A beats B by **20 metres** or **5 seconds**. What is **A's time** for the race?",
    options: ["40 s", "45 s", "50 s", "55 s"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "B covers the last 20 m in 5 seconds, so B's speed is 4 m/s.",
      "B takes 200 ÷ 4 = 50 s, and A is 5 s faster.",
    ],
    solution:
      "1. B covers 20 m in 5 s, so B's speed = 4 m/s.\n2. B's time for 200 m = 200 ÷ 4 = 50 s.\n3. A beats B by 5 s, so A takes 50 − 5 = **45 s**.\n\nAnswer: **45 s**.",
    approach:
      "'Beats by d metres or t seconds' means the loser needs t seconds to cover the last d metres. That gives the loser's speed, from which everything else follows.",
    tags: ["races"],
    timeTargetSec: 120,
  },
  {
    slug: "tsd2-circular-track-same-direction",
    topic: "time-speed-distance",
    title: "Meeting on a circular track",
    prompt:
      "Two runners on a **400 m circular track** run in the **same direction** at **5 m/s and 3 m/s**. After how long do they **first meet again**?",
    options: ["100 s", "150 s", "200 s", "250 s"],
    answer: 2,
    difficulty: "medium",
    hints: ["The faster must gain a full lap on the slower.", "Relative speed 2 m/s over 400 m."],
    solution:
      "1. Relative speed = 5 − 3 = 2 m/s.\n2. To meet, the faster must gain 400 m.\n3. Time = 400 ÷ 2 = **200 s**.\n\nAnswer: **200 s**.",
    approach: "Same direction on a circular track: the gap to close is one full lap at the difference of the speeds. Opposite directions would use the sum.",
    tags: ["circular track"],
    timeTargetSec: 75,
  },
  {
    slug: "tsd2-circular-track-opposite",
    topic: "time-speed-distance",
    title: "Opposite directions on a track",
    prompt:
      "Two runners start together on a **600 m circular track** in **opposite directions** at **4 m/s and 6 m/s**. After how long do they **first meet**?",
    options: ["50 s", "60 s", "75 s", "100 s"],
    answer: 1,
    difficulty: "medium",
    hints: ["Opposite directions: add the speeds.", "They together cover one full lap."],
    solution:
      "1. Closing speed = 4 + 6 = 10 m/s.\n2. Together they must cover one lap of 600 m.\n3. Time = 600 ÷ 10 = **60 s**.\n\nAnswer: **60 s**.",
    approach: "Opposite directions close the lap at the sum of the speeds. Note they meet somewhere on the track, not at the starting point.",
    tags: ["circular track"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd2-speed-reduced-time-increase",
    topic: "time-speed-distance",
    title: "A slower speed costs time",
    prompt:
      "A train travelling at **60 km/h** reaches its destination on time. If it runs at **50 km/h** it arrives **20 minutes late**. What is the **distance**?",
    options: ["80 km", "90 km", "100 km", "120 km"],
    answer: 2,
    difficulty: "hard",
    hints: ["Let the distance be d.", "d/50 − d/60 = 20/60 hours."],
    solution:
      "1. d/50 − d/60 = 1/3 hour.\n2. Common denominator 300: (6d − 5d)/300 = 1/3 → d/300 = 1/3.\n3. d = **100 km**.\n\nAnswer: **100 km**.",
    approach: "Set the difference of the two times equal to the delay. Working in hours throughout avoids a unit slip at the end.",
    tags: ["late early"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-walk-and-ride",
    topic: "time-speed-distance",
    title: "Walking one way, riding the other",
    prompt:
      "A man **walks to a place and rides back**, taking **5 hours 45 minutes** in all. He could have **ridden both ways in 4 hours**. How long would he take to **walk both ways**?",
    options: ["6 h", "6 h 30 min", "7 h", "7 h 30 min"],
    answer: 3,
    difficulty: "hard",
    hints: [
      "Riding both ways takes 4 h, so one ride is 2 h.",
      "Walk + ride = 5 h 45 min, so one walk is 3 h 45 min.",
    ],
    solution:
      "1. Riding both ways = 4 h, so one ride = 2 h.\n2. Walk + ride = 5 h 45 min, so one walk = 5 h 45 min − 2 h = 3 h 45 min.\n3. Walking both ways = 2 × 3 h 45 min = **7 h 30 min**.\n\nAnswer: **7 h 30 min**.",
    approach: "Halve the both-ways time to get one leg, subtract to get the other leg, then double it. No speeds or distances are ever needed.",
    tags: ["wordy"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-stoppage-time",
    topic: "time-speed-distance",
    title: "Stoppages on a bus route",
    prompt:
      "A bus **without stoppages** averages **54 km/h**, and **with stoppages 45 km/h**. For how many **minutes per hour** does the bus stop?",
    options: ["8 min", "10 min", "12 min", "15 min"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "In one hour it loses 9 km of distance because of stopping.",
      "At 54 km/h, covering 9 km takes 9/54 of an hour.",
    ],
    solution:
      "1. Distance lost per hour = 54 − 45 = 9 km.\n2. Time to cover 9 km at the running speed = 9/54 h = 1/6 h.\n3. That is **10 minutes** per hour.\n\nAnswer: **10 min**.",
    approach: "Stoppage time per hour = (difference in speeds) ÷ (speed without stoppages), expressed in minutes. The running speed is always the divisor.",
    tags: ["stoppages"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-man-covers-half-at",
    topic: "time-speed-distance",
    title: "Half the distance at each speed",
    prompt:
      "A man covers **half a journey at 30 km/h** and the **other half at 20 km/h**, taking **10 hours** in all. What is the **total distance**?",
    options: ["200 km", "220 km", "240 km", "260 km"],
    answer: 2,
    difficulty: "hard",
    hints: ["Let the total distance be d; each half is d/2.", "(d/2)/30 + (d/2)/20 = 10."],
    solution:
      "1. (d/2)/30 + (d/2)/20 = 10 → d/60 + d/40 = 10.\n2. Common denominator 120: 2d/120 + 3d/120 = 10 → 5d/120 = 10.\n3. d = 240, so the journey is **240 km**.\n\nAnswer: **240 km**.",
    approach:
      "Write the time for each half in terms of the whole distance and add. The average speed here is 24 km/h, and 24 × 10 = 240 confirms it.",
    tags: ["average speed"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-train-speed-from-two-poles",
    topic: "time-speed-distance",
    title: "Two trains, one pole",
    prompt:
      "A train **passes a pole in 15 seconds** and a **platform 100 m long in 25 seconds**. What is the **length of the train**?",
    options: ["120 m", "150 m", "180 m", "200 m"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Let the train's length be L and its speed v.",
      "L = 15v and L + 100 = 25v; subtract.",
    ],
    solution:
      "1. L = 15v and L + 100 = 25v.\n2. Subtracting: 100 = 10v → v = 10 m/s.\n3. L = 15 × 10 = **150 m**.\n\nAnswer: **150 m**.",
    approach:
      "Two crossing times give two equations in length and speed. Subtracting eliminates the length and hands you the speed immediately.",
    tags: ["trains"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-speed-ratio-time-ratio",
    topic: "time-speed-distance",
    title: "Ratio of speeds to ratio of times",
    prompt:
      "The **speeds of two cars are in the ratio 4 : 5**. What is the ratio of the **times** they take to cover the **same distance**?",
    options: ["4 : 5", "5 : 4", "16 : 25", "25 : 16"],
    answer: 1,
    difficulty: "easy",
    hints: ["Speed and time are inversely proportional for a fixed distance.", "Invert the ratio."],
    solution:
      "1. For the same distance, time ∝ 1/speed.\n2. So the times are in the ratio 1/4 : 1/5 = **5 : 4**.\n\nAnswer: **5 : 4**.",
    approach: "Inverting a ratio is not the same as reversing the numbers in general, but for two terms it is. The faster car takes the smaller time.",
    tags: ["ratio"],
    timeTargetSec: 45,
  },
  {
    slug: "tsd2-two-cars-different-times",
    topic: "time-speed-distance",
    title: "Two cars, same road",
    prompt:
      "Two cars cover the **same distance**, one at **45 km/h** and the other at **60 km/h**. The slower takes **1 hour longer**. What is the **distance**?",
    options: ["120 km", "150 km", "180 km", "200 km"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the distance be d.", "d/45 − d/60 = 1."],
    solution:
      "1. d/45 − d/60 = 1.\n2. Common denominator 180: 4d/180 − 3d/180 = 1 → d/180 = 1.\n3. d = **180 km**.\n\nAnswer: **180 km**.",
    approach: "Difference of times equals the stated delay. The common denominator of the two speeds is usually the distance itself, which is a handy check.",
    tags: ["late early"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-cyclist-and-walker",
    topic: "time-speed-distance",
    title: "A cyclist overtakes a walker",
    prompt:
      "A walker leaves at **6 a.m. at 5 km/h**. A cyclist leaves the same point at **8 a.m. at 15 km/h** along the same road. At what **time** does the cyclist catch up?",
    options: ["8:30 a.m.", "9:00 a.m.", "9:30 a.m.", "10:00 a.m."],
    answer: 1,
    difficulty: "hard",
    hints: [
      "By 8 a.m. the walker is 10 km ahead.",
      "The cyclist closes at 15 − 5 = 10 km/h.",
    ],
    solution:
      "1. In two hours the walker covers 5 × 2 = 10 km.\n2. Closing speed = 15 − 5 = 10 km/h, so the gap closes in 10 ÷ 10 = 1 hour.\n3. The cyclist catches up at **9:00 a.m.**\n\nAnswer: **9:00 a.m.**",
    approach: "Compute the head start in distance, then divide by the relative speed. Add the result to the later departure time, not to the earlier one.",
    tags: ["relative speed"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-boat-time-ratio",
    topic: "time-speed-distance",
    title: "Upstream takes twice as long",
    prompt:
      "A man takes **twice as long to row upstream as downstream**. If the **stream flows at 3 km/h**, what is his speed in **still water**?",
    options: ["6 km/h", "9 km/h", "12 km/h", "15 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Twice the time means half the speed, so downstream = 2 × upstream.",
      "(b + 3) = 2(b − 3).",
    ],
    solution:
      "1. Twice the time upstream means the downstream speed is twice the upstream speed.\n2. b + 3 = 2(b − 3) = 2b − 6 → b = **9 km/h**.\n3. Check: downstream 12, upstream 6 — indeed a 2 : 1 ratio. ✓\n\nAnswer: **9 km/h**.",
    approach: "Convert the ratio of times into the inverse ratio of speeds first. Setting up the equation on times directly works too but is more error-prone.",
    tags: ["boats and streams"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-train-length-two-speeds",
    topic: "time-speed-distance",
    title: "A train and two people",
    prompt:
      "A train passes two people walking in the **same direction** at **2 km/h and 4 km/h** in **9 and 10 seconds** respectively. What is the **speed of the train**?",
    options: ["20 km/h", "22 km/h", "24 km/h", "26 km/h"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "The train's length is the same in both cases.",
      "L = 9 × (v − 2) × 5/18 and L = 10 × (v − 4) × 5/18; equate them.",
    ],
    solution:
      "1. Length L = 9(v − 2) × 5/18 = 10(v − 4) × 5/18.\n2. Cancelling 5/18: 9(v − 2) = 10(v − 4) → 9v − 18 = 10v − 40.\n3. v = **22 km/h**.\n\nAnswer: **22 km/h**.",
    approach: "The train's length is the invariant. Write it twice using the two relative speeds and equate; the unit conversion cancels out entirely.",
    tags: ["trains", "relative speed"],
    timeTargetSec: 135,
  },
  {
    slug: "tsd2-distance-covered-in-minutes",
    topic: "time-speed-distance",
    title: "Distance in minutes",
    prompt: "A cyclist rides at **18 km/h**. How far does he travel in **40 minutes**?",
    options: ["9 km", "10 km", "12 km", "15 km"],
    answer: 2,
    difficulty: "easy",
    hints: ["40 minutes is 2/3 of an hour.", "18 × 2/3."],
    solution: "1. Time = 40/60 = 2/3 hour.\n2. Distance = 18 × 2/3 = **12 km**.\n\nAnswer: **12 km**.",
    approach: "Convert minutes to a fraction of an hour before multiplying. Fractions are safer than decimals when the minutes are not a round tenth.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "tsd2-two-thirds-time-remaining",
    topic: "time-speed-distance",
    title: "Making up lost time",
    prompt:
      "A man covers **two-thirds of a 120 km journey at 20 km/h**. At what **speed** must he cover the rest to complete the whole journey in **5 hours**?",
    options: ["30 km/h", "35 km/h", "40 km/h", "45 km/h"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Two-thirds of 120 km is 80 km, which takes 4 hours at 20 km/h.",
      "That leaves 40 km and only 1 hour.",
    ],
    solution:
      "1. First stretch: 80 km at 20 km/h = 4 hours.\n2. Remaining distance = 40 km, remaining time = 5 − 4 = 1 hour.\n3. Required speed = 40 ÷ 1 = **40 km/h**.\n\nAnswer: **40 km/h**.",
    approach: "Compute the time already used, subtract it from the time allowed, then divide the remaining distance by the remaining time.",
    tags: ["basics"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-escalator-walking",
    topic: "time-speed-distance",
    title: "Walking up a moving escalator",
    prompt:
      "A man walking up a **stationary escalator** takes **90 seconds**. The escalator moving with him standing still takes **60 seconds**. How long does he take **walking up the moving escalator**?",
    options: ["30 s", "36 s", "45 s", "50 s"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Add the two rates: 1/90 + 1/60 of the escalator per second.",
      "Take the escalator as 180 units so both rates are whole numbers.",
    ],
    solution:
      "1. Take the escalator as 180 steps. Walking alone: 2 steps/s. Escalator alone: 3 steps/s.\n2. Together: 5 steps/s.\n3. Time = 180 ÷ 5 = **36 s**.\n\nAnswer: **36 s**.",
    approach:
      "An escalator problem is a time-and-work problem in disguise: the man and the escalator are two workers whose rates add. Take the length as the LCM of the two times.",
    tags: ["escalator"],
    timeTargetSec: 120,
  },
  {
    slug: "tsd2-sound-and-distance",
    topic: "time-speed-distance",
    title: "Two speeds, one round trip",
    prompt:
      "A man goes to a place at **12 km/h** and returns at **8 km/h**, taking **10 hours** in all. What is the **one-way distance**?",
    options: ["36 km", "42 km", "48 km", "54 km"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the one-way distance be d.", "d/12 + d/8 = 10."],
    solution:
      "1. d/12 + d/8 = 10.\n2. Common denominator 24: 2d/24 + 3d/24 = 10 → 5d/24 = 10.\n3. d = **48 km**.\n\nAnswer: **48 km**.",
    approach: "Add the two leg times and equate to the total. The answer is the one-way distance, so do not double it unless asked.",
    tags: ["average speed"],
    timeTargetSec: 90,
  },
  {
    slug: "tsd2-fraction-of-speed-late",
    topic: "time-speed-distance",
    title: "Travelling at a fraction of the usual speed",
    prompt:
      "Walking at **three-quarters of his usual speed**, a man reaches his office **20 minutes late**. What is his **usual time** for the journey?",
    options: ["45 min", "60 min", "75 min", "90 min"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "Three-quarters the speed means four-thirds the time.",
      "The extra one-third of the usual time is the 20 minutes lost.",
    ],
    solution:
      "1. Speed × time is constant, so at 3/4 speed the time becomes 4/3 of usual.\n2. Extra time = (4/3 − 1) × usual = (1/3) × usual = 20 min.\n3. Usual time = **60 minutes**.\n\nAnswer: **60 min**.",
    approach:
      "At a fraction a/b of the usual speed the time becomes b/a of usual. The delay is the difference from 1, so the usual time follows in one step.",
    tags: ["late early"],
    timeTargetSec: 105,
  },
  {
    slug: "tsd2-man-and-train-bridge",
    topic: "time-speed-distance",
    title: "Crossing a bridge on foot",
    prompt: "A man walking at **5 km/h** crosses a bridge in **15 minutes**. What is the **length of the bridge**?",
    options: ["1,000 m", "1,250 m", "1,500 m", "2,000 m"],
    answer: 1,
    difficulty: "easy",
    hints: ["15 minutes is a quarter of an hour.", "5 × 1/4 km, then convert to metres."],
    solution:
      "1. Distance = 5 × (15/60) = 1.25 km.\n2. In metres that is **1,250 m**.\n\nAnswer: **1,250 m**.",
    approach: "Compute in kilometres, then convert once at the end. Converting the speed to m/min first also works: 5 km/h is 83⅓ m/min.",
    tags: ["basics"],
    timeTargetSec: 50,
  },
  {
    slug: "tsd2-two-trains-crossing-time-ratio",
    topic: "time-speed-distance",
    title: "Equal lengths, different speeds",
    prompt:
      "Two trains of **equal length 120 m** run on parallel tracks at **42 km/h and 30 km/h** in the **same direction**. How long does the faster take to **pass the slower**?",
    options: ["60 s", "72 s", "80 s", "90 s"],
    answer: 1,
    difficulty: "medium",
    hints: ["Relative speed = 12 km/h.", "Distance = 120 + 120 = 240 m."],
    solution:
      "1. Relative speed = 42 − 30 = 12 km/h = 12 × 5/18 = 10/3 m/s.\n2. Distance = 240 m.\n3. Time = 240 ÷ (10/3) = 240 × 3/10 = **72 s**.\n\nAnswer: **72 s**.",
    approach: "Same direction, so subtract speeds, and the distance is both lengths together. Keeping 10/3 as a fraction avoids rounding.",
    tags: ["trains", "relative speed"],
    timeTargetSec: 90,
  },
];
