import type { AptitudeSeed } from "./types.js";

/**
 * Logical reasoning: series, coding, blood relations, directions, syllogisms,
 * seating puzzles, analogies and mathematical reasoning.
 */
export const LOGICAL: AptitudeSeed[] = [
  /* ── Number & Letter Series ────────────────────────────────────── */
  {
    slug: "ls-squares-plus-one",
    topic: "number-series",
    title: "2, 5, 10, 17, 26, ?",
    prompt: "Find the next term:\n\n**2, 5, 10, 17, 26, ?**",
    options: ["35", "36", "37", "38"],
    answer: 2,
    difficulty: "easy",
    hints: ["Look at the differences between consecutive terms.", "The differences are 3, 5, 7, 9 — the next is 11."],
    solution:
      "1. Differences: 5 − 2 = 3, 10 − 5 = 5, 17 − 10 = 7, 26 − 17 = 9. They grow by 2.\n2. Next difference = 11, so the term is 26 + 11 = **37**.\n3. Equivalently the terms are n² + 1: 1+1, 4+1, 9+1, 16+1, 25+1, 36+1 = 37.\n\nAnswer: **37**.",
    approach: "Take first differences; if they are not constant, take second differences. A constant second difference means the terms follow a quadratic, usually n² plus a shift.",
    tags: ["differences"],
    timeTargetSec: 45,
  },
  {
    slug: "ls-multiply-add-alternating",
    topic: "number-series",
    title: "3, 7, 15, 31, 63, ?",
    prompt: "Find the next term:\n\n**3, 7, 15, 31, 63, ?**",
    options: ["95", "119", "127", "131"],
    answer: 2,
    difficulty: "easy",
    hints: ["Each term is close to double the one before.", "Term = 2 × previous + 1."],
    solution: "1. 3 × 2 + 1 = 7; 7 × 2 + 1 = 15; 15 × 2 + 1 = 31; 31 × 2 + 1 = 63.\n2. Next = 63 × 2 + 1 = **127**.\n3. The terms are 2ⁿ − 1: 4−1, 8−1, 16−1, 32−1, 64−1, 128−1.\n\nAnswer: **127**.",
    approach: "When terms roughly double, test 'previous × 2 ± k'. Powers of 2 offset by a constant are the most common disguise.",
    tags: ["multiplicative"],
    timeTargetSec: 45,
  },
  {
    slug: "ls-alternating-two-series",
    topic: "number-series",
    title: "5, 11, 8, 14, 11, ?",
    prompt: "Find the next term:\n\n**5, 11, 8, 14, 11, ?**",
    options: ["15", "16", "17", "18"],
    answer: 2,
    difficulty: "medium",
    hints: ["Two series are interleaved. Read alternate terms.", "Odd positions: 5, 8, 11 (+3). Even positions: 11, 14, ?"],
    solution:
      "1. Odd positions (1st, 3rd, 5th): 5, 8, 11 — each +3.\n2. Even positions (2nd, 4th, 6th): 11, 14, … — also +3, so the sixth term is 14 + 3 = **17**.\n\nAnswer: **17**.",
    approach: "If the differences alternate between two values, split the series into odd and even positions and solve each separately.",
    tags: ["alternating"],
    timeTargetSec: 60,
  },
  {
    slug: "ls-letter-skip-two",
    topic: "number-series",
    title: "A, D, G, J, ?",
    prompt: "Find the next letter:\n\n**A, D, G, J, ?**",
    options: ["L", "M", "N", "K"],
    answer: 1,
    difficulty: "easy",
    hints: ["Convert letters to positions: A = 1, D = 4, G = 7.", "Each step adds 3."],
    solution: "1. Positions: A = 1, D = 4, G = 7, J = 10 — each +3.\n2. Next = 13 = **M**.\n\nAnswer: **M**.",
    approach: "Turn letters into numbers (A = 1 … Z = 26), find the numeric rule, then convert back. Knowing the landmarks A=1, E=5, J=10, O=15, T=20, Y=25 makes this instant.",
    tags: ["letters"],
    timeTargetSec: 40,
  },
  {
    slug: "ls-fibonacci-like",
    topic: "number-series",
    title: "4, 6, 10, 16, 26, ?",
    prompt: "Find the next term:\n\n**4, 6, 10, 16, 26, ?**",
    options: ["36", "38", "40", "42"],
    answer: 3,
    difficulty: "medium",
    hints: ["Compare each term with the sum of the two before it.", "10 = 4 + 6; 16 = 6 + 10."],
    solution: "1. Each term is the sum of the previous two: 4 + 6 = 10, 6 + 10 = 16, 10 + 16 = 26.\n2. Next = 16 + 26 = **42**.\n\nAnswer: **42**.",
    approach: "When differences themselves look like earlier terms, test the Fibonacci rule aₙ = aₙ₋₁ + aₙ₋₂ before anything more elaborate.",
    tags: ["fibonacci"],
    timeTargetSec: 50,
  },
  {
    slug: "ls-odd-one-out-series",
    topic: "number-series",
    title: "The number that does not belong",
    prompt: "Which number does **not** belong in this series?\n\n**8, 27, 64, 100, 125, 216**",
    options: ["27", "64", "100", "216"],
    answer: 2,
    difficulty: "easy",
    hints: ["Most of these are perfect cubes.", "100 is a perfect square, not a cube."],
    solution: "1. 8 = 2³, 27 = 3³, 64 = 4³, 125 = 5³, 216 = 6³.\n2. 100 is not a cube (it is 10²), so **100** does not belong.\n\nAnswer: **100**.",
    approach: "Test the small perfect powers first: squares up to 225 and cubes up to 216 cover most such questions.",
    tags: ["odd one out"],
    timeTargetSec: 40,
  },

  /* ── Coding & Decoding ─────────────────────────────────────────── */
  {
    slug: "cd-shift-by-one",
    topic: "coding-decoding",
    title: "If CAT is DBU",
    prompt: "In a certain code, **CAT** is written as **DBU**. How is **DOG** written in that code?",
    options: ["EPG", "DPH", "FQI", "EPH"],
    answer: 3,
    difficulty: "easy",
    hints: ["Compare each letter of CAT with DBU.", "Every letter moves forward by one."],
    solution: "1. C → D, A → B, T → U: each letter shifts +1.\n2. D → E, O → P, G → H, so DOG becomes **EPH**.\n\nAnswer: **EPH**.",
    approach: "Line the words up letter by letter and note the shift for each position. A constant shift is the simplest code and the most common.",
    tags: ["letter shift"],
    timeTargetSec: 40,
  },
  {
    slug: "cd-reverse-and-shift",
    topic: "coding-decoding",
    title: "Shifted, then reversed",
    prompt: "If **BOOK** is coded as **LPPC**, how is **PEN** coded?",
    options: ["QFP", "OFQ", "QFO", "OQF"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "A straight letter-by-letter comparison fails: B does not become L. Try comparing BOOK with the code read backwards.",
      "LPPC read backwards is CPPL. Now compare BOOK with CPPL letter by letter.",
      "B→C, O→P, O→P, K→L is a shift of +1. So the rule is: shift every letter by one, then write the result backwards.",
    ],
    solution:
      "1. Read the code backwards: LPPC → CPPL.\n2. Against BOOK that is B→C, O→P, O→P, K→L — a shift of **+1** on every letter.\n3. So the rule is: shift each letter forward by one, then reverse the word.\n4. PEN shifted by one is QFO; reversed, that is **OFQ**.\n\nAnswer: **OFQ**.",
    approach:
      "When no constant shift matches, test the code against the reversed word before trying anything more elaborate. Shift-then-reverse and reverse-then-shift are the two commonest two-step codes, and reading the given code backwards tells you which within seconds.",
    tags: ["reverse", "letter shift"],
    timeTargetSec: 75,
  },
  {
    slug: "cd-number-code-sum",
    topic: "coding-decoding",
    title: "Words coded as numbers",
    prompt: "If **RED** is coded as **27** and **BLUE** as **40**, how is **PINK** coded? (A = 1, B = 2, …, Z = 26.)",
    options: ["48", "50", "53", "56"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "Convert the letters to their positions in the alphabet and look for an arithmetic rule.",
      "R + E + D = 18 + 5 + 4 = 27, which is exactly the code. Check the rule on BLUE before using it.",
    ],
    solution:
      "1. RED → 18 + 5 + 4 = 27 ✓\n2. BLUE → 2 + 12 + 21 + 5 = 40 ✓ The code is the sum of the letter positions.\n3. PINK → 16 + 9 + 14 + 11 = **50**.\n\nAnswer: **50**.",
    approach:
      "Numeric codes are almost always the sum of letter positions, that sum plus a constant, or the product. Confirm your rule against every example given — one match can be a coincidence, two rarely is.",
    tags: ["letter values"],
    timeTargetSec: 60,
  },
  {
    slug: "cd-substitution-language",
    topic: "coding-decoding",
    title: "A substitution language",
    prompt:
      "In a certain language:\n\n- **'pit na som'** means **'bring me water'**\n- **'som lat tuk'** means **'water is cold'**\n\nWhich word means **'water'**?",
    options: ["pit", "na", "som", "lat"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Find the code word that appears in both sentences, and the English word that appears in both.",
      "Only 'som' is in both codes, and only 'water' is in both meanings.",
    ],
    solution:
      "1. Code words in both sentences: **som** (pit, na, lat and tuk each appear once).\n2. English words in both meanings: **water** (bring, me, is and cold each appear once).\n3. A word that appears in both sentences must translate the meaning that appears in both, so **som = water**.\n\nAnswer: **som**.",
    approach:
      "Intersect the code words of the sentences and intersect their meanings; the two intersections correspond. When more than one word survives on either side, you need a third sentence to separate them.",
    tags: ["substitution"],
    timeTargetSec: 75,
  },
  {
    slug: "cd-position-value-shift",
    topic: "coding-decoding",
    title: "Shift by position",
    prompt: "If **ACE** is coded as **BEH**, how is **BUS** coded?",
    options: ["CWU", "DWV", "CWV", "CVV"],
    answer: 2,
    difficulty: "hard",
    hints: ["Compare each letter's shift separately: A→B, C→E, E→H.", "The shifts are +1, +2, +3 by position."],
    solution:
      "1. A → B is +1, C → E is +2, E → H is +3: the shift equals the letter's position in the word.\n2. B + 1 = C, U + 2 = W, S + 3 = V.\n3. BUS becomes **CWV**.\n\nAnswer: **CWV**.",
    approach: "When the shift is not constant, check whether it increases with position (+1, +2, +3) or alternates in sign. Write the shifts under the letters before guessing.",
    tags: ["variable shift"],
    timeTargetSec: 75,
  },

  /* ── Blood Relations ───────────────────────────────────────────── */
  {
    slug: "br-only-son-of-father",
    topic: "blood-relations",
    title: "Pointing at a photograph",
    prompt: "Pointing to a photograph, a man says, *'He is the son of the only son of my father.'* How is the man related to the person in the photograph?",
    options: ["Uncle", "Father", "Cousin", "Brother"],
    answer: 1,
    difficulty: "medium",
    hints: ["'The only son of my father' — who could that be?", "If the speaker is his father's only son, that phrase means the speaker himself."],
    solution:
      "1. 'The only son of my father' is the speaker himself (he is his father's only son).\n2. So the photograph is of the speaker's son.\n3. The man is the boy's **father**.\n\nAnswer: **Father**.",
    approach: "Resolve the innermost phrase first and replace it with a single person, then work outwards. 'The only son of my father' is the speaker whenever he is male and has no brother.",
    tags: ["photograph"],
    timeTargetSec: 60,
  },
  {
    slug: "br-brother-of-mother",
    topic: "blood-relations",
    title: "Mother's brother's daughter",
    prompt: "How is your **mother's brother's daughter** related to you?",
    options: ["Cousin", "Niece", "Aunt", "Sister"],
    answer: 0,
    difficulty: "easy",
    hints: ["Mother's brother is your uncle.", "An uncle's daughter is a cousin, not a sister."],
    solution: "1. Mother's brother = maternal uncle.\n2. His daughter is your **cousin**.\n\nAnswer: **Cousin**.",
    approach: "Walk the chain one link at a time and name each person as you go. A cousin is any child of a parent's sibling.",
    tags: ["chain"],
    timeTargetSec: 40,
  },
  {
    slug: "br-woman-photo-daughter",
    topic: "blood-relations",
    title: "A woman and a photograph",
    prompt: "A woman says, *'That girl is the daughter of the only daughter of my mother.'* How is the girl related to the woman?",
    options: ["Niece", "Daughter", "Cousin", "Sister"],
    answer: 1,
    difficulty: "medium",
    hints: ["'The only daughter of my mother' — is that the speaker?", "If the speaker is her mother's only daughter, that phrase is the speaker herself."],
    solution:
      "1. 'The only daughter of my mother' is the speaker herself.\n2. So the girl is the speaker's daughter.\n\nAnswer: **Daughter**.",
    approach: "The word 'only' is the hinge in these questions: it forces the phrase to point back at the speaker.",
    tags: ["photograph"],
    timeTargetSec: 50,
  },
  {
    slug: "br-family-of-six",
    topic: "blood-relations",
    title: "Who is the grandfather?",
    prompt:
      "In a family: **A is B's father**, **B is C's mother**, **C is D's sister** and **E is A's wife**. How is **E** related to **D**?",
    options: ["Mother", "Aunt", "Grandmother", "Sister"],
    answer: 2,
    difficulty: "medium",
    hints: ["C and D are siblings, and B is their mother.", "A is B's father, so A and E are B's parents."],
    solution:
      "1. B is the mother of C, and D is C's sibling, so B is D's mother too.\n2. A is B's father and E is A's wife, so E is B's mother.\n3. E is therefore D's **grandmother**.\n\nAnswer: **Grandmother**.",
    approach: "Draw the tree: generations top to bottom, spouses side by side. Two lines of a diagram beat four sentences of reasoning.",
    tags: ["family tree"],
    timeTargetSec: 75,
  },

  /* ── Direction Sense ───────────────────────────────────────────── */
  {
    slug: "ds-walk-and-turn",
    topic: "direction-sense",
    title: "How far from the start",
    prompt: "A man walks **10 m north**, turns right and walks **15 m**, then turns right and walks **10 m**. How far is he from his starting point, and in which direction?",
    options: ["10 m north", "15 m east", "15 m west", "25 m east"],
    answer: 1,
    difficulty: "easy",
    hints: ["Sketch it: north, then east, then south.", "The two 10 m legs cancel."],
    solution:
      "1. North 10 m, then right (east) 15 m, then right (south) 10 m.\n2. The northward and southward 10 m cancel, leaving 15 m east of the start.\n\nAnswer: **15 m east**.",
    approach: "Track the north–south and east–west totals separately, adding for one direction and subtracting for its opposite. Sketch even when the numbers look easy.",
    tags: ["displacement"],
    timeTargetSec: 50,
  },
  {
    slug: "ds-shadow-direction",
    topic: "direction-sense",
    title: "Which way is he facing?",
    prompt: "At sunrise, a man's shadow falls to his **right**. Which direction is he facing?",
    options: ["North", "South", "East", "West"],
    answer: 0,
    difficulty: "medium",
    hints: ["At sunrise the sun is in the east, so shadows point west.", "If west is on his right, what is in front of him?"],
    solution:
      "1. The sun rises in the east, so shadows fall towards the west.\n2. His shadow is on his right, so west is to his right.\n3. Facing with west on the right means facing **north**.\n\nAnswer: **North**.",
    approach: "Fix the sun's side first (east at sunrise, west at sunset), so the shadow points the opposite way. Then rotate yourself until that direction is where the question puts it.",
    tags: ["shadows"],
    timeTargetSec: 60,
  },
  {
    slug: "ds-pythagoras-displacement",
    topic: "direction-sense",
    title: "A right-angled walk",
    prompt: "Ravi walks **6 km east**, then **8 km north**. How far is he from his starting point?",
    options: ["10 km", "12 km", "14 km", "48 km"],
    answer: 0,
    difficulty: "easy",
    hints: ["The two legs are at right angles.", "√(6² + 8²)."],
    solution: "1. The displacement is the hypotenuse: √(36 + 64) = √100 = **10 km**.\n\nAnswer: **10 km**.",
    approach: "Perpendicular legs mean Pythagoras. Watch for the 3-4-5 family (6-8-10 here) and the answer needs no square root.",
    tags: ["pythagoras"],
    timeTargetSec: 40,
  },
  {
    slug: "ds-left-turns",
    topic: "direction-sense",
    title: "Left, left, right",
    prompt: "A person facing **south** turns **left**, then **left** again, and finally **right**. Which direction is he facing now?",
    options: ["East", "West", "North", "South"],
    answer: 0,
    difficulty: "easy",
    hints: [
      "Facing south, your left hand points east — so a left turn leaves you facing east.",
      "Take one turn at a time and name the new direction before moving on.",
    ],
    solution:
      "1. Facing **south**, a left turn faces **east**.\n2. Facing east, another left turn faces **north**.\n3. Facing north, a right turn faces **east**.\n\nAnswer: **East**.",
    approach:
      "Right turns run N → E → S → W → N; left turns run the same list backwards. Step through one turn at a time and say the direction aloud — combining two turns in your head is where the errors come from.",
    tags: ["turns"],
    timeTargetSec: 45,
  },
  {
    slug: "sy-all-cats-animals",
    topic: "syllogisms",
    title: "All cats are animals",
    prompt:
      "**Statements:**\n1. All cats are animals.\n2. All animals are living things.\n\n**Conclusions:**\nI. All cats are living things.\nII. All living things are cats.\n\nWhich conclusion follows?",
    options: ["Only I", "Only II", "Both I and II", "Neither"],
    answer: 0,
    difficulty: "easy",
    hints: ["Draw three circles, smallest inside largest.", "A chain of 'all' statements passes forwards, never backwards."],
    solution:
      "1. Cats ⊂ animals ⊂ living things, so every cat is a living thing: conclusion I follows.\n2. The reverse does not: living things include much more than cats. Conclusion II does not follow.\n\nAnswer: **Only I**.",
    approach: "Venn diagrams settle syllogisms. 'All A are B' draws A inside B; conclusions must hold for every valid drawing, not just the obvious one.",
    tags: ["venn"],
    timeTargetSec: 45,
  },
  {
    slug: "sy-some-pens-are-books",
    topic: "syllogisms",
    title: "Some pens are books",
    prompt:
      "**Statements:**\n1. Some pens are books.\n2. All books are papers.\n\n**Conclusions:**\nI. Some pens are papers.\nII. All papers are books.\n\nWhich conclusion follows?",
    options: ["Only I", "Only II", "Both I and II", "Neither"],
    answer: 0,
    difficulty: "medium",
    hints: ["The pens that are books must also be papers.", "'All books are papers' says nothing about papers that are not books."],
    solution:
      "1. Some pens are books, and all books are papers, so those pens are papers: conclusion I follows.\n2. Conclusion II reverses an 'all' statement, which is invalid.\n\nAnswer: **Only I**.",
    approach: "'Some A are B' plus 'All B are C' always yields 'Some A are C'. Reversing an 'all' is the classic trap.",
    tags: ["some/all"],
    timeTargetSec: 60,
  },
  {
    slug: "sy-no-a-is-b",
    topic: "syllogisms",
    title: "No student is lazy",
    prompt:
      "**Statements:**\n1. No student is lazy.\n2. Some lazy people are rich.\n\n**Conclusions:**\nI. Some rich people are not students.\nII. No rich person is a student.\n\nWhich conclusion follows?",
    options: ["Only I", "Only II", "Both", "Neither"],
    answer: 0,
    difficulty: "hard",
    hints: ["The lazy-and-rich people cannot be students.", "But some other rich people might still be students."],
    solution:
      "1. Some lazy people are rich; no lazy person is a student; so those rich people are not students. Conclusion I follows.\n2. Other rich people (not lazy) could be students, so conclusion II is too strong.\n\nAnswer: **Only I**.",
    approach: "'Some' conclusions are safer than 'no' or 'all'. Ask whether a single counter-drawing can break the conclusion; if yes, it does not follow.",
    tags: ["negative"],
    timeTargetSec: 90,
  },

  /* ── Seating & Puzzles ────────────────────────────────────────── */
  {
    slug: "sa-row-of-five",
    topic: "seating-arrangement",
    title: "Five friends in a row",
    prompt:
      "Five friends sit in a row facing north. **C is at the extreme left**, **E is at the extreme right**, **B is immediately to the right of A**, and **D sits between B and E**. Who sits in the middle?",
    options: ["C", "D", "A", "B"],
    answer: 3,
    difficulty: "medium",
    hints: [
      "Number the seats 1 to 5 from the left and place the fixed people first.",
      "C takes seat 1 and E takes seat 5, leaving seats 2, 3 and 4 for A, B and D.",
      "A and B must be adjacent in that order, and D has to come after B.",
    ],
    solution:
      "1. Seats 1–5 from the left: C = 1, E = 5.\n2. A, B and D fill seats 2, 3 and 4. B is immediately right of A, so A and B are adjacent with A first.\n3. D sits between B and E, so D comes after B — the only fit is A = 2, B = 3, D = 4.\n4. The row is **C, A, B, D, E**, so the middle seat holds **B**.\n\nAnswer: **B**.",
    approach:
      "Place absolute clues first (extreme left, extreme right), then adjacency clues, then 'between' clues, which are the loosest. Write the finished row out and re-read every clue against it before answering.",
    tags: ["linear"],
    timeTargetSec: 90,
  },
  {
    slug: "sa-circle-of-six",
    topic: "seating-arrangement",
    title: "Six around a circular table",
    prompt:
      "Six people — P, Q, R, S, T and U — sit around a circular table **facing the centre**. **P sits opposite S**, **Q is immediately to the left of P**, **R sits opposite Q**, and **T is immediately to the right of S**. Who sits opposite **T**?",
    options: ["R", "U", "P", "Q"],
    answer: 1,
    difficulty: "hard",
    hints: [
      "With six seats, 'opposite' means three seats away.",
      "Number the seats 1 to 6 clockwise and put P at seat 1; S must then be at seat 4.",
      "Facing the centre, a person's left is the next seat clockwise and their right is the next seat anticlockwise.",
    ],
    solution:
      "1. Number the seats 1–6 clockwise and put **P at 1**. Opposite is three seats away, so **S is at 4**.\n2. Facing the centre, the seat to someone's left is the next one clockwise, so **Q is at 2**; opposite Q is **R at 5**.\n3. The seat to S's right is the next one anticlockwise from seat 4, so **T is at 3**, leaving **U at 6**.\n4. Opposite T (seat 3) is seat 6, which is **U**.\n\nAnswer: **U**.",
    approach:
      "In a circle of n seats, opposite means n/2 seats away. Fix one person, then place the rest. The one thing to get right is orientation: facing the centre, left is clockwise and right is anticlockwise — both flip when the group faces outwards.",
    tags: ["circular"],
    timeTargetSec: 120,
  },
  {
    slug: "an-doctor-hospital",
    topic: "analogies-classification",
    title: "Doctor is to hospital",
    prompt: "**Doctor : Hospital :: Teacher : ?**",
    options: ["Student", "School", "Book", "Lesson"],
    answer: 1,
    difficulty: "easy",
    hints: ["What is the relation between a doctor and a hospital?", "It is 'works in', not 'works with'."],
    solution: "1. A doctor works in a hospital.\n2. A teacher works in a **school**.\n\nAnswer: **School**.",
    approach: "State the relation as a short sentence before looking at the options, then test each option in that same sentence. Distractors are usually a different relation ('works with').",
    tags: ["relation"],
    timeTargetSec: 30,
  },
  {
    slug: "an-odd-one-out-words",
    topic: "analogies-classification",
    title: "The word that does not belong",
    prompt: "Which one does **not** belong with the others?\n\n**Rose, Lily, Jasmine, Mango, Marigold**",
    options: ["Marigold", "Rose", "Jasmine", "Mango"],
    answer: 3,
    difficulty: "easy",
    hints: ["Four of these are the same kind of thing.", "Mango is a fruit; the rest are flowers."],
    solution: "1. Rose, Lily, Jasmine and Marigold are flowers.\n2. **Mango** is a fruit.\n\nAnswer: **Mango**.",
    approach: "Find the category that covers most items; the exception is the answer. If two categories fit, prefer the one that leaves exactly one item out.",
    tags: ["classification"],
    timeTargetSec: 30,
  },
  {
    slug: "an-square-cube-analogy",
    topic: "analogies-classification",
    title: "A numerical analogy",
    prompt: "**9 : 81 :: 12 : ?**",
    options: ["120", "132", "144", "156"],
    answer: 2,
    difficulty: "easy",
    hints: ["81 is 9 squared.", "12² = ?"],
    solution: "1. 81 = 9².\n2. 12² = **144**.\n\nAnswer: **144**.",
    approach: "Test the simple operations in order: square, cube, double, add a constant, multiply. Confirm on the given pair before applying.",
    tags: ["numeric analogy"],
    timeTargetSec: 30,
  },

  /* ── Mathematical Reasoning ────────────────────────────────────── */
  {
    slug: "mr-data-sufficiency-age",
    topic: "mathematical-reasoning",
    title: "Data sufficiency: how old is Ravi?",
    prompt:
      "**Question:** How old is Ravi?\n\n**Statement I:** Ravi is 5 years older than his brother.\n**Statement II:** Ravi's brother will be 20 next year.\n\nWhich statements are needed?",
    options: ["I alone is enough", "II alone is enough", "Both together are needed", "Even both are not enough"],
    answer: 2,
    difficulty: "medium",
    hints: ["Statement I alone gives a relation, not a number.", "Statement II gives the brother's age but says nothing about Ravi."],
    solution:
      "1. I alone: Ravi = brother + 5, but the brother's age is unknown. Not enough.\n2. II alone: the brother is 19 now, but Ravi's relation to him is unknown. Not enough.\n3. Together: brother is 19, so Ravi is 24. **Both together are needed**.\n\nAnswer: **Both together are needed**.",
    approach: "Test each statement alone before testing them together, and never carry information from one into the other. Answer the sufficiency question, not the arithmetic one.",
    tags: ["data sufficiency"],
    timeTargetSec: 75,
  },
  {
    slug: "mr-clock-angle",
    topic: "mathematical-reasoning",
    title: "Angle between the hands",
    prompt: "What is the angle between the hour and minute hands of a clock at **3:30**?",
    options: ["70°", "75°", "80°", "90°"],
    answer: 1,
    difficulty: "medium",
    hints: ["The minute hand is at 180°. The hour hand is past 3, not on it.", "Hour hand angle = 30 × hours + 0.5 × minutes."],
    solution:
      "1. Minute hand at 30 min = 30 × 6 = 180°.\n2. Hour hand = 30 × 3 + 0.5 × 30 = 90 + 15 = 105°.\n3. Angle = 180 − 105 = **75°**.\n\nAnswer: **75°**.",
    approach: "Angle = |30H − 5.5M|. If it exceeds 180°, subtract from 360°. The 0.5° per minute drift of the hour hand is what most candidates forget.",
    tags: ["clocks"],
    timeTargetSec: 60,
  },
  {
    slug: "mr-calendar-day",
    topic: "mathematical-reasoning",
    title: "What day was it?",
    prompt: "If **15 August 2026** is a **Saturday**, what day is **15 September 2026**?",
    options: ["Thursday", "Monday", "Tuesday", "Wednesday"],
    answer: 2,
    difficulty: "medium",
    hints: ["August has 31 days.", "31 days later = 3 odd days after Saturday."],
    solution:
      "1. From 15 August to 15 September is 31 days.\n2. 31 = 4 weeks + 3 days, so move 3 days on from Saturday: Sunday, Monday, **Tuesday**.\n\nAnswer: **Tuesday**.",
    approach: "Count 'odd days' — the remainder after dividing by 7 — and advance the weekday by that many. Month lengths matter: 31 days gives 3 odd days, 30 gives 2, February 28 gives 0.",
    tags: ["calendar"],
    timeTargetSec: 60,
  },
  {
    slug: "mr-statement-and-assumption",
    topic: "mathematical-reasoning",
    title: "Statement and assumption",
    prompt:
      "**Statement:** 'Use our coaching, and you will clear the exam in your first attempt.'\n\n**Assumptions:**\nI. People want to clear the exam in the first attempt.\nII. This coaching is the only way to clear the exam.\n\nWhich assumption is implicit?",
    options: ["Only I", "Only II", "Both", "Neither"],
    answer: 0,
    difficulty: "medium",
    hints: ["An assumption is something taken for granted for the statement to make sense.", "Would the advertisement work if nobody cared about a first-attempt pass?"],
    solution:
      "1. The advertisement only appeals if a first-attempt pass is desirable, so assumption I is implicit.\n2. Claiming it is the *only* way is far stronger than the statement needs; II is not implicit.\n\nAnswer: **Only I**.",
    approach: "An implicit assumption must be necessary for the statement to hold, not merely consistent with it. Reject anything containing 'only', 'always' or 'never' unless the statement says so.",
    tags: ["assumptions"],
    timeTargetSec: 75,
  },
];
