import type { AptitudeSeed } from "./types.js";

/**
 * Quantitative aptitude, part one: number system, percentages, profit and
 * loss, ratio and proportion, averages, ages. Every answer was worked by hand
 * and checked twice; the solution shows the working the way an examiner
 * would mark it, and the approach names the shortcut worth remembering.
 */
export const QUANT_ARITHMETIC: AptitudeSeed[] = [
  /* ── Number System ─────────────────────────────────────────────── */
  {
    slug: "ns-remainder-power-of-seven",
    topic: "number-system",
    title: "Remainder of a large power",
    prompt: "What is the remainder when **7¹⁰⁰** is divided by **5**?",
    options: ["1", "2", "3", "4"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Replace 7 by its remainder on division by 5 before raising it to any power.",
      "Powers of 2 leave remainders that repeat in a short cycle when divided by 5. Find the cycle length.",
      "The cycle is 2, 4, 3, 1 — length 4. Where does 100 fall in it?",
    ],
    solution:
      "1. 7 ≡ 2 (mod 5), so 7¹⁰⁰ ≡ 2¹⁰⁰ (mod 5).\n2. Remainders of 2ⁿ on division by 5: 2¹ → 2, 2² → 4, 2³ → 3, 2⁴ → 1, then it repeats every 4.\n3. 100 = 4 × 25, so 2¹⁰⁰ sits at the end of a cycle, where the remainder is **1**.\n\nAnswer: **1**.",
    approach:
      "Reduce the base modulo the divisor first, then look for the cycle in the remainders of successive powers. The exponent's position in that cycle (exponent mod cycle length) gives the answer without any large arithmetic.",
    tags: ["remainders", "cyclicity"],
    timeTargetSec: 75,
  },
  {
    slug: "ns-unit-digit-product",
    topic: "number-system",
    title: "Unit digit of a product of powers",
    prompt: "What is the unit digit of **3⁴⁷ × 7²³**?",
    options: ["1", "3", "7", "9"],
    answer: 0,
    difficulty: "medium",
    hints: [
      "Only the unit digits matter. Unit digits of powers of 3 and of 7 each repeat every 4 steps.",
      "Powers of 3 end in 3, 9, 7, 1, …; powers of 7 end in 7, 9, 3, 1, …. Use exponent mod 4.",
    ],
    solution:
      "1. Unit digits of 3ⁿ cycle as 3, 9, 7, 1. 47 mod 4 = 3, so 3⁴⁷ ends in **7**.\n2. Unit digits of 7ⁿ cycle as 7, 9, 3, 1. 23 mod 4 = 3, so 7²³ ends in **3**.\n3. 7 × 3 = 21, whose unit digit is **1**.\n\nAnswer: **1**.",
    approach:
      "Unit digits of powers cycle with period 4 (or shorter). Take the exponent mod 4 — treating a remainder of 0 as the 4th position — for each factor, then multiply just the unit digits.",
    tags: ["unit digit", "cyclicity"],
    timeTargetSec: 75,
  },
  {
    slug: "ns-hcf-lcm-product",
    topic: "number-system",
    title: "HCF, LCM and the other number",
    prompt: "The HCF of two numbers is **12** and their LCM is **360**. If one of the numbers is **72**, what is the other?",
    options: ["48", "60", "90", "120"],
    answer: 1,
    difficulty: "easy",
    hints: [
      "For two numbers, the product of the HCF and the LCM equals the product of the numbers.",
      "12 × 360 = 4320. Divide by the known number.",
    ],
    solution:
      "1. For any two numbers, HCF × LCM = product of the numbers.\n2. So the other number = (12 × 360) ÷ 72 = 4320 ÷ 72 = **60**.\n3. Check: HCF(72, 60) = 12 and LCM(72, 60) = 360. ✓\n\nAnswer: **60**.",
    approach:
      "HCF × LCM = a × b holds for exactly two numbers (not three or more). When three of the four quantities are known, the fourth is one division away.",
    tags: ["hcf", "lcm"],
    timeTargetSec: 60,
  },
  {
    slug: "ns-divisible-by-nine-digit",
    topic: "number-system",
    title: "A missing digit and divisibility by 9",
    prompt: "For which digit **x** is the four-digit number **45x3** divisible by **9**?",
    options: ["3", "5", "6", "9"],
    answer: 2,
    difficulty: "easy",
    hints: [
      "A number is divisible by 9 exactly when the sum of its digits is divisible by 9.",
      "4 + 5 + x + 3 = 12 + x. Which digit makes that a multiple of 9?",
    ],
    solution:
      "1. Digit sum = 4 + 5 + x + 3 = 12 + x.\n2. For divisibility by 9 the sum must be 18 (the next multiple of 9 above 12 that a single digit can reach): 12 + x = 18 gives x = **6**.\n3. Check: 4563 ÷ 9 = 507. ✓\n\nAnswer: **6**.",
    approach:
      "Divisibility by 3 and by 9 depend only on the digit sum; by 11 on the alternating digit sum; by 4 and 8 on the last two and three digits. Memorise these and a missing-digit question is arithmetic on one line.",
    tags: ["divisibility"],
    timeTargetSec: 45,
  },
  {
    slug: "ns-count-of-divisors",
    topic: "number-system",
    title: "Counting the divisors of 360",
    prompt: "How many positive divisors does **360** have?",
    options: ["18", "20", "24", "30"],
    answer: 2,
    difficulty: "medium",
    hints: [
      "Start from the prime factorisation of 360.",
      "If n = p^a × q^b × r^c, the number of divisors is (a + 1)(b + 1)(c + 1).",
    ],
    solution:
      "1. 360 = 2³ × 3² × 5¹.\n2. Number of divisors = (3 + 1)(2 + 1)(1 + 1) = 4 × 3 × 2 = **24**.\n\nAnswer: **24**.",
    approach:
      "Every divisor picks an exponent for each prime from 0 up to its power, so multiply (exponent + 1) across the primes. The same factorisation also gives the sum of divisors and the number of odd or even divisors.",
    tags: ["factors", "prime factorisation"],
    timeTargetSec: 60,
  },
  {
    slug: "ns-trailing-zeros-factorial",
    topic: "number-system",
    title: "Trailing zeros in 100!",
    prompt: "How many zeros does **100!** end with?",
    options: ["20", "24", "25", "30"],
    answer: 1,
    difficulty: "medium",
    hints: [
      "A trailing zero needs a factor of 10 = 2 × 5. Factors of 2 are plentiful; count the factors of 5.",
      "Count multiples of 5, then add the multiples of 25 (each contributes a second 5).",
    ],
    solution:
      "1. Trailing zeros = number of factors of 5 in 100! (there are always more 2s than 5s).\n2. Multiples of 5 up to 100: ⌊100/5⌋ = 20. Multiples of 25 contribute one more each: ⌊100/25⌋ = 4. Multiples of 125: 0.\n3. Total = 20 + 4 = **24**.\n\nAnswer: **24**.",
    approach:
      "Zeros at the end of n! = ⌊n/5⌋ + ⌊n/25⌋ + ⌊n/125⌋ + …, stopping when the power of 5 exceeds n. The same idea (Legendre's formula) counts any prime's power in a factorial.",
    tags: ["factorial", "trailing zeros"],
    timeTargetSec: 60,
  },
  {
    slug: "ns-consecutive-odd-sum",
    topic: "number-system",
    title: "Three consecutive odd numbers",
    prompt: "The sum of three consecutive odd numbers is **63**. What is the largest of them?",
    options: ["21", "23", "25", "27"],
    answer: 1,
    difficulty: "easy",
    hints: ["The middle number of three consecutive terms is their average.", "63 ÷ 3 = 21 is the middle one."],
    solution:
      "1. Three consecutive odd numbers can be written as n − 2, n, n + 2; their sum is 3n.\n2. 3n = 63, so n = 21 and the numbers are 19, 21, 23.\n3. The largest is **23**.\n\nAnswer: **23**.",
    approach:
      "For an odd count of evenly spaced numbers, the sum divided by the count is the middle term. Avoid the algebra of x, x + 2, x + 4 whenever the count is odd.",
    tags: ["consecutive numbers"],
    timeTargetSec: 40,
  },

  /* ── Percentages ───────────────────────────────────────────────── */
  {
    slug: "pc-successive-up-down",
    topic: "percentages",
    title: "Up 20%, then down 20%",
    prompt: "A price is increased by **20%** and the new price is then decreased by **20%**. What is the net change from the original?",
    options: ["4% decrease", "2% decrease", "No change", "4% increase"],
    answer: 0,
    difficulty: "easy",
    hints: ["The second change applies to the increased price, not the original.", "Multiply the factors: 1.20 × 0.80."],
    solution:
      "1. Take the original as 100. After +20%: 120. After −20% of 120: 120 − 24 = 96.\n2. Net change = 96 − 100 = −4, i.e. a **4% decrease**.\n\nAnswer: **4% decrease**.",
    approach:
      "Successive changes multiply: a% then b% gives a net of a + b + ab/100. An equal rise and fall of x% always nets to a loss of x²/100 percent — here 20²/100 = 4%.",
    tags: ["successive change"],
    timeTargetSec: 45,
  },
  {
    slug: "pc-population-growth",
    topic: "percentages",
    title: "Two years of population growth",
    prompt: "A town's population is **50,000** and grows by **10%** every year. What will it be after **2 years**?",
    options: ["60,000", "60,500", "61,000", "62,500"],
    answer: 1,
    difficulty: "easy",
    hints: ["The second year's 10% is on the population after the first year.", "50,000 × 1.1 × 1.1."],
    solution:
      "1. After year 1: 50,000 × 1.1 = 55,000.\n2. After year 2: 55,000 × 1.1 = **60,500**.\n\nAnswer: **60,500**.",
    approach:
      "Repeated percentage growth is compound growth: multiply by (1 + r/100) once per period. Two years at 10% is a 21% rise, not 20%.",
    tags: ["compound growth"],
    timeTargetSec: 45,
  },
  {
    slug: "pc-failing-marks",
    topic: "percentages",
    title: "Passing marks from a fail margin",
    prompt: "A student scored **240** marks and failed by **30** marks. If the pass mark is **45%** of the total, what is the total?",
    options: ["500", "540", "600", "650"],
    answer: 2,
    difficulty: "easy",
    hints: ["Passing marks = the student's score plus the shortfall.", "270 is 45% of the total."],
    solution:
      "1. Passing marks = 240 + 30 = 270.\n2. 45% of total = 270, so total = 270 ÷ 0.45 = **600**.\n\nAnswer: **600**.",
    approach:
      "Turn the story into one equation: the pass mark is both a percentage of the total and a known number. Then divide. Check the answer by taking 45% of it.",
    tags: ["percent of total"],
    timeTargetSec: 45,
  },
  {
    slug: "pc-more-than-less-than",
    topic: "percentages",
    title: "If A is 25% more than B",
    prompt: "If **A is 25% more than B**, then B is what percent **less than A**?",
    options: ["25%", "30%", "33⅓%", "20%"],
    answer: 3,
    difficulty: "medium",
    hints: ["Put B = 100. Then A = 125.", "The shortfall of B is measured against A, not against B."],
    solution:
      "1. Let B = 100, so A = 125.\n2. B is 25 less than A; as a fraction of A that is 25/125 = 1/5 = **20%**.\n\nAnswer: **20%**.",
    approach:
      "'More than' and 'less than' use different bases. If A is x% more than B, then B is 100x/(100 + x) percent less than A. The reverse of a rise is never the same percentage.",
    tags: ["base change"],
    timeTargetSec: 60,
  },
  {
    slug: "pc-share-percentage-points",
    topic: "percentages",
    title: "Percentage points versus percentage",
    prompt: "A company's market share rose from **30%** to **36%**. By what **percentage** did its share increase?",
    options: ["6%", "20%", "25%", "36%"],
    answer: 1,
    difficulty: "medium",
    hints: ["A rise of 6 percentage points is not a 6% rise.", "Increase ÷ original share = 6 ÷ 30."],
    solution:
      "1. The share went up by 36 − 30 = 6 percentage points.\n2. Relative to the original share of 30, that is 6/30 = **20%**.\n\nAnswer: **20%**.",
    approach:
      "Percentage points are an absolute difference between two percentages; a percentage change is that difference divided by the starting value. Questions that mix the two are testing whether you notice.",
    tags: ["percentage points"],
    timeTargetSec: 45,
  },
  {
    slug: "pc-consumption-cut",
    topic: "percentages",
    title: "Keeping the sugar bill the same",
    prompt: "The price of sugar rises by **25%**. By what percent must a family cut its consumption so that its expenditure on sugar stays the same?",
    options: ["20%", "25%", "30%", "40%"],
    answer: 0,
    difficulty: "medium",
    hints: ["Expenditure = price × quantity. If price becomes 125, quantity must become 100/125 of before.", "100/125 = 0.8, so the cut is 20%."],
    solution:
      "1. Let the old price be 100 and old consumption 100, so expenditure = 10,000.\n2. New price 125; for the same 10,000, consumption must be 10,000 ÷ 125 = 80.\n3. Cut = 100 − 80 = **20%**.\n\nAnswer: **20%**.",
    approach:
      "For a price rise of r%, the consumption cut that keeps spending fixed is 100r/(100 + r) percent. For a price fall of r%, the allowed rise is 100r/(100 − r) percent.",
    tags: ["expenditure"],
    timeTargetSec: 60,
  },

  /* ── Profit & Loss ─────────────────────────────────────────────── */
  {
    slug: "pl-selling-price-from-profit",
    topic: "profit-and-loss",
    title: "Selling price at 15% profit",
    prompt: "An article bought for **₹800** is sold at a **15%** profit. What is the selling price?",
    options: ["₹880", "₹900", "₹920", "₹950"],
    answer: 2,
    difficulty: "easy",
    hints: ["Profit percent is always on the cost price unless stated otherwise.", "15% of 800 is 120."],
    solution: "1. Profit = 15% of 800 = 120.\n2. Selling price = 800 + 120 = **₹920**.\n\nAnswer: **₹920**.",
    approach: "SP = CP × (1 + profit%/100). Work with the multiplier 1.15 directly rather than computing the profit separately when the numbers are friendly.",
    tags: ["basics"],
    timeTargetSec: 40,
  },
  {
    slug: "pl-markup-then-discount",
    topic: "profit-and-loss",
    title: "Marked up 40%, discounted 10%",
    prompt: "A shopkeeper marks goods **40% above cost** and then allows a **10% discount** on the marked price. What is the profit percent?",
    options: ["24%", "26%", "30%", "36%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Take cost as 100. Marked price is 140.", "10% off 140 is 14; selling price is 126."],
    solution:
      "1. Let CP = 100. Marked price = 140.\n2. Discount = 10% of 140 = 14, so SP = 126.\n3. Profit = 26 on a cost of 100 = **26%**.\n\nAnswer: **26%**.",
    approach:
      "Chain the multipliers: CP × 1.40 × 0.90 = CP × 1.26. Markup and discount are percentages of different bases, so they never simply subtract.",
    tags: ["marked price", "discount"],
    timeTargetSec: 60,
  },
  {
    slug: "pl-equal-selling-price",
    topic: "profit-and-loss",
    title: "Same selling price, one gain and one loss",
    prompt: "Two articles are each sold for **₹1,200** — one at a **20% profit**, the other at a **20% loss**. Overall, the seller makes:",
    options: ["4% loss", "2% loss", "No profit, no loss", "4% profit"],
    answer: 0,
    difficulty: "medium",
    hints: ["Find each cost price separately: 1200/1.2 and 1200/0.8.", "Compare total cost with total selling price of 2,400."],
    solution:
      "1. CP of the first = 1200 ÷ 1.2 = 1,000. CP of the second = 1200 ÷ 0.8 = 1,500.\n2. Total CP = 2,500; total SP = 2,400.\n3. Loss = 100 on 2,500 = **4% loss**.\n\nAnswer: **4% loss**.",
    approach:
      "When two items sell at the same price with an equal x% gain and x% loss, the result is always a loss of x²/100 percent. Here 20²/100 = 4%.",
    tags: ["equal selling price"],
    timeTargetSec: 75,
  },
  {
    slug: "pl-false-weight",
    topic: "profit-and-loss",
    title: "A dishonest dealer's scale",
    prompt: "A dealer claims to sell at cost price but uses a **900 g** weight in place of **1 kg**. What is the dealer's profit percent?",
    options: ["9.09%", "10%", "11.11%", "12.5%"],
    answer: 2,
    difficulty: "medium",
    hints: ["The customer pays for 1000 g but receives 900 g.", "Profit is the 100 g gained, measured against the 900 g actually given."],
    solution:
      "1. For every 900 g handed over, the dealer is paid for 1000 g.\n2. Gain = 100 g on goods worth 900 g.\n3. Profit % = 100/900 × 100 = **11.11%**.\n\nAnswer: **11.11%**.",
    approach:
      "Profit percent from a false weight = error ÷ (true weight − error) × 100. The base is what was actually delivered, which is why it is more than 10%.",
    tags: ["false weight"],
    timeTargetSec: 60,
  },
  {
    slug: "pl-sp-of-20-equals-cp-of-25",
    topic: "profit-and-loss",
    title: "SP of 20 articles = CP of 25",
    prompt: "The selling price of **20** articles equals the cost price of **25** articles. What is the profit percent?",
    options: ["20%", "25%", "30%", "45%"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let the cost of one article be 1. Then 20 articles sell for 25.", "Each article sells for 25/20 = 1.25."],
    solution:
      "1. Let CP per article = 1, so CP of 25 = 25 = SP of 20.\n2. SP per article = 25/20 = 1.25.\n3. Profit = 0.25 on 1 = **25%**.\n\nAnswer: **25%**.",
    approach:
      "If SP of a articles = CP of b articles, profit% = (b − a)/a × 100. Setting one cost price to 1 makes these problems a single fraction.",
    tags: ["articles"],
    timeTargetSec: 60,
  },
  {
    slug: "pl-successive-discounts",
    topic: "profit-and-loss",
    title: "Two discounts as one",
    prompt: "Successive discounts of **20%** and **10%** are equivalent to a single discount of:",
    options: ["25%", "28%", "30%", "32%"],
    answer: 1,
    difficulty: "easy",
    hints: ["The second discount applies to the already discounted price.", "Remaining fraction = 0.8 × 0.9."],
    solution:
      "1. After 20% off, 80% remains; after a further 10% off, 90% of that remains.\n2. Remaining = 0.8 × 0.9 = 0.72, so the total discount is 1 − 0.72 = **28%**.\n\nAnswer: **28%**.",
    approach:
      "Successive discounts of a% and b% equal a single discount of a + b − ab/100. Two discounts never add up to their sum.",
    tags: ["discount"],
    timeTargetSec: 40,
  },

  /* ── Ratio & Proportion ────────────────────────────────────────── */
  {
    slug: "rp-divide-in-ratio",
    topic: "ratio-and-proportion",
    title: "Dividing ₹5,400 in the ratio 2 : 3 : 4",
    prompt: "**₹5,400** is divided among A, B and C in the ratio **2 : 3 : 4**. How much does C receive?",
    options: ["₹1,200", "₹1,800", "₹2,400", "₹3,000"],
    answer: 2,
    difficulty: "easy",
    hints: ["Add the ratio parts: 2 + 3 + 4 = 9.", "C's share is 4 of the 9 parts."],
    solution: "1. Total parts = 2 + 3 + 4 = 9, so one part = 5400 ÷ 9 = 600.\n2. C = 4 × 600 = **₹2,400**.\n\nAnswer: **₹2,400**.",
    approach: "Share = (own ratio part ÷ sum of parts) × total. Compute one part once and multiply, rather than computing each share from scratch.",
    tags: ["sharing"],
    timeTargetSec: 40,
  },
  {
    slug: "rp-combine-two-ratios",
    topic: "ratio-and-proportion",
    title: "Combining A : B and B : C",
    prompt: "If **A : B = 2 : 3** and **B : C = 4 : 5**, what is **A : B : C**?",
    options: ["6 : 9 : 10", "4 : 6 : 5", "2 : 3 : 5", "8 : 12 : 15"],
    answer: 3,
    difficulty: "easy",
    hints: ["B must be the same number in both ratios.", "Scale A : B by 4 and B : C by 3 so B becomes 12 in both."],
    solution:
      "1. Make B equal in both: A : B = 2 : 3 = 8 : 12 and B : C = 4 : 5 = 12 : 15.\n2. So A : B : C = **8 : 12 : 15**.\n\nAnswer: **8 : 12 : 15**.",
    approach:
      "To join two ratios that share a term, scale each so the shared term matches (usually its LCM). The same trick chains three or more ratios.",
    tags: ["compound ratio"],
    timeTargetSec: 45,
  },
  {
    slug: "rp-partnership-time-weighted",
    topic: "ratio-and-proportion",
    title: "Profit in a partnership",
    prompt: "A invests **₹20,000** for **12 months**; B invests **₹30,000** for **8 months**. A profit of **₹18,000** is shared in proportion to capital × time. How is it split?",
    options: ["A ₹9,000, B ₹9,000", "A ₹10,000, B ₹8,000", "A ₹12,000, B ₹6,000", "A ₹8,000, B ₹10,000"],
    answer: 0,
    difficulty: "medium",
    hints: ["Weight each investment by the months it stayed in.", "20,000 × 12 versus 30,000 × 8."],
    solution:
      "1. A's share weight = 20,000 × 12 = 240,000. B's = 30,000 × 8 = 240,000.\n2. The ratio is 1 : 1, so each gets 18,000 ÷ 2 = **₹9,000**.\n\nAnswer: **A ₹9,000, B ₹9,000**.",
    approach:
      "Partners share profit in the ratio of capital × time. A smaller investment kept in longer can match a larger one — always multiply before comparing.",
    tags: ["partnership"],
    timeTargetSec: 60,
  },
  {
    slug: "rp-coins-in-a-bag",
    topic: "ratio-and-proportion",
    title: "Coins in the ratio 2 : 3 : 4",
    prompt: "A bag holds ₹1, 50-paise and 25-paise coins in the ratio **2 : 3 : 4** by count, worth **₹90** in total. How many **50-paise** coins are there?",
    options: ["40", "60", "80", "90"],
    answer: 1,
    difficulty: "medium",
    hints: ["Find the value of one 'set' of 2 + 3 + 4 coins.", "One set is worth 2 + 1.5 + 1 = ₹4.50."],
    solution:
      "1. One set of coins (2 rupee coins, 3 fifty-paise, 4 twenty-five-paise) is worth 2 × 1 + 3 × 0.5 + 4 × 0.25 = ₹4.50.\n2. Number of sets = 90 ÷ 4.5 = 20.\n3. Fifty-paise coins = 3 × 20 = **60**.\n\nAnswer: **60**.",
    approach:
      "When counts are in a ratio but the question is about value, price one 'unit set' of the ratio and see how many sets the total buys. Never convert the count ratio to a value ratio in your head.",
    tags: ["coins"],
    timeTargetSec: 75,
  },
  {
    slug: "rp-inverse-variation-workers",
    topic: "ratio-and-proportion",
    title: "More men, fewer days",
    prompt: "**12** men can build a wall in **20** days. Working at the same rate, how many days will **15** men take?",
    options: ["15", "16", "18", "25"],
    answer: 1,
    difficulty: "easy",
    hints: ["Men and days vary inversely: their product stays the same.", "12 × 20 = 15 × d."],
    solution: "1. Total work = 12 × 20 = 240 man-days.\n2. Days for 15 men = 240 ÷ 15 = **16**.\n\nAnswer: **16**.",
    approach: "For inverse variation, keep the product constant (man-days here). Direct variation keeps the ratio constant. Decide which before writing anything.",
    tags: ["variation"],
    timeTargetSec: 40,
  },
  {
    slug: "rp-fourth-proportional",
    topic: "ratio-and-proportion",
    title: "The fourth proportional",
    prompt: "What is the fourth proportional to **4, 6 and 10**?",
    options: ["12", "14", "15", "16"],
    answer: 2,
    difficulty: "easy",
    hints: ["Fourth proportional x satisfies 4 : 6 = 10 : x.", "Cross-multiply: 4x = 60."],
    solution: "1. 4 : 6 = 10 : x means 4x = 6 × 10 = 60.\n2. x = **15**.\n\nAnswer: **15**.",
    approach: "Fourth proportional to a, b, c is bc/a. Third proportional to a, b is b²/a. Mean proportional between a and b is √(ab).",
    tags: ["proportion"],
    timeTargetSec: 40,
  },

  /* ── Averages ──────────────────────────────────────────────────── */
  {
    slug: "av-teacher-joins",
    topic: "averages",
    title: "The teacher joins the class",
    prompt: "The average age of **30** students is **15** years. When the teacher's age is included, the average becomes **16**. How old is the teacher?",
    options: ["45", "46", "47", "48"],
    answer: 1,
    difficulty: "easy",
    hints: ["Compare total ages before and after.", "31 × 16 − 30 × 15."],
    solution:
      "1. Total age of students = 30 × 15 = 450.\n2. Total with the teacher = 31 × 16 = 496.\n3. Teacher = 496 − 450 = **46**.\n\nAnswer: **46**.",
    approach:
      "Shortcut: a newcomer who raises the average of n people by d is worth (new average) + n × d — here 16 + 30 × 1 = 46. The newcomer lifts everyone else by d and is themselves at the new average.",
    tags: ["adding a member"],
    timeTargetSec: 45,
  },
  {
    slug: "av-replacement",
    topic: "averages",
    title: "One person replaced",
    prompt: "The average weight of **8** people increases by **2.5 kg** when a person weighing **65 kg** is replaced by a new one. What is the new person's weight?",
    options: ["75 kg", "80 kg", "85 kg", "90 kg"],
    answer: 2,
    difficulty: "easy",
    hints: ["The total went up by 8 × 2.5.", "New weight = old weight + the rise in total."],
    solution: "1. Rise in total weight = 8 × 2.5 = 20 kg.\n2. New person = 65 + 20 = **85 kg**.\n\nAnswer: **85 kg**.",
    approach: "When one member is swapped, the change in total equals n × (change in average). Add that to the outgoing member's value.",
    tags: ["replacement"],
    timeTargetSec: 45,
  },
  {
    slug: "av-consecutive-even",
    topic: "averages",
    title: "Five consecutive even numbers",
    prompt: "The average of **five consecutive even numbers** is **24**. What is the largest of them?",
    options: ["26", "28", "30", "32"],
    answer: 1,
    difficulty: "easy",
    hints: ["The average of consecutive terms is the middle term.", "The numbers are 20, 22, 24, 26, 28."],
    solution: "1. For evenly spaced numbers the average is the middle term, so the middle one is 24.\n2. The five numbers are 20, 22, 24, 26, 28; the largest is **28**.\n\nAnswer: **28**.",
    approach: "Evenly spaced sets have average = middle term = (first + last)/2. The largest is the middle term plus (count − 1)/2 steps.",
    tags: ["consecutive"],
    timeTargetSec: 40,
  },
  {
    slug: "av-misread-entry",
    topic: "averages",
    title: "A number was misread",
    prompt: "The average of **10** numbers was calculated as **42**. It was then found that one number, **64**, had been read as **46**. What is the correct average?",
    options: ["43.2", "43.8", "44.0", "44.2"],
    answer: 1,
    difficulty: "easy",
    hints: ["Only the total changes, by the size of the mistake.", "64 − 46 = 18 spread over 10 numbers."],
    solution: "1. The total was short by 64 − 46 = 18.\n2. The average rises by 18 ÷ 10 = 1.8.\n3. Correct average = 42 + 1.8 = **43.8**.\n\nAnswer: **43.8**.",
    approach: "A corrected entry changes the average by (correct − wrong) ÷ n. Never recompute the whole total.",
    tags: ["correction"],
    timeTargetSec: 45,
  },
  {
    slug: "av-batsman-innings",
    topic: "averages",
    title: "A big score in the 17th innings",
    prompt: "A batsman's average after **16** innings is **40**. He scores **91** in the 17th innings. What is his new average?",
    options: ["42", "43", "44", "45"],
    answer: 1,
    difficulty: "easy",
    hints: ["Total after 16 innings is 640.", "(640 + 91) ÷ 17."],
    solution: "1. Runs after 16 innings = 16 × 40 = 640.\n2. After 17 innings = 640 + 91 = 731.\n3. New average = 731 ÷ 17 = **43**.\n\nAnswer: **43**.",
    approach: "Shortcut: the new average rises by (new score − old average) ÷ new count = (91 − 40)/17 = 3. Deviation from the old average is what moves the mean.",
    tags: ["running average"],
    timeTargetSec: 45,
  },
  {
    slug: "av-first-fifty-naturals",
    topic: "averages",
    title: "Average of the first 50 natural numbers",
    prompt: "What is the average of the first **50** natural numbers?",
    options: ["25", "25.5", "26", "26.5"],
    answer: 1,
    difficulty: "easy",
    hints: ["The numbers are evenly spaced, so average = (first + last)/2."],
    solution: "1. The numbers 1 to 50 are evenly spaced.\n2. Average = (1 + 50)/2 = **25.5**.\n\nAnswer: **25.5**.",
    approach: "Average of 1 to n is (n + 1)/2. Average of the first n even numbers is n + 1; of the first n odd numbers, n.",
    tags: ["series"],
    timeTargetSec: 30,
  },

  /* ── Ages ──────────────────────────────────────────────────────── */
  {
    slug: "ag-father-thrice-son",
    topic: "ages",
    title: "Father three times the son",
    prompt: "A father is **three times** as old as his son. In **12 years** he will be **twice** as old. How old is the son now?",
    options: ["10", "12", "14", "16"],
    answer: 1,
    difficulty: "easy",
    hints: ["Let the son be s; the father is 3s.", "In 12 years: 3s + 12 = 2(s + 12)."],
    solution: "1. Son = s, father = 3s.\n2. After 12 years: 3s + 12 = 2(s + 12) = 2s + 24, so s = **12**.\n3. Check: 36 + 12 = 48 = 2 × 24. ✓\n\nAnswer: **12**.",
    approach: "Write the present ages with one variable, shift both by the same number of years, and equate. The difference between two people's ages never changes — a quick check on any answer.",
    tags: ["basics"],
    timeTargetSec: 50,
  },
  {
    slug: "ag-ratio-now-and-later",
    topic: "ages",
    title: "Ratio 5 : 7 now, 3 : 4 later",
    prompt: "The ages of A and B are in the ratio **5 : 7**. After **6 years** the ratio becomes **3 : 4**. What is A's present age?",
    options: ["25", "30", "35", "42"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let the ages be 5x and 7x.", "(5x + 6)/(7x + 6) = 3/4; cross-multiply."],
    solution:
      "1. Let A = 5x, B = 7x.\n2. (5x + 6)/(7x + 6) = 3/4 → 20x + 24 = 21x + 18 → x = 6.\n3. A = 5 × 6 = **30**.\n4. Check: 36/48 = 3/4. ✓\n\nAnswer: **30**.",
    approach: "Introduce one variable through the ratio (5x, 7x), then cross-multiply the later ratio. One linear equation, one unknown.",
    tags: ["ratio"],
    timeTargetSec: 60,
  },
  {
    slug: "ag-mother-daughter-sum",
    topic: "ages",
    title: "Mother and daughter",
    prompt: "The sum of the ages of a mother and her daughter is **50**. Five years ago the mother was **seven times** as old as the daughter. How old is the mother now?",
    options: ["35", "38", "40", "45"],
    answer: 2,
    difficulty: "medium",
    hints: ["Let the daughter be d now; the mother is 50 − d.", "Five years ago: 50 − d − 5 = 7(d − 5)."],
    solution:
      "1. Daughter = d, mother = 50 − d.\n2. Five years ago: 45 − d = 7(d − 5) = 7d − 35 → 8d = 80 → d = 10.\n3. Mother = 50 − 10 = **40**.\n4. Check: 35 = 7 × 5. ✓\n\nAnswer: **40**.",
    approach: "Use the sum to express one age through the other, so the 'years ago' condition becomes a single equation.",
    tags: ["years ago"],
    timeTargetSec: 60,
  },
  {
    slug: "ag-ten-years-ago-half",
    topic: "ages",
    title: "Half the age, ten years ago",
    prompt: "Ten years ago, Ram was **half** as old as Shyam. If their present ages are in the ratio **3 : 4**, what is the sum of their present ages?",
    options: ["30", "35", "40", "45"],
    answer: 1,
    difficulty: "medium",
    hints: ["Let the present ages be 3k and 4k.", "Ten years ago: 3k − 10 = (4k − 10)/2."],
    solution:
      "1. Ram = 3k, Shyam = 4k.\n2. Ten years ago: 2(3k − 10) = 4k − 10 → 6k − 20 = 4k − 10 → k = 5.\n3. Ages are 15 and 20; sum = **35**.\n4. Check: 5 is half of 10. ✓\n\nAnswer: **35**.",
    approach: "A present-day ratio gives the variable; the past or future statement gives the equation. Substitute k back before answering — the question may want a sum, not an age.",
    tags: ["ratio"],
    timeTargetSec: 60,
  },
  {
    slug: "ag-product-and-difference",
    topic: "ages",
    title: "Product 48, difference 2",
    prompt: "The product of the ages of two sisters is **48** and the difference is **2**. What is the sum of their ages?",
    options: ["12", "14", "16", "18"],
    answer: 1,
    difficulty: "easy",
    hints: ["Look for two factors of 48 that differ by 2.", "6 × 8 = 48."],
    solution: "1. Factor pairs of 48: (1, 48), (2, 24), (3, 16), (4, 12), (6, 8).\n2. The pair differing by 2 is 6 and 8.\n3. Sum = **14**.\n\nAnswer: **14**.",
    approach: "With small products, list factor pairs instead of solving a quadratic. If you must: (a + b)² = (a − b)² + 4ab = 4 + 192 = 196, so a + b = 14.",
    tags: ["factors"],
    timeTargetSec: 40,
  },
  {
    slug: "ag-percent-of-past-and-future",
    topic: "ages",
    title: "125% of ten years ago",
    prompt: "A man's present age is **125%** of his age **10 years ago** and **83⅓%** of his age **10 years hence**. What is his present age?",
    options: ["45", "50", "55", "60"],
    answer: 1,
    difficulty: "hard",
    hints: ["Use one condition to find the age; use the other only to check.", "a = 1.25(a − 10)."],
    solution:
      "1. Let the present age be a. Then a = 1.25(a − 10) = 1.25a − 12.5, so 0.25a = 12.5 and a = **50**.\n2. Check the second condition: 83⅓% of (50 + 10) = 5/6 × 60 = 50. ✓\n\nAnswer: **50**.",
    approach: "When a question gives two conditions for one unknown, the second is a consistency check, not extra work. Convert the awkward percentage 83⅓% to the fraction 5/6.",
    tags: ["percent"],
    timeTargetSec: 75,
  },
];
