import type { AptitudeSeed } from "./types.js";

/**
 * Quantitative aptitude, part two: time and work, time–speed–distance,
 * interest, permutations and combinations, probability, mixtures and
 * alligation, mensuration.
 */
export const QUANT_APPLIED: AptitudeSeed[] = [
  /* ── Time & Work ───────────────────────────────────────────────── */
  {
    slug: "tw-two-workers-together",
    topic: "time-and-work",
    title: "A and B working together",
    prompt: "A can finish a job in **12 days** and B in **18 days**. Working together, how long do they take?",
    options: ["6 days", "7.2 days", "7.5 days", "8 days"],
    answer: 1,
    difficulty: "easy",
    hints: ["Add their daily rates: 1/12 + 1/18.", "1/12 + 1/18 = 5/36 of the job per day."],
    solution: "1. A does 1/12 per day, B does 1/18 per day.\n2. Together: 1/12 + 1/18 = 3/36 + 2/36 = 5/36 per day.\n3. Time = 36/5 = **7.2 days**.\n\nAnswer: **7.2 days**.",
    approach: "Work in rates, not times. Or take the total work as the LCM of the times (36 units): A does 3 a day, B does 2, together 5, so 36/5 days. The LCM method avoids fractions entirely.",
    tags: ["rates"],
    timeTargetSec: 45,
  },
  {
    slug: "tw-a-leaves-early",
    topic: "time-and-work",
    title: "A leaves after four days",
    prompt: "A and B can finish a job in **10** and **15** days respectively. They start together, but A leaves after **4 days**. How many more days does B need to finish?",
    options: ["4", "5", "6", "7.5"],
    answer: 1,
    difficulty: "medium",
    hints: ["Take the work as 30 units: A does 3 a day, B does 2.", "In 4 days together they do 4 × 5 = 20 units; 10 remain for B alone."],
    solution:
      "1. Let the job be 30 units (LCM of 10 and 15). A does 3 units/day, B does 2.\n2. Together for 4 days: 4 × 5 = 20 units done; 10 remain.\n3. B alone at 2 units/day needs 10/2 = **5 days**.\n\nAnswer: **5 days**.",
    approach: "Choose the LCM of the given times as the total work so every rate is a whole number. Then it is bookkeeping: work done, work left, divide by the rate that continues.",
    tags: ["leaving early"],
    timeTargetSec: 60,
  },
  {
    slug: "tw-pipes-and-cistern",
    topic: "time-and-work",
    title: "Two inlets and one outlet",
    prompt: "Pipe A fills a tank in **6 hours**, pipe B in **9 hours**, and pipe C empties a full tank in **18 hours**. With all three open, how long does the tank take to fill?",
    options: ["4 h", "4.5 h", "5 h", "6 h"],
    answer: 1,
    difficulty: "medium",
    hints: ["An emptying pipe has a negative rate.", "1/6 + 1/9 − 1/18, with 18 as the common denominator."],
    solution:
      "1. Net rate = 1/6 + 1/9 − 1/18 = 3/18 + 2/18 − 1/18 = 4/18 = 2/9 of the tank per hour.\n2. Time = 9/2 = **4.5 hours**.\n\nAnswer: **4.5 h**.",
    approach: "Pipes are workers: inlets add rate, outlets subtract. Take the tank as 18 units (the LCM) and the rates become 3, 2 and −1 per hour, net 4, so 18/4 = 4.5.",
    tags: ["pipes"],
    timeTargetSec: 60,
  },
  {
    slug: "tw-twice-as-efficient",
    topic: "time-and-work",
    title: "A is twice as efficient as B",
    prompt: "A is **twice as efficient** as B, and together they finish a job in **8 days**. How long would B alone take?",
    options: ["12 days", "16 days", "24 days", "32 days"],
    answer: 2,
    difficulty: "medium",
    hints: ["If B does 1 unit a day, A does 2: together 3 units a day.", "Total work = 3 × 8 = 24 units."],
    solution: "1. Let B's rate be 1 unit/day; A's is 2 units/day; together 3 units/day.\n2. Total work = 3 × 8 = 24 units.\n3. B alone: 24/1 = **24 days**.\n\nAnswer: **24 days**.",
    approach: "Efficiency ratios translate directly into rate ratios. Pick the smallest rate as 1 unit and everything else follows.",
    tags: ["efficiency"],
    timeTargetSec: 50,
  },
  {
    slug: "tw-men-and-women",
    topic: "time-and-work",
    title: "Men, women and one job",
    prompt: "**6 men** or **10 women** can complete a job in **15 days**. How many days will **3 men and 5 women** take together?",
    options: ["10", "12", "15", "20"],
    answer: 2,
    difficulty: "medium",
    hints: ["6 men = 10 women in work rate, so 3 men = 5 women.", "3 men + 5 women = 10 women."],
    solution:
      "1. 6 men ≡ 10 women, so 3 men ≡ 5 women.\n2. 3 men + 5 women ≡ 5 women + 5 women = 10 women.\n3. 10 women take **15 days**.\n\nAnswer: **15 days**.",
    approach: "Convert everyone into one unit (men or women) using the equivalence given, then compare with the known group. Half of each group here is exactly the original workforce.",
    tags: ["equivalence"],
    timeTargetSec: 60,
  },
  {
    slug: "tw-alternate-days",
    topic: "time-and-work",
    title: "Working on alternate days",
    prompt: "A can do a job in **10 days** and B in **15 days**. They work on **alternate days**, A starting first. In how many days is the job finished?",
    options: ["11", "12", "12.5", "13"],
    answer: 1,
    difficulty: "hard",
    hints: ["Take the work as 30 units: A does 3 a day, B does 2.", "Every two days (one A day + one B day) 5 units are done. How many such pairs fit exactly?"],
    solution:
      "1. Work = 30 units. A does 3 units on his day, B does 2 on his.\n2. Each 2-day cycle completes 5 units; 30/5 = 6 cycles exactly.\n3. 6 cycles = **12 days**, and the job ends precisely at the close of B's sixth day.\n\nAnswer: **12 days**.",
    approach: "For alternate-day work, find the work per cycle and count whole cycles; then handle any remainder day by day, in order, checking who works that day. Here there is no remainder, which is where many candidates add an extra day by reflex.",
    tags: ["alternate days"],
    timeTargetSec: 90,
  },

  /* ── Time, Speed & Distance ────────────────────────────────────── */
  {
    slug: "tsd-train-passes-pole",
    topic: "time-speed-distance",
    title: "A train passes a pole",
    prompt: "A **150 m** long train passes a pole in **15 seconds**. What is its speed in **km/h**?",
    options: ["30 km/h", "36 km/h", "40 km/h", "45 km/h"],
    answer: 1,
    difficulty: "easy",
    hints: ["To pass a pole the train covers its own length.", "10 m/s; multiply by 18/5 for km/h."],
    solution: "1. Distance = train length = 150 m; time = 15 s; speed = 10 m/s.\n2. 10 m/s × 18/5 = **36 km/h**.\n\nAnswer: **36 km/h**.",
    approach: "m/s to km/h: multiply by 18/5; the reverse: multiply by 5/18. A train passing a point covers its own length; passing a platform, its length plus the platform's.",
    tags: ["trains", "unit conversion"],
    timeTargetSec: 40,
  },
  {
    slug: "tsd-train-crosses-platform",
    topic: "time-speed-distance",
    title: "A train crosses a platform",
    prompt: "A **200 m** train crosses a **300 m** platform in **25 seconds**. What is the speed of the train?",
    options: ["60 km/h", "72 km/h", "80 km/h", "90 km/h"],
    answer: 1,
    difficulty: "easy",
    hints: ["The train travels its own length plus the platform's length.", "500 m in 25 s = 20 m/s."],
    solution: "1. Distance covered = 200 + 300 = 500 m in 25 s, so speed = 20 m/s.\n2. 20 × 18/5 = **72 km/h**.\n\nAnswer: **72 km/h**.",
    approach: "Crossing an object of length L means covering (train length + L). For a person or a pole, L = 0.",
    tags: ["trains"],
    timeTargetSec: 45,
  },
  {
    slug: "tsd-boat-there-and-back",
    topic: "time-speed-distance",
    title: "Downstream and back",
    prompt: "A boat's speed in still water is **12 km/h** and the stream flows at **3 km/h**. How long does the boat take to go **45 km** downstream and return?",
    options: ["7 h", "8 h", "9 h", "10 h"],
    answer: 1,
    difficulty: "medium",
    hints: ["Downstream speed = 12 + 3; upstream speed = 12 − 3.", "45/15 + 45/9."],
    solution: "1. Downstream: 15 km/h, so 45/15 = 3 h.\n2. Upstream: 9 km/h, so 45/9 = 5 h.\n3. Total = **8 hours**.\n\nAnswer: **8 h**.",
    approach: "Downstream = boat + stream; upstream = boat − stream. Given both, boat speed is their average and stream speed is half their difference.",
    tags: ["boats and streams"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd-average-speed-round-trip",
    topic: "time-speed-distance",
    title: "Average speed of a round trip",
    prompt: "A car travels from P to Q at **60 km/h** and returns at **40 km/h**. What is the average speed for the whole trip?",
    options: ["45 km/h", "48 km/h", "50 km/h", "52 km/h"],
    answer: 1,
    difficulty: "medium",
    hints: ["It is not 50. Average speed = total distance ÷ total time.", "For equal distances, average = 2ab/(a + b)."],
    solution:
      "1. Let PQ = 120 km (any distance works). Going: 120/60 = 2 h. Returning: 120/40 = 3 h.\n2. Average = 240 km / 5 h = **48 km/h**.\n3. Or 2 × 60 × 40 / (60 + 40) = 4800/100 = 48.\n\nAnswer: **48 km/h**.",
    approach: "Equal distances at speeds a and b average to the harmonic mean 2ab/(a + b), always below the arithmetic mean. Equal times would average to (a + b)/2.",
    tags: ["average speed"],
    timeTargetSec: 50,
  },
  {
    slug: "tsd-trains-opposite-directions",
    topic: "time-speed-distance",
    title: "Two trains cross each other",
    prompt: "Two trains, **120 m** and **180 m** long, run towards each other at **54 km/h** and **36 km/h**. How long do they take to cross each other?",
    options: ["10 s", "12 s", "15 s", "18 s"],
    answer: 1,
    difficulty: "medium",
    hints: ["Opposite directions: add the speeds.", "90 km/h = 25 m/s; distance = 120 + 180."],
    solution: "1. Relative speed = 54 + 36 = 90 km/h = 90 × 5/18 = 25 m/s.\n2. Distance to clear = 120 + 180 = 300 m.\n3. Time = 300/25 = **12 s**.\n\nAnswer: **12 s**.",
    approach: "Opposite directions add speeds; same direction subtracts them. The distance is always the sum of both lengths when trains cross each other.",
    tags: ["relative speed"],
    timeTargetSec: 60,
  },
  {
    slug: "tsd-late-and-early",
    topic: "time-speed-distance",
    title: "Ten minutes late, five minutes early",
    prompt: "Walking at **4 km/h** a man reaches his office **10 minutes late**; at **6 km/h** he reaches **5 minutes early**. How far is the office?",
    options: ["2 km", "3 km", "4 km", "5 km"],
    answer: 1,
    difficulty: "hard",
    hints: ["The two journeys differ in time by 15 minutes = 1/4 hour.", "d/4 − d/6 = 1/4."],
    solution:
      "1. Time difference between the two speeds = 10 + 5 = 15 min = 1/4 h.\n2. d/4 − d/6 = 1/4 → d(3 − 2)/12 = 1/4 → d/12 = 1/4 → d = **3 km**.\n3. Check: 3/4 h = 45 min and 3/6 h = 30 min, a difference of 15 min. ✓\n\nAnswer: **3 km**.",
    approach: "Late by a and early by b means the two trips differ by (a + b) in time. Set d/s₁ − d/s₂ equal to that difference; the fixed 'on-time' moment never needs to be found.",
    tags: ["late early"],
    timeTargetSec: 90,
  },

  /* ── Interest ──────────────────────────────────────────────────── */
  {
    slug: "in-simple-interest-basic",
    topic: "interest",
    title: "Simple interest for four years",
    prompt: "What is the simple interest on **₹8,000** at **7.5% per annum** for **4 years**?",
    options: ["₹2,000", "₹2,200", "₹2,400", "₹2,600"],
    answer: 2,
    difficulty: "easy",
    hints: ["SI = P × R × T / 100.", "8000 × 7.5 × 4 / 100."],
    solution: "1. SI = 8000 × 7.5 × 4 / 100 = 8000 × 0.3 = **₹2,400**.\n\nAnswer: **₹2,400**.",
    approach: "Simple interest is linear: rate × time gives the total percentage (7.5 × 4 = 30%), then take that percentage of the principal.",
    tags: ["simple interest"],
    timeTargetSec: 40,
  },
  {
    slug: "in-compound-two-years",
    topic: "interest",
    title: "Compound interest for two years",
    prompt: "What is the compound interest on **₹10,000** at **10% per annum** for **2 years**, compounded annually?",
    options: ["₹2,000", "₹2,100", "₹2,200", "₹2,500"],
    answer: 1,
    difficulty: "easy",
    hints: ["Amount = P(1 + r)²; interest = amount − P.", "10,000 × 1.21."],
    solution: "1. Amount = 10,000 × 1.1² = 10,000 × 1.21 = 12,100.\n2. CI = 12,100 − 10,000 = **₹2,100**.\n\nAnswer: **₹2,100**.",
    approach: "For two years, CI% = 2r + r²/100 (here 20 + 1 = 21%). The extra r²/100 is the interest on the first year's interest.",
    tags: ["compound interest"],
    timeTargetSec: 40,
  },
  {
    slug: "in-ci-minus-si",
    topic: "interest",
    title: "Difference between CI and SI",
    prompt: "What is the difference between compound and simple interest on **₹5,000** at **8% per annum** for **2 years**?",
    options: ["₹30", "₹32", "₹36", "₹40"],
    answer: 1,
    difficulty: "medium",
    hints: ["For two years the difference is the interest on the first year's interest.", "P × (r/100)²."],
    solution: "1. For 2 years, CI − SI = P(r/100)² = 5000 × 0.08² = 5000 × 0.0064 = **₹32**.\n2. Check: SI = 800; CI = 5000 × 1.0816 − 5000 = 408 + … = 832. Difference 32. ✓\n\nAnswer: **₹32**.",
    approach: "Two-year difference = P(r/100)². Three-year difference = P(r/100)²(3 + r/100). These save a full amount calculation.",
    tags: ["ci vs si"],
    timeTargetSec: 50,
  },
  {
    slug: "in-doubling-rate",
    topic: "interest",
    title: "Doubling in eight years",
    prompt: "At what rate of **simple interest** will a sum **double** itself in **8 years**?",
    options: ["10%", "12.5%", "15%", "16%"],
    answer: 1,
    difficulty: "easy",
    hints: ["Doubling means the interest equals the principal, i.e. 100% in total.", "100% over 8 years."],
    solution: "1. To double, SI must equal P, i.e. R × T = 100.\n2. R = 100/8 = **12.5%**.\n\nAnswer: **12.5%**.",
    approach: "Under simple interest, a sum becomes n times itself when R × T = 100(n − 1). Doubling: RT = 100; tripling: RT = 200.",
    tags: ["doubling"],
    timeTargetSec: 40,
  },
  {
    slug: "in-principal-from-amount",
    topic: "interest",
    title: "Working back to the principal",
    prompt: "A sum grows to **₹6,050** in **2 years** at **10% per annum** compound interest. What was the sum?",
    options: ["₹4,800", "₹5,000", "₹5,200", "₹5,500"],
    answer: 1,
    difficulty: "easy",
    hints: ["Amount = P × 1.1².", "Divide 6,050 by 1.21."],
    solution: "1. 6050 = P × 1.21.\n2. P = 6050/1.21 = **₹5,000**.\n\nAnswer: **₹5,000**.",
    approach: "Present value = amount ÷ (1 + r)ⁿ. Recognise 1.21 = 1.1², 1.331 = 1.1³, 1.44 = 1.2² and the division is instant.",
    tags: ["present value"],
    timeTargetSec: 40,
  },
  {
    slug: "in-half-yearly-compounding",
    topic: "interest",
    title: "Compounded half-yearly",
    prompt: "What is the compound interest on **₹16,000** at **20% per annum** for **1 year**, compounded **half-yearly**?",
    options: ["₹3,200", "₹3,360", "₹3,400", "₹3,520"],
    answer: 1,
    difficulty: "medium",
    hints: ["Half-yearly: halve the rate and double the number of periods.", "10% per half-year for 2 periods: 16,000 × 1.21."],
    solution: "1. Rate per half-year = 10%; periods = 2.\n2. Amount = 16,000 × 1.1² = 16,000 × 1.21 = 19,360.\n3. CI = 19,360 − 16,000 = **₹3,360**.\n\nAnswer: **₹3,360**.",
    approach: "Compounding k times a year: rate/k per period, n × k periods. More frequent compounding always earns slightly more than annual (here 3,360 versus 3,200).",
    tags: ["half-yearly"],
    timeTargetSec: 60,
  },

  /* ── Permutations & Combinations ───────────────────────────────── */
  {
    slug: "pnc-arrange-mango",
    topic: "permutations-combinations",
    title: "Arranging the letters of MANGO",
    prompt: "How many different arrangements can be made from the letters of the word **MANGO**?",
    options: ["60", "100", "120", "240"],
    answer: 2,
    difficulty: "easy",
    hints: ["All five letters are different.", "5 × 4 × 3 × 2 × 1."],
    solution: "1. Five distinct letters can be arranged in 5! ways.\n2. 5! = **120**.\n\nAnswer: **120**.",
    approach: "n distinct objects arrange in n! ways. The moment letters repeat, divide by the factorial of each repeat count.",
    tags: ["arrangements"],
    timeTargetSec: 30,
  },
  {
    slug: "pnc-arrange-banana",
    topic: "permutations-combinations",
    title: "Arranging the letters of BANANA",
    prompt: "How many distinct arrangements are there of the letters of **BANANA**?",
    options: ["40", "60", "120", "360"],
    answer: 1,
    difficulty: "medium",
    hints: ["BANANA has 6 letters: A three times, N twice, B once.", "6! ÷ (3! × 2!)."],
    solution: "1. 6 letters with A repeated 3 times and N repeated 2 times.\n2. Arrangements = 6!/(3! 2!) = 720/12 = **60**.\n\nAnswer: **60**.",
    approach: "Arrangements of n objects with repeats = n! divided by the product of the factorials of the repeat counts.",
    tags: ["repeated letters"],
    timeTargetSec: 45,
  },
  {
    slug: "pnc-committee-at-least-one-woman",
    topic: "permutations-combinations",
    title: "A committee with at least one woman",
    prompt: "From **5 men** and **4 women**, how many committees of **3** can be formed that include **at least one woman**?",
    options: ["70", "74", "80", "84"],
    answer: 1,
    difficulty: "medium",
    hints: ["'At least one' is easier as 'all minus none'.", "C(9,3) − C(5,3)."],
    solution: "1. All committees of 3 from 9 people: C(9,3) = 84.\n2. Committees with no woman (all men): C(5,3) = 10.\n3. At least one woman: 84 − 10 = **74**.\n\nAnswer: **74**.",
    approach: "'At least one' = total − 'none'. Counting the cases 1, 2, 3 women separately gives the same 40 + 30 + 4 = 74 but takes three times as long.",
    tags: ["combinations", "at least one"],
    timeTargetSec: 60,
  },
  {
    slug: "pnc-three-digit-distinct",
    topic: "permutations-combinations",
    title: "Three-digit numbers with distinct digits",
    prompt: "How many **three-digit** numbers with **all digits different** can be formed using the digits **1 to 6**?",
    options: ["100", "120", "150", "216"],
    answer: 1,
    difficulty: "easy",
    hints: ["Fill the places one at a time.", "6 choices, then 5, then 4."],
    solution: "1. Hundreds digit: 6 choices; tens: 5 remaining; units: 4 remaining.\n2. 6 × 5 × 4 = **120**.\n\nAnswer: **120**.",
    approach: "Fill positions in order and multiply the choices. Watch for a zero, which cannot lead; there is none here.",
    tags: ["digits"],
    timeTargetSec: 40,
  },
  {
    slug: "pnc-round-table",
    topic: "permutations-combinations",
    title: "Six people around a round table",
    prompt: "In how many ways can **6** people be seated around a **round** table?",
    options: ["60", "120", "240", "720"],
    answer: 1,
    difficulty: "easy",
    hints: ["Rotations of the same seating are not counted as different.", "Fix one person; arrange the other five."],
    solution: "1. Fix one person to remove rotations; the remaining 5 can be arranged in 5! ways.\n2. 5! = **120**.\n\nAnswer: **120**.",
    approach: "Circular arrangements of n people = (n − 1)!. If the table can also be flipped (necklaces, garlands), halve it again: (n − 1)!/2.",
    tags: ["circular"],
    timeTargetSec: 40,
  },
  {
    slug: "pnc-handshakes",
    topic: "permutations-combinations",
    title: "Handshakes at a party",
    prompt: "At a party every person shakes hands exactly once with every other person, making **66** handshakes in all. How many people are there?",
    options: ["11", "12", "13", "22"],
    answer: 1,
    difficulty: "medium",
    hints: ["A handshake is a pair of people: C(n, 2).", "n(n − 1)/2 = 66."],
    solution: "1. Handshakes = C(n,2) = n(n − 1)/2 = 66, so n(n − 1) = 132.\n2. 12 × 11 = 132, so n = **12**.\n\nAnswer: **12**.",
    approach: "Handshakes, matches in a league, diagonals plus sides of a polygon — all are C(n,2). Solve n(n − 1) = 2k by finding consecutive factors.",
    tags: ["combinations"],
    timeTargetSec: 50,
  },

  /* ── Probability ───────────────────────────────────────────────── */
  {
    slug: "pr-two-dice-sum-nine",
    topic: "probability",
    title: "Sum of two dice is 9",
    prompt: "Two fair dice are rolled. What is the probability that the sum is **9**?",
    options: ["1/12", "5/36", "1/6", "1/9"],
    answer: 3,
    difficulty: "easy",
    hints: ["There are 36 equally likely outcomes.", "List the ordered pairs that add to 9."],
    solution: "1. Pairs summing to 9: (3,6), (4,5), (5,4), (6,3) — 4 outcomes.\n2. Probability = 4/36 = **1/9**.\n\nAnswer: **1/9**.",
    approach: "For two dice, the number of ways to get a sum s is s − 1 for s ≤ 7 and 13 − s for s ≥ 7. So sum 9 has 4 ways, sum 7 has 6.",
    tags: ["dice"],
    timeTargetSec: 45,
  },
  {
    slug: "pr-king-or-heart",
    topic: "probability",
    title: "A king or a heart",
    prompt: "One card is drawn from a standard pack of 52. What is the probability that it is a **king or a heart**?",
    options: ["17/52", "1/4", "15/52", "4/13"],
    answer: 3,
    difficulty: "easy",
    hints: ["Kings: 4. Hearts: 13. One card is both.", "4 + 13 − 1."],
    solution: "1. Favourable cards = 4 kings + 13 hearts − 1 (the king of hearts, counted twice) = 16.\n2. Probability = 16/52 = **4/13**.\n\nAnswer: **4/13**.",
    approach: "P(A or B) = P(A) + P(B) − P(A and B). Forgetting the overlap gives 17/52, which is offered as a trap.",
    tags: ["cards", "union"],
    timeTargetSec: 45,
  },
  {
    slug: "pr-two-red-without-replacement",
    topic: "probability",
    title: "Two reds without replacement",
    prompt: "A bag has **4 red** and **6 blue** balls. Two balls are drawn one after another **without replacement**. What is the probability that both are red?",
    options: ["6/45", "2/15", "4/25", "1/5"],
    answer: 1,
    difficulty: "medium",
    hints: ["After one red is drawn, 3 reds remain among 9 balls.", "(4/10) × (3/9)."],
    solution: "1. P(first red) = 4/10. P(second red | first red) = 3/9.\n2. P(both red) = 4/10 × 3/9 = 12/90 = **2/15**.\n3. Or C(4,2)/C(10,2) = 6/45 = 2/15.\n\nAnswer: **2/15**.",
    approach: "Without replacement, update both numerator and denominator after each draw — or count combinations directly. With replacement it would be (4/10)² = 4/25.",
    tags: ["without replacement"],
    timeTargetSec: 50,
  },
  {
    slug: "pr-three-coins-at-least-two-heads",
    topic: "probability",
    title: "At least two heads in three tosses",
    prompt: "Three fair coins are tossed. What is the probability of getting **at least two heads**?",
    options: ["1/4", "3/8", "1/2", "5/8"],
    answer: 2,
    difficulty: "easy",
    hints: ["There are 8 outcomes.", "Count outcomes with exactly 2 heads and exactly 3 heads."],
    solution: "1. Exactly two heads: HHT, HTH, THH (3). Exactly three: HHH (1).\n2. Favourable = 4 of 8, probability = **1/2**.\n\nAnswer: **1/2**.",
    approach: "With a small sample space, list it. By symmetry, 'at least two heads' and 'at least two tails' are equally likely and together cover everything, so each is 1/2.",
    tags: ["coins"],
    timeTargetSec: 40,
  },
  {
    slug: "pr-leap-year-53-sundays",
    topic: "probability",
    title: "53 Sundays in a leap year",
    prompt: "What is the probability that a **leap year** has **53 Sundays**?",
    options: ["3/7", "1/2", "1/7", "2/7"],
    answer: 3,
    difficulty: "medium",
    hints: ["366 days = 52 weeks + 2 extra days.", "The two extra days are consecutive; which pairs include a Sunday?"],
    solution:
      "1. 366 = 52 × 7 + 2, so every weekday occurs 52 times plus two consecutive extra days.\n2. The extra pair is one of 7 equally likely pairs: (Sun,Mon), (Mon,Tue), …, (Sat,Sun). Two of them contain a Sunday.\n3. Probability = **2/7**.\n\nAnswer: **2/7**.",
    approach: "A leap year has 2 spare days, a normal year 1. So P(53 of a given day) = 2/7 in a leap year and 1/7 otherwise.",
    tags: ["calendar"],
    timeTargetSec: 60,
  },
  {
    slug: "pr-problem-solved-by-either",
    topic: "probability",
    title: "Solved by at least one of them",
    prompt: "A can solve a problem with probability **2/3** and B with probability **3/4**, independently. What is the probability that the problem is solved?",
    options: ["1/2", "5/12", "11/12", "3/4"],
    answer: 2,
    difficulty: "medium",
    hints: ["'Solved' means at least one solves it. Find the probability that neither does.", "P(neither) = (1/3)(1/4)."],
    solution: "1. P(A fails) = 1/3, P(B fails) = 1/4; independent, so P(both fail) = 1/12.\n2. P(solved) = 1 − 1/12 = **11/12**.\n\nAnswer: **11/12**.",
    approach: "For independent events, P(at least one) = 1 − product of the failure probabilities. Complements turn 'or' questions into one multiplication.",
    tags: ["independent events"],
    timeTargetSec: 50,
  },

  /* ── Mixtures & Alligation ─────────────────────────────────────── */
  {
    slug: "ma-mixing-two-prices",
    topic: "mixtures-alligation",
    title: "Mixing rice of two prices",
    prompt: "Rice at **₹40/kg** is mixed with rice at **₹60/kg** so that the mixture costs **₹52/kg**. In what ratio are they mixed?",
    options: ["3 : 4", "2 : 3", "3 : 2", "1 : 2"],
    answer: 1,
    difficulty: "easy",
    hints: ["Alligation: the ratio is (dearer − mean) : (mean − cheaper).", "(60 − 52) : (52 − 40)."],
    solution: "1. Cheaper : dearer = (60 − 52) : (52 − 40) = 8 : 12 = **2 : 3**.\n2. Check: (2 × 40 + 3 × 60)/5 = 260/5 = 52. ✓\n\nAnswer: **2 : 3**.",
    approach: "The alligation cross: quantity of cheaper ÷ quantity of dearer = (dearer − mean) ÷ (mean − cheaper). The mean sits closer to the ingredient there is more of.",
    tags: ["alligation"],
    timeTargetSec: 45,
  },
  {
    slug: "ma-add-water-to-milk",
    topic: "mixtures-alligation",
    title: "Adding water to a milk mixture",
    prompt: "A **60-litre** mixture contains milk and water in the ratio **2 : 1**. How much water must be added to make the ratio **1 : 1**?",
    options: ["10 L", "15 L", "20 L", "30 L"],
    answer: 2,
    difficulty: "easy",
    hints: ["Milk stays fixed at 40 L; only water changes.", "For 1 : 1, water must also be 40 L."],
    solution: "1. Milk = 2/3 × 60 = 40 L; water = 20 L.\n2. For 1 : 1, water must equal milk = 40 L.\n3. Add 40 − 20 = **20 L**.\n\nAnswer: **20 L**.",
    approach: "Anchor on the component that does not change (milk) and work out what the other must become. Never re-derive both.",
    tags: ["milk and water"],
    timeTargetSec: 45,
  },
  {
    slug: "ma-replace-twice",
    topic: "mixtures-alligation",
    title: "Replacing milk with water, twice",
    prompt: "A vessel holds **100 L** of milk. **10 L** is drawn off and replaced with water, and this is done **twice** in all. How much milk remains?",
    options: ["80 L", "81 L", "82 L", "90 L"],
    answer: 1,
    difficulty: "medium",
    hints: ["Each replacement leaves 90% of the milk that was there.", "100 × 0.9 × 0.9."],
    solution: "1. Each operation removes 10% of the current milk, leaving 90%.\n2. After two operations: 100 × 0.9² = **81 L**.\n\nAnswer: **81 L**.",
    approach: "Repeated replacement: remaining = initial × (1 − drawn/total)ⁿ. It is a compound-decay formula in disguise.",
    tags: ["replacement"],
    timeTargetSec: 50,
  },
  {
    slug: "ma-two-alloys",
    topic: "mixtures-alligation",
    title: "Blending two alloys",
    prompt: "Alloy A is **40% copper** and alloy B is **70% copper**. In what ratio should they be melted together to give an alloy that is **50% copper**?",
    options: ["3 : 2", "1 : 1", "2 : 1", "1 : 2"],
    answer: 2,
    difficulty: "easy",
    hints: ["Alligation on the copper percentages.", "(70 − 50) : (50 − 40)."],
    solution: "1. A : B = (70 − 50) : (50 − 40) = 20 : 10 = **2 : 1**.\n2. Check: (2 × 40 + 1 × 70)/3 = 150/3 = 50. ✓\n\nAnswer: **2 : 1**.",
    approach: "Percent concentrations obey the same alligation cross as prices. The target closer to A means more of A.",
    tags: ["alloys"],
    timeTargetSec: 45,
  },
  {
    slug: "ma-skilled-and-unskilled",
    topic: "mixtures-alligation",
    title: "Skilled and unskilled workers",
    prompt: "The average wage of **30** workers is **₹500**. Skilled workers earn **₹600** and unskilled **₹450**. How many workers are skilled?",
    options: ["10", "12", "15", "20"],
    answer: 0,
    difficulty: "medium",
    hints: ["Alligation with the average as the mean.", "Skilled : unskilled = (500 − 450) : (600 − 500)."],
    solution: "1. Skilled : unskilled = (500 − 450) : (600 − 500) = 50 : 100 = 1 : 2.\n2. Skilled = 1/3 × 30 = **10**.\n3. Check: (10 × 600 + 20 × 450)/30 = 15,000/30 = 500. ✓\n\nAnswer: **10**.",
    approach: "Any weighted-average question with two groups is an alligation. The group whose value is farther from the mean is the smaller group.",
    tags: ["weighted average"],
    timeTargetSec: 60,
  },
  {
    slug: "ma-dilute-acid",
    topic: "mixtures-alligation",
    title: "Diluting an acid solution",
    prompt: "How much water must be added to **40 L** of a **30%** acid solution to make it a **20%** solution?",
    options: ["10 L", "15 L", "20 L", "25 L"],
    answer: 2,
    difficulty: "easy",
    hints: ["The amount of acid does not change: 12 L.", "12 = 20% of the new total."],
    solution: "1. Acid = 30% of 40 = 12 L, and it stays 12 L.\n2. New total = 12/0.2 = 60 L.\n3. Water added = 60 − 40 = **20 L**.\n\nAnswer: **20 L**.",
    approach: "Dilution keeps the solute fixed. Solute ÷ new concentration = new total volume; subtract the old volume.",
    tags: ["dilution"],
    timeTargetSec: 45,
  },

  /* ── Mensuration ───────────────────────────────────────────────── */
  {
    slug: "me-rectangle-from-perimeter",
    topic: "mensuration",
    title: "Area from perimeter and length",
    prompt: "A rectangle has a perimeter of **56 cm** and a length of **16 cm**. What is its area?",
    options: ["168 cm²", "180 cm²", "192 cm²", "224 cm²"],
    answer: 2,
    difficulty: "easy",
    hints: ["Perimeter = 2(l + b), so l + b = 28.", "Breadth = 28 − 16."],
    solution: "1. l + b = 56/2 = 28, so b = 28 − 16 = 12 cm.\n2. Area = 16 × 12 = **192 cm²**.\n\nAnswer: **192 cm²**.",
    approach: "Halve the perimeter to get l + b, then subtract the known side. Two lines, no equations.",
    tags: ["rectangle"],
    timeTargetSec: 40,
  },
  {
    slug: "me-circle-from-circumference",
    topic: "mensuration",
    title: "Area of a circle from its circumference",
    prompt: "The circumference of a circle is **44 cm**. What is its area? (Take π = 22/7.)",
    options: ["144 cm²", "154 cm²", "164 cm²", "176 cm²"],
    answer: 1,
    difficulty: "easy",
    hints: ["2πr = 44 gives r.", "r = 7; area = πr²."],
    solution: "1. 2 × 22/7 × r = 44 → r = 7 cm.\n2. Area = 22/7 × 49 = **154 cm²**.\n\nAnswer: **154 cm²**.",
    approach: "With π = 22/7, radii that are multiples of 7 make everything cancel. Circumference 44 ↔ r = 7 ↔ area 154 is worth remembering.",
    tags: ["circle"],
    timeTargetSec: 40,
  },
  {
    slug: "me-cylinder-volume",
    topic: "mensuration",
    title: "Volume of a cylinder",
    prompt: "What is the volume of a cylinder with radius **7 cm** and height **10 cm**? (Take π = 22/7.)",
    options: ["1,440 cm³", "1,540 cm³", "1,650 cm³", "1,760 cm³"],
    answer: 1,
    difficulty: "easy",
    hints: ["Volume = πr²h.", "22/7 × 49 × 10."],
    solution: "1. V = πr²h = 22/7 × 7 × 7 × 10 = 22 × 7 × 10 = **1,540 cm³**.\n\nAnswer: **1,540 cm³**.",
    approach: "Base area × height for any prism or cylinder. Cancel the 7 in π = 22/7 against the radius before multiplying.",
    tags: ["cylinder"],
    timeTargetSec: 40,
  },
  {
    slug: "me-cube-from-surface-area",
    topic: "mensuration",
    title: "Volume of a cube from its surface area",
    prompt: "The total surface area of a cube is **216 cm²**. What is its volume?",
    options: ["144 cm³", "196 cm³", "216 cm³", "256 cm³"],
    answer: 2,
    difficulty: "easy",
    hints: ["A cube has 6 equal square faces: 6a² = 216.", "a = 6."],
    solution: "1. 6a² = 216 → a² = 36 → a = 6 cm.\n2. Volume = 6³ = **216 cm³**.\n\nAnswer: **216 cm³**.",
    approach: "Cube: surface 6a², volume a³, diagonal a√3. The coincidence that 216 appears twice here is because a = 6 makes 6a² = a³.",
    tags: ["cube"],
    timeTargetSec: 40,
  },
  {
    slug: "me-triangle-5-12-13",
    topic: "mensuration",
    title: "Area of a 5–12–13 triangle",
    prompt: "What is the area of a triangle with sides **5 cm, 12 cm and 13 cm**?",
    options: ["30 cm²", "32.5 cm²", "60 cm²", "65 cm²"],
    answer: 0,
    difficulty: "easy",
    hints: ["Check whether 5² + 12² = 13².", "A right triangle's area is half the product of the legs."],
    solution: "1. 25 + 144 = 169 = 13², so the triangle is right-angled with legs 5 and 12.\n2. Area = ½ × 5 × 12 = **30 cm²**.\n\nAnswer: **30 cm²**.",
    approach: "Recognise Pythagorean triples (3-4-5, 5-12-13, 8-15-17, 7-24-25) and skip Heron's formula entirely.",
    tags: ["triangle"],
    timeTargetSec: 40,
  },
  {
    slug: "me-path-inside-field",
    topic: "mensuration",
    title: "A path inside a rectangular field",
    prompt: "A path **2 m** wide runs **inside** a rectangular field **30 m × 20 m**, along its boundary. What is the area of the path?",
    options: ["176 m²", "184 m²", "192 m²", "200 m²"],
    answer: 1,
    difficulty: "medium",
    hints: ["Path area = outer rectangle − inner rectangle.", "The inner rectangle is (30 − 4) × (20 − 4)."],
    solution: "1. Outer area = 30 × 20 = 600 m².\n2. Inner rectangle (path removed on all sides): (30 − 4) × (20 − 4) = 26 × 16 = 416 m².\n3. Path = 600 − 416 = **184 m²**.\n\nAnswer: **184 m²**.",
    approach: "A border path is the difference of two rectangles; the width comes off twice from each dimension. For an outside path, add 2w instead.",
    tags: ["path"],
    timeTargetSec: 60,
  },
];
