/** Origin attribution per challenge title — the company/incident that inspired it. */

export const ORIGINS: Record<string, string> = {
  // ── Originals ──
  "The Checkout Meltdown": "Classic e-commerce",
  "Ghost Rows in the Audit Log": "Every admin dashboard",
  "Access Denied at Midnight": "Production on-call",
  "The Vanishing Search Results": "Typeahead search UIs",
  "False Positives at the Signup Gate": "Signup-form lore",
  "The Token That Never Dies": "JWT deployments",
  "Rate Limiter Free-for-All": "Public API platforms",
  "The Phantom WHERE Clause": "ORM refactors",
  "Cache Stampede at Dawn": "Analytics at scale",
  // ── Wave 2 ──
  "The 140-Character Lie": "Twitter",
  "The Resurfaced Memory": "Facebook · Year in Review",
  "Shuffle Isn't Random": "Spotify",
  "Ten Seconds to Next Episode": "Netflix autoplay",
  "The Phantom Unread Badge": "Slack",
  "Double-Charged at Checkout": "Stripe idempotency",
  "The One-Night Overcharge": "Airbnb-style booking",
  "Cursor Chaos After the Emoji": "Google Docs",
  "The Upvote That Counted Twice": "Reddit",
  "Infinite Scroll, Infinite Repeats": "TikTok feeds",
  "Undo Send Never Works": "Gmail",
  "The ETA That Went Negative": "Uber",
  // ── Wave 3 ──
  "The Flag That Fired Old Code": "Knight Capital · 2012",
  "One Typo, Half the Internet": "AWS S3 · 2017",
  "The Greedy Regex": "Cloudflare · 2019",
  "The Leap Day Meltdown": "GitHub · 2012",
  "Left-Pad the World": "npm · 2016",
  "The Negative Invoice": "PayPal-class exploits",
  "Infinite Leverage": "Robinhood · 2019",
  "The Null Price Latte": "Starbucks POS",
  "Retry After What?": "Slack API clients",
  "The Replayed Webhook": "Stripe webhooks",
  "Happy New Year, Dropped Messages": "WhatsApp NYE",
  "Locked Out of Everything": "Facebook · 2021",
  // ── Wave 4 ──
  "The Zune Freeze": "Microsoft Zune · 2008",
  "248 Days to Reboot": "Boeing 787",
  "Ariane's Sixteen Bits": "Ariane 5 · 1996",
  "The Year 2038 Problem": "Unix time",
  "Gangnam Style Broke the Counter": "YouTube · 2014",
  "The Negative Shard": "Java hashCode lore",
  "The Auction That Closed Instantly": "eBay-class markets",
  "The February 29th Certificate": "Microsoft Azure · 2012",
  "Satoshis, Not Doubles": "Crypto exchanges",
  "The Clock That Ran Backwards": "Twitter Snowflake",
  "The Midpoint That Overflowed": "The JDK itself",
  "Sessions for Someone Else": "Java == lore",
  // ── Wave 5 ──
  "The Metric Mars Mission": "NASA · Mars Climate Orbiter",
  "The Patriot's Drifting Clock": "Patriot missile · 1991",
  "The 1900 Leap Year Lie": "Excel / Lotus 1-2-3",
  "The Alarm That Slept In": "Apple iOS alarms",
  "Two Digits Too Few": "Y2K",
  "The Index That Rounded Itself Poor": "Vancouver Stock Exchange",
  "Half an Emoji in the Username": "MySQL utf8",
  "Noon in Which Timezone?": "Calendar apps",
  "The Ledger That Leaked Cents": "Floating-point money lore",
  "The Missing Table Rows": "Intel Pentium · 1994",
  "The Streak That Died at Midnight": "Duolingo-class apps",
  "The Backup That Backed Up Nothing": "GitLab · 2017",
  // ── Wave 6 ──
  "The N+1 Query Storm": "Every ORM",
  "Release the Connection!": "Connection pools",
  "The Optimistic Lock That Wasn't": "CMS platforms",
  "Keyset Without a Tiebreak": "Data-export pipelines",
  "IN () Means Nothing": "Query builders",
  "NULL Isn't Equal to NULL": "SQL three-valued logic",
  "Read Your Own Writes": "Replicated databases",
  "The Cache Key With a Twist": "CDN edges",
  "The Runaway Retry": "Retry storms",
  "Escaping the Wildcard": "Search boxes",
  "The Half-Applied Batch": "Ledger systems",
  "The Rotation That Ate the Backups": "Retention scripts",
  "The Upsert That Forgot to Add": "Analytics counters",
  // ── Wave 7 ──
  "alg: none": "JWT libraries · 2015",
  "The Wrong Audience": "OAuth deployments",
  "Heartbleed's Little Cousin": "OpenSSL · 2014",
  "The Path That Climbed Out": "Path traversal · CWE-22",
  "The Open Redirect": "Login pages everywhere",
  "The Lookalike Domain": "IDN homographs",
  "The Spreadsheet That Ran Code": "CSV injection",
  "The Log That Looked Things Up": "Log4Shell · 2021",
  "The Regex That Trusted Email": "Email-validation lore",
  "Rounded Out of a Refund": "Python round()",
  "The Tip That Didn't Add Up": "Gig-economy payouts",
  "The 37th of March": "java.util.Calendar",
  "Default Country Roulette": "Twilio-class SMS",
  // ── Wave 8 ──
  "The Gene Named September 2nd": "Excel × genomics",
  "Stuck on Mute": "Zoom-era calls",
  "Six Degrees, Give or Take": "LinkedIn",
  "The Leaning Tower of Pins": "Pinterest",
  "The 130% Progress Bar": "Upload dialogs",
  "The Toast That Never Left": "Notification trays",
  "The Infinite Spinner": "Every SPA",
  "The Leaderboard Shuffle": "Live-ops games",
  "The Coupon That Stacked Itself": "Black Friday",
  "The Generator That Vanished": "Python generators",
  "The Mutable Default Trap": "Python footguns",
  "The Reducer That Bit the Hand": "Redux lore",
  "A Century of Missing Interest": "Core banking",
  // ── Wave 9 ──
  "The One-Cent Book of Madness": "Amazon repricers",
  "Sold Out, Sold Again": "Ticketmaster-class sales",
  "The Negative-Price Flash Sale": "Steam-class sales",
  "The Notification Echo": "Coinbase-class alerts",
  "Nine A.M. Somewhere": "Lifecycle email",
  "Version 1.10 Beats Version 1.9": "Auto-updaters",
  "The Autosave That Cut You Off": "Document editors",
  "The Percent That Escaped": "URL encoding",
  "Average Watch Time: Infinity": "Analytics dashboards",
  "The Cursor at the End of Time": "REST APIs",
  "Schrödinger's Follower Count": "Social counters",
  "The Draft That Overwrote the Publish": "Sync engines",
  "One Frame Behind Forever": "Game engines",
};
