/** Origin attribution per challenge title — the company/incident that inspired it. */

export const ORIGINS: Record<string, string> = {
  // ── Originals ──
  "The Checkout Meltdown": "Classic e-commerce",
  "Ghost Rows in the Audit Log": "Every admin dashboard",
  "Access Denied at Midnight": "Production on-call",
  "The Vanishing Search Results": "Typeahead search UIs",
  "False Positives at the Signup Gate": "Signup-form lore",
  "The Token That Never Dies": "JWT deployments",
  "Rate Limiter Free-for-All": "Public API platforms",
  "The Phantom WHERE Clause": "ORM refactors",
  "Cache Stampede at Dawn": "Analytics at scale",
  // ── Wave 2 ──
  "The 140-Character Lie": "Twitter",
  "The Resurfaced Memory": "Facebook · Year in Review",
  "Shuffle Isn't Random": "Spotify",
  "Ten Seconds to Next Episode": "Netflix autoplay",
  "The Phantom Unread Badge": "Slack",
  "Double-Charged at Checkout": "Stripe idempotency",
  "The One-Night Overcharge": "Airbnb-style booking",
  "Cursor Chaos After the Emoji": "Google Docs",
  "The Upvote That Counted Twice": "Reddit",
  "Infinite Scroll, Infinite Repeats": "TikTok feeds",
  "Undo Send Never Works": "Gmail",
  "The ETA That Went Negative": "Uber",
  // ── Wave 3 ──
  "The Flag That Fired Old Code": "Knight Capital · 2012",
  "One Typo, Half the Internet": "AWS S3 · 2017",
  "The Greedy Regex": "Cloudflare · 2019",
  "The Leap Day Meltdown": "GitHub · 2012",
  "Left-Pad the World": "npm · 2016",
  "The Negative Invoice": "PayPal-class exploits",
  "Infinite Leverage": "Robinhood · 2019",
  "The Null Price Latte": "Starbucks POS",
  "Retry After What?": "Slack API clients",
  "The Replayed Webhook": "Stripe webhooks",
  "Happy New Year, Dropped Messages": "WhatsApp NYE",
  "Locked Out of Everything": "Facebook · 2021",
  // ── Wave 4 ──
  "The Zune Freeze": "Microsoft Zune · 2008",
  "248 Days to Reboot": "Boeing 787",
  "Ariane's Sixteen Bits": "Ariane 5 · 1996",
  "The Year 2038 Problem": "Unix time",
  "Gangnam Style Broke the Counter": "YouTube · 2014",
  "The Negative Shard": "Java hashCode lore",
  "The Auction That Closed Instantly": "eBay-class markets",
  "The February 29th Certificate": "Microsoft Azure · 2012",
  "Satoshis, Not Doubles": "Crypto exchanges",
  "The Clock That Ran Backwards": "Twitter Snowflake",
  "The Midpoint That Overflowed": "The JDK itself",
  "Sessions for Someone Else": "Java == lore",
  // ── Wave 5 ──
  "The Metric Mars Mission": "NASA · Mars Climate Orbiter",
  "The Patriot's Drifting Clock": "Patriot missile · 1991",
  "The 1900 Leap Year Lie": "Excel / Lotus 1-2-3",
  "The Alarm That Slept In": "Apple iOS alarms",
  "Two Digits Too Few": "Y2K",
  "The Index That Rounded Itself Poor": "Vancouver Stock Exchange",
  "Half an Emoji in the Username": "MySQL utf8",
  "Noon in Which Timezone?": "Calendar apps",
  "The Ledger That Leaked Cents": "Floating-point money lore",
  "The Missing Table Rows": "Intel Pentium · 1994",
  "The Streak That Died at Midnight": "Duolingo-class apps",
  "The Backup That Backed Up Nothing": "GitLab · 2017",
  // ── Wave 6 ──
  "The N+1 Query Storm": "Every ORM",
  "Release the Connection!": "Connection pools",
  "The Optimistic Lock That Wasn't": "CMS platforms",
  "Keyset Without a Tiebreak": "Data-export pipelines",
  "IN () Means Nothing": "Query builders",
  "NULL Isn't Equal to NULL": "SQL three-valued logic",
  "Read Your Own Writes": "Replicated databases",
  "The Cache Key With a Twist": "CDN edges",
  "The Runaway Retry": "Retry storms",
  "Escaping the Wildcard": "Search boxes",
  "The Half-Applied Batch": "Ledger systems",
  "The Rotation That Ate the Backups": "Retention scripts",
  "The Upsert That Forgot to Add": "Analytics counters",
  // ── Wave 7 ──
  "alg: none": "JWT libraries · 2015",
  "The Wrong Audience": "OAuth deployments",
  "Heartbleed's Little Cousin": "OpenSSL · 2014",
  "The Path That Climbed Out": "Path traversal · CWE-22",
  "The Open Redirect": "Login pages everywhere",
  "The Lookalike Domain": "IDN homographs",
  "The Spreadsheet That Ran Code": "CSV injection",
  "The Log That Looked Things Up": "Log4Shell · 2021",
  "The Regex That Trusted Email": "Email-validation lore",
  "Rounded Out of a Refund": "Python round()",
  "The Tip That Didn't Add Up": "Gig-economy payouts",
  "The 37th of March": "java.util.Calendar",
  "Default Country Roulette": "Twilio-class SMS",
  // ── Wave 8 ──
  "The Gene Named September 2nd": "Excel × genomics",
  "Stuck on Mute": "Zoom-era calls",
  "Six Degrees, Give or Take": "LinkedIn",
  "The Leaning Tower of Pins": "Pinterest",
  "The 130% Progress Bar": "Upload dialogs",
  "The Toast That Never Left": "Notification trays",
  "The Infinite Spinner": "Every SPA",
  "The Leaderboard Shuffle": "Live-ops games",
  "The Coupon That Stacked Itself": "Black Friday",
  "The Generator That Vanished": "Python generators",
  "The Mutable Default Trap": "Python footguns",
  "The Reducer That Bit the Hand": "Redux lore",
  "A Century of Missing Interest": "Core banking",
  // ── Wave 9 ──
  "The One-Cent Book of Madness": "Amazon repricers",
  "Sold Out, Sold Again": "Ticketmaster-class sales",
  "The Negative-Price Flash Sale": "Steam-class sales",
  "The Notification Echo": "Coinbase-class alerts",
  "Nine A.M. Somewhere": "Lifecycle email",
  "Version 1.10 Beats Version 1.9": "Auto-updaters",
  "The Autosave That Cut You Off": "Document editors",
  "The Percent That Escaped": "URL encoding",
  "Average Watch Time: Infinity": "Analytics dashboards",
  "The Cursor at the End of Time": "REST APIs",
  "Schrödinger's Follower Count": "Social counters",
  "The Draft That Overwrote the Publish": "Sync engines",
  "One Frame Behind Forever": "Game engines",
  // ── Wave 10 ──
  "The Pointer That Ran Past the Buffer": "Cloudflare · Cloudbleed 2017",
  "Goto Fail, Goto Fail": "Apple · CVE-2014-1266",
  "Entropy Removed to Silence a Warning": "Debian OpenSSL · CVE-2008-0166",
  "Seven Minutes to Parse a Menu": "GTA Online · 2021",
  "The Slash That Flagged the Whole Web": "Google Safe Browsing · 2009",
  "Divide by Zero, Dead in the Water": "USS Yorktown · 1997",
  "Crossing the Date Line": "F-22 Raptor · 2007",
  "The Cleanup That Deleted the Customers": "Atlassian Jira · 2022",
  "The Console That Thought 2010 Was a Leap Year": "PlayStation 3 · 2010",
  "Back to 1970": "Apple iOS · 2016",
  "184 Billion Coins From Nowhere": "Bitcoin · CVE-2010-5139",
  "The Wallet Library That Killed Itself": "Parity multisig · 2017",
  "The Transaction That Changed Its Own Name": "Mt. Gox · 2014",
  // ── Wave 11 ──
  "The Opening Cross That Never Closed": "Nasdaq · Facebook IPO 2012",
  "Three Checkboxes and $900 Million": "Citibank · Revlon 2020",
  "Someone Else's Bank Account": "TSB Bank · 2018",
  "The Script That Granted Everyone Everything": "Salesforce Pardot · 2019",
  "Scaling Up Past the Thread Limit": "AWS Kinesis · 2020",
  "Everyone Tried to Fix It at Once": "Facebook · 2010",
  "rm -rf on an Empty Variable": "Steam for Linux · 2015",
  "The Update That Redirected Your Documents Away": "Windows 10 · 1809",
  "The Extra Second That Pegged Every CPU": "Linux leap second · 2012",
  "One Sensor, No Second Opinion": "Boeing 737 MAX · MCAS",
  "Touchdown at Forty Metres": "NASA · Mars Polar Lander 1999",
  "Negative Altitude, Underground": "ESA · Schiaparelli 2016",
  "The Task That Ran Out of Stack": "Toyota ETCS · Bookout 2013",
  // ── Wave 12 ──
  "The Route Leak Nobody Filtered": "Verizon / Cloudflare · 2019",
  "One Customer's Config Took Down the Edge": "Fastly · 2021",
  "Both Halves Thought They Were Primary": "GitHub · 2018",
  "Zero Usage Meant Zero Quota": "Google auth · 2020",
  "Scaled Down Overnight, Trampled at Dawn": "Slack · 2021",
  "The Node Update That Cut the Network": "Datadog · 2023",
  "The Label That Kubernetes Removed": "Reddit · Pi-Day 2023",
  "Half the Servers Had the Old Config": "NYSE · 2015",
  "The Scheduler That Never Converged": "Southwest Airlines · 2022",
  "Twenty-One Fields, Twenty Supplied": "CrowdStrike · 2024",
  "More Routes Than the Router Could Hold": "Optus · 2023",
  "The Filter That Held Back the Flood": "Rogers · 2022",
  "The Re-Mirror Storm": "Amazon EBS · 2011",
  // ── Wave 13 ──
  "The Environment Variable That Ran Code": "Shellshock · CVE-2014-6271",
  "The Password in the Debug Log": "Twitter · 2018",
  "Readable Passwords at Rest": "Facebook · 2019",
  "The Fetch That Reached the Metadata Service": "Capital One · 2019",
  "Document 000000001, No Login Required": "First American · 2019",
  "The Endpoint That Forgot Private Meant Private": "Peloton · 2021",
  "Audio Before the Call Was Answered": "Apple FaceTime · 2019",
  "Nine Digits and You're In the Meeting": "Zoom · 2020",
  "The Heatmap That Mapped the Base": "Strava · 2018",
  "The API That Returned More Than the Profile": "Google+ · 2018",
  "Version 2.3.10 Is Not Older Than 2.3.9": "Equifax · 2017",
  "Every Post, One Id at a Time": "Parler · 2021",
  "The Unauthenticated Customer Lookup": "Panera Bread · 2018",
};
