/**
 * Wave 11 — more documented production incidents, one planted bug each.
 *
 * Project files are Node 12-safe JS: no ??, ?., replaceAll, .at() or .flat().
 */
import type { BugSpec } from "./bugs-data.js";

export const WAVE11: BugSpec[] = [

  {
    title: "The Opening Cross That Never Closed",
    difficulty: "hard",
    category: "backend",
    language: "javascript",
    tags: ["Concurrency", "Convergence"],
    description: `Modelled on the **Nasdaq Facebook IPO** (18 May 2012): the opening cross recalculated the opening price, but orders cancelled during the calculation were fed back in and forced another pass. The loop never converged, the IPO opened 30 minutes late, and confirmations were delayed for hours.

\`cross.js\` recomputes until nothing changed, but it re-queues the very events it generates.

Fix \`runCross\` so it converges: only events that arrived **before** the pass began may trigger another one, and the loop is bounded.`,
    bugReport: `**BUG-FBIPO** · Priority: Critical · Reported by: market operations

runCross(book) must:
- repeatedly recompute the price while pending cancellations remain
- process each pass against a SNAPSHOT of the pending list taken at the start
  of that pass
- return { price, passes } — passes must be small and bounded

Observed: each pass appends its own bookkeeping event back onto the pending
list, so the loop runs until the 100000-iteration guard trips.`,
    logs: `[cross] pass 99998 pending=1 price=42
[cross] convergence guard tripped; opening delayed`,
    files: [
      {
        filePath: "src/market/cross.js",
        isEditable: true,
        language: "javascript",
        content: `// Recomputes the opening price until the book settles.
exports.runCross = function (book) {
  var passes = 0;
  var price = book.reference;
  while (book.pending.length > 0) {
    passes++;
    if (passes > 100000) return { price: price, passes: passes };
    for (var i = 0; i < book.pending.length; i++) {
      price = price + book.pending[i].delta;
      // Every processed cancellation logs a re-quote back into the queue.
      book.pending.push({ delta: 0, requote: true });
    }
    book.pending = book.pending.slice(1);
  }
  return { price: price, passes: passes };
};
`,
      },
      {
        filePath: "src/market/RULES.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nThe cross must reach a fixed point. Work generated *by* a pass belongs to the
next auction, not this one: take a snapshot of the pending queue at the start
of each pass and process only that.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "an empty book settles immediately",
        isHidden: false,
        source: `var c = require("src/market/cross").runCross;
assert.equal(c({ reference: 38, pending: [] }), { price: 38, passes: 0 });`,
      },
      {
        name: "a book with cancellations converges quickly",
        isHidden: false,
        source: `var c = require("src/market/cross").runCross;
var out = c({ reference: 38, pending: [{ delta: 2 }, { delta: -1 }, { delta: 3 }] });
assert.equal(out.price, 42);
assert.ok(out.passes <= 5, "the cross must converge, saw " + out.passes + " passes");`,
      },
      {
        name: "a single cancellation applies once",
        isHidden: true,
        source: `var c = require("src/market/cross").runCross;
var out = c({ reference: 10, pending: [{ delta: 5 }] });
assert.equal(out.price, 15);
assert.ok(out.passes <= 3);`,
      },
      {
        name: "the pending queue is drained",
        isHidden: true,
        source: `var c = require("src/market/cross").runCross;
var book = { reference: 1, pending: [{ delta: 1 }, { delta: 1 }] };
c(book);
assert.equal(book.pending.length, 0, "the auction must consume its queue");`,
      },
    ],
    fixedFiles: {
      "src/market/cross.js": `// Recomputes the opening price until the book settles.
exports.runCross = function (book) {
  var passes = 0;
  var price = book.reference;
  while (book.pending.length > 0) {
    passes++;
    if (passes > 100000) return { price: price, passes: passes };
    // Snapshot: work generated by this pass belongs to the next auction, not
    // to this one. Without the snapshot the loop feeds itself forever.
    var batch = book.pending;
    book.pending = [];
    for (var i = 0; i < batch.length; i++) {
      price = price + batch[i].delta;
    }
  }
  return { price: price, passes: passes };
};
`,
    },
  },

  {
    title: "Three Checkboxes and $900 Million",
    difficulty: "medium",
    category: "frontend",
    language: "javascript",
    tags: ["Forms", "Defaults"],
    description: `Modelled on **Citibank's Revlon payment** (August 2020): to send only an interest payment through the loan system, an operator had to tick *three* separate checkboxes. Ticking one left the other two unset, and the system wired the entire $894 million principal instead. Much of it was never recovered.

\`payment.js\` decides what to send. Its defaults are dangerously permissive.

Fix \`buildPayment\` so an incompletely configured interest-only payment is **refused** rather than silently escalated to the full principal.`,
    bugReport: `**BUG-REVLON** · Priority: Critical (funds) · Reported by: wire operations

buildPayment(loan, flags) must return:
- { kind: "interest", amount: loan.interest } when flags.principal,
  flags.frontFund and flags.escrow are ALL false — the interest-only route
- { kind: "principal", amount: loan.principal } when all three are true
- { kind: "refused", amount: 0 } for any partial combination

Observed: a partial combination falls through to the principal branch and wires
the whole loan.`,
    logs: `[wire] kind=principal amount=894000000 flags={principal:false,frontFund:true,escrow:false}
[wire] operator intent recorded as: interest only`,
    files: [
      {
        filePath: "src/payments/payment.js",
        isEditable: true,
        language: "javascript",
        content: `// Decides which payment to send.
exports.buildPayment = function (loan, flags) {
  if (!flags.principal && !flags.frontFund && !flags.escrow) {
    return { kind: "interest", amount: loan.interest };
  }
  // Anything else is treated as a full principal payoff.
  return { kind: "principal", amount: loan.principal };
};
`,
      },
      {
        filePath: "src/payments/RUNBOOK.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nAn interest-only payment and a principal payoff differ by three orders of
magnitude. A partially configured request is an operator error, not an
instruction: refuse it and surface the mismatch.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "no flags means interest only",
        isHidden: false,
        source: `var b = require("src/payments/payment").buildPayment;
var loan = { interest: 7800000, principal: 894000000 };
assert.equal(b(loan, { principal: false, frontFund: false, escrow: false }), { kind: "interest", amount: 7800000 });`,
      },
      {
        name: "a partial combination is refused",
        isHidden: false,
        source: `var b = require("src/payments/payment").buildPayment;
var loan = { interest: 7800000, principal: 894000000 };
assert.equal(b(loan, { principal: false, frontFund: true, escrow: false }), { kind: "refused", amount: 0 }, "a half-configured payment must never escalate to the principal");`,
      },
      {
        name: "all three flags means a real payoff",
        isHidden: false,
        source: `var b = require("src/payments/payment").buildPayment;
var loan = { interest: 100, principal: 5000 };
assert.equal(b(loan, { principal: true, frontFund: true, escrow: true }), { kind: "principal", amount: 5000 });`,
      },
      {
        name: "every other partial combination is refused",
        isHidden: true,
        source: `var b = require("src/payments/payment").buildPayment;
var loan = { interest: 1, principal: 999 };
assert.equal(b(loan, { principal: true, frontFund: false, escrow: false }).kind, "refused");
assert.equal(b(loan, { principal: true, frontFund: true, escrow: false }).kind, "refused");
assert.equal(b(loan, { principal: false, frontFund: false, escrow: true }).kind, "refused");`,
      },
    ],
    fixedFiles: {
      "src/payments/payment.js": `// Decides which payment to send.
exports.buildPayment = function (loan, flags) {
  var set = 0;
  if (flags.principal) set++;
  if (flags.frontFund) set++;
  if (flags.escrow) set++;

  if (set === 0) return { kind: "interest", amount: loan.interest };
  if (set === 3) return { kind: "principal", amount: loan.principal };
  // A partial combination is an operator error, not a payoff instruction.
  return { kind: "refused", amount: 0 };
};
`,
    },
  },

  {
    title: "Someone Else's Bank Account",
    difficulty: "medium",
    category: "database",
    language: "javascript",
    tags: ["Migration", "Identifiers"],
    description: `Modelled on the **TSB Bank migration** (April 2018): moving 1.3 billion customer records onto a new platform, records were re-keyed incorrectly and customers logging in were shown **other people's** accounts and balances. The outage ran for weeks and cost the bank around £330 million.

\`migrate.js\` re-keys accounts during the move and joins on the wrong field.

Fix \`migrateAccounts\` so every account stays with its own customer.`,
    bugReport: `**BUG-TSB18** · Priority: Critical (data integrity) · Reported by: migration control

migrateAccounts(legacyAccounts, customers) must return, for each account,
{ accountId, customerId, name } where the name is the name of the customer
whose id matches the account's customerId.

Observed: accounts are matched to customers by array position instead of by id.
Because the two lists are not in the same order, customers see each other's
accounts.`,
    logs: `[migrate] account acc-2 (customerId cust-9) attached to name="Priya Nair" (cust-3)
[migrate] 21403 mismatched attachments in this batch`,
    files: [
      {
        filePath: "src/migration/migrate.js",
        isEditable: true,
        language: "javascript",
        content: `// Attaches each legacy account to its customer.
exports.migrateAccounts = function (legacyAccounts, customers) {
  var out = [];
  for (var i = 0; i < legacyAccounts.length; i++) {
    var acc = legacyAccounts[i];
    // The two extracts were exported together, so position i lines up.
    var customer = customers[i];
    out.push({ accountId: acc.accountId, customerId: acc.customerId, name: customer.name });
  }
  return out;
};
`,
      },
      {
        filePath: "src/migration/EXTRACT.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nThe account and customer extracts are produced by different systems and are
NOT guaranteed to share an ordering. Join on customerId. An account whose
customer is missing must be reported with name "UNKNOWN", never attached to
whichever record happened to be at the same index.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "accounts attach to the right customer",
        isHidden: false,
        source: `var m = require("src/migration/migrate").migrateAccounts;
var accounts = [{ accountId: "acc-1", customerId: "cust-3" }, { accountId: "acc-2", customerId: "cust-9" }];
var customers = [{ id: "cust-9", name: "Dan Okafor" }, { id: "cust-3", name: "Priya Nair" }];
assert.equal(m(accounts, customers), [
  { accountId: "acc-1", customerId: "cust-3", name: "Priya Nair" },
  { accountId: "acc-2", customerId: "cust-9", name: "Dan Okafor" }
], "join on customerId, not on position");`,
      },
      {
        name: "an account with no customer is marked UNKNOWN",
        isHidden: false,
        source: `var m = require("src/migration/migrate").migrateAccounts;
var accounts = [{ accountId: "acc-5", customerId: "cust-404" }];
var customers = [{ id: "cust-1", name: "A" }];
assert.equal(m(accounts, customers), [{ accountId: "acc-5", customerId: "cust-404", name: "UNKNOWN" }]);`,
      },
      {
        name: "more customers than accounts is fine",
        isHidden: true,
        source: `var m = require("src/migration/migrate").migrateAccounts;
var accounts = [{ accountId: "a", customerId: "c2" }];
var customers = [{ id: "c1", name: "One" }, { id: "c2", name: "Two" }, { id: "c3", name: "Three" }];
assert.equal(m(accounts, customers), [{ accountId: "a", customerId: "c2", name: "Two" }]);`,
      },
      {
        name: "two accounts for the same customer both resolve",
        isHidden: true,
        source: `var m = require("src/migration/migrate").migrateAccounts;
var accounts = [{ accountId: "a1", customerId: "c1" }, { accountId: "a2", customerId: "c1" }];
var customers = [{ id: "c1", name: "Solo" }];
assert.equal(m(accounts, customers), [
  { accountId: "a1", customerId: "c1", name: "Solo" },
  { accountId: "a2", customerId: "c1", name: "Solo" }
]);`,
      },
    ],
    fixedFiles: {
      "src/migration/migrate.js": `// Attaches each legacy account to its customer.
exports.migrateAccounts = function (legacyAccounts, customers) {
  // Index by id: the two extracts come from different systems and share no
  // ordering guarantee.
  var byId = {};
  for (var c = 0; c < customers.length; c++) {
    byId[customers[c].id] = customers[c];
  }
  var out = [];
  for (var i = 0; i < legacyAccounts.length; i++) {
    var acc = legacyAccounts[i];
    var customer = byId[acc.customerId];
    out.push({
      accountId: acc.accountId,
      customerId: acc.customerId,
      name: customer ? customer.name : "UNKNOWN"
    });
  }
  return out;
};
`,
    },
  },

  {
    title: "The Script That Granted Everyone Everything",
    difficulty: "medium",
    category: "database",
    language: "javascript",
    tags: ["Permissions", "Scoping"],
    description: `Modelled on the **Salesforce Pardot incident** (May 2019): a database script intended to adjust permissions for one feature applied a broad grant instead, giving every user in affected orgs read *and write* access to all company data. Salesforce shut the service down for over 15 hours while it unwound the change.

\`grants.js\` applies a permission change and ignores the scope it was given.

Fix \`applyGrant\` so it only touches users inside the requested scope.`,
    bugReport: `**BUG-PARDOT** · Priority: Critical (data exposure) · Reported by: trust & safety

applyGrant(users, scope, permission) must:
- set permission on users whose orgId is in scope.orgIds AND whose role is in
  scope.roles
- leave every other user's permissions exactly as they were
- return the number of users changed

Observed: the scope is accepted but never consulted; every user in the store is
granted the permission.`,
    logs: `[grants] applied "write:all" to 100% of users (scope requested: 1 org, role=admin)
[grants] service disabled pending remediation`,
    files: [
      {
        filePath: "src/authz/grants.js",
        isEditable: true,
        language: "javascript",
        content: `// Applies a permission grant to the users in scope.
exports.applyGrant = function (users, scope, permission) {
  var changed = 0;
  for (var i = 0; i < users.length; i++) {
    var u = users[i];
    if (u.permissions.indexOf(permission) === -1) {
      u.permissions.push(permission);
      changed++;
    }
  }
  return changed;
};
`,
      },
      {
        filePath: "src/authz/POLICY.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nA grant is only valid inside its scope. Both conditions must hold: the user's
orgId must appear in scope.orgIds, and the user's role must appear in
scope.roles. A user already holding the permission is not counted as changed.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "only in-scope users are granted",
        isHidden: false,
        source: `var g = require("src/authz/grants").applyGrant;
var users = [
  { id: 1, orgId: "o1", role: "admin", permissions: [] },
  { id: 2, orgId: "o2", role: "admin", permissions: [] },
  { id: 3, orgId: "o1", role: "viewer", permissions: [] }
];
var changed = g(users, { orgIds: ["o1"], roles: ["admin"] }, "write:all");
assert.equal(changed, 1);
assert.equal(users[0].permissions, ["write:all"]);
assert.equal(users[1].permissions, [], "another org must be untouched");
assert.equal(users[2].permissions, [], "another role must be untouched");`,
      },
      {
        name: "an empty scope changes nobody",
        isHidden: false,
        source: `var g = require("src/authz/grants").applyGrant;
var users = [{ id: 1, orgId: "o1", role: "admin", permissions: [] }];
assert.equal(g(users, { orgIds: [], roles: [] }, "write:all"), 0);
assert.equal(users[0].permissions, []);`,
      },
      {
        name: "an existing permission is not double-counted",
        isHidden: true,
        source: `var g = require("src/authz/grants").applyGrant;
var users = [{ id: 1, orgId: "o1", role: "admin", permissions: ["write:all"] }];
assert.equal(g(users, { orgIds: ["o1"], roles: ["admin"] }, "write:all"), 0);
assert.equal(users[0].permissions, ["write:all"]);`,
      },
      {
        name: "multiple orgs and roles are honoured",
        isHidden: true,
        source: `var g = require("src/authz/grants").applyGrant;
var users = [
  { id: 1, orgId: "o1", role: "admin", permissions: [] },
  { id: 2, orgId: "o2", role: "editor", permissions: [] },
  { id: 3, orgId: "o3", role: "admin", permissions: [] }
];
assert.equal(g(users, { orgIds: ["o1", "o2"], roles: ["admin", "editor"] }, "read:all"), 2);
assert.equal(users[2].permissions, []);`,
      },
    ],
    fixedFiles: {
      "src/authz/grants.js": `// Applies a permission grant to the users in scope.
function inScope(user, scope) {
  if (scope.orgIds.indexOf(user.orgId) === -1) return false;
  if (scope.roles.indexOf(user.role) === -1) return false;
  return true;
}

exports.applyGrant = function (users, scope, permission) {
  var changed = 0;
  for (var i = 0; i < users.length; i++) {
    var u = users[i];
    // The scope is the whole point of the grant — consult it before writing.
    if (!inScope(u, scope)) continue;
    if (u.permissions.indexOf(permission) === -1) {
      u.permissions.push(permission);
      changed++;
    }
  }
  return changed;
};
`,
    },
  },

  {
    title: "Scaling Up Past the Thread Limit",
    difficulty: "medium",
    category: "backend",
    language: "javascript",
    tags: ["Capacity", "Resource Limits"],
    description: `Modelled on the **AWS Kinesis outage** (25 November 2020): adding capacity to the front-end fleet pushed the number of OS threads per server past a configured limit, because each server maintains a thread per peer. The fleet failed to build its shard map and the outage cascaded into CloudWatch, Cognito and beyond.

\`fleet.js\` adds servers without checking the per-server thread budget.

Fix \`addServers\` so a change that would exceed the limit is refused, leaving the fleet as it was.`,
    bugReport: `**BUG-KINESIS** · Priority: Critical · Reported by: capacity engineering

addServers(fleet, count):
- each server keeps one thread per OTHER server, so a fleet of n servers uses
  n - 1 threads per server
- the change must be refused if the resulting per-server thread count would
  exceed fleet.threadLimit
- returns { applied: bool, servers: <resulting count> }

Observed: the fleet grows regardless, the servers exceed the limit, and none of
them can complete the shard-map handshake.`,
    logs: `[fleet] servers=1024 threadsPerServer=1023 limit=900
[fleet] shard map construction failed on 100% of front-ends`,
    files: [
      {
        filePath: "src/fleet/fleet.js",
        isEditable: true,
        language: "javascript",
        content: `// Grows the front-end fleet.
exports.addServers = function (fleet, count) {
  fleet.servers += count;
  return { applied: true, servers: fleet.servers };
};

exports.threadsPerServer = function (fleet) {
  return fleet.servers - 1;
};
`,
      },
      {
        filePath: "src/fleet/CAPACITY.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nEvery front-end holds one thread per peer. Before any scaling change, compute
the resulting threads-per-server and compare it with the configured limit.
A change that would breach the limit must not be applied at all — a partially
scaled fleet cannot build a consistent shard map.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a safe scale-up is applied",
        isHidden: false,
        source: `var f = require("src/fleet/fleet");
var fleet = { servers: 10, threadLimit: 900 };
assert.equal(f.addServers(fleet, 5), { applied: true, servers: 15 });
assert.equal(f.threadsPerServer(fleet), 14);`,
      },
      {
        name: "a scale-up past the limit is refused",
        isHidden: false,
        source: `var f = require("src/fleet/fleet");
var fleet = { servers: 895, threadLimit: 900 };
assert.equal(f.addServers(fleet, 200), { applied: false, servers: 895 }, "the fleet must not grow past the thread limit");
assert.equal(fleet.servers, 895);`,
      },
      {
        name: "growing exactly to the limit is allowed",
        isHidden: true,
        source: `var f = require("src/fleet/fleet");
var fleet = { servers: 100, threadLimit: 200 };
assert.equal(f.addServers(fleet, 101), { applied: true, servers: 201 });
assert.equal(f.threadsPerServer(fleet), 200);`,
      },
      {
        name: "one server over the limit is refused",
        isHidden: true,
        source: `var f = require("src/fleet/fleet");
var fleet = { servers: 100, threadLimit: 200 };
assert.equal(f.addServers(fleet, 102), { applied: false, servers: 100 });`,
      },
    ],
    fixedFiles: {
      "src/fleet/fleet.js": `// Grows the front-end fleet.
exports.addServers = function (fleet, count) {
  var resulting = fleet.servers + count;
  // One thread per peer: check the resulting budget BEFORE applying anything.
  // A half-scaled fleet cannot build a consistent shard map.
  if (resulting - 1 > fleet.threadLimit) {
    return { applied: false, servers: fleet.servers };
  }
  fleet.servers = resulting;
  return { applied: true, servers: fleet.servers };
};

exports.threadsPerServer = function (fleet) {
  return fleet.servers - 1;
};
`,
    },
  },

  {
    title: "Everyone Tried to Fix It at Once",
    difficulty: "hard",
    category: "backend",
    language: "javascript",
    tags: ["Feedback Loops", "Caching"],
    description: `Modelled on the **Facebook outage of 23 September 2010**: a configuration value was judged invalid, so every client cleared its cache and queried the database for a correct value — which was still the invalid one. Hundreds of thousands of clients hammered the database in a self-sustaining loop, and the site had to be taken offline to break it.

\`config.js\` has the same shape: a failed lookup invalidates the cache and retries without limit.

Fix \`resolve\` so a persistently invalid value is cached as a negative result instead of driving unbounded traffic.`,
    bugReport: `**BUG-FB2010** · Priority: Critical · Reported by: site reliability

resolve(cache, db, key) must:
- return the cached value when present and valid
- otherwise query the database at most ONCE per call
- when the database also returns an invalid value, remember that (a negative
  cache entry) and return null
- return { value, queries } so the caller can see the database load

Observed: an invalid value makes the function clear the cache and loop, issuing
thousands of queries for a single lookup.`,
    logs: `[config] key="threshold" queries=98211 value=invalid
[config] database at 100% CPU; site taken offline to break the loop`,
    files: [
      {
        filePath: "src/config/config.js",
        isEditable: true,
        language: "javascript",
        content: `function valid(v) {
  return v !== null && v !== "invalid";
}

exports.resolve = function (cache, db, key) {
  var queries = 0;
  while (true) {
    if (cache.hasOwnProperty(key) && valid(cache[key])) {
      return { value: cache[key], queries: queries };
    }
    // The cached value looks wrong — throw it away and ask the source again.
    delete cache[key];
    queries++;
    cache[key] = db.read(key);
    if (queries > 100000) return { value: null, queries: queries };
  }
};
`,
      },
      {
        filePath: "src/config/NOTES.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nThe database is the source of truth. If it returns a value the client considers
invalid, retrying cannot help — the answer will not change. Record the failure
so the next lookup is served from cache rather than from the database.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a valid cached value costs no queries",
        isHidden: false,
        source: `var c = require("src/config/config").resolve;
var cache = { threshold: 42 };
var db = { read: function () { throw new Error("must not query"); } };
assert.equal(c(cache, db, "threshold"), { value: 42, queries: 0 });`,
      },
      {
        name: "an invalid value queries once and gives up",
        isHidden: false,
        source: `var c = require("src/config/config").resolve;
var cache = {};
var db = { read: function () { return "invalid"; } };
var out = c(cache, db, "threshold");
assert.equal(out.value, null);
assert.equal(out.queries, 1, "one failed lookup must not become a retry storm");`,
      },
      {
        name: "a negative result is remembered",
        isHidden: false,
        source: `var c = require("src/config/config").resolve;
var cache = {};
var db = { read: function () { return "invalid"; } };
c(cache, db, "threshold");
var second = c(cache, db, "threshold");
assert.equal(second.queries, 0, "the failure must be cached");`,
      },
      {
        name: "a cold cache with a good value queries once",
        isHidden: true,
        source: `var c = require("src/config/config").resolve;
var cache = {};
var db = { read: function () { return 7; } };
assert.equal(c(cache, db, "k"), { value: 7, queries: 1 });
assert.equal(c(cache, db, "k"), { value: 7, queries: 0 });`,
      },
    ],
    fixedFiles: {
      "src/config/config.js": `function valid(v) {
  return v !== null && v !== "invalid";
}

exports.resolve = function (cache, db, key) {
  if (cache.hasOwnProperty(key)) {
    if (valid(cache[key])) return { value: cache[key], queries: 0 };
    // A remembered failure: the database already told us, do not ask again.
    return { value: null, queries: 0 };
  }
  // Exactly one query per lookup. Retrying cannot change the source of truth,
  // so an invalid answer is cached negatively rather than driving a loop.
  var fetched = db.read(key);
  cache[key] = fetched;
  if (!valid(fetched)) return { value: null, queries: 1 };
  return { value: fetched, queries: 1 };
};
`,
    },
  },

  {
    title: "rm -rf on an Empty Variable",
    difficulty: "easy",
    category: "backend",
    language: "javascript",
    tags: ["Shell Safety", "Empty Values"],
    description: `Modelled on the **Steam for Linux** bug (January 2015): an uninstall script ran \`rm -rf "$STEAMROOT/"*\`. When \`STEAMROOT\` was empty the expansion became \`rm -rf "/"*\`, and users lost everything the account could write, including mounted backup drives.

\`uninstall.js\` builds the same kind of path and never checks that the root is real.

Fix \`buildRemovePath\` so an empty, missing or root value is refused.`,
    bugReport: `**BUG-STEAMROOT** · Priority: Critical (data loss) · Reported by: linux support

buildRemovePath(root, subdir) must return:
- { safe: true, path: root + "/" + subdir } for a sane absolute root
- { safe: false, path: "" } when root is empty, undefined, "/" or does not
  start with "/"

Observed: an empty root produces "/steamapps" — and callers happily recurse
from the filesystem root.`,
    logs: `[uninstall] removing "/*" (STEAMROOT was empty)
[uninstall] 1.4 TB removed from an external mount`,
    files: [
      {
        filePath: "src/installer/uninstall.js",
        isEditable: true,
        language: "javascript",
        content: `// Builds the directory the uninstaller will remove.
exports.buildRemovePath = function (root, subdir) {
  return { safe: true, path: root + "/" + subdir };
};
`,
      },
      {
        filePath: "src/installer/SAFETY.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nAny path handed to a recursive delete must be validated first. An unset
variable is not a path. "/" is never a valid install root. A relative path is
resolved against an unknown working directory and is equally unsafe.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a normal root builds a path",
        isHidden: false,
        source: `var b = require("src/installer/uninstall").buildRemovePath;
assert.equal(b("/home/kai/.steam", "steamapps"), { safe: true, path: "/home/kai/.steam/steamapps" });`,
      },
      {
        name: "an empty root is refused",
        isHidden: false,
        source: `var b = require("src/installer/uninstall").buildRemovePath;
assert.equal(b("", "steamapps"), { safe: false, path: "" }, "an unset root must never become /");`,
      },
      {
        name: "the filesystem root is refused",
        isHidden: true,
        source: `var b = require("src/installer/uninstall").buildRemovePath;
assert.equal(b("/", "steamapps"), { safe: false, path: "" });`,
      },
      {
        name: "an undefined or relative root is refused",
        isHidden: true,
        source: `var b = require("src/installer/uninstall").buildRemovePath;
assert.equal(b(undefined, "steamapps"), { safe: false, path: "" });
assert.equal(b("steam", "steamapps"), { safe: false, path: "" });`,
      },
    ],
    fixedFiles: {
      "src/installer/uninstall.js": `// Builds the directory the uninstaller will remove.
exports.buildRemovePath = function (root, subdir) {
  // An unset variable is not a path, and "/" is never an install root.
  if (!root) return { safe: false, path: "" };
  if (typeof root !== "string") return { safe: false, path: "" };
  if (root === "/") return { safe: false, path: "" };
  if (root.charAt(0) !== "/") return { safe: false, path: "" };
  return { safe: true, path: root + "/" + subdir };
};
`,
    },
  },

  {
    title: "The Update That Redirected Your Documents Away",
    difficulty: "medium",
    category: "backend",
    language: "javascript",
    tags: ["Migration", "Data Loss"],
    description: `Modelled on the **Windows 10 October 2018 Update** (build 1809): known-folder redirection had left some users with two Documents folders. The updater deleted the *original* folder without checking whether it still held files, and people lost photos and documents. Microsoft pulled the update within days.

\`redirect.js\` performs the same cleanup and skips the emptiness check.

Fix \`cleanupOldFolder\` so a folder with contents is never removed.`,
    bugReport: `**BUG-1809** · Priority: Critical (data loss) · Reported by: update reliability

cleanupOldFolder(fs, oldPath, newPath) must:
- remove oldPath only when it exists AND is empty
- never remove it when it still contains files
- never remove newPath under any circumstance
- return { removed: bool, reason: "ok" | "not-empty" | "missing" | "same" }

Observed: the old folder is deleted unconditionally, taking its contents with it.`,
    logs: `[kfr] removed C:\\Users\\sam\\Documents (14,203 files)
[kfr] redirect target C:\\OneDrive\\Documents contained 0 of them`,
    files: [
      {
        filePath: "src/update/redirect.js",
        isEditable: true,
        language: "javascript",
        content: `// Removes the pre-redirect folder after a known-folder move.
exports.cleanupOldFolder = function (fs, oldPath, newPath) {
  delete fs[oldPath];
  return { removed: true, reason: "ok" };
};
`,
      },
      {
        filePath: "src/update/FS.js",
        isEditable: false,
        language: "javascript",
        content: `/*\n\`fs\` maps a path to an array of file names. A path that is not a key does not
exist. Cleanup after a redirect is an optimisation, never a requirement — when
in doubt, leave the folder alone.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "an empty old folder is removed",
        isHidden: false,
        source: `var c = require("src/update/redirect").cleanupOldFolder;
var fs = { "C:/old": [], "C:/new": ["a.txt"] };
assert.equal(c(fs, "C:/old", "C:/new"), { removed: true, reason: "ok" });
assert.ok(!fs.hasOwnProperty("C:/old"));`,
      },
      {
        name: "a folder with files is never removed",
        isHidden: false,
        source: `var c = require("src/update/redirect").cleanupOldFolder;
var fs = { "C:/old": ["photo.jpg", "taxes.pdf"], "C:/new": [] };
assert.equal(c(fs, "C:/old", "C:/new"), { removed: false, reason: "not-empty" }, "a non-empty folder must survive");
assert.equal(fs["C:/old"], ["photo.jpg", "taxes.pdf"]);`,
      },
      {
        name: "a missing folder reports missing",
        isHidden: true,
        source: `var c = require("src/update/redirect").cleanupOldFolder;
var fs = { "C:/new": [] };
assert.equal(c(fs, "C:/old", "C:/new"), { removed: false, reason: "missing" });`,
      },
      {
        name: "the redirect target is never removed",
        isHidden: true,
        source: `var c = require("src/update/redirect").cleanupOldFolder;
var fs = { "C:/same": [] };
assert.equal(c(fs, "C:/same", "C:/same"), { removed: false, reason: "same" });
assert.ok(fs.hasOwnProperty("C:/same"));`,
      },
    ],
    fixedFiles: {
      "src/update/redirect.js": `// Removes the pre-redirect folder after a known-folder move.
exports.cleanupOldFolder = function (fs, oldPath, newPath) {
  // Never delete the folder we just redirected to.
  if (oldPath === newPath) return { removed: false, reason: "same" };
  if (!fs.hasOwnProperty(oldPath)) return { removed: false, reason: "missing" };
  // Cleanup is an optimisation; a folder that still holds files stays.
  if (fs[oldPath].length > 0) return { removed: false, reason: "not-empty" };
  delete fs[oldPath];
  return { removed: true, reason: "ok" };
};
`,
    },
  },

  {
    title: "The Extra Second That Pegged Every CPU",
    difficulty: "hard",
    category: "backend",
    language: "javascript",
    tags: ["Time", "Livelock"],
    description: `Modelled on the **leap second of 30 June 2012**: inserting a 61st second left kernel timers with a deadline that had already passed. The timer loop re-armed a task that was instantly due again, so it spun without progressing. Reddit, Mozilla, LinkedIn and Qantas all went down at the same instant.

\`scheduler.js\` re-arms timers by adding an interval to the *deadline*, which never catches up once the clock jumps backwards.

Fix \`runDueTimers\` so it always makes progress, even when the clock steps.`,
    bugReport: `**BUG-LEAPSEC** · Priority: Critical · Reported by: kernel team

runDueTimers(now, timers) must:
- fire every timer whose deadline is at or before \`now\`
- re-arm each fired timer strictly AFTER \`now\`
- return { fired, timers } and terminate in bounded time

Observed: when the clock steps backwards, a re-armed timer is immediately due
again and the loop spins until the iteration guard trips.`,
    logs: `[timer] iterations=1000000 fired=1000000 pending=1
[timer] all cores at 100%; ntp step -1s`,
    files: [
      {
        filePath: "src/kernel/scheduler.js",
        isEditable: true,
        language: "javascript",
        content: `// Fires every timer that is due, re-arming it for its next interval.
exports.runDueTimers = function (now, timers) {
  var fired = 0;
  var guard = 0;
  var due = true;
  while (due) {
    due = false;
    for (var i = 0; i < timers.length; i++) {
      if (timers[i].deadline <= now) {
        fired++;
        // Re-arm relative to the old deadline.
        timers[i].deadline = timers[i].deadline + timers[i].interval;
        due = true;
      }
    }
    guard++;
    if (guard > 1000000) break;
  }
  return { fired: fired, timers: timers };
};
`,
      },
      {
        filePath: "src/kernel/TIMERS.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nThe wall clock can step in either direction. A timer must always be re-armed
to a deadline strictly greater than the current time, or the scheduler cannot
make progress.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a due timer fires once and re-arms",
        isHidden: false,
        source: `var s = require("src/kernel/scheduler").runDueTimers;
var timers = [{ deadline: 100, interval: 50 }];
var out = s(100, timers);
assert.equal(out.fired, 1);
assert.ok(timers[0].deadline > 100, "the timer must be re-armed after now");`,
      },
      {
        name: "a clock step backwards does not livelock",
        isHidden: false,
        source: `var s = require("src/kernel/scheduler").runDueTimers;
var timers = [{ deadline: 10, interval: 5 }];
var out = s(1000, timers);
assert.ok(out.fired <= 2, "a stale deadline must fire once, not spin, saw " + out.fired);
assert.ok(timers[0].deadline > 1000);`,
      },
      {
        name: "timers that are not due do not fire",
        isHidden: true,
        source: `var s = require("src/kernel/scheduler").runDueTimers;
var timers = [{ deadline: 500, interval: 10 }];
assert.equal(s(100, timers).fired, 0);
assert.equal(timers[0].deadline, 500);`,
      },
      {
        name: "several timers each fire once",
        isHidden: true,
        source: `var s = require("src/kernel/scheduler").runDueTimers;
var timers = [{ deadline: 1, interval: 5 }, { deadline: 2, interval: 7 }, { deadline: 900, interval: 3 }];
var out = s(100, timers);
assert.equal(out.fired, 2);
assert.ok(timers[0].deadline > 100 && timers[1].deadline > 100);`,
      },
    ],
    fixedFiles: {
      "src/kernel/scheduler.js": `// Fires every timer that is due, re-arming it for its next interval.
exports.runDueTimers = function (now, timers) {
  var fired = 0;
  for (var i = 0; i < timers.length; i++) {
    if (timers[i].deadline > now) continue;
    fired++;
    // Re-arm relative to NOW, not to a deadline that may already be far in the
    // past — otherwise a clock step leaves the timer permanently due.
    var next = timers[i].deadline + timers[i].interval;
    if (next <= now) {
      var behind = now - timers[i].deadline;
      var skips = Math.floor(behind / timers[i].interval) + 1;
      next = timers[i].deadline + skips * timers[i].interval;
    }
    if (next <= now) next = now + timers[i].interval;
    timers[i].deadline = next;
  }
  return { fired: fired, timers: timers };
};
`,
    },
  },

  {
    title: "One Sensor, No Second Opinion",
    difficulty: "medium",
    category: "backend",
    language: "javascript",
    tags: ["Redundancy", "Sensor Fusion"],
    description: `Modelled on the **Boeing 737 MAX MCAS** design: the system trimmed the aircraft nose-down based on a **single** angle-of-attack sensor, even though two were fitted. A single failed vane commanded repeated nose-down trim, and two crashes followed.

\`mcas.js\` reads one sensor and acts on it.

Fix \`computeTrim\` so it cross-checks both sensors and disengages when they disagree.`,
    bugReport: `**BUG-MCAS** · Priority: Critical (safety) · Reported by: flight controls

computeTrim(left, right, threshold, disagreeLimit) must:
- disengage (return 0) when |left - right| exceeds disagreeLimit — the sensors
  disagree and neither can be trusted
- otherwise use the AVERAGE of the two; trim nose-down by -1 when the average
  exceeds threshold, and 0 otherwise

Observed: only the left sensor is read. A stuck vane at 74.5 degrees commands
continuous nose-down trim while the right sensor reads a healthy 5 degrees.`,
    logs: `[mcas] trim=-1 aoaLeft=74.5 aoaRight=5.0
[mcas] trim command repeated 21 times`,
    files: [
      {
        filePath: "src/flight/mcas.js",
        isEditable: true,
        language: "javascript",
        content: `// Decides whether to command nose-down trim.
exports.computeTrim = function (left, right, threshold, disagreeLimit) {
  if (left > threshold) return -1;
  return 0;
};
`,
      },
      {
        filePath: "src/flight/DESIGN.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nTwo angle-of-attack sensors are fitted. A control law that can command a
flight-critical surface must never depend on one of them: compare both, and
if they disagree beyond the limit, disengage rather than guess.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "agreeing sensors below the threshold command no trim",
        isHidden: false,
        source: `var m = require("src/flight/mcas").computeTrim;
assert.equal(m(5, 5.4, 20, 5), 0);`,
      },
      {
        name: "a single stuck sensor disengages the system",
        isHidden: false,
        source: `var m = require("src/flight/mcas").computeTrim;
assert.equal(m(74.5, 5.0, 20, 5), 0, "disagreeing sensors must disengage, not trim");`,
      },
      {
        name: "agreeing sensors above the threshold do trim",
        isHidden: false,
        source: `var m = require("src/flight/mcas").computeTrim;
assert.equal(m(30, 32, 20, 5), -1);`,
      },
      {
        name: "the average is used, not either sensor alone",
        isHidden: true,
        source: `var m = require("src/flight/mcas").computeTrim;
assert.equal(m(22, 18, 20, 5), 0, "average 20 does not exceed the threshold");
assert.equal(m(24, 22, 20, 5), -1);`,
      },
    ],
    fixedFiles: {
      "src/flight/mcas.js": `// Decides whether to command nose-down trim.
exports.computeTrim = function (left, right, threshold, disagreeLimit) {
  var spread = left - right;
  if (spread < 0) spread = -spread;
  // Disagreement means neither sensor can be trusted — disengage rather than
  // command a flight-critical surface on a guess.
  if (spread > disagreeLimit) return 0;
  var average = (left + right) / 2;
  if (average > threshold) return -1;
  return 0;
};
`,
    },
  },

  {
    title: "Touchdown at Forty Metres",
    difficulty: "medium",
    category: "backend",
    language: "javascript",
    tags: ["Sensors", "State Latching"],
    description: `Modelled on the **Mars Polar Lander** loss (December 1999): the leg-deployment jolt produced a spurious touchdown signal. The flight software latched that transient as "landed" and shut the descent engine down about 40 metres up. The lander fell.

\`descent.js\` latches the touchdown flag the moment it first sees it.

Fix \`shouldCutEngine\` so a transient during leg deployment cannot latch, and touchdown is only believed once it is stable and the altitude agrees.`,
    bugReport: `**BUG-MPL** · Priority: Critical · Reported by: EDL team

shouldCutEngine(samples, altitude, legDeploymentEndsAt) must return true only
when BOTH hold:
- the last 3 samples all read touchdown=true, and none of those samples has an
  index below legDeploymentEndsAt (transients during deployment are ignored)
- altitude is at or below 2 metres

Observed: one true sample anywhere in the record latches the state and the
engine is cut, whatever the altitude.`,
    logs: `[edl] engine cut at altitude=40.1m
[edl] touchdown asserted at sample 3 (leg deployment ends at sample 12)`,
    files: [
      {
        filePath: "src/edl/descent.js",
        isEditable: true,
        language: "javascript",
        content: `// Decides whether the descent engine may be shut down.
exports.shouldCutEngine = function (samples, altitude, legDeploymentEndsAt) {
  var latched = false;
  for (var i = 0; i < samples.length; i++) {
    if (samples[i].touchdown) latched = true;
  }
  return latched;
};
`,
      },
      {
        filePath: "src/edl/SEQUENCE.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nLeg deployment produces mechanical shock that the touchdown sensors register as
a momentary contact. Samples with index < legDeploymentEndsAt must be discarded
outright. Real touchdown is a sustained signal, corroborated by altitude.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a sustained touchdown near the ground cuts the engine",
        isHidden: false,
        source: `var d = require("src/edl/descent").shouldCutEngine;
var s = [];
for (var i = 0; i < 15; i++) s.push({ touchdown: false });
s.push({ touchdown: true }); s.push({ touchdown: true }); s.push({ touchdown: true });
assert.equal(d(s, 0.4, 12), true);`,
      },
      {
        name: "a deployment transient does not cut the engine",
        isHidden: false,
        source: `var d = require("src/edl/descent").shouldCutEngine;
var s = [];
for (var i = 0; i < 20; i++) s.push({ touchdown: i === 3 });
assert.equal(d(s, 40.1, 12), false, "a transient during leg deployment must be ignored");`,
      },
      {
        name: "touchdown high above the ground is rejected",
        isHidden: true,
        source: `var d = require("src/edl/descent").shouldCutEngine;
var s = [];
for (var i = 0; i < 15; i++) s.push({ touchdown: false });
s.push({ touchdown: true }); s.push({ touchdown: true }); s.push({ touchdown: true });
assert.equal(d(s, 40.1, 12), false);`,
      },
      {
        name: "a single late blip is not enough",
        isHidden: true,
        source: `var d = require("src/edl/descent").shouldCutEngine;
var s = [];
for (var i = 0; i < 20; i++) s.push({ touchdown: i === 19 });
assert.equal(d(s, 0.2, 12), false);`,
      },
    ],
    fixedFiles: {
      "src/edl/descent.js": `// Decides whether the descent engine may be shut down.
exports.shouldCutEngine = function (samples, altitude, legDeploymentEndsAt) {
  // Altitude must corroborate the sensors.
  if (altitude > 2) return false;
  if (samples.length < 3) return false;
  var start = samples.length - 3;
  // Samples taken during leg deployment are mechanical shock, not touchdown.
  if (start < legDeploymentEndsAt) return false;
  for (var i = start; i < samples.length; i++) {
    if (!samples[i].touchdown) return false;
  }
  return true;
};
`,
    },
  },

  {
    title: "Negative Altitude, Underground",
    difficulty: "medium",
    category: "backend",
    language: "javascript",
    tags: ["Sensors", "Saturation"],
    description: `Modelled on the **Schiaparelli lander** (October 2016): the inertial unit saturated during parachute deployment and reported a rotation rate far beyond its range. The navigation filter integrated that value, concluded the lander was *below ground level*, and jettisoned the parachute and shut off the thrusters at about 3.7 km altitude.

\`navfilter.js\` integrates every sample it is handed, saturated or not.

Fix \`estimateAltitude\` so saturated samples are discarded and the estimate can never go negative.`,
    bugReport: `**BUG-EDM16** · Priority: Critical · Reported by: GNC

estimateAltitude(start, samples, maxRate):
- integrates each sample's rate (metres lost per step)
- a sample whose |rate| exceeds maxRate is SATURATED and must be discarded,
  with the previous accepted rate used in its place (0 if there is none)
- the returned altitude is clamped to a floor of 0

Observed: one saturated sample drives the estimate to a large negative altitude
and the descent sequence fires early.`,
    logs: `[gnc] altitude=-2400.0 after sample rate=98000.0 (max 500.0)
[gnc] parachute jettisoned at true altitude 3.7km`,
    files: [
      {
        filePath: "src/gnc/navfilter.js",
        isEditable: true,
        language: "javascript",
        content: `// Integrates descent rates into an altitude estimate.
exports.estimateAltitude = function (start, samples, maxRate) {
  var altitude = start;
  for (var i = 0; i < samples.length; i++) {
    altitude = altitude - samples[i].rate;
  }
  return altitude;
};
`,
      },
      {
        filePath: "src/gnc/IMU.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nThe inertial unit saturates during parachute deployment. A reading outside the
instrument's range carries no information and must not be integrated. Altitude
is a physical quantity with a floor of zero.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "normal samples integrate",
        isHidden: false,
        source: `var e = require("src/gnc/navfilter").estimateAltitude;
assert.equal(e(1000, [{ rate: 100 }, { rate: 100 }], 500), 800);`,
      },
      {
        name: "a saturated sample is discarded",
        isHidden: false,
        source: `var e = require("src/gnc/navfilter").estimateAltitude;
assert.equal(e(1000, [{ rate: 100 }, { rate: 98000 }, { rate: 100 }], 500), 700, "a saturated reading must not be integrated");`,
      },
      {
        name: "altitude never goes negative",
        isHidden: true,
        source: `var e = require("src/gnc/navfilter").estimateAltitude;
assert.equal(e(150, [{ rate: 100 }, { rate: 100 }], 500), 0);`,
      },
      {
        name: "a leading saturated sample substitutes zero",
        isHidden: true,
        source: `var e = require("src/gnc/navfilter").estimateAltitude;
assert.equal(e(1000, [{ rate: 99999 }, { rate: 50 }], 500), 950);`,
      },
    ],
    fixedFiles: {
      "src/gnc/navfilter.js": `// Integrates descent rates into an altitude estimate.
exports.estimateAltitude = function (start, samples, maxRate) {
  var altitude = start;
  var lastGood = 0;
  for (var i = 0; i < samples.length; i++) {
    var rate = samples[i].rate;
    var magnitude = rate < 0 ? -rate : rate;
    // A saturated reading carries no information — hold the last good rate.
    if (magnitude > maxRate) rate = lastGood;
    else lastGood = rate;
    altitude = altitude - rate;
  }
  // Altitude is physical: it has a floor of zero.
  return altitude < 0 ? 0 : altitude;
};
`,
    },
  },

  {
    title: "The Task That Ran Out of Stack",
    difficulty: "hard",
    category: "backend",
    language: "javascript",
    tags: ["Recursion", "Resource Limits"],
    description: `Modelled on the findings in the **Toyota unintended-acceleration** case (Bookout v. Toyota, 2013): the engine control software's stack usage was far larger than analysed, and there was no protection when it overflowed — a task could die silently and leave the throttle in its last commanded state.

\`ecu.js\` walks a nested task graph recursively with no depth limit and no fallback if the walk fails.

Fix \`computeThrottle\` so deep graphs cannot blow the stack, and a failed evaluation returns the safe default rather than the last value.`,
    bugReport: `**BUG-ETCS** · Priority: Critical (safety) · Reported by: powertrain

computeThrottle(graph, maxDepth) must:
- sum the demand of every node in the tree
- refuse graphs deeper than maxDepth, returning { ok: false, throttle: 0 }
- return { ok: true, throttle: <sum> } otherwise

Observed: a deeply nested graph overflows the stack. The caller keeps the
previous throttle value, which on the road means the pedal stops responding.`,
    logs: `[ecu] RangeError: Maximum call stack size exceeded at depth 11
[ecu] throttle held at last commanded value`,
    files: [
      {
        filePath: "src/ecu/ecu.js",
        isEditable: true,
        language: "javascript",
        content: `// Sums the demand across the task graph.
function walk(node) {
  var total = node.demand;
  for (var i = 0; i < node.children.length; i++) {
    total += walk(node.children[i]);
  }
  return total;
}

exports.computeThrottle = function (graph, maxDepth) {
  return { ok: true, throttle: walk(graph) };
};
`,
      },
      {
        filePath: "src/ecu/SAFETY.js",
        isEditable: false,
        language: "javascript",
        content: `/*\nA control task that cannot complete must fail to the safe state — throttle
closed — not leave the previous command standing. Recursion depth in a
real-time task must be bounded by analysis, and enforced at run time.
\n*/\n`,
      },
    ],
    tests: [
      {
        name: "a shallow graph sums correctly",
        isHidden: false,
        source: `var c = require("src/ecu/ecu").computeThrottle;
var g = { demand: 1, children: [{ demand: 2, children: [] }, { demand: 3, children: [] }] };
assert.equal(c(g, 10), { ok: true, throttle: 6 });`,
      },
      {
        name: "a too-deep graph fails safe instead of crashing",
        isHidden: false,
        source: `var c = require("src/ecu/ecu").computeThrottle;
var node = { demand: 1, children: [] };
for (var i = 0; i < 5000; i++) node = { demand: 1, children: [node] };
assert.equal(c(node, 64), { ok: false, throttle: 0 }, "an over-deep graph must fail to a closed throttle");`,
      },
      {
        name: "a single node works",
        isHidden: true,
        source: `var c = require("src/ecu/ecu").computeThrottle;
assert.equal(c({ demand: 7, children: [] }, 10), { ok: true, throttle: 7 });`,
      },
      {
        name: "a graph exactly at the depth limit is accepted",
        isHidden: true,
        source: `var c = require("src/ecu/ecu").computeThrottle;
var node = { demand: 1, children: [] };
for (var i = 0; i < 4; i++) node = { demand: 1, children: [node] };
assert.equal(c(node, 5), { ok: true, throttle: 5 });`,
      },
    ],
    fixedFiles: {
      "src/ecu/ecu.js": `// Sums the demand across the task graph.
// Iterative walk with an explicit depth budget: a real-time task must not put
// unbounded pressure on the stack, and must fail to the safe state.
exports.computeThrottle = function (graph, maxDepth) {
  var stack = [{ node: graph, depth: 1 }];
  var total = 0;
  while (stack.length > 0) {
    var entry = stack.pop();
    if (entry.depth > maxDepth) return { ok: false, throttle: 0 };
    total += entry.node.demand;
    var kids = entry.node.children;
    for (var i = 0; i < kids.length; i++) {
      stack.push({ node: kids[i], depth: entry.depth + 1 });
    }
  }
  return { ok: true, throttle: total };
};
`,
    },
  },

  // ── END WAVE11 ──
];
